### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.SerializationMode
  id: SerializationMode
  children:
  - System.Web.Configuration.SerializationMode.Binary
  - System.Web.Configuration.SerializationMode.ProviderSpecific
  - System.Web.Configuration.SerializationMode.String
  - System.Web.Configuration.SerializationMode.Xml
  langs:
  - csharp
  name: SerializationMode
  nameWithType: SerializationMode
  fullName: System.Web.Configuration.SerializationMode
  type: Enum
  summary: "Determina o método de serialização usado para um <xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref> objeto."
  remarks: "O <xref:System.Web.Configuration.ProfilePropertySettings.SerializeAs%2A>propriedade o <xref:System.Web.Configuration.ProfilePropertySettings>objeto controla o modo de serialização para uma configuração de propriedade de perfil.</xref:System.Web.Configuration.ProfilePropertySettings> </xref:System.Web.Configuration.ProfilePropertySettings.SerializeAs%2A>"
  example:
  - "The following code example shows how to use the <xref:System.Web.Configuration.ProfilePropertySettings.SerializeAs%2A> property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.ProfileSection> class.  \n  \n [!code-cs[System.Web.Configuration.ProfileSection#17](~/add/codesnippet/csharp/t-system.web.configurati_92_1.cs)]\n [!code-vb[System.Web.Configuration.ProfileSection#17](~/add/codesnippet/visualbasic/t-system.web.configurati_92_1.vb)]"
  syntax:
    content: public enum SerializationMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.SerializationMode.Binary
  id: Binary
  parent: System.Web.Configuration.SerializationMode
  langs:
  - csharp
  name: Binary
  nameWithType: SerializationMode.Binary
  fullName: System.Web.Configuration.SerializationMode.Binary
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "O <xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref> o objeto é serializado usando a serialização binária."
  syntax:
    content: Binary
    return:
      type: System.Web.Configuration.SerializationMode
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SerializationMode.ProviderSpecific
  id: ProviderSpecific
  parent: System.Web.Configuration.SerializationMode
  langs:
  - csharp
  name: ProviderSpecific
  nameWithType: SerializationMode.ProviderSpecific
  fullName: System.Web.Configuration.SerializationMode.ProviderSpecific
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "O provedor tiver conhecimento implícito do tipo e é responsável por decidir como serializar o <xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref> o objeto para o repositório de dados."
  syntax:
    content: ProviderSpecific
    return:
      type: System.Web.Configuration.SerializationMode
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SerializationMode.String
  id: String
  parent: System.Web.Configuration.SerializationMode
  langs:
  - csharp
  name: String
  nameWithType: SerializationMode.String
  fullName: System.Web.Configuration.SerializationMode.String
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "O <xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref> objeto é serializado como uma cadeia de caracteres simple."
  syntax:
    content: String
    return:
      type: System.Web.Configuration.SerializationMode
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SerializationMode.Xml
  id: Xml
  parent: System.Web.Configuration.SerializationMode
  langs:
  - csharp
  name: Xml
  nameWithType: SerializationMode.Xml
  fullName: System.Web.Configuration.SerializationMode.Xml
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "O perfil <xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref> é serializado como XML usando a serialização de XML."
  syntax:
    content: Xml
    return:
      type: System.Web.Configuration.SerializationMode
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.SerializationMode.Binary
  parent: System.Web.Configuration.SerializationMode
  isExternal: false
  name: Binary
  nameWithType: SerializationMode.Binary
  fullName: System.Web.Configuration.SerializationMode.Binary
- uid: System.Web.Configuration.SerializationMode
  parent: System.Web.Configuration
  isExternal: false
  name: SerializationMode
  nameWithType: SerializationMode
  fullName: System.Web.Configuration.SerializationMode
- uid: System.Web.Configuration.SerializationMode.ProviderSpecific
  parent: System.Web.Configuration.SerializationMode
  isExternal: false
  name: ProviderSpecific
  nameWithType: SerializationMode.ProviderSpecific
  fullName: System.Web.Configuration.SerializationMode.ProviderSpecific
- uid: System.Web.Configuration.SerializationMode.String
  parent: System.Web.Configuration.SerializationMode
  isExternal: false
  name: String
  nameWithType: SerializationMode.String
  fullName: System.Web.Configuration.SerializationMode.String
- uid: System.Web.Configuration.SerializationMode.Xml
  parent: System.Web.Configuration.SerializationMode
  isExternal: false
  name: Xml
  nameWithType: SerializationMode.Xml
  fullName: System.Web.Configuration.SerializationMode.Xml
