### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel
  id: ProcessModelComAuthenticationLevel
  children:
  - System.Web.Configuration.ProcessModelComAuthenticationLevel.Call
  - System.Web.Configuration.ProcessModelComAuthenticationLevel.Connect
  - System.Web.Configuration.ProcessModelComAuthenticationLevel.Default
  - System.Web.Configuration.ProcessModelComAuthenticationLevel.None
  - System.Web.Configuration.ProcessModelComAuthenticationLevel.Pkt
  - System.Web.Configuration.ProcessModelComAuthenticationLevel.PktIntegrity
  - System.Web.Configuration.ProcessModelComAuthenticationLevel.PktPrivacy
  langs:
  - csharp
  name: ProcessModelComAuthenticationLevel
  nameWithType: ProcessModelComAuthenticationLevel
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel
  type: Enum
  summary: "Especifica o nível de autenticação de segurança do DCOM."
  remarks: "O ProcessModelComAuthenticationLevel enumera os valores a serem usados quando você define o <xref:System.Web.Configuration.ProcessModelSection.ComAuthenticationLevel%2A>propriedade.</xref:System.Web.Configuration.ProcessModelSection.ComAuthenticationLevel%2A>       O padrão é conectar.      > [!NOTE] > ProcessModelComAuthenticationLevel as configurações são relevantes apenas quando você usar o modelo de processo do ASP.NET (serviços de informações da Internet [IIS] 5.n ou modo compatível no IIS 6 somente)."
  example:
  - "The following code example shows how to get the current <xref:System.Web.Configuration.ProcessModelSection.ComAuthenticationLevel%2A> property value and then set the <xref:System.Web.Configuration.ProcessModelSection.ComAuthenticationLevel%2A> property to a new value of Call.  \n  \n [!code-cs[System.Web.Configuration.ProcessModelSection#21](~/add/codesnippet/csharp/t-system.web.configurati_40_1.cs)]\n [!code-vb[System.Web.Configuration.ProcessModelSection#21](~/add/codesnippet/visualbasic/t-system.web.configurati_40_1.vb)]"
  syntax:
    content: public enum ProcessModelComAuthenticationLevel
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.Call
  id: Call
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  langs:
  - csharp
  name: Call
  nameWithType: ProcessModelComAuthenticationLevel.Call
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.Call
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Especifica que o DCOM autentica as credenciais do cliente. Esse campo é constante."
  remarks: "O DCOM autentica as credenciais do cliente quando o servidor recebe a solicitação no início de cada chamada de procedimento remoto."
  syntax:
    content: Call
    return:
      type: System.Web.Configuration.ProcessModelComAuthenticationLevel
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.Connect
  id: Connect
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  langs:
  - csharp
  name: Connect
  nameWithType: ProcessModelComAuthenticationLevel.Connect
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.Connect
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Especifica que o DCOM autentica as credenciais do cliente. Esse campo é constante."
  remarks: "DCOM autentica as credenciais do cliente somente quando o cliente estabelece uma relação com o servidor.       Este é o valor padrão."
  syntax:
    content: Connect
    return:
      type: System.Web.Configuration.ProcessModelComAuthenticationLevel
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.Default
  id: Default
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  langs:
  - csharp
  name: Default
  nameWithType: ProcessModelComAuthenticationLevel.Default
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.Default
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Especifica que o DCOM determina o nível de autenticação. Esse campo é constante."
  remarks: "DCOM determina o nível de autenticação usando seu algoritmo normal de negociação de segurança."
  syntax:
    content: Default
    return:
      type: System.Web.Configuration.ProcessModelComAuthenticationLevel
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.None
  id: None
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  langs:
  - csharp
  name: None
  nameWithType: ProcessModelComAuthenticationLevel.None
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.None
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Especifica nenhuma autenticação. Esse campo é constante."
  syntax:
    content: None
    return:
      type: System.Web.Configuration.ProcessModelComAuthenticationLevel
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.Pkt
  id: Pkt
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  langs:
  - csharp
  name: Pkt
  nameWithType: ProcessModelComAuthenticationLevel.Pkt
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.Pkt
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Especifica que o DCOM verifica se todos os dados recebidos do cliente esperado. Esse campo é constante."
  remarks: "Os transportes de datagrama sempre usam a autenticação de Pkt."
  syntax:
    content: Pkt
    return:
      type: System.Web.Configuration.ProcessModelComAuthenticationLevel
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.PktIntegrity
  id: PktIntegrity
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  langs:
  - csharp
  name: PktIntegrity
  nameWithType: ProcessModelComAuthenticationLevel.PktIntegrity
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.PktIntegrity
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Especifica que o DCOM autentica e verifica os dados transferidos. Esse campo é constante."
  remarks: "DCOM verifica que nenhum dos dados transferidos entre o cliente e o servidor foi modificado."
  syntax:
    content: PktIntegrity
    return:
      type: System.Web.Configuration.ProcessModelComAuthenticationLevel
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.PktPrivacy
  id: PktPrivacy
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  langs:
  - csharp
  name: PktPrivacy
  nameWithType: ProcessModelComAuthenticationLevel.PktPrivacy
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.PktPrivacy
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Especifica que o DCOM autentica todos os níveis anteriores e faz a criptografia. Esse campo é constante."
  remarks: "DCOM autentica todos os níveis anteriores e criptografa o valor do argumento de cada chamada de procedimento remoto."
  syntax:
    content: PktPrivacy
    return:
      type: System.Web.Configuration.ProcessModelComAuthenticationLevel
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.Call
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  isExternal: false
  name: Call
  nameWithType: ProcessModelComAuthenticationLevel.Call
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.Call
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel
  parent: System.Web.Configuration
  isExternal: false
  name: ProcessModelComAuthenticationLevel
  nameWithType: ProcessModelComAuthenticationLevel
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.Connect
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  isExternal: false
  name: Connect
  nameWithType: ProcessModelComAuthenticationLevel.Connect
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.Connect
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.Default
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  isExternal: false
  name: Default
  nameWithType: ProcessModelComAuthenticationLevel.Default
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.Default
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.None
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  isExternal: false
  name: None
  nameWithType: ProcessModelComAuthenticationLevel.None
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.None
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.Pkt
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  isExternal: false
  name: Pkt
  nameWithType: ProcessModelComAuthenticationLevel.Pkt
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.Pkt
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.PktIntegrity
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  isExternal: false
  name: PktIntegrity
  nameWithType: ProcessModelComAuthenticationLevel.PktIntegrity
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.PktIntegrity
- uid: System.Web.Configuration.ProcessModelComAuthenticationLevel.PktPrivacy
  parent: System.Web.Configuration.ProcessModelComAuthenticationLevel
  isExternal: false
  name: PktPrivacy
  nameWithType: ProcessModelComAuthenticationLevel.PktPrivacy
  fullName: System.Web.Configuration.ProcessModelComAuthenticationLevel.PktPrivacy
