### YamlMime:ManagedReference
items:
- uid: System.Configuration.SpecialSettingAttribute
  id: SpecialSettingAttribute
  children:
  - System.Configuration.SpecialSettingAttribute.#ctor(System.Configuration.SpecialSetting)
  - System.Configuration.SpecialSettingAttribute.SpecialSetting
  langs:
  - csharp
  name: SpecialSettingAttribute
  nameWithType: SpecialSettingAttribute
  fullName: System.Configuration.SpecialSettingAttribute
  type: Class
  summary: "Indica que uma propriedade de configurações do aplicativo tem um significado especial. Essa classe não pode ser herdada."
  remarks: "Determinadas propriedades de configurações do aplicativo tem um significado especial que altera a maneira na qual sua configurações associadas em provedor deve processá-los. O SpecialSettingAttribute é usado para identificar tais propriedades. Essa classe usa a <xref:System.Configuration.SpecialSetting?displayProperty=fullName>enumeração para indicar qual categoria especial, a propriedade pertence.</xref:System.Configuration.SpecialSetting?displayProperty=fullName>       SpecialSettingAttribute só pode ser aplicado à classe de configurações ou para a propriedade de configurações individuais.       Para obter um exemplo de como um provedor de configurações lida com a SpecialSettingAttribute, consulte o <xref:System.Configuration.LocalFileSettingsProvider.GetPropertyValues%2A>método de <xref:System.Configuration.LocalFileSettingsProvider>classe.</xref:System.Configuration.LocalFileSettingsProvider> </xref:System.Configuration.LocalFileSettingsProvider.GetPropertyValues%2A>"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Property)]

      public sealed class SpecialSettingAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SpecialSettingAttribute.#ctor(System.Configuration.SpecialSetting)
  id: '#ctor(System.Configuration.SpecialSetting)'
  parent: System.Configuration.SpecialSettingAttribute
  langs:
  - csharp
  name: SpecialSettingAttribute(SpecialSetting)
  nameWithType: SpecialSettingAttribute.SpecialSettingAttribute(SpecialSetting)
  fullName: System.Configuration.SpecialSettingAttribute.SpecialSettingAttribute(SpecialSetting)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Configuration.SpecialSettingAttribute&quot;> </xref> classe."
  syntax:
    content: public SpecialSettingAttribute (System.Configuration.SpecialSetting specialSetting);
    parameters:
    - id: specialSetting
      type: System.Configuration.SpecialSetting
      description: "Um <xref href=&quot;System.Configuration.SpecialSetting&quot;> </xref> valor de enumeração define a categoria da propriedade de configurações do aplicativo."
  overload: System.Configuration.SpecialSettingAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SpecialSettingAttribute.SpecialSetting
  id: SpecialSetting
  parent: System.Configuration.SpecialSettingAttribute
  langs:
  - csharp
  name: SpecialSetting
  nameWithType: SpecialSettingAttribute.SpecialSetting
  fullName: System.Configuration.SpecialSettingAttribute.SpecialSetting
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Obtém o valor que descreve a categoria especial de configuração da propriedade de configurações do aplicativo."
  remarks: "A propriedade SpecialSetting está definida no <xref:System.Configuration.SpecialSettingAttribute.%23ctor%2A>construtor desta classe.</xref:System.Configuration.SpecialSettingAttribute.%23ctor%2A>"
  syntax:
    content: public System.Configuration.SpecialSetting SpecialSetting { get; }
    return:
      type: System.Configuration.SpecialSetting
      description: "Um <xref href=&quot;System.Configuration.SpecialSetting&quot;> </xref> valor de enumeração define a categoria da propriedade de configurações do aplicativo."
  overload: System.Configuration.SpecialSettingAttribute.SpecialSetting*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SpecialSettingAttribute.#ctor(System.Configuration.SpecialSetting)
  parent: System.Configuration.SpecialSettingAttribute
  isExternal: false
  name: SpecialSettingAttribute(SpecialSetting)
  nameWithType: SpecialSettingAttribute.SpecialSettingAttribute(SpecialSetting)
  fullName: System.Configuration.SpecialSettingAttribute.SpecialSettingAttribute(SpecialSetting)
- uid: System.Configuration.SpecialSetting
  parent: System.Configuration
  isExternal: false
  name: SpecialSetting
  nameWithType: SpecialSetting
  fullName: System.Configuration.SpecialSetting
- uid: System.Configuration.SpecialSettingAttribute.SpecialSetting
  parent: System.Configuration.SpecialSettingAttribute
  isExternal: false
  name: SpecialSetting
  nameWithType: SpecialSettingAttribute.SpecialSetting
  fullName: System.Configuration.SpecialSettingAttribute.SpecialSetting
- uid: System.Configuration.SpecialSettingAttribute.#ctor*
  parent: System.Configuration.SpecialSettingAttribute
  isExternal: false
  name: SpecialSettingAttribute
  nameWithType: SpecialSettingAttribute.SpecialSettingAttribute
- uid: System.Configuration.SpecialSettingAttribute.SpecialSetting*
  parent: System.Configuration.SpecialSettingAttribute
  isExternal: false
  name: SpecialSetting
  nameWithType: SpecialSettingAttribute.SpecialSetting
