### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.NamedPipeTransportSecurity
  id: NamedPipeTransportSecurity
  children:
  - System.ServiceModel.NamedPipeTransportSecurity.#ctor
  - System.ServiceModel.NamedPipeTransportSecurity.ProtectionLevel
  langs:
  - csharp
  name: NamedPipeTransportSecurity
  nameWithType: NamedPipeTransportSecurity
  fullName: System.ServiceModel.NamedPipeTransportSecurity
  type: Class
  summary: "Fornece propriedades que controlam o nível de proteção de um pipe nomeado."
  remarks: "Essa classe é usada por <xref:System.ServiceModel.NetNamedPipeSecurity.Transport%2A>para definir as configurações de segurança de nível de transporte de uma associação.</xref:System.ServiceModel.NetNamedPipeSecurity.Transport%2A>"
  syntax:
    content: public sealed class NamedPipeTransportSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.NamedPipeTransportSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.NamedPipeTransportSecurity
  langs:
  - csharp
  name: NamedPipeTransportSecurity()
  nameWithType: NamedPipeTransportSecurity.NamedPipeTransportSecurity()
  fullName: System.ServiceModel.NamedPipeTransportSecurity.NamedPipeTransportSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Inicializa uma nova instância do <xref href=&quot;System.ServiceModel.NamedPipeTransportSecurity&quot;> </xref> classe."
  syntax:
    content: public NamedPipeTransportSecurity ();
    parameters: []
  overload: System.ServiceModel.NamedPipeTransportSecurity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.NamedPipeTransportSecurity.ProtectionLevel
  id: ProtectionLevel
  parent: System.ServiceModel.NamedPipeTransportSecurity
  langs:
  - csharp
  name: ProtectionLevel
  nameWithType: NamedPipeTransportSecurity.ProtectionLevel
  fullName: System.ServiceModel.NamedPipeTransportSecurity.ProtectionLevel
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Especifica a proteção para o pipe nomeado."
  remarks: "O membro de enumeração retornado indica os serviços de segurança solicitados para o fluxo autenticado.       Os valores válidos são os seguintes:- <xref:System.Net.Security.ProtectionLevel>- <xref:System.Net.Security.ProtectionLevel>- <xref:System.Net.Security.ProtectionLevel></xref:System.Net.Security.ProtectionLevel> </xref:System.Net.Security.ProtectionLevel> </xref:System.Net.Security.ProtectionLevel>"
  syntax:
    content: public System.Net.Security.ProtectionLevel ProtectionLevel { get; set; }
    return:
      type: System.Net.Security.ProtectionLevel
      description: "A <xref href=&quot;System.Net.Security.ProtectionLevel&quot;></xref>. O padrão é <xref href=&quot;System.Net.Security.ProtectionLevel&quot;> </xref>."
  overload: System.ServiceModel.NamedPipeTransportSecurity.ProtectionLevel*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "O valor não é válido <xref href=&quot;System.Net.Security.ProtectionLevel&quot;> </xref>."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.ServiceModel.NamedPipeTransportSecurity.#ctor
  parent: System.ServiceModel.NamedPipeTransportSecurity
  isExternal: false
  name: NamedPipeTransportSecurity()
  nameWithType: NamedPipeTransportSecurity.NamedPipeTransportSecurity()
  fullName: System.ServiceModel.NamedPipeTransportSecurity.NamedPipeTransportSecurity()
- uid: System.ServiceModel.NamedPipeTransportSecurity.ProtectionLevel
  parent: System.ServiceModel.NamedPipeTransportSecurity
  isExternal: false
  name: ProtectionLevel
  nameWithType: NamedPipeTransportSecurity.ProtectionLevel
  fullName: System.ServiceModel.NamedPipeTransportSecurity.ProtectionLevel
- uid: System.Net.Security.ProtectionLevel
  parent: System.Net.Security
  isExternal: false
  name: ProtectionLevel
  nameWithType: ProtectionLevel
  fullName: System.Net.Security.ProtectionLevel
- uid: System.ServiceModel.NamedPipeTransportSecurity.#ctor*
  parent: System.ServiceModel.NamedPipeTransportSecurity
  isExternal: false
  name: NamedPipeTransportSecurity
  nameWithType: NamedPipeTransportSecurity.NamedPipeTransportSecurity
- uid: System.ServiceModel.NamedPipeTransportSecurity.ProtectionLevel*
  parent: System.ServiceModel.NamedPipeTransportSecurity
  isExternal: false
  name: ProtectionLevel
  nameWithType: NamedPipeTransportSecurity.ProtectionLevel
