### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement
  id: IBindingConfigurationElement
  children:
  - System.ServiceModel.Configuration.IBindingConfigurationElement.ApplyConfiguration(System.ServiceModel.Channels.Binding)
  - System.ServiceModel.Configuration.IBindingConfigurationElement.CloseTimeout
  - System.ServiceModel.Configuration.IBindingConfigurationElement.Name
  - System.ServiceModel.Configuration.IBindingConfigurationElement.OpenTimeout
  - System.ServiceModel.Configuration.IBindingConfigurationElement.ReceiveTimeout
  - System.ServiceModel.Configuration.IBindingConfigurationElement.SendTimeout
  langs:
  - csharp
  name: IBindingConfigurationElement
  nameWithType: IBindingConfigurationElement
  fullName: System.ServiceModel.Configuration.IBindingConfigurationElement
  type: Interface
  summary: "Fornece as definições de configuração básica para um elemento de associação."
  syntax:
    content: public interface IBindingConfigurationElement
  implements: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.ApplyConfiguration(System.ServiceModel.Channels.Binding)
  id: ApplyConfiguration(System.ServiceModel.Channels.Binding)
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  langs:
  - csharp
  name: ApplyConfiguration(Binding)
  nameWithType: IBindingConfigurationElement.ApplyConfiguration(Binding)
  fullName: System.ServiceModel.Configuration.IBindingConfigurationElement.ApplyConfiguration(Binding)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Aplica-se o conteúdo da associação especificada para essa seção de configuração de associação."
  syntax:
    content: public void ApplyConfiguration (System.ServiceModel.Channels.Binding binding);
    parameters:
    - id: binding
      type: System.ServiceModel.Channels.Binding
      description: "Uma associação."
  overload: System.ServiceModel.Configuration.IBindingConfigurationElement.ApplyConfiguration*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.CloseTimeout
  id: CloseTimeout
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  langs:
  - csharp
  name: CloseTimeout
  nameWithType: IBindingConfigurationElement.CloseTimeout
  fullName: System.ServiceModel.Configuration.IBindingConfigurationElement.CloseTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém o intervalo de tempo fornecido para uma operação de fechamento concluir."
  syntax:
    content: public TimeSpan CloseTimeout { get; }
    return:
      type: System.TimeSpan
      description: "O <xref:System.TimeSpan>que especifica quanto tempo a operação de fechamento deve concluir antes do tempo limite.</xref:System.TimeSpan>"
  overload: System.ServiceModel.Configuration.IBindingConfigurationElement.CloseTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.Name
  id: Name
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  langs:
  - csharp
  name: Name
  nameWithType: IBindingConfigurationElement.Name
  fullName: System.ServiceModel.Configuration.IBindingConfigurationElement.Name
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém o nome da associação."
  syntax:
    content: public string Name { get; }
    return:
      type: System.String
      description: "O nome da associação."
  overload: System.ServiceModel.Configuration.IBindingConfigurationElement.Name*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.OpenTimeout
  id: OpenTimeout
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  langs:
  - csharp
  name: OpenTimeout
  nameWithType: IBindingConfigurationElement.OpenTimeout
  fullName: System.ServiceModel.Configuration.IBindingConfigurationElement.OpenTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém o intervalo de tempo fornecido para uma operação de abertura concluir."
  syntax:
    content: public TimeSpan OpenTimeout { get; }
    return:
      type: System.TimeSpan
      description: "O <xref:System.TimeSpan>que especifica quanto tempo a operação de abertura deve concluir antes do tempo limite.</xref:System.TimeSpan>"
  overload: System.ServiceModel.Configuration.IBindingConfigurationElement.OpenTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.ReceiveTimeout
  id: ReceiveTimeout
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  langs:
  - csharp
  name: ReceiveTimeout
  nameWithType: IBindingConfigurationElement.ReceiveTimeout
  fullName: System.ServiceModel.Configuration.IBindingConfigurationElement.ReceiveTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém o intervalo de tempo fornecido para uma operação de recebimento concluir."
  syntax:
    content: public TimeSpan ReceiveTimeout { get; }
    return:
      type: System.TimeSpan
      description: "O <xref:System.TimeSpan>que especifica quanto tempo a operação de recebimento tem para concluir antes do tempo limite.</xref:System.TimeSpan>"
  overload: System.ServiceModel.Configuration.IBindingConfigurationElement.ReceiveTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.SendTimeout
  id: SendTimeout
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  langs:
  - csharp
  name: SendTimeout
  nameWithType: IBindingConfigurationElement.SendTimeout
  fullName: System.ServiceModel.Configuration.IBindingConfigurationElement.SendTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém o intervalo de tempo fornecido para uma operação de envio concluir."
  syntax:
    content: public TimeSpan SendTimeout { get; }
    return:
      type: System.TimeSpan
      description: "O <xref:System.TimeSpan>que especifica quanto tempo a operação de envio deve concluir antes do tempo limite.</xref:System.TimeSpan>"
  overload: System.ServiceModel.Configuration.IBindingConfigurationElement.SendTimeout*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.ApplyConfiguration(System.ServiceModel.Channels.Binding)
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  isExternal: false
  name: ApplyConfiguration(Binding)
  nameWithType: IBindingConfigurationElement.ApplyConfiguration(Binding)
  fullName: System.ServiceModel.Configuration.IBindingConfigurationElement.ApplyConfiguration(Binding)
- uid: System.ServiceModel.Channels.Binding
  parent: System.ServiceModel.Channels
  isExternal: true
  name: Binding
  nameWithType: Binding
  fullName: System.ServiceModel.Channels.Binding
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.CloseTimeout
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  isExternal: false
  name: CloseTimeout
  nameWithType: IBindingConfigurationElement.CloseTimeout
  fullName: System.ServiceModel.Configuration.IBindingConfigurationElement.CloseTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.Name
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  isExternal: false
  name: Name
  nameWithType: IBindingConfigurationElement.Name
  fullName: System.ServiceModel.Configuration.IBindingConfigurationElement.Name
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.OpenTimeout
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  isExternal: false
  name: OpenTimeout
  nameWithType: IBindingConfigurationElement.OpenTimeout
  fullName: System.ServiceModel.Configuration.IBindingConfigurationElement.OpenTimeout
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.ReceiveTimeout
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  isExternal: false
  name: ReceiveTimeout
  nameWithType: IBindingConfigurationElement.ReceiveTimeout
  fullName: System.ServiceModel.Configuration.IBindingConfigurationElement.ReceiveTimeout
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.SendTimeout
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  isExternal: false
  name: SendTimeout
  nameWithType: IBindingConfigurationElement.SendTimeout
  fullName: System.ServiceModel.Configuration.IBindingConfigurationElement.SendTimeout
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.ApplyConfiguration*
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  isExternal: false
  name: ApplyConfiguration
  nameWithType: IBindingConfigurationElement.ApplyConfiguration
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.CloseTimeout*
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  isExternal: false
  name: CloseTimeout
  nameWithType: IBindingConfigurationElement.CloseTimeout
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.Name*
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  isExternal: false
  name: Name
  nameWithType: IBindingConfigurationElement.Name
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.OpenTimeout*
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  isExternal: false
  name: OpenTimeout
  nameWithType: IBindingConfigurationElement.OpenTimeout
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.ReceiveTimeout*
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  isExternal: false
  name: ReceiveTimeout
  nameWithType: IBindingConfigurationElement.ReceiveTimeout
- uid: System.ServiceModel.Configuration.IBindingConfigurationElement.SendTimeout*
  parent: System.ServiceModel.Configuration.IBindingConfigurationElement
  isExternal: false
  name: SendTimeout
  nameWithType: IBindingConfigurationElement.SendTimeout
