### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement
  id: AuthorizationPolicyTypeElement
  children:
  - System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.#ctor
  - System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.#ctor(System.String)
  - System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.PolicyType
  - System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.Properties
  langs:
  - csharp
  name: AuthorizationPolicyTypeElement
  nameWithType: AuthorizationPolicyTypeElement
  fullName: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement
  type: Class
  summary: "Contém um elemento de configuração que especifica uma política de autorização, que permite que a transformação de um conjunto de declarações de entrada em outro conjunto de declarações. Controle de acesso pode ser concedido ou negado com base no que. Essa classe não pode ser herdada."
  remarks: "O modelo de controle de acesso oferece suporte a um conjunto de políticas de autorização como tipos de provisionamento. Este elemento define um conjunto de implementações de diretiva de autorização, que permitem a transformação de um conjunto de declarações de entrada em outro conjunto de declarações. Um conjunto de declarações, em seguida, é operado e uma decisão de controle de acesso é atingida depois da fase de transformação de diretiva de autorização."
  syntax:
    content: 'public sealed class AuthorizationPolicyTypeElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement
  langs:
  - csharp
  name: AuthorizationPolicyTypeElement()
  nameWithType: AuthorizationPolicyTypeElement.AuthorizationPolicyTypeElement()
  fullName: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.AuthorizationPolicyTypeElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.ServiceModel.Configuration.AuthorizationPolicyTypeElement&quot;> </xref> classe."
  syntax:
    content: public AuthorizationPolicyTypeElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement
  langs:
  - csharp
  name: AuthorizationPolicyTypeElement(String)
  nameWithType: AuthorizationPolicyTypeElement.AuthorizationPolicyTypeElement(String)
  fullName: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.AuthorizationPolicyTypeElement(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.ServiceModel.Configuration.AuthorizationPolicyTypeElement&quot;> </xref> classe com o tipo de política especificada."
  syntax:
    content: public AuthorizationPolicyTypeElement (string policyType);
    parameters:
    - id: policyType
      type: System.String
      description: "O tipo de política a ser inicializado."
  overload: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>policyType</code>é <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> ou vazio."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.PolicyType
  id: PolicyType
  parent: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement
  langs:
  - csharp
  name: PolicyType
  nameWithType: AuthorizationPolicyTypeElement.PolicyType
  fullName: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.PolicyType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém ou define o tipo de política."
  syntax:
    content: public string PolicyType { get; set; }
    return:
      type: System.String
      description: "O tipo de política."
  overload: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.PolicyType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement
  langs:
  - csharp
  name: Properties
  nameWithType: AuthorizationPolicyTypeElement.Properties
  fullName: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A ser adicionado."
  overload: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.#ctor
  parent: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement
  isExternal: false
  name: AuthorizationPolicyTypeElement()
  nameWithType: AuthorizationPolicyTypeElement.AuthorizationPolicyTypeElement()
  fullName: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.AuthorizationPolicyTypeElement()
- uid: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.#ctor(System.String)
  parent: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement
  isExternal: false
  name: AuthorizationPolicyTypeElement(String)
  nameWithType: AuthorizationPolicyTypeElement.AuthorizationPolicyTypeElement(String)
  fullName: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.AuthorizationPolicyTypeElement(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.PolicyType
  parent: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement
  isExternal: false
  name: PolicyType
  nameWithType: AuthorizationPolicyTypeElement.PolicyType
  fullName: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.PolicyType
- uid: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.Properties
  parent: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement
  isExternal: false
  name: Properties
  nameWithType: AuthorizationPolicyTypeElement.Properties
  fullName: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.#ctor*
  parent: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement
  isExternal: false
  name: AuthorizationPolicyTypeElement
  nameWithType: AuthorizationPolicyTypeElement.AuthorizationPolicyTypeElement
- uid: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.PolicyType*
  parent: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement
  isExternal: false
  name: PolicyType
  nameWithType: AuthorizationPolicyTypeElement.PolicyType
- uid: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.Properties*
  parent: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement
  isExternal: false
  name: Properties
  nameWithType: AuthorizationPolicyTypeElement.Properties
