### YamlMime:ManagedReference
items:
- uid: System.Activities.WorkflowApplicationTerminatedException
  id: WorkflowApplicationTerminatedException
  children:
  - System.Activities.WorkflowApplicationTerminatedException.#ctor
  - System.Activities.WorkflowApplicationTerminatedException.#ctor(System.String)
  - System.Activities.WorkflowApplicationTerminatedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Activities.WorkflowApplicationTerminatedException.#ctor(System.String,System.Exception)
  - System.Activities.WorkflowApplicationTerminatedException.#ctor(System.String,System.Guid)
  - System.Activities.WorkflowApplicationTerminatedException.#ctor(System.String,System.Guid,System.Exception)
  langs:
  - csharp
  name: WorkflowApplicationTerminatedException
  nameWithType: WorkflowApplicationTerminatedException
  fullName: System.Activities.WorkflowApplicationTerminatedException
  type: Class
  summary: "Uma exceção que é lançada quando uma operação em uma instância de fluxo de trabalho não é válida porque a instância foi encerrada."
  syntax:
    content: 'public class WorkflowApplicationTerminatedException : System.Activities.WorkflowApplicationCompletedException'
  inheritance:
  - System.Exception
  - System.Activities.WorkflowApplicationException
  - System.Activities.WorkflowApplicationCompletedException
  implements: []
  inheritedMembers:
  - System.Activities.WorkflowApplicationException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Activities.WorkflowApplicationException.InstanceId
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationTerminatedException.#ctor
  id: '#ctor'
  parent: System.Activities.WorkflowApplicationTerminatedException
  langs:
  - csharp
  name: WorkflowApplicationTerminatedException()
  nameWithType: WorkflowApplicationTerminatedException.WorkflowApplicationTerminatedException()
  fullName: System.Activities.WorkflowApplicationTerminatedException.WorkflowApplicationTerminatedException()
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Cria uma nova instância do <xref href=&quot;System.Activities.WorkflowApplicationTerminatedException&quot;> </xref> classe."
  syntax:
    content: public WorkflowApplicationTerminatedException ();
    parameters: []
  overload: System.Activities.WorkflowApplicationTerminatedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationTerminatedException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Activities.WorkflowApplicationTerminatedException
  langs:
  - csharp
  name: WorkflowApplicationTerminatedException(String)
  nameWithType: WorkflowApplicationTerminatedException.WorkflowApplicationTerminatedException(String)
  fullName: System.Activities.WorkflowApplicationTerminatedException.WorkflowApplicationTerminatedException(String)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Cria uma nova instância do <xref href=&quot;System.Activities.WorkflowApplicationTerminatedException&quot;> </xref> classe com uma descrição de cadeia de caracteres de texto da exceção."
  syntax:
    content: public WorkflowApplicationTerminatedException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Uma descrição do aplicativo foi finalizado a exceção."
  overload: System.Activities.WorkflowApplicationTerminatedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationTerminatedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Activities.WorkflowApplicationTerminatedException
  langs:
  - csharp
  name: WorkflowApplicationTerminatedException(SerializationInfo,StreamingContext)
  nameWithType: WorkflowApplicationTerminatedException.WorkflowApplicationTerminatedException(SerializationInfo,StreamingContext)
  fullName: System.Activities.WorkflowApplicationTerminatedException.WorkflowApplicationTerminatedException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Cria uma nova instância do <xref href=&quot;System.Activities.WorkflowApplicationTerminatedException&quot;> </xref> classe com as informações de serialização e contexto necessárias para recuperar dados sobre esta exceção de um fluxo serializado."
  syntax:
    content: protected WorkflowApplicationTerminatedException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "Todas as informações necessárias para serializar ou desserializar o aplicativo foi finalizado o objeto de exceção."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "A origem e destino de um determinado fluxo serializado e um contexto adicional definido pelo chamador."
  overload: System.Activities.WorkflowApplicationTerminatedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationTerminatedException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Activities.WorkflowApplicationTerminatedException
  langs:
  - csharp
  name: WorkflowApplicationTerminatedException(String,Exception)
  nameWithType: WorkflowApplicationTerminatedException.WorkflowApplicationTerminatedException(String,Exception)
  fullName: System.Activities.WorkflowApplicationTerminatedException.WorkflowApplicationTerminatedException(String,Exception)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Cria uma nova instância do <xref href=&quot;System.Activities.WorkflowApplicationTerminatedException&quot;> </xref> classe com uma descrição de cadeia de caracteres de texto da exceção e com uma exceção que é a causa do aplicativo finalizado a exceção."
  syntax:
    content: public WorkflowApplicationTerminatedException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Uma descrição do aplicativo foi finalizado a exceção."
    - id: innerException
      type: System.Exception
      description: "Uma exceção que tenha uma relação causal para o aplicativo foi finalizado a exceção. A exceção de aplicativo finalizado é gerada em resposta a exceção interna e pode usar as informações da exceção interna para tratar o erro mais adequadamente."
  overload: System.Activities.WorkflowApplicationTerminatedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationTerminatedException.#ctor(System.String,System.Guid)
  id: '#ctor(System.String,System.Guid)'
  parent: System.Activities.WorkflowApplicationTerminatedException
  langs:
  - csharp
  name: WorkflowApplicationTerminatedException(String,Guid)
  nameWithType: WorkflowApplicationTerminatedException.WorkflowApplicationTerminatedException(String,Guid)
  fullName: System.Activities.WorkflowApplicationTerminatedException.WorkflowApplicationTerminatedException(String,Guid)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Cria uma nova instância do <xref href=&quot;System.Activities.WorkflowApplicationTerminatedException&quot;> </xref> classe com uma descrição de cadeia de caracteres de texto da exceção e com um identificador exclusivo para ele."
  syntax:
    content: public WorkflowApplicationTerminatedException (string message, Guid instanceId);
    parameters:
    - id: message
      type: System.String
      description: "Uma descrição do aplicativo foi finalizado a exceção."
    - id: instanceId
      type: System.Guid
      description: "Um identificador globalmente exclusivo."
  overload: System.Activities.WorkflowApplicationTerminatedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationTerminatedException.#ctor(System.String,System.Guid,System.Exception)
  id: '#ctor(System.String,System.Guid,System.Exception)'
  parent: System.Activities.WorkflowApplicationTerminatedException
  langs:
  - csharp
  name: WorkflowApplicationTerminatedException(String,Guid,Exception)
  nameWithType: WorkflowApplicationTerminatedException.WorkflowApplicationTerminatedException(String,Guid,Exception)
  fullName: System.Activities.WorkflowApplicationTerminatedException.WorkflowApplicationTerminatedException(String,Guid,Exception)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Cria uma nova instância do <xref href=&quot;System.Activities.WorkflowApplicationTerminatedException&quot;> </xref> classe com uma descrição de cadeia de caracteres de texto da exceção, um identificador exclusivo e uma exceção que é a causa da exceção atual."
  syntax:
    content: public WorkflowApplicationTerminatedException (string message, Guid instanceId, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Uma descrição do aplicativo foi finalizado a exceção."
    - id: instanceId
      type: System.Guid
      description: "Um identificador globalmente exclusivo."
    - id: innerException
      type: System.Exception
      description: "Uma exceção que tenha uma relação causal para o aplicativo foi finalizado a exceção. A exceção de aplicativo finalizado é gerada em resposta a exceção interna e pode usar as informações da exceção interna para tratar o erro mais adequadamente."
  overload: System.Activities.WorkflowApplicationTerminatedException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Activities.WorkflowApplicationCompletedException
  isExternal: false
  name: System.Activities.WorkflowApplicationCompletedException
- uid: System.Activities.WorkflowApplicationTerminatedException.#ctor
  parent: System.Activities.WorkflowApplicationTerminatedException
  isExternal: false
  name: WorkflowApplicationTerminatedException()
  nameWithType: WorkflowApplicationTerminatedException.WorkflowApplicationTerminatedException()
  fullName: System.Activities.WorkflowApplicationTerminatedException.WorkflowApplicationTerminatedException()
- uid: System.Activities.WorkflowApplicationTerminatedException.#ctor(System.String)
  parent: System.Activities.WorkflowApplicationTerminatedException
  isExternal: false
  name: WorkflowApplicationTerminatedException(String)
  nameWithType: WorkflowApplicationTerminatedException.WorkflowApplicationTerminatedException(String)
  fullName: System.Activities.WorkflowApplicationTerminatedException.WorkflowApplicationTerminatedException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Activities.WorkflowApplicationTerminatedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Activities.WorkflowApplicationTerminatedException
  isExternal: false
  name: WorkflowApplicationTerminatedException(SerializationInfo,StreamingContext)
  nameWithType: WorkflowApplicationTerminatedException.WorkflowApplicationTerminatedException(SerializationInfo,StreamingContext)
  fullName: System.Activities.WorkflowApplicationTerminatedException.WorkflowApplicationTerminatedException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Activities.WorkflowApplicationTerminatedException.#ctor(System.String,System.Exception)
  parent: System.Activities.WorkflowApplicationTerminatedException
  isExternal: false
  name: WorkflowApplicationTerminatedException(String,Exception)
  nameWithType: WorkflowApplicationTerminatedException.WorkflowApplicationTerminatedException(String,Exception)
  fullName: System.Activities.WorkflowApplicationTerminatedException.WorkflowApplicationTerminatedException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Activities.WorkflowApplicationTerminatedException.#ctor(System.String,System.Guid)
  parent: System.Activities.WorkflowApplicationTerminatedException
  isExternal: false
  name: WorkflowApplicationTerminatedException(String,Guid)
  nameWithType: WorkflowApplicationTerminatedException.WorkflowApplicationTerminatedException(String,Guid)
  fullName: System.Activities.WorkflowApplicationTerminatedException.WorkflowApplicationTerminatedException(String,Guid)
- uid: System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Activities.WorkflowApplicationTerminatedException.#ctor(System.String,System.Guid,System.Exception)
  parent: System.Activities.WorkflowApplicationTerminatedException
  isExternal: false
  name: WorkflowApplicationTerminatedException(String,Guid,Exception)
  nameWithType: WorkflowApplicationTerminatedException.WorkflowApplicationTerminatedException(String,Guid,Exception)
  fullName: System.Activities.WorkflowApplicationTerminatedException.WorkflowApplicationTerminatedException(String,Guid,Exception)
- uid: System.Activities.WorkflowApplicationTerminatedException.#ctor*
  parent: System.Activities.WorkflowApplicationTerminatedException
  isExternal: false
  name: WorkflowApplicationTerminatedException
  nameWithType: WorkflowApplicationTerminatedException.WorkflowApplicationTerminatedException
