### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsManageability
  id: SettingsManageability
  children:
  - System.Configuration.SettingsManageability.Roaming
  langs:
  - csharp
  name: SettingsManageability
  nameWithType: SettingsManageability
  fullName: System.Configuration.SettingsManageability
  type: Enum
  summary: "Fornece valores para indicar quais serviços devem ser disponibilizados para configurações de aplicativo."
  remarks: "O ttribute é usado para aplicar as propriedades de configurações de aplicativos individuais e grupos de propriedades para indicar que serviços predefinidos especiais devem ser fornecidas para eles. A enumeração SettingsManageability lista os serviços que estão disponíveis. A maioria desses serviços será fornecida pelo sistema operacional Windows."
  syntax:
    content: public enum SettingsManageability
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.SettingsManageability.Roaming
  id: Roaming
  parent: System.Configuration.SettingsManageability
  langs:
  - csharp
  name: Roaming
  nameWithType: SettingsManageability.Roaming
  fullName: System.Configuration.SettingsManageability.Roaming
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Permite que as configurações de aplicativo a ser armazenado em perfis de usuário móvel. Para obter mais informações sobre perfis de usuário móvel, consulte [armazenamento isolado e Roaming](http://msdn.microsoft.com/en-us/d3cca593-4521-408d-b323-ea398d226de3)."
  syntax:
    content: Roaming
    return:
      type: System.Configuration.SettingsManageability
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.SettingsManageability.Roaming
  parent: System.Configuration.SettingsManageability
  isExternal: false
  name: Roaming
  nameWithType: SettingsManageability.Roaming
  fullName: System.Configuration.SettingsManageability.Roaming
- uid: System.Configuration.SettingsManageability
  parent: System.Configuration
  isExternal: false
  name: SettingsManageability
  nameWithType: SettingsManageability
  fullName: System.Configuration.SettingsManageability
