### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsSavingEventHandler
  id: SettingsSavingEventHandler
  langs:
  - csharp
  name: SettingsSavingEventHandler
  nameWithType: SettingsSavingEventHandler
  fullName: System.Configuration.SettingsSavingEventHandler
  type: Delegate
  summary: "Representa o método que manipulará o <xref href=&quot;System.Configuration.ApplicationSettingsBase.SettingsSaving&quot;> </xref> eventos."
  remarks: "O <xref:System.Configuration.ApplicationSettingsBase.SettingsSaving>evento ocorre somente antes de um grupo de configurações serão mantidas, geralmente durante a execução do <xref:System.Configuration.ApplicationSettingsBase.Save%2A>método de uma classe wrapper derivado de <xref:System.Configuration.ApplicationSettingsBase>.</xref:System.Configuration.ApplicationSettingsBase> </xref:System.Configuration.ApplicationSettingsBase.Save%2A> de aplicativo</xref:System.Configuration.ApplicationSettingsBase.SettingsSaving>"
  syntax:
    content: public delegate void SettingsSavingEventHandler(object sender, CancelEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
