### YamlMime:ManagedReference
items:
- uid: System.Transactions.Configuration.TransactionsSectionGroup
  id: TransactionsSectionGroup
  children:
  - System.Transactions.Configuration.TransactionsSectionGroup.#ctor
  - System.Transactions.Configuration.TransactionsSectionGroup.DefaultSettings
  - System.Transactions.Configuration.TransactionsSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  - System.Transactions.Configuration.TransactionsSectionGroup.MachineSettings
  langs:
  - csharp
  name: TransactionsSectionGroup
  nameWithType: TransactionsSectionGroup
  fullName: System.Transactions.Configuration.TransactionsSectionGroup
  type: Class
  summary: "Representa uma seção de configuração que encapsula e permite a passagem de todos os elementos XML de configuração transação e atributos que estão dentro da seção de configuração. Essa classe não pode ser herdada."
  syntax:
    content: 'public sealed class TransactionsSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  platform:
  - net462
- uid: System.Transactions.Configuration.TransactionsSectionGroup.#ctor
  id: '#ctor'
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  langs:
  - csharp
  name: TransactionsSectionGroup()
  nameWithType: TransactionsSectionGroup.TransactionsSectionGroup()
  fullName: System.Transactions.Configuration.TransactionsSectionGroup.TransactionsSectionGroup()
  type: Constructor
  assemblies:
  - System.Transactions
  namespace: System.Transactions.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Transactions.Configuration.TransactionsSectionGroup&quot;> </xref> classe."
  syntax:
    content: public TransactionsSectionGroup ();
    parameters: []
  overload: System.Transactions.Configuration.TransactionsSectionGroup.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Transactions.Configuration.TransactionsSectionGroup.DefaultSettings
  id: DefaultSettings
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  langs:
  - csharp
  name: DefaultSettings
  nameWithType: TransactionsSectionGroup.DefaultSettings
  fullName: System.Transactions.Configuration.TransactionsSectionGroup.DefaultSettings
  type: Property
  assemblies:
  - System.Transactions
  namespace: System.Transactions.Configuration
  summary: "Obtém as configurações padrão usadas para inicializar os elementos e atributos em uma seção de transações."
  syntax:
    content: public System.Transactions.Configuration.DefaultSettingsSection DefaultSettings { get; }
    return:
      type: System.Transactions.Configuration.DefaultSettingsSection
      description: "Um <xref href=&quot;System.Transactions.Configuration.DefaultSettingsSection&quot;> </xref> que representa as configurações padrão. O padrão é um <xref href=&quot;System.Transactions.Configuration.DefaultSettingsSection&quot;> </xref> que é preenchida com valores padrão."
  overload: System.Transactions.Configuration.TransactionsSectionGroup.DefaultSettings*
  exceptions: []
  platform:
  - net462
- uid: System.Transactions.Configuration.TransactionsSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  id: GetSectionGroup(System.Configuration.Configuration)
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  langs:
  - csharp
  name: GetSectionGroup(Configuration)
  nameWithType: TransactionsSectionGroup.GetSectionGroup(Configuration)
  fullName: System.Transactions.Configuration.TransactionsSectionGroup.GetSectionGroup(Configuration)
  type: Method
  assemblies:
  - System.Transactions
  namespace: System.Transactions.Configuration
  summary: "Fornece acesso estático para uma <xref href=&quot;System.Transactions.Configuration.TransactionsSectionGroup&quot;> </xref>."
  syntax:
    content: public static System.Transactions.Configuration.TransactionsSectionGroup GetSectionGroup (System.Configuration.Configuration config);
    parameters:
    - id: config
      type: System.Configuration.Configuration
      description: "Um <xref href=&quot;System.Configuration.Configuration&quot;> </xref> que representa as definições de configuração que se aplicam a um determinado computador, aplicativo ou recurso."
    return:
      type: System.Transactions.Configuration.TransactionsSectionGroup
      description: "A <xref href=&quot;System.Transactions.Configuration.TransactionsSectionGroup&quot;></xref> object."
  overload: System.Transactions.Configuration.TransactionsSectionGroup.GetSectionGroup*
  exceptions: []
  platform:
  - net462
- uid: System.Transactions.Configuration.TransactionsSectionGroup.MachineSettings
  id: MachineSettings
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  langs:
  - csharp
  name: MachineSettings
  nameWithType: TransactionsSectionGroup.MachineSettings
  fullName: System.Transactions.Configuration.TransactionsSectionGroup.MachineSettings
  type: Property
  assemblies:
  - System.Transactions
  namespace: System.Transactions.Configuration
  summary: "Obtém as definições de configuração definida no nível do computador."
  syntax:
    content: public System.Transactions.Configuration.MachineSettingsSection MachineSettings { get; }
    return:
      type: System.Transactions.Configuration.MachineSettingsSection
      description: "Um <xref href=&quot;System.Transactions.Configuration.MachineSettingsSection&quot;> </xref> que representa as definições de configuração no nível do computador. O padrão é um <xref href=&quot;System.Transactions.Configuration.MachineSettingsSection&quot;> </xref> que é preenchida com valores padrão."
  overload: System.Transactions.Configuration.TransactionsSectionGroup.MachineSettings*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: System.Configuration.ConfigurationSectionGroup
- uid: System.Transactions.Configuration.TransactionsSectionGroup.#ctor
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  isExternal: false
  name: TransactionsSectionGroup()
  nameWithType: TransactionsSectionGroup.TransactionsSectionGroup()
  fullName: System.Transactions.Configuration.TransactionsSectionGroup.TransactionsSectionGroup()
- uid: System.Transactions.Configuration.TransactionsSectionGroup.DefaultSettings
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  isExternal: false
  name: DefaultSettings
  nameWithType: TransactionsSectionGroup.DefaultSettings
  fullName: System.Transactions.Configuration.TransactionsSectionGroup.DefaultSettings
- uid: System.Transactions.Configuration.DefaultSettingsSection
  parent: System.Transactions.Configuration
  isExternal: false
  name: DefaultSettingsSection
  nameWithType: DefaultSettingsSection
  fullName: System.Transactions.Configuration.DefaultSettingsSection
- uid: System.Transactions.Configuration.TransactionsSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  isExternal: false
  name: GetSectionGroup(Configuration)
  nameWithType: TransactionsSectionGroup.GetSectionGroup(Configuration)
  fullName: System.Transactions.Configuration.TransactionsSectionGroup.GetSectionGroup(Configuration)
- uid: System.Transactions.Configuration.TransactionsSectionGroup
  parent: System.Transactions.Configuration
  isExternal: false
  name: TransactionsSectionGroup
  nameWithType: TransactionsSectionGroup
  fullName: System.Transactions.Configuration.TransactionsSectionGroup
- uid: System.Configuration.Configuration
  parent: System.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: System.Transactions.Configuration.TransactionsSectionGroup.MachineSettings
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  isExternal: false
  name: MachineSettings
  nameWithType: TransactionsSectionGroup.MachineSettings
  fullName: System.Transactions.Configuration.TransactionsSectionGroup.MachineSettings
- uid: System.Transactions.Configuration.MachineSettingsSection
  parent: System.Transactions.Configuration
  isExternal: false
  name: MachineSettingsSection
  nameWithType: MachineSettingsSection
  fullName: System.Transactions.Configuration.MachineSettingsSection
- uid: System.Transactions.Configuration.TransactionsSectionGroup.#ctor*
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  isExternal: false
  name: TransactionsSectionGroup
  nameWithType: TransactionsSectionGroup.TransactionsSectionGroup
- uid: System.Transactions.Configuration.TransactionsSectionGroup.DefaultSettings*
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  isExternal: false
  name: DefaultSettings
  nameWithType: TransactionsSectionGroup.DefaultSettings
- uid: System.Transactions.Configuration.TransactionsSectionGroup.GetSectionGroup*
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  isExternal: false
  name: GetSectionGroup
  nameWithType: TransactionsSectionGroup.GetSectionGroup
- uid: System.Transactions.Configuration.TransactionsSectionGroup.MachineSettings*
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  isExternal: false
  name: MachineSettings
  nameWithType: TransactionsSectionGroup.MachineSettings
