### YamlMime:ManagedReference
items:
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs
  id: CreatingCookieEventArgs
  children:
  - System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet
  - System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential
  - System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent
  - System.Web.ApplicationServices.CreatingCookieEventArgs.Password
  - System.Web.ApplicationServices.CreatingCookieEventArgs.UserName
  langs:
  - csharp
  name: CreatingCookieEventArgs
  nameWithType: CreatingCookieEventArgs
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs
  type: Class
  summary: "Fornece dados para o <xref href=&quot;System.Web.ApplicationServices.AuthenticationService.CreatingCookie&quot;> </xref> eventos."
  remarks: "A classe CreatingCookieEventArgs fornece valores para qualquer <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie>manipulador de eventos.</xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> Usando as propriedades dessa classe, você pode recuperar as credenciais do usuário quando você cria um cookie de autenticação personalizada.       O <xref:System.Web.ApplicationServices.AuthenticationService>classe gera o <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie>evento quando ele define o cookie de autenticação, depois que as credenciais de usuário autenticadas.</xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> </xref:System.Web.ApplicationServices.AuthenticationService> O <xref:System.Web.ApplicationServices.AuthenticationService>classe constrói um objeto CreatingCookieEventArgs e passá-lo para qualquer <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie>manipulador de eventos.</xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> </xref:System.Web.ApplicationServices.AuthenticationService>       Recuperar as credenciais do usuário por meio de <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.UserName%2A> <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.Password%2A>, e <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential%2A>Propriedades.</xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential%2A> </xref:System.Web.ApplicationServices.CreatingCookieEventArgs.Password%2A></xref:System.Web.ApplicationServices.CreatingCookieEventArgs.UserName%2A> O <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential%2A>propriedade pode conter todos os valores personalizados que você precisa para autenticar, como um número de identificação.</xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential%2A> O <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent%2A>propriedade indica se o cookie de autenticação deve ser mantido após a sessão atual.</xref:System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent%2A> Definir o <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet%2A>propriedade `true` se você criar o cookie de autenticação, para que o <xref:System.Web.ApplicationServices.AuthenticationService>classe não cria o cookie.</xref:System.Web.ApplicationServices.AuthenticationService> </xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet%2A>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> event. The handler retrieves user values from the CreatingCookieEventArgs object to customize the authentication cookie. The handler saves the value from the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential%2A> property in the authentication ticket and sets the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet%2A> property to `true` to indicate that the authentication cookie has been created.  \n  \n [!code-cs[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/csharp/t-system.web.application_1_1.asax)]\n [!code-vb[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/visualbasic/t-system.web.application_1_1.asax)]"
  syntax:
    content: 'public class CreatingCookieEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet
  id: CookieIsSet
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  langs:
  - csharp
  name: CookieIsSet
  nameWithType: CreatingCookieEventArgs.CookieIsSet
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Obtém ou define um valor que indica se o cookie de autenticação foi criado."
  remarks: "O <xref:System.Web.ApplicationServices.AuthenticationService>classe verifica a propriedade CookieIsSet para determinar se o cookie de autenticação foi criado.</xref:System.Web.ApplicationServices.AuthenticationService> Defina esse valor como `true` se você criar um cookie de autenticação em um manipulador de eventos para o <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie>evento.</xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> Se CookieIsSet for definido como `false` (o valor padrão), o <xref:System.Web.ApplicationServices.AuthenticationService>classe cria um cookie de autenticação, isso substitui qualquer cookie que você criou no manipulador para o <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie>evento.</xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> </xref:System.Web.ApplicationServices.AuthenticationService>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> event. The handler retrieves user values from the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs> object to customize the authentication cookie. The CookieIsSet property is set to `true` after the authentication ticket is created.  \n  \n [!code-cs[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/csharp/p-system.web.application_11_1.asax)]\n [!code-vb[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/visualbasic/p-system.web.application_11_1.asax)]"
  syntax:
    content: public bool CookieIsSet { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se o cookie de autenticação foi criado; Caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential
  id: CustomCredential
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  langs:
  - csharp
  name: CustomCredential
  nameWithType: CreatingCookieEventArgs.CustomCredential
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Obtém os valores de autenticação adicional que são fornecidos pelo usuário."
  remarks: "Você pode usar a propriedade CustomCredential para recuperar valores personalizados no tíquete de autenticação. A propriedade CustomCredential contém o valor passado para o <xref:System.Web.ApplicationServices.AuthenticationService.Login%2A>método.</xref:System.Web.ApplicationServices.AuthenticationService.Login%2A> Normalmente, essa propriedade é usada para passar valores personalizados que devem ser validados com o nome de usuário e senha, como um número de identificação. Se mais de um valor é armazenado na propriedade, você deve analisar a propriedade CustomCredential para recuperar valores."
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> event. The handler retrieves user values from the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs> object in order to customize the authentication cookie. The value passed in the CustomCredential property is stored in the <xref:System.Web.Security.FormsAuthenticationTicket.UserData%2A> property of the forms authentication ticket.  \n  \n> [!NOTE]\n>  Store the CustomCredential property in a cookie only when you know that the data in the property is not sensitive. Malicious users can access the values in the cookie.  \n  \n [!code-cs[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/csharp/p-system.web.application_2_1.asax)]\n [!code-vb[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/visualbasic/p-system.web.application_2_1.asax)]"
  syntax:
    content: public string CustomCredential { get; }
    return:
      type: System.String
      description: "Os valores personalizados necessários para autenticação, que não seja o nome de usuário e senha."
  overload: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent
  id: IsPersistent
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  langs:
  - csharp
  name: IsPersistent
  nameWithType: CreatingCookieEventArgs.IsPersistent
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Obtém um valor que indica se o cookie de autenticação deve ser mantido além da sessão atual."
  remarks: "Quando você cria um <xref:System.Web.Security.FormsAuthenticationTicket>do objeto, você pode usar a propriedade IsPersistent para especificar se o cookie de autenticação é mantido além da sessão atual.</xref:System.Web.Security.FormsAuthenticationTicket>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> event. The handler retrieves user values from the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs> object in order to customize the authentication cookie. The <xref:System.Web.Security.FormsAuthenticationTicket.IsPersistent%2A> property of the <xref:System.Web.Security.FormsAuthenticationTicket> object is set to the value in the IsPersistent property.  \n  \n [!code-cs[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/csharp/p-system.web.application_0_1.asax)]\n [!code-vb[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/visualbasic/p-system.web.application_0_1.asax)]"
  syntax:
    content: public bool IsPersistent { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se o cookie deve ser retido além da sessão atual; Caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.Password
  id: Password
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  langs:
  - csharp
  name: Password
  nameWithType: CreatingCookieEventArgs.Password
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.Password
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Obtém a senha do usuário."
  remarks: "Você pode usar a propriedade de senha para recuperar a senha quando você definir valores personalizados no tíquete de autenticação.      > [!NOTE] > Não salvar o valor da propriedade Password no tíquete de autenticação. Um usuário mal-intencionado pode acessar o cookie e recuperar a senha, mesmo que o cookie é criptografado."
  syntax:
    content: public string Password { get; }
    return:
      type: System.String
      description: "A senha fornecida pelo usuário para autenticação."
  overload: System.Web.ApplicationServices.CreatingCookieEventArgs.Password*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName
  id: UserName
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  langs:
  - csharp
  name: UserName
  nameWithType: CreatingCookieEventArgs.UserName
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Obtém o nome do usuário."
  remarks: "Você pode usar a propriedade de nome de usuário para recuperar o nome de autenticação quando você definir valores personalizados no tíquete de autenticação. Normalmente, você define o <xref:System.Web.Security.FormsAuthenticationTicket.Name%2A>propriedade o <xref:System.Web.Security.FormsAuthenticationTicket>objeto para o valor de nome de usuário.</xref:System.Web.Security.FormsAuthenticationTicket> </xref:System.Web.Security.FormsAuthenticationTicket.Name%2A>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> event. The handler retrieves user values from the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs> object to customize the authentication cookie. The <xref:System.Web.Security.FormsAuthenticationTicket.Name%2A> property is set to the values of the UserName property.  \n  \n [!code-cs[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/csharp/p-system.web.application_6_1.asax)]\n [!code-vb[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/visualbasic/p-system.web.application_6_1.asax)]"
  syntax:
    content: public string UserName { get; }
    return:
      type: System.String
      description: "O nome fornecido pelo usuário para autenticação."
  overload: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: CookieIsSet
  nameWithType: CreatingCookieEventArgs.CookieIsSet
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: CustomCredential
  nameWithType: CreatingCookieEventArgs.CustomCredential
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: IsPersistent
  nameWithType: CreatingCookieEventArgs.IsPersistent
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.Password
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: Password
  nameWithType: CreatingCookieEventArgs.Password
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.Password
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: UserName
  nameWithType: CreatingCookieEventArgs.UserName
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet*
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: CookieIsSet
  nameWithType: CreatingCookieEventArgs.CookieIsSet
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential*
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: CustomCredential
  nameWithType: CreatingCookieEventArgs.CustomCredential
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent*
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: IsPersistent
  nameWithType: CreatingCookieEventArgs.IsPersistent
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.Password*
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: Password
  nameWithType: CreatingCookieEventArgs.Password
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName*
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: UserName
  nameWithType: CreatingCookieEventArgs.UserName
