### YamlMime:ManagedReference
items:
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  id: ITransformerConfigurationControl
  children:
  - System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
  - System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
  langs:
  - csharp
  name: ITransformerConfigurationControl
  nameWithType: ITransformerConfigurationControl
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  type: Interface
  summary: "Define o contrato que implementa um controle para atuar como um controle de configuração para um transformador em uma conexão de Web Parts."
  remarks: "Um controle de configuração pode ser exibido quando um transformador requer que um usuário para configurá-lo. O controle de configuração fornece uma interface de usuário (UI) que permite que o usuário selecione quais valores serão transformados. Ela é processada em uma zona de conexões. O <xref:System.Web.UI.WebControls.WebParts.WebPartTransformer.CreateConfigurationControl%2A?displayProperty=fullName>método retorna um controle de configuração.</xref:System.Web.UI.WebControls.WebParts.WebPartTransformer.CreateConfigurationControl%2A?displayProperty=fullName>       Você pode substituir o <xref:System.Web.UI.WebControls.WebParts.WebPartTransformer.CreateConfigurationControl%2A>método quando o transformador requer uma interface do usuário personalizada.</xref:System.Web.UI.WebControls.WebParts.WebPartTransformer.CreateConfigurationControl%2A> O controle de configuração deve implementar ITransformerConfigurationControl interface, que inclui o <xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled>e <xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded>eventos.</xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded> </xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled> Esses eventos ocorrem quando um controle de transformador não foi configurado ou configurado com êxito, respectivamente."
  syntax:
    content: public interface ITransformerConfigurationControl
  implements: []
  platform:
  - net462
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
  id: Cancelled
  parent: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  langs:
  - csharp
  name: Cancelled
  nameWithType: ITransformerConfigurationControl.Cancelled
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
  type: Event
  assemblies:
  - System.Web
  namespace: System.Web.UI.WebControls.WebParts
  summary: "Ocorre quando a configuração de transformador não foi concluída."
  remarks: "O controle de Web Parts que implementa <xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl>gera esse evento quando uma configuração de transformador não for concluída, porque o usuário cancelou a configuração ou a configuração não pôde ser executada.</xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl>"
  syntax:
    content: public event EventHandler Cancelled;
    return:
      type: System.EventHandler
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
  id: Succeeded
  parent: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  langs:
  - csharp
  name: Succeeded
  nameWithType: ITransformerConfigurationControl.Succeeded
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
  type: Event
  assemblies:
  - System.Web
  namespace: System.Web.UI.WebControls.WebParts
  summary: "Ocorre quando a configuração de transformador for concluída com êxito."
  remarks: "O controle de Web Parts que implementa <xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl>gera esse evento quando uma configuração de transformador for concluída com êxito.</xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl>"
  syntax:
    content: public event EventHandler Succeeded;
    return:
      type: System.EventHandler
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
  parent: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  isExternal: false
  name: Cancelled
  nameWithType: ITransformerConfigurationControl.Cancelled
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
- uid: System.EventHandler
  parent: System
  isExternal: true
  name: EventHandler
  nameWithType: EventHandler
  fullName: System.EventHandler
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
  parent: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  isExternal: false
  name: Succeeded
  nameWithType: ITransformerConfigurationControl.Succeeded
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
