### YamlMime:ManagedReference
items:
- uid: System.Web.UnvalidatedRequestValuesBase
  id: UnvalidatedRequestValuesBase
  children:
  - System.Web.UnvalidatedRequestValuesBase.#ctor
  - System.Web.UnvalidatedRequestValuesBase.Cookies
  - System.Web.UnvalidatedRequestValuesBase.Files
  - System.Web.UnvalidatedRequestValuesBase.Form
  - System.Web.UnvalidatedRequestValuesBase.Headers
  - System.Web.UnvalidatedRequestValuesBase.Item(System.String)
  - System.Web.UnvalidatedRequestValuesBase.Path
  - System.Web.UnvalidatedRequestValuesBase.PathInfo
  - System.Web.UnvalidatedRequestValuesBase.QueryString
  - System.Web.UnvalidatedRequestValuesBase.RawUrl
  - System.Web.UnvalidatedRequestValuesBase.Url
  langs:
  - csharp
  name: UnvalidatedRequestValuesBase
  nameWithType: UnvalidatedRequestValuesBase
  fullName: System.Web.UnvalidatedRequestValuesBase
  type: Class
  summary: "Serve como a classe base para classes que fornecem acesso a valores de solicitação HTTP sem disparar a validação de solicitação do ASP.NET."
  remarks: "Para obter informações sobre a validação de solicitação, consulte <xref:System.Web.UnvalidatedRequestValues>.</xref:System.Web.UnvalidatedRequestValues>"
  syntax:
    content: public abstract class UnvalidatedRequestValuesBase
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValuesBase.#ctor
  id: '#ctor'
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: UnvalidatedRequestValuesBase()
  nameWithType: UnvalidatedRequestValuesBase.UnvalidatedRequestValuesBase()
  fullName: System.Web.UnvalidatedRequestValuesBase.UnvalidatedRequestValuesBase()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Chamado a partir de construtores em classes derivadas para inicializar o <xref href=&quot;System.Web.UnvalidatedRequestValuesBase&quot;> </xref> classe."
  syntax:
    content: protected UnvalidatedRequestValuesBase ();
    parameters: []
  overload: System.Web.UnvalidatedRequestValuesBase.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValuesBase.Cookies
  id: Cookies
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: Cookies
  nameWithType: UnvalidatedRequestValuesBase.Cookies
  fullName: System.Web.UnvalidatedRequestValuesBase.Cookies
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Quando substituído em uma classe derivada, obtém a coleção de cookies que o cliente enviou, sem disparar a validação de solicitação do ASP.NET."
  syntax:
    content: public virtual System.Web.HttpCookieCollection Cookies { get; }
    return:
      type: System.Web.HttpCookieCollection
      description: "Os cookies de solicitação HTTP."
  overload: System.Web.UnvalidatedRequestValuesBase.Cookies*
  exceptions:
  - type: System.NotImplementedException
    commentId: T:System.NotImplementedException
    description: "A propriedade não está implementada."
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValuesBase.Files
  id: Files
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: Files
  nameWithType: UnvalidatedRequestValuesBase.Files
  fullName: System.Web.UnvalidatedRequestValuesBase.Files
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Quando substituído em uma classe derivada, obtém a coleção de arquivos que o cliente carregado, sem disparar a validação de solicitação do ASP.NET."
  syntax:
    content: public virtual System.Web.HttpFileCollectionBase Files { get; }
    return:
      type: System.Web.HttpFileCollectionBase
      description: "Os arquivos de solicitação HTTP."
  overload: System.Web.UnvalidatedRequestValuesBase.Files*
  exceptions:
  - type: System.NotImplementedException
    commentId: T:System.NotImplementedException
    description: "A propriedade não está implementada."
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValuesBase.Form
  id: Form
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: Form
  nameWithType: UnvalidatedRequestValuesBase.Form
  fullName: System.Web.UnvalidatedRequestValuesBase.Form
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Quando substituído em uma classe derivada, obtém a coleção de variáveis de forma que o cliente enviou, sem disparar a validação de solicitação do ASP.NET."
  syntax:
    content: public virtual System.Collections.Specialized.NameValueCollection Form { get; }
    return:
      type: System.Collections.Specialized.NameValueCollection
      description: "As variáveis de formulário de solicitação HTTP."
  overload: System.Web.UnvalidatedRequestValuesBase.Form*
  exceptions:
  - type: System.NotImplementedException
    commentId: T:System.NotImplementedException
    description: "A propriedade não está implementada."
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValuesBase.Headers
  id: Headers
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: Headers
  nameWithType: UnvalidatedRequestValuesBase.Headers
  fullName: System.Web.UnvalidatedRequestValuesBase.Headers
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Quando substituído em uma classe derivada, obtém a coleção de cabeçalhos HTTP que o cliente enviou, sem disparar a validação de solicitação do ASP.NET."
  syntax:
    content: public virtual System.Collections.Specialized.NameValueCollection Headers { get; }
    return:
      type: System.Collections.Specialized.NameValueCollection
      description: "Os cabeçalhos da solicitação de HTTP."
  overload: System.Web.UnvalidatedRequestValuesBase.Headers*
  exceptions:
  - type: System.NotImplementedException
    commentId: T:System.NotImplementedException
    description: "A propriedade não está implementada."
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValuesBase.Item(System.String)
  id: Item(System.String)
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: Item(String)
  nameWithType: UnvalidatedRequestValuesBase.Item(String)
  fullName: System.Web.UnvalidatedRequestValuesBase.Item(String)
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Quando substituído em uma classe derivada, obtém o objeto especificado do <> </> *>, <> </> *>, <> </> *>, ou <> </> *> coleção, sem disparar a validação de solicitação do ASP.NET."
  syntax:
    content: public virtual string this[string field] { get; }
    parameters:
    - id: field
      type: System.String
      description: "A chave do objeto a ser recuperada."
    return:
      type: System.String
      description: "O objeto especificado pelo <code> field </code> parâmetro."
  overload: System.Web.UnvalidatedRequestValuesBase.Item*
  exceptions:
  - type: System.NotImplementedException
    commentId: T:System.NotImplementedException
    description: "A propriedade não está implementada."
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValuesBase.Path
  id: Path
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: Path
  nameWithType: UnvalidatedRequestValuesBase.Path
  fullName: System.Web.UnvalidatedRequestValuesBase.Path
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Quando substituído em uma classe derivada, obtém o caminho virtual do recurso solicitado sem disparar a validação de solicitação do ASP.NET."
  syntax:
    content: public virtual string Path { get; }
    return:
      type: System.String
      description: "O caminho virtual."
  overload: System.Web.UnvalidatedRequestValuesBase.Path*
  exceptions:
  - type: System.NotImplementedException
    commentId: T:System.NotImplementedException
    description: "A propriedade não está implementada."
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValuesBase.PathInfo
  id: PathInfo
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: PathInfo
  nameWithType: UnvalidatedRequestValuesBase.PathInfo
  fullName: System.Web.UnvalidatedRequestValuesBase.PathInfo
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Quando substituído em uma classe derivada, obtém informações de caminho adicionais para um recurso que tem uma extensão de URL, sem disparar a validação de solicitação do ASP.NET."
  syntax:
    content: public virtual string PathInfo { get; }
    return:
      type: System.String
      description: "Uma cadeia de caracteres que contém informações de caminho adicionais para um recurso."
  overload: System.Web.UnvalidatedRequestValuesBase.PathInfo*
  exceptions:
  - type: System.NotImplementedException
    commentId: T:System.NotImplementedException
    description: "A propriedade não está implementada."
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValuesBase.QueryString
  id: QueryString
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: QueryString
  nameWithType: UnvalidatedRequestValuesBase.QueryString
  fullName: System.Web.UnvalidatedRequestValuesBase.QueryString
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Quando substituído em uma classe derivada, obtém a coleção de consulta HTTP variáveis de cadeia de caracteres que o cliente enviou, sem disparar a validação de solicitação do ASP.NET."
  syntax:
    content: public virtual System.Collections.Specialized.NameValueCollection QueryString { get; }
    return:
      type: System.Collections.Specialized.NameValueCollection
      description: "A coleção de variáveis de cadeia de caracteres de consulta enviada pelo cliente."
  overload: System.Web.UnvalidatedRequestValuesBase.QueryString*
  exceptions:
  - type: System.NotImplementedException
    commentId: T:System.NotImplementedException
    description: "A propriedade não está implementada."
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValuesBase.RawUrl
  id: RawUrl
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: RawUrl
  nameWithType: UnvalidatedRequestValuesBase.RawUrl
  fullName: System.Web.UnvalidatedRequestValuesBase.RawUrl
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Quando substituído em uma classe derivada, obtém a parte da URL solicitada que segue o nome do site, sem disparar a validação de solicitação do ASP.NET."
  remarks: "Se a URL de solicitação completa é `http://www.contoso.com/default.aspx?id=44`, o valor de RawUrl é `/default.aspx?id=44`."
  syntax:
    content: public virtual string RawUrl { get; }
    return:
      type: System.String
      description: "A parte da URL que segue o nome do site."
  overload: System.Web.UnvalidatedRequestValuesBase.RawUrl*
  exceptions:
  - type: System.NotImplementedException
    commentId: T:System.NotImplementedException
    description: "A propriedade não está implementada."
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValuesBase.Url
  id: Url
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: Url
  nameWithType: UnvalidatedRequestValuesBase.Url
  fullName: System.Web.UnvalidatedRequestValuesBase.Url
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Quando substituído em uma classe derivada, obtém os dados de URL para a solicitação sem disparar a validação de solicitação."
  remarks: "Você pode recuperar dados de URL, como o número da porta, nome de host, informações de caminho e dados sobre o usuário a <xref:System.Uri>objeto retornado por essa propriedade.</xref:System.Uri>"
  syntax:
    content: public virtual Uri Url { get; }
    return:
      type: System.Uri
      description: "Um objeto que contém os dados de URL para a solicitação."
  overload: System.Web.UnvalidatedRequestValuesBase.Url*
  exceptions:
  - type: System.NotImplementedException
    commentId: T:System.NotImplementedException
    description: "A propriedade não está implementada."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.NotImplementedException
  isExternal: true
  name: System.NotImplementedException
- uid: System.Web.UnvalidatedRequestValuesBase.#ctor
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: UnvalidatedRequestValuesBase()
  nameWithType: UnvalidatedRequestValuesBase.UnvalidatedRequestValuesBase()
  fullName: System.Web.UnvalidatedRequestValuesBase.UnvalidatedRequestValuesBase()
- uid: System.Web.UnvalidatedRequestValuesBase.Cookies
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Cookies
  nameWithType: UnvalidatedRequestValuesBase.Cookies
  fullName: System.Web.UnvalidatedRequestValuesBase.Cookies
- uid: System.Web.HttpCookieCollection
  parent: System.Web
  isExternal: false
  name: HttpCookieCollection
  nameWithType: HttpCookieCollection
  fullName: System.Web.HttpCookieCollection
- uid: System.Web.UnvalidatedRequestValuesBase.Files
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Files
  nameWithType: UnvalidatedRequestValuesBase.Files
  fullName: System.Web.UnvalidatedRequestValuesBase.Files
- uid: System.Web.HttpFileCollectionBase
  parent: System.Web
  isExternal: true
  name: HttpFileCollectionBase
  nameWithType: HttpFileCollectionBase
  fullName: System.Web.HttpFileCollectionBase
- uid: System.Web.UnvalidatedRequestValuesBase.Form
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Form
  nameWithType: UnvalidatedRequestValuesBase.Form
  fullName: System.Web.UnvalidatedRequestValuesBase.Form
- uid: System.Collections.Specialized.NameValueCollection
  parent: System.Collections.Specialized
  isExternal: false
  name: NameValueCollection
  nameWithType: NameValueCollection
  fullName: System.Collections.Specialized.NameValueCollection
- uid: System.Web.UnvalidatedRequestValuesBase.Headers
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Headers
  nameWithType: UnvalidatedRequestValuesBase.Headers
  fullName: System.Web.UnvalidatedRequestValuesBase.Headers
- uid: System.Web.UnvalidatedRequestValuesBase.Item(System.String)
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Item(String)
  nameWithType: UnvalidatedRequestValuesBase.Item(String)
  fullName: System.Web.UnvalidatedRequestValuesBase.Item(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.UnvalidatedRequestValuesBase.Path
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Path
  nameWithType: UnvalidatedRequestValuesBase.Path
  fullName: System.Web.UnvalidatedRequestValuesBase.Path
- uid: System.Web.UnvalidatedRequestValuesBase.PathInfo
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: PathInfo
  nameWithType: UnvalidatedRequestValuesBase.PathInfo
  fullName: System.Web.UnvalidatedRequestValuesBase.PathInfo
- uid: System.Web.UnvalidatedRequestValuesBase.QueryString
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: QueryString
  nameWithType: UnvalidatedRequestValuesBase.QueryString
  fullName: System.Web.UnvalidatedRequestValuesBase.QueryString
- uid: System.Web.UnvalidatedRequestValuesBase.RawUrl
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: RawUrl
  nameWithType: UnvalidatedRequestValuesBase.RawUrl
  fullName: System.Web.UnvalidatedRequestValuesBase.RawUrl
- uid: System.Web.UnvalidatedRequestValuesBase.Url
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Url
  nameWithType: UnvalidatedRequestValuesBase.Url
  fullName: System.Web.UnvalidatedRequestValuesBase.Url
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.Web.UnvalidatedRequestValuesBase.#ctor*
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: UnvalidatedRequestValuesBase
  nameWithType: UnvalidatedRequestValuesBase.UnvalidatedRequestValuesBase
- uid: System.Web.UnvalidatedRequestValuesBase.Cookies*
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Cookies
  nameWithType: UnvalidatedRequestValuesBase.Cookies
- uid: System.Web.UnvalidatedRequestValuesBase.Files*
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Files
  nameWithType: UnvalidatedRequestValuesBase.Files
- uid: System.Web.UnvalidatedRequestValuesBase.Form*
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Form
  nameWithType: UnvalidatedRequestValuesBase.Form
- uid: System.Web.UnvalidatedRequestValuesBase.Headers*
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Headers
  nameWithType: UnvalidatedRequestValuesBase.Headers
- uid: System.Web.UnvalidatedRequestValuesBase.Item*
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Item
  nameWithType: UnvalidatedRequestValuesBase.Item
- uid: System.Web.UnvalidatedRequestValuesBase.Path*
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Path
  nameWithType: UnvalidatedRequestValuesBase.Path
- uid: System.Web.UnvalidatedRequestValuesBase.PathInfo*
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: PathInfo
  nameWithType: UnvalidatedRequestValuesBase.PathInfo
- uid: System.Web.UnvalidatedRequestValuesBase.QueryString*
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: QueryString
  nameWithType: UnvalidatedRequestValuesBase.QueryString
- uid: System.Web.UnvalidatedRequestValuesBase.RawUrl*
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: RawUrl
  nameWithType: UnvalidatedRequestValuesBase.RawUrl
- uid: System.Web.UnvalidatedRequestValuesBase.Url*
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Url
  nameWithType: UnvalidatedRequestValuesBase.Url
