### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsLoadedEventHandler
  id: SettingsLoadedEventHandler
  langs:
  - csharp
  name: SettingsLoadedEventHandler
  nameWithType: SettingsLoadedEventHandler
  fullName: System.Configuration.SettingsLoadedEventHandler
  type: Delegate
  summary: "Representa o método que manipulará o <xref href=&quot;System.Configuration.ApplicationSettingsBase.SettingsLoaded&quot;> </xref> eventos."
  remarks: "O <xref:System.Configuration.ApplicationSettingsBase.SettingsLoaded>evento ocorre quando as configurações são recuperadas de um provedor.</xref:System.Configuration.ApplicationSettingsBase.SettingsLoaded> Esse evento é acionado uma vez para cada provedor."
  syntax:
    content: public delegate void SettingsLoadedEventHandler(object sender, SettingsLoadedEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
