### YamlMime:ManagedReference
items:
- uid: System.Web.ApplicationShutdownReason
  id: ApplicationShutdownReason
  children:
  - System.Web.ApplicationShutdownReason.BinDirChangeOrDirectoryRename
  - System.Web.ApplicationShutdownReason.BrowsersDirChangeOrDirectoryRename
  - System.Web.ApplicationShutdownReason.BuildManagerChange
  - System.Web.ApplicationShutdownReason.ChangeInGlobalAsax
  - System.Web.ApplicationShutdownReason.ChangeInSecurityPolicyFile
  - System.Web.ApplicationShutdownReason.CodeDirChangeOrDirectoryRename
  - System.Web.ApplicationShutdownReason.ConfigurationChange
  - System.Web.ApplicationShutdownReason.HostingEnvironment
  - System.Web.ApplicationShutdownReason.HttpRuntimeClose
  - System.Web.ApplicationShutdownReason.IdleTimeout
  - System.Web.ApplicationShutdownReason.InitializationError
  - System.Web.ApplicationShutdownReason.MaxRecompilationsReached
  - System.Web.ApplicationShutdownReason.None
  - System.Web.ApplicationShutdownReason.PhysicalApplicationPathChanged
  - System.Web.ApplicationShutdownReason.ResourcesDirChangeOrDirectoryRename
  - System.Web.ApplicationShutdownReason.UnloadAppDomainCalled
  langs:
  - csharp
  name: ApplicationShutdownReason
  nameWithType: ApplicationShutdownReason
  fullName: System.Web.ApplicationShutdownReason
  type: Enum
  summary: "Especifica o motivo do <xref href=&quot;System.AppDomain&quot;> </xref> classe desligar."
  remarks: "O ApplicationShutdownReason representa os possíveis valores para a <xref:System.Web.Hosting.HostingEnvironment.ShutdownReason%2A>propriedade de <xref:System.Web.Hosting.HostingEnvironment>classe.</xref:System.Web.Hosting.HostingEnvironment> </xref:System.Web.Hosting.HostingEnvironment.ShutdownReason%2A>"
  syntax:
    content: public enum ApplicationShutdownReason
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.BinDirChangeOrDirectoryRename
  id: BinDirChangeOrDirectoryRename
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: BinDirChangeOrDirectoryRename
  nameWithType: ApplicationShutdownReason.BinDirChangeOrDirectoryRename
  fullName: System.Web.ApplicationShutdownReason.BinDirChangeOrDirectoryRename
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Uma alteração foi feita para a pasta Bin ou arquivos."
  syntax:
    content: BinDirChangeOrDirectoryRename
    return:
      type: System.Web.ApplicationShutdownReason
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.BrowsersDirChangeOrDirectoryRename
  id: BrowsersDirChangeOrDirectoryRename
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: BrowsersDirChangeOrDirectoryRename
  nameWithType: ApplicationShutdownReason.BrowsersDirChangeOrDirectoryRename
  fullName: System.Web.ApplicationShutdownReason.BrowsersDirChangeOrDirectoryRename
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Uma alteração foi feita para a pasta App_Browsers ou arquivos."
  syntax:
    content: BrowsersDirChangeOrDirectoryRename
    return:
      type: System.Web.ApplicationShutdownReason
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.BuildManagerChange
  id: BuildManagerChange
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: BuildManagerChange
  nameWithType: ApplicationShutdownReason.BuildManagerChange
  fullName: System.Web.ApplicationShutdownReason.BuildManagerChange
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "O sistema de compilação desligue o domínio de aplicativo. O membro BuildManagerChange é introduzido no .NET Framework versão 3.5.  Para obter mais informações, consulte [versões do .NET Framework e dependências](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: BuildManagerChange
    return:
      type: System.Web.ApplicationShutdownReason
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.ChangeInGlobalAsax
  id: ChangeInGlobalAsax
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: ChangeInGlobalAsax
  nameWithType: ApplicationShutdownReason.ChangeInGlobalAsax
  fullName: System.Web.ApplicationShutdownReason.ChangeInGlobalAsax
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Foi feita uma alteração no arquivo global. asax."
  syntax:
    content: ChangeInGlobalAsax
    return:
      type: System.Web.ApplicationShutdownReason
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.ChangeInSecurityPolicyFile
  id: ChangeInSecurityPolicyFile
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: ChangeInSecurityPolicyFile
  nameWithType: ApplicationShutdownReason.ChangeInSecurityPolicyFile
  fullName: System.Web.ApplicationShutdownReason.ChangeInSecurityPolicyFile
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Uma alteração foi feita no arquivo de política de segurança de acesso do código."
  syntax:
    content: ChangeInSecurityPolicyFile
    return:
      type: System.Web.ApplicationShutdownReason
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.CodeDirChangeOrDirectoryRename
  id: CodeDirChangeOrDirectoryRename
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: CodeDirChangeOrDirectoryRename
  nameWithType: ApplicationShutdownReason.CodeDirChangeOrDirectoryRename
  fullName: System.Web.ApplicationShutdownReason.CodeDirChangeOrDirectoryRename
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Uma alteração foi feita para a pasta App_Code ou arquivos."
  syntax:
    content: CodeDirChangeOrDirectoryRename
    return:
      type: System.Web.ApplicationShutdownReason
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.ConfigurationChange
  id: ConfigurationChange
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: ConfigurationChange
  nameWithType: ApplicationShutdownReason.ConfigurationChange
  fullName: System.Web.ApplicationShutdownReason.ConfigurationChange
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Uma alteração foi feita para o arquivo de configuração de nível de aplicativo."
  syntax:
    content: ConfigurationChange
    return:
      type: System.Web.ApplicationShutdownReason
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.HostingEnvironment
  id: HostingEnvironment
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: HostingEnvironment
  nameWithType: ApplicationShutdownReason.HostingEnvironment
  fullName: System.Web.ApplicationShutdownReason.HostingEnvironment
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "O ambiente de hospedagem desligar o domínio de aplicativo."
  syntax:
    content: HostingEnvironment
    return:
      type: System.Web.ApplicationShutdownReason
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.HttpRuntimeClose
  id: HttpRuntimeClose
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: HttpRuntimeClose
  nameWithType: ApplicationShutdownReason.HttpRuntimeClose
  fullName: System.Web.ApplicationShutdownReason.HttpRuntimeClose
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Foi feita uma chamada para <xref:System.Web.HttpRuntime.Close*>.</xref:System.Web.HttpRuntime.Close*>"
  syntax:
    content: HttpRuntimeClose
    return:
      type: System.Web.ApplicationShutdownReason
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.IdleTimeout
  id: IdleTimeout
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: IdleTimeout
  nameWithType: ApplicationShutdownReason.IdleTimeout
  fullName: System.Web.ApplicationShutdownReason.IdleTimeout
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "O limite de tempo ocioso máximo foi atingido."
  syntax:
    content: IdleTimeout
    return:
      type: System.Web.ApplicationShutdownReason
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.InitializationError
  id: InitializationError
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: InitializationError
  nameWithType: ApplicationShutdownReason.InitializationError
  fullName: System.Web.ApplicationShutdownReason.InitializationError
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Um <xref href=&quot;System.AppDomain&quot;> </xref> erro de inicialização."
  syntax:
    content: InitializationError
    return:
      type: System.Web.ApplicationShutdownReason
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.MaxRecompilationsReached
  id: MaxRecompilationsReached
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: MaxRecompilationsReached
  nameWithType: ApplicationShutdownReason.MaxRecompilationsReached
  fullName: System.Web.ApplicationShutdownReason.MaxRecompilationsReached
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "O número máximo de recompilações dinâmicas de recursos foi atingido."
  syntax:
    content: MaxRecompilationsReached
    return:
      type: System.Web.ApplicationShutdownReason
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.None
  id: None
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: None
  nameWithType: ApplicationShutdownReason.None
  fullName: System.Web.ApplicationShutdownReason.None
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Não foi fornecido nenhum motivo do desligamento."
  syntax:
    content: None
    return:
      type: System.Web.ApplicationShutdownReason
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.PhysicalApplicationPathChanged
  id: PhysicalApplicationPathChanged
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: PhysicalApplicationPathChanged
  nameWithType: ApplicationShutdownReason.PhysicalApplicationPathChanged
  fullName: System.Web.ApplicationShutdownReason.PhysicalApplicationPathChanged
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Uma alteração foi feita para o caminho físico do aplicativo."
  syntax:
    content: PhysicalApplicationPathChanged
    return:
      type: System.Web.ApplicationShutdownReason
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.ResourcesDirChangeOrDirectoryRename
  id: ResourcesDirChangeOrDirectoryRename
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: ResourcesDirChangeOrDirectoryRename
  nameWithType: ApplicationShutdownReason.ResourcesDirChangeOrDirectoryRename
  fullName: System.Web.ApplicationShutdownReason.ResourcesDirChangeOrDirectoryRename
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Foi feita uma alteração na pasta App_GlobalResources ou para arquivos."
  syntax:
    content: ResourcesDirChangeOrDirectoryRename
    return:
      type: System.Web.ApplicationShutdownReason
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.UnloadAppDomainCalled
  id: UnloadAppDomainCalled
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: UnloadAppDomainCalled
  nameWithType: ApplicationShutdownReason.UnloadAppDomainCalled
  fullName: System.Web.ApplicationShutdownReason.UnloadAppDomainCalled
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Foi feita uma chamada para <xref:System.Web.HttpRuntime.UnloadAppDomain*>.</xref:System.Web.HttpRuntime.UnloadAppDomain*>"
  syntax:
    content: UnloadAppDomainCalled
    return:
      type: System.Web.ApplicationShutdownReason
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.ApplicationShutdownReason.BinDirChangeOrDirectoryRename
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: BinDirChangeOrDirectoryRename
  nameWithType: ApplicationShutdownReason.BinDirChangeOrDirectoryRename
  fullName: System.Web.ApplicationShutdownReason.BinDirChangeOrDirectoryRename
- uid: System.Web.ApplicationShutdownReason
  parent: System.Web
  isExternal: false
  name: ApplicationShutdownReason
  nameWithType: ApplicationShutdownReason
  fullName: System.Web.ApplicationShutdownReason
- uid: System.Web.ApplicationShutdownReason.BrowsersDirChangeOrDirectoryRename
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: BrowsersDirChangeOrDirectoryRename
  nameWithType: ApplicationShutdownReason.BrowsersDirChangeOrDirectoryRename
  fullName: System.Web.ApplicationShutdownReason.BrowsersDirChangeOrDirectoryRename
- uid: System.Web.ApplicationShutdownReason.BuildManagerChange
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: BuildManagerChange
  nameWithType: ApplicationShutdownReason.BuildManagerChange
  fullName: System.Web.ApplicationShutdownReason.BuildManagerChange
- uid: System.Web.ApplicationShutdownReason.ChangeInGlobalAsax
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: ChangeInGlobalAsax
  nameWithType: ApplicationShutdownReason.ChangeInGlobalAsax
  fullName: System.Web.ApplicationShutdownReason.ChangeInGlobalAsax
- uid: System.Web.ApplicationShutdownReason.ChangeInSecurityPolicyFile
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: ChangeInSecurityPolicyFile
  nameWithType: ApplicationShutdownReason.ChangeInSecurityPolicyFile
  fullName: System.Web.ApplicationShutdownReason.ChangeInSecurityPolicyFile
- uid: System.Web.ApplicationShutdownReason.CodeDirChangeOrDirectoryRename
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: CodeDirChangeOrDirectoryRename
  nameWithType: ApplicationShutdownReason.CodeDirChangeOrDirectoryRename
  fullName: System.Web.ApplicationShutdownReason.CodeDirChangeOrDirectoryRename
- uid: System.Web.ApplicationShutdownReason.ConfigurationChange
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: ConfigurationChange
  nameWithType: ApplicationShutdownReason.ConfigurationChange
  fullName: System.Web.ApplicationShutdownReason.ConfigurationChange
- uid: System.Web.ApplicationShutdownReason.HostingEnvironment
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: HostingEnvironment
  nameWithType: ApplicationShutdownReason.HostingEnvironment
  fullName: System.Web.ApplicationShutdownReason.HostingEnvironment
- uid: System.Web.ApplicationShutdownReason.HttpRuntimeClose
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: HttpRuntimeClose
  nameWithType: ApplicationShutdownReason.HttpRuntimeClose
  fullName: System.Web.ApplicationShutdownReason.HttpRuntimeClose
- uid: System.Web.ApplicationShutdownReason.IdleTimeout
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: IdleTimeout
  nameWithType: ApplicationShutdownReason.IdleTimeout
  fullName: System.Web.ApplicationShutdownReason.IdleTimeout
- uid: System.Web.ApplicationShutdownReason.InitializationError
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: InitializationError
  nameWithType: ApplicationShutdownReason.InitializationError
  fullName: System.Web.ApplicationShutdownReason.InitializationError
- uid: System.Web.ApplicationShutdownReason.MaxRecompilationsReached
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: MaxRecompilationsReached
  nameWithType: ApplicationShutdownReason.MaxRecompilationsReached
  fullName: System.Web.ApplicationShutdownReason.MaxRecompilationsReached
- uid: System.Web.ApplicationShutdownReason.None
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: None
  nameWithType: ApplicationShutdownReason.None
  fullName: System.Web.ApplicationShutdownReason.None
- uid: System.Web.ApplicationShutdownReason.PhysicalApplicationPathChanged
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: PhysicalApplicationPathChanged
  nameWithType: ApplicationShutdownReason.PhysicalApplicationPathChanged
  fullName: System.Web.ApplicationShutdownReason.PhysicalApplicationPathChanged
- uid: System.Web.ApplicationShutdownReason.ResourcesDirChangeOrDirectoryRename
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: ResourcesDirChangeOrDirectoryRename
  nameWithType: ApplicationShutdownReason.ResourcesDirChangeOrDirectoryRename
  fullName: System.Web.ApplicationShutdownReason.ResourcesDirChangeOrDirectoryRename
- uid: System.Web.ApplicationShutdownReason.UnloadAppDomainCalled
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: UnloadAppDomainCalled
  nameWithType: ApplicationShutdownReason.UnloadAppDomainCalled
  fullName: System.Web.ApplicationShutdownReason.UnloadAppDomainCalled
