### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement
  id: NetMsmqSecurityElement
  children:
  - System.ServiceModel.Configuration.NetMsmqSecurityElement.#ctor
  - System.ServiceModel.Configuration.NetMsmqSecurityElement.Message
  - System.ServiceModel.Configuration.NetMsmqSecurityElement.Mode
  - System.ServiceModel.Configuration.NetMsmqSecurityElement.Properties
  - System.ServiceModel.Configuration.NetMsmqSecurityElement.Transport
  langs:
  - csharp
  name: NetMsmqSecurityElement
  nameWithType: NetMsmqSecurityElement
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement
  type: Class
  summary: "A classe NetMsmqSecurityElement encapsula os recursos de segurança MSMQ disponíveis ao usar o <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> associação."
  remarks: "Objetos desse tipo são criados por meio da criação de uma instância do <xref:System.ServiceModel.NetMsmqBinding>associação.</xref:System.ServiceModel.NetMsmqBinding> Você pode usar esse objeto para fazer referência a todas as várias configurações de segurança relacionadas ao <xref:System.ServiceModel.NetMsmqBinding>associação.</xref:System.ServiceModel.NetMsmqBinding>"
  syntax:
    content: 'public sealed class NetMsmqSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  langs:
  - csharp
  name: NetMsmqSecurityElement()
  nameWithType: NetMsmqSecurityElement.NetMsmqSecurityElement()
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.NetMsmqSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.ServiceModel.Configuration.NetMsmqSecurityElement&quot;> </xref> classe."
  syntax:
    content: public NetMsmqSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.NetMsmqSecurityElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Message
  id: Message
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  langs:
  - csharp
  name: Message
  nameWithType: NetMsmqSecurityElement.Message
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.Message
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém o <xref href=&quot;System.ServiceModel.MessageSecurityOverMsmq&quot;> </xref> instância que está associada com o <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> associação."
  remarks: "O <xref:System.ServiceModel.MessageSecurityOverMsmq>instância encapsula as configurações de segurança de mensagem SOAP.</xref:System.ServiceModel.MessageSecurityOverMsmq>"
  syntax:
    content: public System.ServiceModel.Configuration.MessageSecurityOverMsmqElement Message { get; }
    return:
      type: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
      description: "O <xref href=&quot;System.ServiceModel.MessageSecurityOverMsmq&quot;> </xref> instância que está associada com o <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> associação."
  overload: System.ServiceModel.Configuration.NetMsmqSecurityElement.Message*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Mode
  id: Mode
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  langs:
  - csharp
  name: Mode
  nameWithType: NetMsmqSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém ou define o <xref href=&quot;System.ServiceModel.NetMsmqSecurityMode&quot;> </xref> instância que está associada com o <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> associação."
  remarks: "Essa propriedade determina o tipo de segurança usado pelo associado `NetMsmqBinding`. A lista a seguir descreve os valores aceitáveis:- `None` -nenhuma segurança será usada.      - `Transport` -Segurança de transporte será usada.      - `Message` -Segurança com base em mensagem será usado.      - `Both` -Ambos segurança de transporte e segurança baseada em mensagem será usado."
  syntax:
    content: public System.ServiceModel.NetMsmqSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.NetMsmqSecurityMode
      description: "O <xref href=&quot;System.ServiceModel.NetMsmqSecurityMode&quot;> </xref> instância que está associada com o <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> associação."
  overload: System.ServiceModel.Configuration.NetMsmqSecurityElement.Mode*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: NetMsmqSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A ser adicionado."
  overload: System.ServiceModel.Configuration.NetMsmqSecurityElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Transport
  id: Transport
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  langs:
  - csharp
  name: Transport
  nameWithType: NetMsmqSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém o <xref href=&quot;System.ServiceModel.Configuration.MsmqTransportSecurityElement&quot;> </xref> elemento que está associado com o <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> associação."
  remarks: "Essa propriedade permite o acesso às configurações de segurança de transporte Msmq."
  syntax:
    content: public System.ServiceModel.Configuration.MsmqTransportSecurityElement Transport { get; }
    return:
      type: System.ServiceModel.Configuration.MsmqTransportSecurityElement
      description: "O <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> instância que está associada com o <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> associação."
  overload: System.ServiceModel.Configuration.NetMsmqSecurityElement.Transport*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: NetMsmqSecurityElement()
  nameWithType: NetMsmqSecurityElement.NetMsmqSecurityElement()
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.NetMsmqSecurityElement()
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Message
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Message
  nameWithType: NetMsmqSecurityElement.Message
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.Message
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: MessageSecurityOverMsmqElement
  nameWithType: MessageSecurityOverMsmqElement
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Mode
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Mode
  nameWithType: NetMsmqSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.Mode
- uid: System.ServiceModel.NetMsmqSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: NetMsmqSecurityMode
  nameWithType: NetMsmqSecurityMode
  fullName: System.ServiceModel.NetMsmqSecurityMode
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Properties
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Properties
  nameWithType: NetMsmqSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Transport
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Transport
  nameWithType: NetMsmqSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.Transport
- uid: System.ServiceModel.Configuration.MsmqTransportSecurityElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: MsmqTransportSecurityElement
  nameWithType: MsmqTransportSecurityElement
  fullName: System.ServiceModel.Configuration.MsmqTransportSecurityElement
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: NetMsmqSecurityElement
  nameWithType: NetMsmqSecurityElement.NetMsmqSecurityElement
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Message*
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Message
  nameWithType: NetMsmqSecurityElement.Message
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Mode*
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Mode
  nameWithType: NetMsmqSecurityElement.Mode
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Properties
  nameWithType: NetMsmqSecurityElement.Properties
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Transport*
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Transport
  nameWithType: NetMsmqSecurityElement.Transport
