### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  id: ServiceSettingsResponseInfo
  children:
  - System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor
  - System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor(System.Boolean)
  - System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape
  - System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody
  langs:
  - csharp
  name: ServiceSettingsResponseInfo
  nameWithType: ServiceSettingsResponseInfo
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  type: Class
  summary: "Contém as informações retornadas quando um par de solicita as configurações para um serviço resolvedor de pares."
  remarks: "As instâncias dessa classe são usadas principalmente para transmitir informações de resposta de configurações de serviço do serviço de resolução para um cliente de rede desse serviço."
  syntax:
    content: >-
      [System.ServiceModel.MessageContract(IsWrapped=false)]

      public class ServiceSettingsResponseInfo
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor
  id: '#ctor'
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  langs:
  - csharp
  name: ServiceSettingsResponseInfo()
  nameWithType: ServiceSettingsResponseInfo.ServiceSettingsResponseInfo()
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ServiceSettingsResponseInfo()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Inicializa uma nova instância padrão do <xref href=&quot;System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo&quot;> </xref> classe."
  remarks: "O valor padrão de `control` é definido como true."
  syntax:
    content: public ServiceSettingsResponseInfo ();
    parameters: []
  overload: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor(System.Boolean)
  id: '#ctor(System.Boolean)'
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  langs:
  - csharp
  name: ServiceSettingsResponseInfo(Boolean)
  nameWithType: ServiceSettingsResponseInfo.ServiceSettingsResponseInfo(Boolean)
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ServiceSettingsResponseInfo(Boolean)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Inicializa uma nova instância do <xref href=&quot;System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo&quot;> </xref> classe com o valor da diretiva de referência fornecida."
  syntax:
    content: public ServiceSettingsResponseInfo (bool control);
    parameters:
    - id: control
      type: System.Boolean
      description: "<xref:System.Boolean>que indica se as referências são passadas pelo serviço de resolução.</xref:System.Boolean>"
  overload: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape
  id: ControlMeshShape
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  langs:
  - csharp
  name: ControlMeshShape
  nameWithType: ServiceSettingsResponseInfo.ControlMeshShape
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Obtém ou define se as referências são passadas pelo serviço de resolução."
  syntax:
    content: public bool ControlMeshShape { get; set; }
    return:
      type: System.Boolean
      description: "True se as referências de pares de participantes na malha são passadas; False se eles são ignorados."
  overload: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody
  id: HasBody
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  langs:
  - csharp
  name: HasBody()
  nameWithType: ServiceSettingsResponseInfo.HasBody()
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Indica se o corpo da mensagem que contém uma instância serializada desse tipo é formado corretamente."
  syntax:
    content: public bool HasBody ();
    parameters: []
    return:
      type: System.Boolean
      description: "True se o corpo de informações de resposta de configurações de serviço está formado corretamente pelo remetente; False se não for."
  overload: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: ServiceSettingsResponseInfo()
  nameWithType: ServiceSettingsResponseInfo.ServiceSettingsResponseInfo()
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ServiceSettingsResponseInfo()
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor(System.Boolean)
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: ServiceSettingsResponseInfo(Boolean)
  nameWithType: ServiceSettingsResponseInfo.ServiceSettingsResponseInfo(Boolean)
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ServiceSettingsResponseInfo(Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: ControlMeshShape
  nameWithType: ServiceSettingsResponseInfo.ControlMeshShape
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: HasBody()
  nameWithType: ServiceSettingsResponseInfo.HasBody()
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody()
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor*
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: ServiceSettingsResponseInfo
  nameWithType: ServiceSettingsResponseInfo.ServiceSettingsResponseInfo
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape*
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: ControlMeshShape
  nameWithType: ServiceSettingsResponseInfo.ControlMeshShape
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody*
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: HasBody
  nameWithType: ServiceSettingsResponseInfo.HasBody
