### YamlMime:ManagedReference
items:
- uid: System.Net.UploadValuesCompletedEventHandler
  id: UploadValuesCompletedEventHandler
  langs:
  - csharp
  name: UploadValuesCompletedEventHandler
  nameWithType: UploadValuesCompletedEventHandler
  fullName: System.Net.UploadValuesCompletedEventHandler
  type: Delegate
  summary: "Representa o método que manipulará o <xref:System.Net.WebClient.UploadValuesCompleted>evento de <xref:System.Net.WebClient>.</xref:System.Net.WebClient> </xref:System.Net.WebClient.UploadValuesCompleted>"
  remarks: 'Quando você cria um delegado UploadValuesCompletedEventHandler, identifica o método que manipulará o evento. Para associar o evento com o manipulador de eventos, adicione uma instância do representante ao evento. O manipulador de eventos é chamado sempre que o evento ocorre, a menos que você remova o delegado. Para obter mais informações sobre delegados de manipulador de eventos, consulte [NIB: eventos e delegados](http://msdn.microsoft.com/en-us/d98fd58b-fa4f-4598-8378-addf4355a115).'
  syntax:
    content: public delegate void UploadValuesCompletedEventHandler(object sender, UploadValuesCompletedEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
