### YamlMime:ManagedReference
items:
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute
  id: SettingsAllowAnonymousAttribute
  children:
  - System.Web.Profile.SettingsAllowAnonymousAttribute.#ctor(System.Boolean)
  - System.Web.Profile.SettingsAllowAnonymousAttribute.Allow
  - System.Web.Profile.SettingsAllowAnonymousAttribute.IsDefaultAttribute
  langs:
  - csharp
  name: SettingsAllowAnonymousAttribute
  nameWithType: SettingsAllowAnonymousAttribute
  fullName: System.Web.Profile.SettingsAllowAnonymousAttribute
  type: Class
  summary: "Identifica se uma propriedade de perfil pode ser definida ou acessada por um usuário anônimo."
  remarks: "A classe SettingsAllowAnonymousAttribute é usada para identificar se uma propriedade de uma implementação personalizada de perfil pode ser acessada se o usuário for um usuário anônimo. Para obter informações sobre como habilitar identificação anônima, consulte a documentação fornecida para o elemento de configuração.       Se nenhum SettingsAllowAnonymousAttribute é especificado para uma propriedade de perfil, o acesso anônimo da propriedade do perfil não é permitido.       Uma implementação personalizada de perfil é uma classe que herda de <xref:System.Web.Profile.ProfileBase>classe abstrata e define as propriedades do perfil de usuário que não são especificadas no elemento de configuração.</xref:System.Web.Profile.ProfileBase> Você pode especificar um tipo de perfil de usuário personalizada no arquivo de Web. config do aplicativo com o `inherits` atributo do elemento de configuração, conforme mostrado no exemplo a seguir.       `<configuration>`       `<connectionStrings>`       `<add`       `name=&quot;SqlServices&quot;`       `connectionString=&quot;Data Source=localhost;Integrated Security=SSPI;Initial Catalog=aspnetdb;&quot; />`       `</connectionStrings>`       `<system.web>`       `<authentication mode=&quot;Forms&quot; >`       `<forms`       `loginUrl=&quot;login.aspx&quot;`       `name=&quot;.ASPXFORMSAUTH&quot; />`       `</authentication>`       `<authorization>`       `<deny users=&quot;?&quot; />`       `</authorization>`       `<profile inherits=&quot;Samples.AspNet.Profile.EmployeeProfile&quot;`       `defaultProvider=&quot;SqlProvider&quot;>`       `<providers>`       `<clear />`       `<add`       `name=&quot;SqlProvider&quot;`       `type=&quot;System.Web.Profile.SqlProfileProvider&quot;`       `connectionStringName=&quot;SqlServices&quot;`       `description=&quot;SQL Profile Provider for Sample&quot;/>`       `<add`       `name=&quot;EmployeeInfoProvider&quot;`       `type=&quot;System.Web.Profile.SqlProfileProvider&quot;`       `connectionStringName=&quot;SqlServices&quot;`       `description=&quot;SQL Profile Provider for Employee Info&quot;/>`       `</providers>`       `<properties>`       `<add name=&quot;GarmentSize&quot; />`       `</properties>`       `</profile>`       `</system.web>`       `</configuration>`"
  example:
  - "The following code example defines a class that inherits from the <xref:System.Web.Profile.ProfileBase> to create a custom profile. The type of the custom profile is specified in the `inherits` attribute of the  configuration element in the Web.config file for an application.  \n  \n [!code-cs[System.Web.Profile.ProfileBase#1](~/add/codesnippet/csharp/t-system.web.profile.set_1.cs)]\n [!code-vb[System.Web.Profile.ProfileBase#1](~/add/codesnippet/visualbasic/t-system.web.profile.set_1.vb)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class SettingsAllowAnonymousAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.#ctor(System.Boolean)
  id: '#ctor(System.Boolean)'
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  langs:
  - csharp
  name: SettingsAllowAnonymousAttribute(Boolean)
  nameWithType: SettingsAllowAnonymousAttribute.SettingsAllowAnonymousAttribute(Boolean)
  fullName: System.Web.Profile.SettingsAllowAnonymousAttribute.SettingsAllowAnonymousAttribute(Boolean)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Profile
  summary: "Cria uma nova instância do <xref href=&quot;System.Web.Profile.SettingsAllowAnonymousAttribute&quot;> </xref> classe e especifica se deve permitir o acesso anônimo para a propriedade de perfil associados."
  remarks: "O <xref:System.Web.Profile.SettingsAllowAnonymousAttribute>classe é usada para identificar se uma propriedade de uma implementação personalizada de perfil pode ser acessada se o usuário for um usuário anônimo.</xref:System.Web.Profile.SettingsAllowAnonymousAttribute> Para obter informações sobre como habilitar identificação anônima, consulte o elemento de configuração.       Se nenhum <xref:System.Web.Profile.SettingsAllowAnonymousAttribute>foi especificado para uma propriedade de perfil, o acesso anônimo para a propriedade de perfil não é permitida.</xref:System.Web.Profile.SettingsAllowAnonymousAttribute>       Uma implementação personalizada de perfil é uma classe que herda de <xref:System.Web.Profile.ProfileBase>classe abstrata e define as propriedades do perfil de usuário que não são especificadas no elemento de configuração.</xref:System.Web.Profile.ProfileBase>"
  example:
  - "The following example defines a class that inherits from the <xref:System.Web.Profile.ProfileBase> class to create a custom profile. The type of the custom profile is specified in the `inherits` attribute of the  configuration element in the Web.config file for an application. For an example of a configuration file that specifies a custom profile implementation, see the <xref:System.Web.Profile.SettingsAllowAnonymousAttribute> class overview.  \n  \n [!code-cs[System.Web.Profile.ProfileBase#1](~/add/codesnippet/csharp/m-system.web.profile.set_1.cs)]\n [!code-vb[System.Web.Profile.ProfileBase#1](~/add/codesnippet/visualbasic/m-system.web.profile.set_1.vb)]"
  syntax:
    content: public SettingsAllowAnonymousAttribute (bool allow);
    parameters:
    - id: allow
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se usuários anônimos podem acessar a propriedade de perfil associados; Caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Profile.SettingsAllowAnonymousAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.Allow
  id: Allow
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  langs:
  - csharp
  name: Allow
  nameWithType: SettingsAllowAnonymousAttribute.Allow
  fullName: System.Web.Profile.SettingsAllowAnonymousAttribute.Allow
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Profile
  summary: "Obtém um valor que indica se a propriedade associada de uma implementação personalizada de perfil pode ser acessada se o usuário for um usuário anônimo."
  syntax:
    content: public bool Allow { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se usuários anônimos podem acessar a propriedade de perfil associados; Caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Profile.SettingsAllowAnonymousAttribute.Allow*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.IsDefaultAttribute
  id: IsDefaultAttribute
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  langs:
  - csharp
  name: IsDefaultAttribute()
  nameWithType: SettingsAllowAnonymousAttribute.IsDefaultAttribute()
  fullName: System.Web.Profile.SettingsAllowAnonymousAttribute.IsDefaultAttribute()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Profile
  summary: "Obtém um valor que indica se o <xref:System.Web.Profile.SettingsAllowAnonymousAttribute.Allow*>propriedade é definida como o valor padrão.</xref:System.Web.Profile.SettingsAllowAnonymousAttribute.Allow*>"
  syntax:
    content: public override bool IsDefaultAttribute ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se o <xref:System.Web.Profile.SettingsAllowAnonymousAttribute.Allow*>propriedade é definida como o valor padrão; caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.Web.Profile.SettingsAllowAnonymousAttribute.Allow*>"
  overload: System.Web.Profile.SettingsAllowAnonymousAttribute.IsDefaultAttribute*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.#ctor(System.Boolean)
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  isExternal: false
  name: SettingsAllowAnonymousAttribute(Boolean)
  nameWithType: SettingsAllowAnonymousAttribute.SettingsAllowAnonymousAttribute(Boolean)
  fullName: System.Web.Profile.SettingsAllowAnonymousAttribute.SettingsAllowAnonymousAttribute(Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.Allow
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  isExternal: false
  name: Allow
  nameWithType: SettingsAllowAnonymousAttribute.Allow
  fullName: System.Web.Profile.SettingsAllowAnonymousAttribute.Allow
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.IsDefaultAttribute
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  isExternal: false
  name: IsDefaultAttribute()
  nameWithType: SettingsAllowAnonymousAttribute.IsDefaultAttribute()
  fullName: System.Web.Profile.SettingsAllowAnonymousAttribute.IsDefaultAttribute()
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.#ctor*
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  isExternal: false
  name: SettingsAllowAnonymousAttribute
  nameWithType: SettingsAllowAnonymousAttribute.SettingsAllowAnonymousAttribute
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.Allow*
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  isExternal: false
  name: Allow
  nameWithType: SettingsAllowAnonymousAttribute.Allow
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.IsDefaultAttribute*
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  isExternal: false
  name: IsDefaultAttribute
  nameWithType: SettingsAllowAnonymousAttribute.IsDefaultAttribute
