### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationLocationCollection
  id: ConfigurationLocationCollection
  children:
  - System.Configuration.ConfigurationLocationCollection.Item(System.Int32)
  langs:
  - csharp
  name: ConfigurationLocationCollection
  nameWithType: ConfigurationLocationCollection
  fullName: System.Configuration.ConfigurationLocationCollection
  type: Class
  summary: "Contém uma coleção de objetos ConfigurationLocationCollection."
  remarks: "Use a classe ConfigurationLocationCollection para iterar por meio de uma coleção de <xref:System.Configuration.ConfigurationLocation>objetos que representam os recursos para os quais definições de configuração específicas de local são definidas.</xref:System.Configuration.ConfigurationLocation> ConfigurationLocationCollection é o tipo retornado pelo <xref:System.Configuration.Configuration.Locations%2A>propriedade.</xref:System.Configuration.Configuration.Locations%2A>      > [!NOTE] > ConfigurationLocationCollection a classe não pode fazer referência à coleção de <xref:System.Configuration.ConfigurationLocation>objetos na ordem em que foram especificados no arquivo de configuração.</xref:System.Configuration.ConfigurationLocation>"
  example:
  - "In the following code example, the Web configuration for the application `MySampleApp` is loaded, and the locations defined in this configuration are displayed by iterating through the ConfigurationLocationCollection object returned by the <xref:System.Configuration.Configuration.Locations%2A> property.  \n  \n [!code-vb[ConfigurationLocationCollection#1](~/add/codesnippet/visualbasic/t-system.configuration.c_1_1.vb)]\n [!code-cs[ConfigurationLocationCollection#1](~/add/codesnippet/csharp/t-system.configuration.c_1_1.cs)]"
  syntax:
    content: 'public class ConfigurationLocationCollection : System.Collections.ReadOnlyCollectionBase'
  inheritance:
  - System.Object
  - System.Collections.ReadOnlyCollectionBase
  implements: []
  inheritedMembers:
  - System.Collections.ReadOnlyCollectionBase.Count
  - System.Collections.ReadOnlyCollectionBase.GetEnumerator
  - System.Collections.ReadOnlyCollectionBase.InnerList
  - System.Collections.ReadOnlyCollectionBase.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  - System.Collections.ReadOnlyCollectionBase.System#Collections#ICollection#IsSynchronized
  - System.Collections.ReadOnlyCollectionBase.System#Collections#ICollection#SyncRoot
  platform:
  - net462
- uid: System.Configuration.ConfigurationLocationCollection.Item(System.Int32)
  id: Item(System.Int32)
  parent: System.Configuration.ConfigurationLocationCollection
  langs:
  - csharp
  name: Item(Int32)
  nameWithType: ConfigurationLocationCollection.Item(Int32)
  fullName: System.Configuration.ConfigurationLocationCollection.Item(Int32)
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Obtém o <xref href=&quot;System.Configuration.ConfigurationLocationCollection&quot;> </xref> objeto no índice especificado."
  remarks: "Use o acessador de Item para o <xref:System.Configuration.ConfigurationLocationCollection>classe para obter um determinado <xref:System.Configuration.ConfigurationLocation>objeto da coleção, especificando seu índice na coleção.</xref:System.Configuration.ConfigurationLocation> </xref:System.Configuration.ConfigurationLocationCollection>"
  syntax:
    content: public System.Configuration.ConfigurationLocation this[int index] { get; }
    parameters:
    - id: index
      type: System.Int32
      description: "A posição do índice de <xref href=&quot;System.Configuration.ConfigurationLocationCollection&quot;> </xref> para retornar."
    return:
      type: System.Configuration.ConfigurationLocation
      description: "O <xref href=&quot;System.Configuration.ConfigurationLocationCollection&quot;> </xref> no índice especificado."
  overload: System.Configuration.ConfigurationLocationCollection.Item*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Collections.ReadOnlyCollectionBase
  isExternal: false
  name: System.Collections.ReadOnlyCollectionBase
- uid: System.Configuration.ConfigurationLocationCollection.Item(System.Int32)
  parent: System.Configuration.ConfigurationLocationCollection
  isExternal: false
  name: Item(Int32)
  nameWithType: ConfigurationLocationCollection.Item(Int32)
  fullName: System.Configuration.ConfigurationLocationCollection.Item(Int32)
- uid: System.Configuration.ConfigurationLocation
  parent: System.Configuration
  isExternal: false
  name: ConfigurationLocation
  nameWithType: ConfigurationLocation
  fullName: System.Configuration.ConfigurationLocation
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.ConfigurationLocationCollection.Item*
  parent: System.Configuration.ConfigurationLocationCollection
  isExternal: false
  name: Item
  nameWithType: ConfigurationLocationCollection.Item
