### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsDescriptionAttribute
  id: SettingsDescriptionAttribute
  children:
  - System.Configuration.SettingsDescriptionAttribute.#ctor(System.String)
  - System.Configuration.SettingsDescriptionAttribute.Description
  langs:
  - csharp
  name: SettingsDescriptionAttribute
  nameWithType: SettingsDescriptionAttribute
  fullName: System.Configuration.SettingsDescriptionAttribute
  type: Class
  summary: "Fornece uma cadeia de caracteres que descreve uma propriedade de configuração individual. Essa classe não pode ser herdada."
  remarks: "O SettingsDescriptionAttribute destina-se para ajudar a ferramentas de tempo de design e ferramentas de tempo de execução administrativas identificar e descrever a propriedade de configuração associada.       Esse atributo é opcional e só pode ser aplicado no nível de propriedade de configuração individual."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class SettingsDescriptionAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsDescriptionAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsDescriptionAttribute
  langs:
  - csharp
  name: SettingsDescriptionAttribute(String)
  nameWithType: SettingsDescriptionAttribute.SettingsDescriptionAttribute(String)
  fullName: System.Configuration.SettingsDescriptionAttribute.SettingsDescriptionAttribute(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicializa uma instância do <xref href=&quot;System.Configuration.SettingsDescriptionAttribute&quot;> </xref> classe."
  remarks: "Embora a descrição tem um comprimento máximo teórico do <xref:System.String>classe, cujo comprimento é representado por um <xref:System.Int32>, as seguintes considerações práticas dois limitará o tamanho do `description` parâmetro:-descrições de texto grandes são difíceis de serem exibidos em uma interface de usuário (UI) e difíceis de ler o usuário.</xref:System.Int32> </xref:System.String>      -Provedores de configurações podem impor cotas de uso geral e são necessárias para impor cotas de configuração do usuário."
  syntax:
    content: public SettingsDescriptionAttribute (string description);
    parameters:
    - id: description
      type: System.String
      description: "O <xref:System.String>usado como um texto descritivo.</xref:System.String>"
  overload: System.Configuration.SettingsDescriptionAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsDescriptionAttribute.Description
  id: Description
  parent: System.Configuration.SettingsDescriptionAttribute
  langs:
  - csharp
  name: Description
  nameWithType: SettingsDescriptionAttribute.Description
  fullName: System.Configuration.SettingsDescriptionAttribute.Description
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Obtém o texto descritivo para a propriedade de configuração associada."
  remarks: "A propriedade de descrição é definida pelo <xref:System.Configuration.SettingsDescriptionAttribute.%23ctor%2A>construtor.</xref:System.Configuration.SettingsDescriptionAttribute.%23ctor%2A>"
  syntax:
    content: public string Description { get; }
    return:
      type: System.String
      description: "Um <xref:System.String>que contém o texto descritivo para a propriedade de configuração associada.</xref:System.String>"
  overload: System.Configuration.SettingsDescriptionAttribute.Description*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsDescriptionAttribute.#ctor(System.String)
  parent: System.Configuration.SettingsDescriptionAttribute
  isExternal: false
  name: SettingsDescriptionAttribute(String)
  nameWithType: SettingsDescriptionAttribute.SettingsDescriptionAttribute(String)
  fullName: System.Configuration.SettingsDescriptionAttribute.SettingsDescriptionAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsDescriptionAttribute.Description
  parent: System.Configuration.SettingsDescriptionAttribute
  isExternal: false
  name: Description
  nameWithType: SettingsDescriptionAttribute.Description
  fullName: System.Configuration.SettingsDescriptionAttribute.Description
- uid: System.Configuration.SettingsDescriptionAttribute.#ctor*
  parent: System.Configuration.SettingsDescriptionAttribute
  isExternal: false
  name: SettingsDescriptionAttribute
  nameWithType: SettingsDescriptionAttribute.SettingsDescriptionAttribute
- uid: System.Configuration.SettingsDescriptionAttribute.Description*
  parent: System.Configuration.SettingsDescriptionAttribute
  isExternal: false
  name: Description
  nameWithType: SettingsDescriptionAttribute.Description
