### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.HttpListenerTimeoutsElement
  id: HttpListenerTimeoutsElement
  children:
  - System.Net.Configuration.HttpListenerTimeoutsElement.#ctor
  - System.Net.Configuration.HttpListenerTimeoutsElement.DrainEntityBody
  - System.Net.Configuration.HttpListenerTimeoutsElement.EntityBody
  - System.Net.Configuration.HttpListenerTimeoutsElement.HeaderWait
  - System.Net.Configuration.HttpListenerTimeoutsElement.IdleConnection
  - System.Net.Configuration.HttpListenerTimeoutsElement.MinSendBytesPerSecond
  - System.Net.Configuration.HttpListenerTimeoutsElement.Properties
  - System.Net.Configuration.HttpListenerTimeoutsElement.RequestQueue
  langs:
  - csharp
  name: HttpListenerTimeoutsElement
  nameWithType: HttpListenerTimeoutsElement
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement
  type: Class
  summary: "Representa o <xref href=&quot;System.Net.HttpListener&quot;> </xref> tempos limite elemento no arquivo de configuração. Essa classe não pode ser herdada."
  remarks: "O elemento de tempos limite define os limites de tempo limite de conexão dafault para um <xref:System.Net.HttpListener>instância.</xref:System.Net.HttpListener>"
  syntax:
    content: 'public sealed class HttpListenerTimeoutsElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  langs:
  - csharp
  name: HttpListenerTimeoutsElement()
  nameWithType: HttpListenerTimeoutsElement.HttpListenerTimeoutsElement()
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.HttpListenerTimeoutsElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Net.Configuration.HttpListenerTimeoutsElement&quot;> </xref> classe."
  syntax:
    content: public HttpListenerTimeoutsElement ();
    parameters: []
  overload: System.Net.Configuration.HttpListenerTimeoutsElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.DrainEntityBody
  id: DrainEntityBody
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  langs:
  - csharp
  name: DrainEntityBody
  nameWithType: HttpListenerTimeoutsElement.DrainEntityBody
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.DrainEntityBody
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Obtém o tempo, em segundos, permitido para o <xref href=&quot;System.Net.HttpListener&quot;> </xref> para descarregar o corpo da entidade em uma conexão Keep-Alive."
  remarks: "Em uma conexão Keep-Alive, depois que o aplicativo enviou uma resposta para uma solicitação e antes da solicitação de corpo de entidade completamente foi recebido, o <xref:System.Net.HttpListener>inicia esgotar o restante do corpo da entidade para acessar outro potencialmente redirecionasse solicitação do cliente.</xref:System.Net.HttpListener> Se o tempo para que o corpo da entidade restantes exceder o período permitido a conexão se esgota."
  syntax:
    content: public TimeSpan DrainEntityBody { get; }
    return:
      type: System.TimeSpan
      description: "Retorna <xref:System.TimeSpan>.</xref:System.TimeSpan>       O tempo, em segundos, permitido para o <xref href=&quot;System.Net.HttpListener&quot;> </xref> para descarregar o corpo da entidade em uma conexão Keep-Alive."
  overload: System.Net.Configuration.HttpListenerTimeoutsElement.DrainEntityBody*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.EntityBody
  id: EntityBody
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  langs:
  - csharp
  name: EntityBody
  nameWithType: HttpListenerTimeoutsElement.EntityBody
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.EntityBody
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Obtém o tempo, em segundos, permitido para o corpo da entidade de solicitação chegar."
  remarks: "O <xref:System.Net.HttpListener>ativa o temporizador quando a solicitação tem um corpo de entidade.</xref:System.Net.HttpListener> Inicialmente, a expiração do temporizador é definida como o valor configurado. Quando o <xref:System.Net.HttpListener>recebe indicações de dados adicionais na solicitação, ele redefine o timer para dar a conexão outro intervalo.</xref:System.Net.HttpListener>"
  syntax:
    content: public TimeSpan EntityBody { get; }
    return:
      type: System.TimeSpan
      description: "Retorna <xref:System.TimeSpan>.</xref:System.TimeSpan>       O tempo, em segundos, permitido para o corpo da entidade de solicitação chegar."
  overload: System.Net.Configuration.HttpListenerTimeoutsElement.EntityBody*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.HeaderWait
  id: HeaderWait
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  langs:
  - csharp
  name: HeaderWait
  nameWithType: HttpListenerTimeoutsElement.HeaderWait
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.HeaderWait
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Obtém o tempo, em segundos, permitido para o <xref href=&quot;System.Net.HttpListener&quot;> </xref> para analisar o cabeçalho de solicitação."
  remarks: "Esse tempo limite é aplicada apenas depois que a primeira solicitação em que a conexão é roteada para <xref:System.Net.HttpListener>.</xref:System.Net.HttpListener>       O sistema não pode determinar a fila de solicitação ou o grupo de URL associada com a solicitação até que os cabeçalhos foram analisados. Portanto, o <xref:System.Net.HttpListener>impõe o padrão <xref:System.Net.HttpListenerTimeoutManager.HeaderWait%2A>timer para a primeira solicitação em uma conexão.</xref:System.Net.HttpListenerTimeoutManager.HeaderWait%2A> </xref:System.Net.HttpListener> As solicitações subsequentes em uma conexão Keep-Alive usará o valor definido nesta propriedade."
  syntax:
    content: public TimeSpan HeaderWait { get; }
    return:
      type: System.TimeSpan
      description: "Retorna <xref:System.TimeSpan>.</xref:System.TimeSpan>       O tempo, em segundos, permitido para o <xref href=&quot;System.Net.HttpListener&quot;> </xref> para analisar o cabeçalho de solicitação."
  overload: System.Net.Configuration.HttpListenerTimeoutsElement.HeaderWait*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.IdleConnection
  id: IdleConnection
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  langs:
  - csharp
  name: IdleConnection
  nameWithType: HttpListenerTimeoutsElement.IdleConnection
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.IdleConnection
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Obtém o tempo, em segundos, permitido para uma conexão ociosa."
  remarks: "Esse tempo limite é aplicada apenas depois que a primeira solicitação em que a conexão é roteada para <xref:System.Net.HttpListener>.</xref:System.Net.HttpListener>       O sistema não pode determinar a fila de solicitação ou o grupo de URL associada com a solicitação até que os cabeçalhos foram analisados. Portanto, o <xref:System.Net.HttpListener>impõe o padrão <xref:System.Net.HttpListenerTimeoutManager.IdleConnection%2A>timer para a primeira solicitação em uma conexão.</xref:System.Net.HttpListenerTimeoutManager.IdleConnection%2A> </xref:System.Net.HttpListener> As solicitações subsequentes em uma conexão Keep-Alive usará o valor definido nesta propriedade."
  syntax:
    content: public TimeSpan IdleConnection { get; }
    return:
      type: System.TimeSpan
      description: "Retorna <xref:System.TimeSpan>.</xref:System.TimeSpan>       O tempo, em segundos, permitido para uma conexão ociosa."
  overload: System.Net.Configuration.HttpListenerTimeoutsElement.IdleConnection*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.MinSendBytesPerSecond
  id: MinSendBytesPerSecond
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  langs:
  - csharp
  name: MinSendBytesPerSecond
  nameWithType: HttpListenerTimeoutsElement.MinSendBytesPerSecond
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.MinSendBytesPerSecond
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Obtém a taxa mínima de envio, em bytes por segundo, para a resposta."
  syntax:
    content: public long MinSendBytesPerSecond { get; }
    return:
      type: System.Int64
      description: "Retorna <xref:System.Int64>.</xref:System.Int64>       A taxa mínima de envio, em bytes por segundo para a resposta."
  overload: System.Net.Configuration.HttpListenerTimeoutsElement.MinSendBytesPerSecond*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.Properties
  id: Properties
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  langs:
  - csharp
  name: Properties
  nameWithType: HttpListenerTimeoutsElement.Properties
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A ser adicionado."
  overload: System.Net.Configuration.HttpListenerTimeoutsElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.RequestQueue
  id: RequestQueue
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  langs:
  - csharp
  name: RequestQueue
  nameWithType: HttpListenerTimeoutsElement.RequestQueue
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.RequestQueue
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Obtém o tempo, em segundos, permitido para a solicitação permanecem na fila de solicitação antes do <xref href=&quot;System.Net.HttpListener&quot;> </xref> coleta."
  syntax:
    content: public TimeSpan RequestQueue { get; }
    return:
      type: System.TimeSpan
      description: "Retorna <xref:System.TimeSpan>.</xref:System.TimeSpan>       O tempo, em segundos, permitido para a solicitação permanecem na fila de solicitação antes do <xref href=&quot;System.Net.HttpListener&quot;> </xref> coleta."
  overload: System.Net.Configuration.HttpListenerTimeoutsElement.RequestQueue*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.#ctor
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: HttpListenerTimeoutsElement()
  nameWithType: HttpListenerTimeoutsElement.HttpListenerTimeoutsElement()
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.HttpListenerTimeoutsElement()
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.DrainEntityBody
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: DrainEntityBody
  nameWithType: HttpListenerTimeoutsElement.DrainEntityBody
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.DrainEntityBody
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.EntityBody
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: EntityBody
  nameWithType: HttpListenerTimeoutsElement.EntityBody
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.EntityBody
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.HeaderWait
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: HeaderWait
  nameWithType: HttpListenerTimeoutsElement.HeaderWait
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.HeaderWait
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.IdleConnection
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: IdleConnection
  nameWithType: HttpListenerTimeoutsElement.IdleConnection
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.IdleConnection
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.MinSendBytesPerSecond
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: MinSendBytesPerSecond
  nameWithType: HttpListenerTimeoutsElement.MinSendBytesPerSecond
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.MinSendBytesPerSecond
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.Properties
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: Properties
  nameWithType: HttpListenerTimeoutsElement.Properties
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.RequestQueue
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: RequestQueue
  nameWithType: HttpListenerTimeoutsElement.RequestQueue
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.RequestQueue
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.#ctor*
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: HttpListenerTimeoutsElement
  nameWithType: HttpListenerTimeoutsElement.HttpListenerTimeoutsElement
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.DrainEntityBody*
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: DrainEntityBody
  nameWithType: HttpListenerTimeoutsElement.DrainEntityBody
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.EntityBody*
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: EntityBody
  nameWithType: HttpListenerTimeoutsElement.EntityBody
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.HeaderWait*
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: HeaderWait
  nameWithType: HttpListenerTimeoutsElement.HeaderWait
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.IdleConnection*
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: IdleConnection
  nameWithType: HttpListenerTimeoutsElement.IdleConnection
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.MinSendBytesPerSecond*
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: MinSendBytesPerSecond
  nameWithType: HttpListenerTimeoutsElement.MinSendBytesPerSecond
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.Properties*
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: Properties
  nameWithType: HttpListenerTimeoutsElement.Properties
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.RequestQueue*
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: RequestQueue
  nameWithType: HttpListenerTimeoutsElement.RequestQueue
