### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  id: XmlFormatExtensionPointAttribute
  children:
  - System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor(System.String)
  - System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
  - System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
  langs:
  - csharp
  name: XmlFormatExtensionPointAttribute
  nameWithType: XmlFormatExtensionPointAttribute
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  type: Class
  summary: "Especifica o namespace XML e um prefixo de namespace XML a ser usado para uma extensão de formato de descrição de serviço dentro de uma descrição de serviço. Essa classe não pode ser herdada."
  remarks: "Uma extensão de formato de descrição de serviço estende como uma descrição de serviço é gerada para um serviço Web XML criado usando ASP.NET. Especificamente, uma extensão de formato de descrição de serviço adiciona elementos XML para a descrição do serviço. Isso é útil quando uma extensão SOAP é criada para ser executado no lado do cliente e o servidor de um serviço da Web em XML, como informações sobre as extensões SOAP não são colocadas automaticamente na descrição do serviço. Se você adicionar informações sobre a extensão SOAP para a descrição do serviço, um cliente pode interpretar assim que ele deve executar a extensão SOAP específica. Um exemplo de uma extensão SOAP que deve ser executado no cliente e servidor é uma extensão SOAP de criptografia. Se uma criptografia extensão SOAP é executada somente no servidor, e ele criptografa os valores de retorno antes de enviá-los de volta ao cliente, o cliente deve ter a extensão SOAP em execução para descriptografar a mensagem SOAP. Caso contrário, o cliente não pode processar o valor de retorno.       Use as seguintes etapas para criar uma extensão de formato de descrição de serviço: 1.  Criar uma classe que deriva de <xref:System.Web.Services.Description.ServiceDescriptionFormatExtension>.</xref:System.Web.Services.Description.ServiceDescriptionFormatExtension>      2.  Aplicar um <xref:System.Web.Services.Configuration.XmlFormatExtensionAttribute>à classe e especifique os pontos de extensão em que a extensão de formato de descrição de serviço deve ser executado.</xref:System.Web.Services.Configuration.XmlFormatExtensionAttribute>      3.  Opcionalmente, aplique um XmlFormatExtensionPointAttribute à classe e especifique um membro dentro da classe para agir como um novo ponto de extensão.      4.  Opcionalmente, aplique um <xref:System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute>à classe e especifique o prefixo de namespace XML para ser associado a elementos XML gerados pela extensão de formato de descrição de serviço.</xref:System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute>      5.  Configurar a extensão de formato de descrição de serviço para ser executado no `serviceDescriptionFormatExtensionTypes` seção do arquivo de configuração."
  example:
  - >-
    [!code-cs[ServiceDescriptionFormatExtension#1](~/add/codesnippet/csharp/t-system.web.services.co_1_1.cs)]
     [!code-vb[ServiceDescriptionFormatExtension#1](~/add/codesnippet/visualbasic/t-system.web.services.co_1_1.vb)]
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class)]

      public sealed class XmlFormatExtensionPointAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  langs:
  - csharp
  name: XmlFormatExtensionPointAttribute(String)
  nameWithType: XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute(String)
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute(String)
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Web.Services.Configuration.XmlFormatExtensionPointAttribute&quot;> </xref> classe."
  syntax:
    content: public XmlFormatExtensionPointAttribute (string memberName);
    parameters:
    - id: memberName
      type: System.String
      description: "O membro da classe que implementa a extensão do formato de descrição de serviço que pode ter uma extensão de formato de descrição de serviço associada a ele."
  overload: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
  id: AllowElements
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  langs:
  - csharp
  name: AllowElements
  nameWithType: XmlFormatExtensionPointAttribute.AllowElements
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Obtém ou define um valor que indica se o membro da classe que implementa a extensão de formato de descrição de serviço especificada no <xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*>propriedade pode aceitar os elementos XML brutos.</xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*>"
  syntax:
    content: public bool AllowElements { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se o membro da classe que implementa a descrição do serviço Formatar extensão especificada no <xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*>propriedade pode aceitar os elementos XML brutos; caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*> O padrão é <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
  id: MemberName
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  langs:
  - csharp
  name: MemberName
  nameWithType: XmlFormatExtensionPointAttribute.MemberName
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Especifica que o membro da classe que implementa a extensão de formato de descrição de serviço pode ter uma extensão de formato de descrição de serviço associada a ele."
  syntax:
    content: public string MemberName { get; set; }
    return:
      type: System.String
      description: "O membro da classe que implementa a extensão do formato de descrição de serviço que pode ter uma extensão de formato de descrição de serviço associada a ele."
  overload: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor(System.String)
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: XmlFormatExtensionPointAttribute(String)
  nameWithType: XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute(String)
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: AllowElements
  nameWithType: XmlFormatExtensionPointAttribute.AllowElements
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: MemberName
  nameWithType: XmlFormatExtensionPointAttribute.MemberName
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: XmlFormatExtensionPointAttribute
  nameWithType: XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: AllowElements
  nameWithType: XmlFormatExtensionPointAttribute.AllowElements
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: MemberName
  nameWithType: XmlFormatExtensionPointAttribute.MemberName
