### YamlMime:ManagedReference
items:
- uid: System.Runtime.Caching.Hosting.IApplicationIdentifier
  id: IApplicationIdentifier
  children:
  - System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId
  langs:
  - csharp
  name: IApplicationIdentifier
  nameWithType: IApplicationIdentifier
  fullName: System.Runtime.Caching.Hosting.IApplicationIdentifier
  type: Interface
  summary: "Define um identificador para domínios de aplicativo que pode usar uma implementação de cache para interagir com um ambiente de host."
  remarks: "Um [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] ambiente de host, como o ASP.NET pode usar a interface de IApplicationIdentifier defina cadeias de caracteres que identificam os domínios de aplicativo individual. O ambiente de host implementa a interface IApplicationIdentifier. Essa interface estará disponível para <xref:System.Runtime.Caching.ObjectCache>implementações por meio de <xref:System.Runtime.Caching.ObjectCache.Host%2A>propriedade.</xref:System.Runtime.Caching.ObjectCache.Host%2A> </xref:System.Runtime.Caching.ObjectCache>       Uma implementação de cache usa essa referência para obter um identificador para o domínio de aplicativo. No ASP.NET, implementações de cache usam o identificador do aplicativo para construir identificadores para contadores de desempenho do cache. Isso fornece nomes para desempenho instâncias de contadores que podem ser distinguidas entre domínios de aplicativos quando vários domínios de aplicativo estão em execução."
  syntax:
    content: public interface IApplicationIdentifier
  implements: []
  platform:
  - net462
- uid: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId
  id: GetApplicationId
  parent: System.Runtime.Caching.Hosting.IApplicationIdentifier
  langs:
  - csharp
  name: GetApplicationId()
  nameWithType: IApplicationIdentifier.GetApplicationId()
  fullName: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId()
  type: Method
  assemblies:
  - System.Runtime.Caching
  namespace: System.Runtime.Caching.Hosting
  summary: "Obtém um identificador para um domínio de aplicativo."
  remarks: "O método GetApplicationId costuma ser implementado por um [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] ambiente de host para construir um identificador de aplicativo para um <xref:System.Runtime.Caching.ObjectCache>implementação.</xref:System.Runtime.Caching.ObjectCache> Um <xref:System.Runtime.Caching.ObjectCache>implementação usa essas informações para identificar o domínio de aplicativo que está sendo executado.</xref:System.Runtime.Caching.ObjectCache>       Por exemplo, no ASP.NET, o cache usa um identificador de aplicativo para construir identificadores para contadores de desempenho do cache. O cache chama o método de GetApplicationId que é implementado pelo ambiente de host e o host retorna o identificador. Isso fornece nomes para desempenho instâncias de contadores que podem ser distinguidas entre domínios de aplicativos quando vários domínios de aplicativo estão em execução."
  syntax:
    content: public string GetApplicationId ();
    parameters: []
    return:
      type: System.String
      description: "Um identificador exclusivo para o domínio de aplicativo atual."
  overload: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId
  parent: System.Runtime.Caching.Hosting.IApplicationIdentifier
  isExternal: false
  name: GetApplicationId()
  nameWithType: IApplicationIdentifier.GetApplicationId()
  fullName: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId()
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId*
  parent: System.Runtime.Caching.Hosting.IApplicationIdentifier
  isExternal: false
  name: GetApplicationId
  nameWithType: IApplicationIdentifier.GetApplicationId
