### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.MsmqTransportSecurityElement
  id: MsmqTransportSecurityElement
  children:
  - System.ServiceModel.Configuration.MsmqTransportSecurityElement.#ctor
  - System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqAuthenticationMode
  - System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqEncryptionAlgorithm
  - System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqProtectionLevel
  - System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqSecureHashAlgorithm
  - System.ServiceModel.Configuration.MsmqTransportSecurityElement.Properties
  langs:
  - csharp
  name: MsmqTransportSecurityElement
  nameWithType: MsmqTransportSecurityElement
  fullName: System.ServiceModel.Configuration.MsmqTransportSecurityElement
  type: Class
  summary: "A classe MsmqTransportSecurityElement encapsula as configurações de segurança de transporte para transportes na fila."
  syntax:
    content: 'public sealed class MsmqTransportSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MsmqTransportSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.MsmqTransportSecurityElement
  langs:
  - csharp
  name: MsmqTransportSecurityElement()
  nameWithType: MsmqTransportSecurityElement.MsmqTransportSecurityElement()
  fullName: System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqTransportSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.ServiceModel.Configuration.MsmqTransportSecurityElement&quot;> </xref> classe."
  syntax:
    content: public MsmqTransportSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.MsmqTransportSecurityElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqAuthenticationMode
  id: MsmqAuthenticationMode
  parent: System.ServiceModel.Configuration.MsmqTransportSecurityElement
  langs:
  - csharp
  name: MsmqAuthenticationMode
  nameWithType: MsmqTransportSecurityElement.MsmqAuthenticationMode
  fullName: System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqAuthenticationMode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém ou define o <xref href=&quot;System.ServiceModel.MsmqAuthenticationMode&quot;> </xref> que está associado esta instância do <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> classe."
  remarks: "Enfileiramento de mensagens (MSMQ) pode autenticar mensagens enviadas para filas de mensagens que exigem autenticação ou mensagens explicitamente podem solicitar a autenticação. O modo de autenticação padrão é <xref:System.ServiceModel.MsmqAuthenticationMode>.</xref:System.ServiceModel.MsmqAuthenticationMode>"
  syntax:
    content: public System.ServiceModel.MsmqAuthenticationMode MsmqAuthenticationMode { get; set; }
    return:
      type: System.ServiceModel.MsmqAuthenticationMode
      description: "O <xref href=&quot;System.ServiceModel.MsmqAuthenticationMode&quot;> </xref> que está associado esta instância do <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> classe."
  overload: System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqAuthenticationMode*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqEncryptionAlgorithm
  id: MsmqEncryptionAlgorithm
  parent: System.ServiceModel.Configuration.MsmqTransportSecurityElement
  langs:
  - csharp
  name: MsmqEncryptionAlgorithm
  nameWithType: MsmqTransportSecurityElement.MsmqEncryptionAlgorithm
  fullName: System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqEncryptionAlgorithm
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém ou define o <xref href=&quot;System.ServiceModel.MsmqEncryptionAlgorithm&quot;> </xref> que está associado esta instância do <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> classe."
  remarks: "Serviço de enfileiramento de mensagens (MSMQ) pode criptografar mensagens na conexão durante a transferência de mensagens entre os gerenciadores de fila de mensagem. O algoritmo de criptografia padrão é <xref:System.ServiceModel.MsmqEncryptionAlgorithm>.</xref:System.ServiceModel.MsmqEncryptionAlgorithm>"
  syntax:
    content: public System.ServiceModel.MsmqEncryptionAlgorithm MsmqEncryptionAlgorithm { get; set; }
    return:
      type: System.ServiceModel.MsmqEncryptionAlgorithm
      description: "O <xref href=&quot;System.ServiceModel.MsmqEncryptionAlgorithm&quot;> </xref> que está associado esta instância do <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> classe."
  overload: System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqEncryptionAlgorithm*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqProtectionLevel
  id: MsmqProtectionLevel
  parent: System.ServiceModel.Configuration.MsmqTransportSecurityElement
  langs:
  - csharp
  name: MsmqProtectionLevel
  nameWithType: MsmqTransportSecurityElement.MsmqProtectionLevel
  fullName: System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqProtectionLevel
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém ou define o <xref href=&quot;System.Net.Security.ProtectionLevel&quot;> </xref> que está associado esta instância do <xref href=&quot;System.ServiceModel.Configuration.MsmqTransportSecurityElement&quot;> </xref> classe."
  remarks: "O nível de proteção padrão é <xref:System.Net.Security.ProtectionLevel>.</xref:System.Net.Security.ProtectionLevel>"
  syntax:
    content: public System.Net.Security.ProtectionLevel MsmqProtectionLevel { get; set; }
    return:
      type: System.Net.Security.ProtectionLevel
      description: "O <xref href=&quot;System.Net.Security.ProtectionLevel&quot;> </xref> que está associado esta instância do <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> classe."
  overload: System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqProtectionLevel*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqSecureHashAlgorithm
  id: MsmqSecureHashAlgorithm
  parent: System.ServiceModel.Configuration.MsmqTransportSecurityElement
  langs:
  - csharp
  name: MsmqSecureHashAlgorithm
  nameWithType: MsmqTransportSecurityElement.MsmqSecureHashAlgorithm
  fullName: System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqSecureHashAlgorithm
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém ou define o <xref href=&quot;System.ServiceModel.MsmqSecureHashAlgorithm&quot;> </xref> que está associado esta instância do <xref href=&quot;System.ServiceModel.Configuration.MsmqTransportSecurityElement&quot;> </xref> classe."
  remarks: "O algoritmo de hash padrão é <xref:System.ServiceModel.MsmqSecureHashAlgorithm>.</xref:System.ServiceModel.MsmqSecureHashAlgorithm>"
  syntax:
    content: public System.ServiceModel.MsmqSecureHashAlgorithm MsmqSecureHashAlgorithm { get; set; }
    return:
      type: System.ServiceModel.MsmqSecureHashAlgorithm
      description: "O <xref href=&quot;System.ServiceModel.MsmqSecureHashAlgorithm&quot;> </xref> que está associado esta instância do <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> classe."
  overload: System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqSecureHashAlgorithm*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MsmqTransportSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.MsmqTransportSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: MsmqTransportSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.MsmqTransportSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A ser adicionado."
  overload: System.ServiceModel.Configuration.MsmqTransportSecurityElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.MsmqTransportSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.MsmqTransportSecurityElement
  isExternal: false
  name: MsmqTransportSecurityElement()
  nameWithType: MsmqTransportSecurityElement.MsmqTransportSecurityElement()
  fullName: System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqTransportSecurityElement()
- uid: System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqAuthenticationMode
  parent: System.ServiceModel.Configuration.MsmqTransportSecurityElement
  isExternal: false
  name: MsmqAuthenticationMode
  nameWithType: MsmqTransportSecurityElement.MsmqAuthenticationMode
  fullName: System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqAuthenticationMode
- uid: System.ServiceModel.MsmqAuthenticationMode
  parent: System.ServiceModel
  isExternal: false
  name: MsmqAuthenticationMode
  nameWithType: MsmqAuthenticationMode
  fullName: System.ServiceModel.MsmqAuthenticationMode
- uid: System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqEncryptionAlgorithm
  parent: System.ServiceModel.Configuration.MsmqTransportSecurityElement
  isExternal: false
  name: MsmqEncryptionAlgorithm
  nameWithType: MsmqTransportSecurityElement.MsmqEncryptionAlgorithm
  fullName: System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqEncryptionAlgorithm
- uid: System.ServiceModel.MsmqEncryptionAlgorithm
  parent: System.ServiceModel
  isExternal: false
  name: MsmqEncryptionAlgorithm
  nameWithType: MsmqEncryptionAlgorithm
  fullName: System.ServiceModel.MsmqEncryptionAlgorithm
- uid: System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqProtectionLevel
  parent: System.ServiceModel.Configuration.MsmqTransportSecurityElement
  isExternal: false
  name: MsmqProtectionLevel
  nameWithType: MsmqTransportSecurityElement.MsmqProtectionLevel
  fullName: System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqProtectionLevel
- uid: System.Net.Security.ProtectionLevel
  parent: System.Net.Security
  isExternal: false
  name: ProtectionLevel
  nameWithType: ProtectionLevel
  fullName: System.Net.Security.ProtectionLevel
- uid: System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqSecureHashAlgorithm
  parent: System.ServiceModel.Configuration.MsmqTransportSecurityElement
  isExternal: false
  name: MsmqSecureHashAlgorithm
  nameWithType: MsmqTransportSecurityElement.MsmqSecureHashAlgorithm
  fullName: System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqSecureHashAlgorithm
- uid: System.ServiceModel.MsmqSecureHashAlgorithm
  parent: System.ServiceModel
  isExternal: false
  name: MsmqSecureHashAlgorithm
  nameWithType: MsmqSecureHashAlgorithm
  fullName: System.ServiceModel.MsmqSecureHashAlgorithm
- uid: System.ServiceModel.Configuration.MsmqTransportSecurityElement.Properties
  parent: System.ServiceModel.Configuration.MsmqTransportSecurityElement
  isExternal: false
  name: Properties
  nameWithType: MsmqTransportSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.MsmqTransportSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.MsmqTransportSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.MsmqTransportSecurityElement
  isExternal: false
  name: MsmqTransportSecurityElement
  nameWithType: MsmqTransportSecurityElement.MsmqTransportSecurityElement
- uid: System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqAuthenticationMode*
  parent: System.ServiceModel.Configuration.MsmqTransportSecurityElement
  isExternal: false
  name: MsmqAuthenticationMode
  nameWithType: MsmqTransportSecurityElement.MsmqAuthenticationMode
- uid: System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqEncryptionAlgorithm*
  parent: System.ServiceModel.Configuration.MsmqTransportSecurityElement
  isExternal: false
  name: MsmqEncryptionAlgorithm
  nameWithType: MsmqTransportSecurityElement.MsmqEncryptionAlgorithm
- uid: System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqProtectionLevel*
  parent: System.ServiceModel.Configuration.MsmqTransportSecurityElement
  isExternal: false
  name: MsmqProtectionLevel
  nameWithType: MsmqTransportSecurityElement.MsmqProtectionLevel
- uid: System.ServiceModel.Configuration.MsmqTransportSecurityElement.MsmqSecureHashAlgorithm*
  parent: System.ServiceModel.Configuration.MsmqTransportSecurityElement
  isExternal: false
  name: MsmqSecureHashAlgorithm
  nameWithType: MsmqTransportSecurityElement.MsmqSecureHashAlgorithm
- uid: System.ServiceModel.Configuration.MsmqTransportSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.MsmqTransportSecurityElement
  isExternal: false
  name: Properties
  nameWithType: MsmqTransportSecurityElement.Properties
