### YamlMime:ManagedReference
items:
- uid: System.Configuration.CallbackValidator
  id: CallbackValidator
  children:
  - System.Configuration.CallbackValidator.#ctor(System.Type,System.Configuration.ValidatorCallback)
  - System.Configuration.CallbackValidator.CanValidate(System.Type)
  - System.Configuration.CallbackValidator.Validate(System.Object)
  langs:
  - csharp
  name: CallbackValidator
  nameWithType: CallbackValidator
  fullName: System.Configuration.CallbackValidator
  type: Class
  summary: "Fornece validação dinâmica de um objeto."
  remarks: "Para usar essa classe, você precisa implementar um <xref:System.Configuration.ValidatorCallback>delegar para o tipo de objeto que você deseja validar.</xref:System.Configuration.ValidatorCallback> Quando você cria uma instância dessa classe, você passar o tipo de objeto e uma referência ao representante. Em seguida, você pode chamar <xref:System.Configuration.CallbackValidator.CanValidate%2A>para determinar se um objeto é do tipo correto ou <xref:System.Configuration.CallbackValidator.Validate%2A>para executar o delegado no objeto.</xref:System.Configuration.CallbackValidator.Validate%2A> </xref:System.Configuration.CallbackValidator.CanValidate%2A>"
  syntax:
    content: 'public sealed class CallbackValidator : System.Configuration.ConfigurationValidatorBase'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationValidatorBase
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.CallbackValidator.#ctor(System.Type,System.Configuration.ValidatorCallback)
  id: '#ctor(System.Type,System.Configuration.ValidatorCallback)'
  parent: System.Configuration.CallbackValidator
  langs:
  - csharp
  name: CallbackValidator(Type,ValidatorCallback)
  nameWithType: CallbackValidator.CallbackValidator(Type,ValidatorCallback)
  fullName: System.Configuration.CallbackValidator.CallbackValidator(Type,ValidatorCallback)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Configuration.CallbackValidator&quot;> </xref> classe."
  syntax:
    content: public CallbackValidator (Type type, System.Configuration.ValidatorCallback callback);
    parameters:
    - id: type
      type: System.Type
      description: "O tipo de objeto que será validado."
    - id: callback
      type: System.Configuration.ValidatorCallback
      description: "O <xref href=&quot;System.Configuration.ValidatorCallback&quot;> </xref> usado como o delegado."
  overload: System.Configuration.CallbackValidator.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>type </code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.Configuration.CallbackValidator.CanValidate(System.Type)
  id: CanValidate(System.Type)
  parent: System.Configuration.CallbackValidator
  langs:
  - csharp
  name: CanValidate(Type)
  nameWithType: CallbackValidator.CanValidate(Type)
  fullName: System.Configuration.CallbackValidator.CanValidate(Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Determina se o tipo de objeto pode ser validado."
  syntax:
    content: public override bool CanValidate (Type type);
    parameters:
    - id: type
      type: System.Type
      description: "O tipo de objeto."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se o <xref uid=&quot;langword_csharp_type&quot; name=&quot;type&quot; href=&quot;&quot;> </xref> parâmetro corresponde ao tipo usado como o primeiro parâmetro ao criar uma instância de <xref href=&quot;System.Configuration.CallbackValidator&quot;> </xref>; caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.CallbackValidator.CanValidate*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.CallbackValidator.Validate(System.Object)
  id: Validate(System.Object)
  parent: System.Configuration.CallbackValidator
  langs:
  - csharp
  name: Validate(Object)
  nameWithType: CallbackValidator.Validate(Object)
  fullName: System.Configuration.CallbackValidator.Validate(Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Determina se o valor de um objeto é válido."
  remarks: "O <xref:System.Configuration.CallbackValidator>classe contém o tipo e o delegado necessário para validar um objeto.</xref:System.Configuration.CallbackValidator> O tipo e o delegado são estabelecidos quando uma instância do <xref:System.Configuration.CallbackValidator>classe é criada.</xref:System.Configuration.CallbackValidator> O objeto para validar é passado como um parâmetro do método Validate."
  syntax:
    content: public override void Validate (object value);
    parameters:
    - id: value
      type: System.Object
      description: "O valor de um objeto."
  overload: System.Configuration.CallbackValidator.Validate*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: System.Configuration.ConfigurationValidatorBase
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Configuration.CallbackValidator.#ctor(System.Type,System.Configuration.ValidatorCallback)
  parent: System.Configuration.CallbackValidator
  isExternal: false
  name: CallbackValidator(Type,ValidatorCallback)
  nameWithType: CallbackValidator.CallbackValidator(Type,ValidatorCallback)
  fullName: System.Configuration.CallbackValidator.CallbackValidator(Type,ValidatorCallback)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.ValidatorCallback
  parent: System.Configuration
  isExternal: false
  name: ValidatorCallback
  nameWithType: ValidatorCallback
  fullName: System.Configuration.ValidatorCallback
- uid: System.Configuration.CallbackValidator.CanValidate(System.Type)
  parent: System.Configuration.CallbackValidator
  isExternal: false
  name: CanValidate(Type)
  nameWithType: CallbackValidator.CanValidate(Type)
  fullName: System.Configuration.CallbackValidator.CanValidate(Type)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.CallbackValidator.Validate(System.Object)
  parent: System.Configuration.CallbackValidator
  isExternal: false
  name: Validate(Object)
  nameWithType: CallbackValidator.Validate(Object)
  fullName: System.Configuration.CallbackValidator.Validate(Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.CallbackValidator.#ctor*
  parent: System.Configuration.CallbackValidator
  isExternal: false
  name: CallbackValidator
  nameWithType: CallbackValidator.CallbackValidator
- uid: System.Configuration.CallbackValidator.CanValidate*
  parent: System.Configuration.CallbackValidator
  isExternal: false
  name: CanValidate
  nameWithType: CallbackValidator.CanValidate
- uid: System.Configuration.CallbackValidator.Validate*
  parent: System.Configuration.CallbackValidator
  isExternal: false
  name: Validate
  nameWithType: CallbackValidator.Validate
