### YamlMime:ManagedReference
items:
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  id: PeerApplicationRegistrationType
  children:
  - System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
  - System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
  langs:
  - csharp
  name: PeerApplicationRegistrationType
  nameWithType: PeerApplicationRegistrationType
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  type: Enum
  summary: "Especifica o tipo de registro para executar para uma <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> ou <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerObject&quot;> </xref> registro."
  remarks: "Registrando um <xref:System.Net.PeerToPeer.Collaboration.PeerApplication>permite que ele receba <xref:System.Net.PeerToPeer.Collaboration.PeerCollaboration>solicitações de convite.</xref:System.Net.PeerToPeer.Collaboration.PeerCollaboration> </xref:System.Net.PeerToPeer.Collaboration.PeerApplication> O serviço ou aplicativo que executa o registro deve ter permissão para fazer isso, como ele requer acesso para o <xref:System.Net.PeerToPeer.Collaboration.ContactManager>e outros recursos, como usuários, aplicativos e serviços no computador remoto.</xref:System.Net.PeerToPeer.Collaboration.ContactManager>"
  syntax:
    content: public enum PeerApplicationRegistrationType
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
  id: AllUsers
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  langs:
  - csharp
  name: AllUsers
  nameWithType: PeerApplicationRegistrationType.AllUsers
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
  type: Field
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "O <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> ou <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerObject&quot;> </xref> está sendo registrado para todos os pares de host do aplicativo"
  syntax:
    content: AllUsers
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
  id: CurrentUser
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  langs:
  - csharp
  name: CurrentUser
  nameWithType: PeerApplicationRegistrationType.CurrentUser
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
  type: Field
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "O aplicativo ou o objeto está sendo registrado apenas para o usuário associado com o par de chamada"
  syntax:
    content: CurrentUser
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  isExternal: false
  name: AllUsers
  nameWithType: PeerApplicationRegistrationType.AllUsers
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerApplicationRegistrationType
  nameWithType: PeerApplicationRegistrationType
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  isExternal: false
  name: CurrentUser
  nameWithType: PeerApplicationRegistrationType.CurrentUser
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
