### YamlMime:ManagedReference
items:
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute
  id: PositiveTimeSpanValidatorAttribute
  children:
  - System.Configuration.PositiveTimeSpanValidatorAttribute.#ctor
  - System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: PositiveTimeSpanValidatorAttribute
  nameWithType: PositiveTimeSpanValidatorAttribute
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute
  type: Class
  summary: "Declarativamente instrui o .NET Framework para executar a validação de tempo em uma propriedade de configuração. Essa classe não pode ser herdada."
  remarks: "Você pode usar o atributo PositiveTimeSpanValidatorAttribute para decorar uma propriedade de configuração. Isso instrui o .NET Framework para validar a propriedade usando um <xref:System.Configuration.PositiveTimeSpanValidator>do objeto e passar o valor dos parâmetros de decoração.</xref:System.Configuration.PositiveTimeSpanValidator>       Você pode aplicar objetos PositiveTimeSpanValidatorAttribute somente aos tipos de propriedade."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class PositiveTimeSpanValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net462
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  langs:
  - csharp
  name: PositiveTimeSpanValidatorAttribute()
  nameWithType: PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute()
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Configuration.PositiveTimeSpanValidatorAttribute&quot;> </xref> classe."
  remarks: "Use este construtor no modelo atribuído para garantir que o tipo do valor atribuído à propriedade relacionada é um positivo <xref:System.TimeSpan>objeto.</xref:System.TimeSpan>"
  syntax:
    content: public PositiveTimeSpanValidatorAttribute ();
    parameters: []
  overload: System.Configuration.PositiveTimeSpanValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: PositiveTimeSpanValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Obtém uma instância do <xref href=&quot;System.Configuration.PositiveTimeSpanValidator&quot;> </xref> classe."
  remarks: "Use a propriedade ValidatorInstance executar positivo <xref:System.TimeSpan>objeto validação chamando o <xref:System.Configuration.PositiveTimeSpanValidator.Validate%2A?displayProperty=fullName>método.</xref:System.Configuration.PositiveTimeSpanValidator.Validate%2A?displayProperty=fullName> </xref:System.TimeSpan>"
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "O <xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref> instância de validador."
  overload: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.#ctor
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  isExternal: false
  name: PositiveTimeSpanValidatorAttribute()
  nameWithType: PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute()
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute()
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: PositiveTimeSpanValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.#ctor*
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  isExternal: false
  name: PositiveTimeSpanValidatorAttribute
  nameWithType: PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: PositiveTimeSpanValidatorAttribute.ValidatorInstance
