### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsSerializeAs
  id: SettingsSerializeAs
  children:
  - System.Configuration.SettingsSerializeAs.Binary
  - System.Configuration.SettingsSerializeAs.ProviderSpecific
  - System.Configuration.SettingsSerializeAs.String
  - System.Configuration.SettingsSerializeAs.Xml
  langs:
  - csharp
  name: SettingsSerializeAs
  nameWithType: SettingsSerializeAs
  fullName: System.Configuration.SettingsSerializeAs
  type: Enum
  summary: "Determina o esquema de serialização usado para armazenar configurações de aplicativo."
  remarks: "O SettingsSerializeAsenumeration é usado para especificar o mecanismo de serialização usado pelo provedor de configurações do aplicativo para manter os valores das propriedades de configurações do aplicativo. Por exemplo, o ttribute usa essa enumeração em seu construtor para solicitar uma propriedade ou um grupo de propriedades ser mantidas usando o mecanismo de serialização especificada."
  syntax:
    content: public enum SettingsSerializeAs
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.SettingsSerializeAs.Binary
  id: Binary
  parent: System.Configuration.SettingsSerializeAs
  langs:
  - csharp
  name: Binary
  nameWithType: SettingsSerializeAs.Binary
  fullName: System.Configuration.SettingsSerializeAs.Binary
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "A propriedade de configurações é serializada usando a serialização de objeto binário."
  syntax:
    content: Binary
    return:
      type: System.Configuration.SettingsSerializeAs
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsSerializeAs.ProviderSpecific
  id: ProviderSpecific
  parent: System.Configuration.SettingsSerializeAs
  langs:
  - csharp
  name: ProviderSpecific
  nameWithType: SettingsSerializeAs.ProviderSpecific
  fullName: System.Configuration.SettingsSerializeAs.ProviderSpecific
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "O provedor de configurações tiver conhecimento implícito da propriedade ou seu tipo e escolhe um mecanismo de serialização apropriado. Geralmente usado para serialização personalizada."
  syntax:
    content: ProviderSpecific
    return:
      type: System.Configuration.SettingsSerializeAs
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsSerializeAs.String
  id: String
  parent: System.Configuration.SettingsSerializeAs
  langs:
  - csharp
  name: String
  nameWithType: SettingsSerializeAs.String
  fullName: System.Configuration.SettingsSerializeAs.String
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "A propriedade de configurações é serializada como texto sem formatação."
  syntax:
    content: String
    return:
      type: System.Configuration.SettingsSerializeAs
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsSerializeAs.Xml
  id: Xml
  parent: System.Configuration.SettingsSerializeAs
  langs:
  - csharp
  name: Xml
  nameWithType: SettingsSerializeAs.Xml
  fullName: System.Configuration.SettingsSerializeAs.Xml
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "A propriedade de configurações é serializada como XML usando a serialização de XML."
  syntax:
    content: Xml
    return:
      type: System.Configuration.SettingsSerializeAs
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.SettingsSerializeAs.Binary
  parent: System.Configuration.SettingsSerializeAs
  isExternal: false
  name: Binary
  nameWithType: SettingsSerializeAs.Binary
  fullName: System.Configuration.SettingsSerializeAs.Binary
- uid: System.Configuration.SettingsSerializeAs
  parent: System.Configuration
  isExternal: false
  name: SettingsSerializeAs
  nameWithType: SettingsSerializeAs
  fullName: System.Configuration.SettingsSerializeAs
- uid: System.Configuration.SettingsSerializeAs.ProviderSpecific
  parent: System.Configuration.SettingsSerializeAs
  isExternal: false
  name: ProviderSpecific
  nameWithType: SettingsSerializeAs.ProviderSpecific
  fullName: System.Configuration.SettingsSerializeAs.ProviderSpecific
- uid: System.Configuration.SettingsSerializeAs.String
  parent: System.Configuration.SettingsSerializeAs
  isExternal: false
  name: String
  nameWithType: SettingsSerializeAs.String
  fullName: System.Configuration.SettingsSerializeAs.String
- uid: System.Configuration.SettingsSerializeAs.Xml
  parent: System.Configuration.SettingsSerializeAs
  isExternal: false
  name: Xml
  nameWithType: SettingsSerializeAs.Xml
  fullName: System.Configuration.SettingsSerializeAs.Xml
