### YamlMime:ManagedReference
items:
- uid: System.Activities.WorkflowApplicationCompletedException
  id: WorkflowApplicationCompletedException
  children:
  - System.Activities.WorkflowApplicationCompletedException.#ctor
  - System.Activities.WorkflowApplicationCompletedException.#ctor(System.String)
  - System.Activities.WorkflowApplicationCompletedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Activities.WorkflowApplicationCompletedException.#ctor(System.String,System.Exception)
  - System.Activities.WorkflowApplicationCompletedException.#ctor(System.String,System.Guid)
  - System.Activities.WorkflowApplicationCompletedException.#ctor(System.String,System.Guid,System.Exception)
  langs:
  - csharp
  name: WorkflowApplicationCompletedException
  nameWithType: WorkflowApplicationCompletedException
  fullName: System.Activities.WorkflowApplicationCompletedException
  type: Class
  summary: "Representa a exceção que é lançada quando uma operação em uma instância de fluxo de trabalho não é válida porque a instância foi concluída."
  syntax:
    content: 'public class WorkflowApplicationCompletedException : System.Activities.WorkflowApplicationException'
  inheritance:
  - System.Exception
  - System.Activities.WorkflowApplicationException
  implements: []
  inheritedMembers:
  - System.Activities.WorkflowApplicationException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Activities.WorkflowApplicationException.InstanceId
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor
  id: '#ctor'
  parent: System.Activities.WorkflowApplicationCompletedException
  langs:
  - csharp
  name: WorkflowApplicationCompletedException()
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException()
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException()
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Cria uma nova instância do <xref href=&quot;System.Activities.WorkflowApplicationCompletedException&quot;> </xref> classe."
  syntax:
    content: public WorkflowApplicationCompletedException ();
    parameters: []
  overload: System.Activities.WorkflowApplicationCompletedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Activities.WorkflowApplicationCompletedException
  langs:
  - csharp
  name: WorkflowApplicationCompletedException(String)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Cria uma nova instância do <xref href=&quot;System.Activities.WorkflowApplicationCompletedException&quot;> </xref> classe com uma descrição de cadeia de caracteres de texto da exceção."
  syntax:
    content: public WorkflowApplicationCompletedException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Uma descrição do aplicativo foi concluída a exceção."
  overload: System.Activities.WorkflowApplicationCompletedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Activities.WorkflowApplicationCompletedException
  langs:
  - csharp
  name: WorkflowApplicationCompletedException(SerializationInfo,StreamingContext)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(SerializationInfo,StreamingContext)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Cria uma nova instância do <xref href=&quot;System.Activities.WorkflowApplicationCompletedException&quot;> </xref> classe com as informações de serialização e contexto necessárias para recuperar dados sobre esta exceção de um fluxo serializado."
  syntax:
    content: protected WorkflowApplicationCompletedException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "Todas as informações necessárias para serializar ou desserializar o objeto de exceção de aplicativo concluído."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "A origem e destino de um determinado fluxo serializado e um contexto adicional definido pelo chamador."
  overload: System.Activities.WorkflowApplicationCompletedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Activities.WorkflowApplicationCompletedException
  langs:
  - csharp
  name: WorkflowApplicationCompletedException(String,Exception)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Exception)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Exception)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Cria uma nova instância do <xref href=&quot;System.Activities.WorkflowApplicationCompletedException&quot;> </xref> classe com uma descrição de cadeia de caracteres de texto da exceção e com uma exceção adicional que é a causa da exceção de aplicativo concluído."
  syntax:
    content: public WorkflowApplicationCompletedException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Uma descrição do aplicativo foi concluída a exceção."
    - id: innerException
      type: System.Exception
      description: "Uma exceção que tenha uma relação causal para o aplicativo concluir a exceção. A exceção de aplicativo concluída é gerada em resposta a exceção interna e pode usar as informações da exceção interna para tratar o erro mais adequadamente."
  overload: System.Activities.WorkflowApplicationCompletedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.String,System.Guid)
  id: '#ctor(System.String,System.Guid)'
  parent: System.Activities.WorkflowApplicationCompletedException
  langs:
  - csharp
  name: WorkflowApplicationCompletedException(String,Guid)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Guid)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Guid)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Cria uma nova instância do <xref href=&quot;System.Activities.WorkflowApplicationCompletedException&quot;> </xref> classe com uma descrição de cadeia de caracteres de texto da exceção e com um identificador exclusivo para a exceção."
  syntax:
    content: public WorkflowApplicationCompletedException (string message, Guid instanceId);
    parameters:
    - id: message
      type: System.String
      description: "Uma descrição do aplicativo foi concluída a exceção."
    - id: instanceId
      type: System.Guid
      description: "Um identificador globalmente exclusivo."
  overload: System.Activities.WorkflowApplicationCompletedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.String,System.Guid,System.Exception)
  id: '#ctor(System.String,System.Guid,System.Exception)'
  parent: System.Activities.WorkflowApplicationCompletedException
  langs:
  - csharp
  name: WorkflowApplicationCompletedException(String,Guid,Exception)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Guid,Exception)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Guid,Exception)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Cria uma nova instância do <xref href=&quot;System.Activities.WorkflowApplicationCompletedException&quot;> </xref> classe com uma descrição de cadeia de caracteres de texto da exceção adicional que é a causa da exceção de aplicativo concluída, um identificador exclusivo para ela e a exceção."
  syntax:
    content: public WorkflowApplicationCompletedException (string message, Guid instanceId, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Uma descrição do aplicativo foi concluída a exceção."
    - id: instanceId
      type: System.Guid
      description: "Um identificador globalmente exclusivo."
    - id: innerException
      type: System.Exception
      description: "Uma exceção que tenha uma relação causal para o aplicativo concluir a exceção. A exceção de aplicativo concluída é gerada em resposta a exceção interna e pode usar as informações da exceção interna para tratar o erro mais adequadamente."
  overload: System.Activities.WorkflowApplicationCompletedException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Activities.WorkflowApplicationException
  isExternal: false
  name: System.Activities.WorkflowApplicationException
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor
  parent: System.Activities.WorkflowApplicationCompletedException
  isExternal: false
  name: WorkflowApplicationCompletedException()
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException()
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException()
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.String)
  parent: System.Activities.WorkflowApplicationCompletedException
  isExternal: false
  name: WorkflowApplicationCompletedException(String)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Activities.WorkflowApplicationCompletedException
  isExternal: false
  name: WorkflowApplicationCompletedException(SerializationInfo,StreamingContext)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(SerializationInfo,StreamingContext)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.String,System.Exception)
  parent: System.Activities.WorkflowApplicationCompletedException
  isExternal: false
  name: WorkflowApplicationCompletedException(String,Exception)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Exception)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.String,System.Guid)
  parent: System.Activities.WorkflowApplicationCompletedException
  isExternal: false
  name: WorkflowApplicationCompletedException(String,Guid)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Guid)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Guid)
- uid: System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.String,System.Guid,System.Exception)
  parent: System.Activities.WorkflowApplicationCompletedException
  isExternal: false
  name: WorkflowApplicationCompletedException(String,Guid,Exception)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Guid,Exception)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Guid,Exception)
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor*
  parent: System.Activities.WorkflowApplicationCompletedException
  isExternal: false
  name: WorkflowApplicationCompletedException
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException
