### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.HostSettings
  id: HostSettings
  children:
  - System.ServiceModel.Activities.HostSettings.#ctor
  - System.ServiceModel.Activities.HostSettings.IncludeExceptionDetailInFaults
  - System.ServiceModel.Activities.HostSettings.ScopeName
  - System.ServiceModel.Activities.HostSettings.UseNoPersistHandle
  langs:
  - csharp
  name: HostSettings
  nameWithType: HostSettings
  fullName: System.ServiceModel.Activities.HostSettings
  type: Class
  summary: "Representa as configurações que definem as características operacionais de um host."
  syntax:
    content: public sealed class HostSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.HostSettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.HostSettings
  langs:
  - csharp
  name: HostSettings()
  nameWithType: HostSettings.HostSettings()
  fullName: System.ServiceModel.Activities.HostSettings.HostSettings()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Inicializa uma nova instância do <xref href=&quot;System.ServiceModel.Activities.HostSettings&quot;> </xref> classe."
  syntax:
    content: public HostSettings ();
    parameters: []
  overload: System.ServiceModel.Activities.HostSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.HostSettings.IncludeExceptionDetailInFaults
  id: IncludeExceptionDetailInFaults
  parent: System.ServiceModel.Activities.HostSettings
  langs:
  - csharp
  name: IncludeExceptionDetailInFaults
  nameWithType: HostSettings.IncludeExceptionDetailInFaults
  fullName: System.ServiceModel.Activities.HostSettings.IncludeExceptionDetailInFaults
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Obtém ou define se os detalhes da exceção são incluídos em falhas."
  syntax:
    content: public bool IncludeExceptionDetailInFaults { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se os detalhes da exceção são incluídos em falhas. Caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Activities.HostSettings.IncludeExceptionDetailInFaults*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.HostSettings.ScopeName
  id: ScopeName
  parent: System.ServiceModel.Activities.HostSettings
  langs:
  - csharp
  name: ScopeName
  nameWithType: HostSettings.ScopeName
  fullName: System.ServiceModel.Activities.HostSettings.ScopeName
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Obtém ou define o nome do escopo."
  syntax:
    content: public System.Xml.Linq.XName ScopeName { get; set; }
    return:
      type: System.Xml.Linq.XName
      description: "O nome do escopo."
  overload: System.ServiceModel.Activities.HostSettings.ScopeName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.HostSettings.UseNoPersistHandle
  id: UseNoPersistHandle
  parent: System.ServiceModel.Activities.HostSettings
  langs:
  - csharp
  name: UseNoPersistHandle
  nameWithType: HostSettings.UseNoPersistHandle
  fullName: System.ServiceModel.Activities.HostSettings.UseNoPersistHandle
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Obtém ou define um valor que indica se deve usar o identificador não persistente."
  syntax:
    content: public bool UseNoPersistHandle { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se o identificador não persistente é usado; Caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Activities.HostSettings.UseNoPersistHandle*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.Activities.HostSettings.#ctor
  parent: System.ServiceModel.Activities.HostSettings
  isExternal: false
  name: HostSettings()
  nameWithType: HostSettings.HostSettings()
  fullName: System.ServiceModel.Activities.HostSettings.HostSettings()
- uid: System.ServiceModel.Activities.HostSettings.IncludeExceptionDetailInFaults
  parent: System.ServiceModel.Activities.HostSettings
  isExternal: false
  name: IncludeExceptionDetailInFaults
  nameWithType: HostSettings.IncludeExceptionDetailInFaults
  fullName: System.ServiceModel.Activities.HostSettings.IncludeExceptionDetailInFaults
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Activities.HostSettings.ScopeName
  parent: System.ServiceModel.Activities.HostSettings
  isExternal: false
  name: ScopeName
  nameWithType: HostSettings.ScopeName
  fullName: System.ServiceModel.Activities.HostSettings.ScopeName
- uid: System.Xml.Linq.XName
  parent: System.Xml.Linq
  isExternal: true
  name: XName
  nameWithType: XName
  fullName: System.Xml.Linq.XName
- uid: System.ServiceModel.Activities.HostSettings.UseNoPersistHandle
  parent: System.ServiceModel.Activities.HostSettings
  isExternal: false
  name: UseNoPersistHandle
  nameWithType: HostSettings.UseNoPersistHandle
  fullName: System.ServiceModel.Activities.HostSettings.UseNoPersistHandle
- uid: System.ServiceModel.Activities.HostSettings.#ctor*
  parent: System.ServiceModel.Activities.HostSettings
  isExternal: false
  name: HostSettings
  nameWithType: HostSettings.HostSettings
- uid: System.ServiceModel.Activities.HostSettings.IncludeExceptionDetailInFaults*
  parent: System.ServiceModel.Activities.HostSettings
  isExternal: false
  name: IncludeExceptionDetailInFaults
  nameWithType: HostSettings.IncludeExceptionDetailInFaults
- uid: System.ServiceModel.Activities.HostSettings.ScopeName*
  parent: System.ServiceModel.Activities.HostSettings
  isExternal: false
  name: ScopeName
  nameWithType: HostSettings.ScopeName
- uid: System.ServiceModel.Activities.HostSettings.UseNoPersistHandle*
  parent: System.ServiceModel.Activities.HostSettings
  isExternal: false
  name: UseNoPersistHandle
  nameWithType: HostSettings.UseNoPersistHandle
