### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  id: ICustomIdentityConfiguration
  children:
  - System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(System.Xml.XmlNodeList)
  langs:
  - csharp
  name: ICustomIdentityConfiguration
  nameWithType: ICustomIdentityConfiguration
  fullName: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  type: Interface
  summary: "Define métodos que permitem que uma classe para carregar a configuração personalizada."
  remarks: "Classes que implementam a interface ICustomIdentityConfiguration podem carregar a configuração personalizada do XML.       Várias classes de Windows Identity Foundation (WIF) implementam a interface de ICustomIdentityConfiguration para fornecer a capacidade de definir uma configuração personalizada de classes derivadas de um arquivo de configuração. Muitas das classes WIF fornecem uma implementação de base deste método para fornecer a configuração padrão para os objetos que eles representam."
  syntax:
    content: public interface ICustomIdentityConfiguration
  implements: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(System.Xml.XmlNodeList)
  id: LoadCustomConfiguration(System.Xml.XmlNodeList)
  parent: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  langs:
  - csharp
  name: LoadCustomConfiguration(XmlNodeList)
  nameWithType: ICustomIdentityConfiguration.LoadCustomConfiguration(XmlNodeList)
  fullName: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(XmlNodeList)
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Configuração personalizada de cargas de XML. Substitua este método para fornecer manipulação personalizada de elementos de configuração."
  remarks: "O método LoadCustomConfiguration é chamado pela infraestrutura de configuração. Quando este método é chamado, o `nodelist` parâmetro contém os elementos filho de nível superior do elemento pai que define a classe de objeto do arquivo de configuração. Por exemplo, uma classe derivada de <xref:System.IdentityModel.Tokens.IssuerNameRegistry>, terá os elementos filho do [ \\&lt; issuerNameRegistry\\&gt;](../Topic/%3CissuerNameRegistry%3E.md) elemento passado a `nodelist` parâmetro.</xref:System.IdentityModel.Tokens.IssuerNameRegistry> O `nodelist` é composta inteiramente de <xref:System.Xml.XmlElement>objetos.</xref:System.Xml.XmlElement> Cada um deles pode ter atributos e elementos filho dependendo do esquema de configuração definida para a classe que está sendo configurada."
  syntax:
    content: public void LoadCustomConfiguration (System.Xml.XmlNodeList nodeList);
    parameters:
    - id: nodeList
      type: System.Xml.XmlNodeList
      description: "Os nós XML que contêm a configuração personalizada. Cada nó na lista é do tipo <xref href=&quot;System.Xml.XmlElement&quot;> </xref>."
  overload: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration*
  exceptions: []
  platform:
  - net462
references:
- uid: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(System.Xml.XmlNodeList)
  parent: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  isExternal: false
  name: LoadCustomConfiguration(XmlNodeList)
  nameWithType: ICustomIdentityConfiguration.LoadCustomConfiguration(XmlNodeList)
  fullName: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(XmlNodeList)
- uid: System.Xml.XmlNodeList
  parent: System.Xml
  isExternal: false
  name: XmlNodeList
  nameWithType: XmlNodeList
  fullName: System.Xml.XmlNodeList
- uid: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration*
  parent: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  isExternal: false
  name: LoadCustomConfiguration
  nameWithType: ICustomIdentityConfiguration.LoadCustomConfiguration
