### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ClaimTypeElement
  id: ClaimTypeElement
  children:
  - System.ServiceModel.Configuration.ClaimTypeElement.#ctor
  - System.ServiceModel.Configuration.ClaimTypeElement.#ctor(System.String,System.Boolean)
  - System.ServiceModel.Configuration.ClaimTypeElement.ClaimType
  - System.ServiceModel.Configuration.ClaimTypeElement.IsOptional
  - System.ServiceModel.Configuration.ClaimTypeElement.Properties
  langs:
  - csharp
  name: ClaimTypeElement
  nameWithType: ClaimTypeElement
  fullName: System.ServiceModel.Configuration.ClaimTypeElement
  type: Class
  summary: "Representa um elemento de configuração que contém o tipo de declaração. Essa classe não pode ser herdada."
  syntax:
    content: 'public sealed class ClaimTypeElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ClaimTypeElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ClaimTypeElement
  langs:
  - csharp
  name: ClaimTypeElement()
  nameWithType: ClaimTypeElement.ClaimTypeElement()
  fullName: System.ServiceModel.Configuration.ClaimTypeElement.ClaimTypeElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.ServiceModel.Configuration.ClaimTypeElement&quot;> </xref> classe."
  syntax:
    content: public ClaimTypeElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ClaimTypeElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ClaimTypeElement.#ctor(System.String,System.Boolean)
  id: '#ctor(System.String,System.Boolean)'
  parent: System.ServiceModel.Configuration.ClaimTypeElement
  langs:
  - csharp
  name: ClaimTypeElement(String,Boolean)
  nameWithType: ClaimTypeElement.ClaimTypeElement(String,Boolean)
  fullName: System.ServiceModel.Configuration.ClaimTypeElement.ClaimTypeElement(String,Boolean)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.ServiceModel.Configuration.ClaimTypeElement&quot;> </xref> classe."
  syntax:
    content: public ClaimTypeElement (string claimType, bool isOptional);
    parameters:
    - id: claimType
      type: System.String
      description: "Um identificador de recurso uniforme (URI) que especifica o tipo de declaração. Tipos de declaração predefinidos estão disponíveis como propriedades estáticas do <xref href=&quot;System.IdentityModel.Claims.ClaimTypes&quot;> </xref> classe."
    - id: isOptional
      type: System.Boolean
      description: "Um valor booleano que especifica se a declaração é opcional."
  overload: System.ServiceModel.Configuration.ClaimTypeElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ClaimTypeElement.ClaimType
  id: ClaimType
  parent: System.ServiceModel.Configuration.ClaimTypeElement
  langs:
  - csharp
  name: ClaimType
  nameWithType: ClaimTypeElement.ClaimType
  fullName: System.ServiceModel.Configuration.ClaimTypeElement.ClaimType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém ou define uma representação de cadeia de caracteres de um uniform resource identifier (URI) que especifica o tipo de declaração."
  remarks: "Tipos de declaração predefinidos estão disponíveis como propriedades estáticas da <xref:System.IdentityModel.Claims.ClaimTypes>classe.</xref:System.IdentityModel.Claims.ClaimTypes>"
  syntax:
    content: public string ClaimType { get; set; }
    return:
      type: System.String
      description: "Um identificador de recurso uniforme (URI) que especifica o tipo de declaração."
  overload: System.ServiceModel.Configuration.ClaimTypeElement.ClaimType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ClaimTypeElement.IsOptional
  id: IsOptional
  parent: System.ServiceModel.Configuration.ClaimTypeElement
  langs:
  - csharp
  name: IsOptional
  nameWithType: ClaimTypeElement.IsOptional
  fullName: System.ServiceModel.Configuration.ClaimTypeElement.IsOptional
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém ou define um valor booleano que especifica se a declaração é opcional."
  syntax:
    content: public bool IsOptional { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se a declaração é opcional. Caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Configuration.ClaimTypeElement.IsOptional*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ClaimTypeElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ClaimTypeElement
  langs:
  - csharp
  name: Properties
  nameWithType: ClaimTypeElement.Properties
  fullName: System.ServiceModel.Configuration.ClaimTypeElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A ser adicionado."
  overload: System.ServiceModel.Configuration.ClaimTypeElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.ClaimTypeElement.#ctor
  parent: System.ServiceModel.Configuration.ClaimTypeElement
  isExternal: false
  name: ClaimTypeElement()
  nameWithType: ClaimTypeElement.ClaimTypeElement()
  fullName: System.ServiceModel.Configuration.ClaimTypeElement.ClaimTypeElement()
- uid: System.ServiceModel.Configuration.ClaimTypeElement.#ctor(System.String,System.Boolean)
  parent: System.ServiceModel.Configuration.ClaimTypeElement
  isExternal: false
  name: ClaimTypeElement(String,Boolean)
  nameWithType: ClaimTypeElement.ClaimTypeElement(String,Boolean)
  fullName: System.ServiceModel.Configuration.ClaimTypeElement.ClaimTypeElement(String,Boolean)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.ClaimTypeElement.ClaimType
  parent: System.ServiceModel.Configuration.ClaimTypeElement
  isExternal: false
  name: ClaimType
  nameWithType: ClaimTypeElement.ClaimType
  fullName: System.ServiceModel.Configuration.ClaimTypeElement.ClaimType
- uid: System.ServiceModel.Configuration.ClaimTypeElement.IsOptional
  parent: System.ServiceModel.Configuration.ClaimTypeElement
  isExternal: false
  name: IsOptional
  nameWithType: ClaimTypeElement.IsOptional
  fullName: System.ServiceModel.Configuration.ClaimTypeElement.IsOptional
- uid: System.ServiceModel.Configuration.ClaimTypeElement.Properties
  parent: System.ServiceModel.Configuration.ClaimTypeElement
  isExternal: false
  name: Properties
  nameWithType: ClaimTypeElement.Properties
  fullName: System.ServiceModel.Configuration.ClaimTypeElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ClaimTypeElement.#ctor*
  parent: System.ServiceModel.Configuration.ClaimTypeElement
  isExternal: false
  name: ClaimTypeElement
  nameWithType: ClaimTypeElement.ClaimTypeElement
- uid: System.ServiceModel.Configuration.ClaimTypeElement.ClaimType*
  parent: System.ServiceModel.Configuration.ClaimTypeElement
  isExternal: false
  name: ClaimType
  nameWithType: ClaimTypeElement.ClaimType
- uid: System.ServiceModel.Configuration.ClaimTypeElement.IsOptional*
  parent: System.ServiceModel.Configuration.ClaimTypeElement
  isExternal: false
  name: IsOptional
  nameWithType: ClaimTypeElement.IsOptional
- uid: System.ServiceModel.Configuration.ClaimTypeElement.Properties*
  parent: System.ServiceModel.Configuration.ClaimTypeElement
  isExternal: false
  name: Properties
  nameWithType: ClaimTypeElement.Properties
