### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DeploymentProgressState
  id: DeploymentProgressState
  children:
  - System.Deployment.Application.DeploymentProgressState.DownloadingApplicationFiles
  - System.Deployment.Application.DeploymentProgressState.DownloadingApplicationInformation
  - System.Deployment.Application.DeploymentProgressState.DownloadingDeploymentInformation
  langs:
  - csharp
  name: DeploymentProgressState
  nameWithType: DeploymentProgressState
  fullName: System.Deployment.Application.DeploymentProgressState
  type: Enum
  summary: "Especifica o estágio atual de um [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] operação de download."
  remarks: "DeploymentProgressState é passado por meio do <xref:System.Deployment.Application.DownloadProgressChangedEventArgs.State%2A>membro <xref:System.Deployment.Application.DeploymentProgressChangedEventArgs>, que é usado pelo <xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged>, <xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged>, e <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>eventos.</xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged> </xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged> </xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged> </xref:System.Deployment.Application.DeploymentProgressChangedEventArgs> </xref:System.Deployment.Application.DownloadProgressChangedEventArgs.State%2A> Use os membros dessa enumeração para determinar qual parte do [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] implantação já foi baixada no computador local."
  example:
  - "The following code example installs the latest [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] application update asynchronously.  \n  \n [!code-cs[ClickOnceAPI#1](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#1)]\n [!code-cpp[ClickOnceAPI#1](~/add/codesnippet/cpp/t-system.deployment.appl_0_1.cpp)]\n [!code-vb[ClickOnceAPI#1](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#1)]"
  syntax:
    content: public enum DeploymentProgressState
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentProgressState.DownloadingApplicationFiles
  id: DownloadingApplicationFiles
  parent: System.Deployment.Application.DeploymentProgressState
  langs:
  - csharp
  name: DownloadingApplicationFiles
  nameWithType: DeploymentProgressState.DownloadingApplicationFiles
  fullName: System.Deployment.Application.DeploymentProgressState.DownloadingApplicationFiles
  type: Field
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: '[!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)]é baixar os arquivos de dados e DLLs que abrange o aplicativo.'
  syntax:
    content: DownloadingApplicationFiles
    return:
      type: System.Deployment.Application.DeploymentProgressState
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentProgressState.DownloadingApplicationInformation
  id: DownloadingApplicationInformation
  parent: System.Deployment.Application.DeploymentProgressState
  langs:
  - csharp
  name: DownloadingApplicationInformation
  nameWithType: DeploymentProgressState.DownloadingApplicationInformation
  fullName: System.Deployment.Application.DeploymentProgressState.DownloadingApplicationInformation
  type: Field
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: '[!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)]Baixando o manifesto do aplicativo.'
  syntax:
    content: DownloadingApplicationInformation
    return:
      type: System.Deployment.Application.DeploymentProgressState
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentProgressState.DownloadingDeploymentInformation
  id: DownloadingDeploymentInformation
  parent: System.Deployment.Application.DeploymentProgressState
  langs:
  - csharp
  name: DownloadingDeploymentInformation
  nameWithType: DeploymentProgressState.DownloadingDeploymentInformation
  fullName: System.Deployment.Application.DeploymentProgressState.DownloadingDeploymentInformation
  type: Field
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: '[!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)]Baixando o manifesto de implantação.'
  syntax:
    content: DownloadingDeploymentInformation
    return:
      type: System.Deployment.Application.DeploymentProgressState
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Deployment.Application.DeploymentProgressState.DownloadingApplicationFiles
  parent: System.Deployment.Application.DeploymentProgressState
  isExternal: false
  name: DownloadingApplicationFiles
  nameWithType: DeploymentProgressState.DownloadingApplicationFiles
  fullName: System.Deployment.Application.DeploymentProgressState.DownloadingApplicationFiles
- uid: System.Deployment.Application.DeploymentProgressState
  parent: System.Deployment.Application
  isExternal: false
  name: DeploymentProgressState
  nameWithType: DeploymentProgressState
  fullName: System.Deployment.Application.DeploymentProgressState
- uid: System.Deployment.Application.DeploymentProgressState.DownloadingApplicationInformation
  parent: System.Deployment.Application.DeploymentProgressState
  isExternal: false
  name: DownloadingApplicationInformation
  nameWithType: DeploymentProgressState.DownloadingApplicationInformation
  fullName: System.Deployment.Application.DeploymentProgressState.DownloadingApplicationInformation
- uid: System.Deployment.Application.DeploymentProgressState.DownloadingDeploymentInformation
  parent: System.Deployment.Application.DeploymentProgressState
  isExternal: false
  name: DownloadingDeploymentInformation
  nameWithType: DeploymentProgressState.DownloadingDeploymentInformation
  fullName: System.Deployment.Application.DeploymentProgressState.DownloadingDeploymentInformation
