### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.NetMsmqSecurity
  id: NetMsmqSecurity
  children:
  - System.ServiceModel.NetMsmqSecurity.#ctor
  - System.ServiceModel.NetMsmqSecurity.Message
  - System.ServiceModel.NetMsmqSecurity.Mode
  - System.ServiceModel.NetMsmqSecurity.Transport
  langs:
  - csharp
  name: NetMsmqSecurity
  nameWithType: NetMsmqSecurity
  fullName: System.ServiceModel.NetMsmqSecurity
  type: Class
  summary: "A classe NetMsmqSecurity encapsula os recursos de segurança MSMQ disponíveis ao usar o <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> associação."
  remarks: "Objetos desse tipo são criados por meio da criação de uma instância do <xref:System.ServiceModel.NetMsmqBinding>associação.</xref:System.ServiceModel.NetMsmqBinding> Você pode usar esse objeto para fazer referência a todas as várias configurações de segurança relacionadas ao <xref:System.ServiceModel.NetMsmqBinding>associação.</xref:System.ServiceModel.NetMsmqBinding>"
  example:
  - >-
    [!code-cs[UENetMsmqSecurity#1](~/add/codesnippet/csharp/t-system.servicemodel.ne_3_1.cs)]
     [!code-vb[UENetMsmqSecurity#1](~/add/codesnippet/visualbasic/t-system.servicemodel.ne_3_1.vb)]
  syntax:
    content: public sealed class NetMsmqSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.NetMsmqSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.NetMsmqSecurity
  langs:
  - csharp
  name: NetMsmqSecurity()
  nameWithType: NetMsmqSecurity.NetMsmqSecurity()
  fullName: System.ServiceModel.NetMsmqSecurity.NetMsmqSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Inicializa uma nova instância do <xref href=&quot;System.ServiceModel.NetMsmqSecurity&quot;> </xref> classe."
  syntax:
    content: public NetMsmqSecurity ();
    parameters: []
  overload: System.ServiceModel.NetMsmqSecurity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.NetMsmqSecurity.Message
  id: Message
  parent: System.ServiceModel.NetMsmqSecurity
  langs:
  - csharp
  name: Message
  nameWithType: NetMsmqSecurity.Message
  fullName: System.ServiceModel.NetMsmqSecurity.Message
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Obtém ou define o <xref href=&quot;System.ServiceModel.MessageSecurityOverMsmq&quot;> </xref> que está associado a <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> associação."
  remarks: "O <xref:System.ServiceModel.MessageSecurityOverMsmq>encapsula as configurações de segurança de mensagem SOAP.</xref:System.ServiceModel.MessageSecurityOverMsmq>"
  example:
  - >-
    [!code-cs[UENetMsmqSecurity#2](~/add/codesnippet/csharp/p-system.servicemodel.ne_11_1.cs)]
     [!code-vb[UENetMsmqSecurity#2](~/add/codesnippet/visualbasic/p-system.servicemodel.ne_11_1.vb)]
  syntax:
    content: public System.ServiceModel.MessageSecurityOverMsmq Message { get; set; }
    return:
      type: System.ServiceModel.MessageSecurityOverMsmq
      description: "O <xref href=&quot;System.ServiceModel.MessageSecurityOverMsmq&quot;> </xref> que está associado a <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> associação."
  overload: System.ServiceModel.NetMsmqSecurity.Message*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.NetMsmqSecurity.Mode
  id: Mode
  parent: System.ServiceModel.NetMsmqSecurity
  langs:
  - csharp
  name: Mode
  nameWithType: NetMsmqSecurity.Mode
  fullName: System.ServiceModel.NetMsmqSecurity.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Obtém ou define o <xref href=&quot;System.ServiceModel.NetMsmqSecurityMode&quot;> </xref> que está associado a <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> associação."
  remarks: "Essa propriedade determina o tipo de segurança usado pelo NetMsmqBinding associado. A lista a seguir descreve os valores aceitáveis:- **nenhum** -nenhuma segurança é usada.      - **Transporte** -segurança de transporte é usada.      - **Mensagem** -segurança com base na mensagem é usado.      - **Ambos** -ambos segurança de transporte e segurança baseada em mensagem é usada."
  example:
  - >-
    [!code-cs[UENetMsmqSecurity#3](~/add/codesnippet/csharp/p-system.servicemodel.ne_13_1.cs)]
     [!code-vb[UENetMsmqSecurity#3](~/add/codesnippet/visualbasic/p-system.servicemodel.ne_13_1.vb)]
  syntax:
    content: public System.ServiceModel.NetMsmqSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.NetMsmqSecurityMode
      description: "O <xref href=&quot;System.ServiceModel.NetMsmqSecurityMode&quot;> </xref> que está associado a <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> associação."
  overload: System.ServiceModel.NetMsmqSecurity.Mode*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Valor não é um dos <xref href=&quot;System.ServiceModel.NetMsmqSecurityMode&quot;> </xref> valores."
  platform:
  - net462
- uid: System.ServiceModel.NetMsmqSecurity.Transport
  id: Transport
  parent: System.ServiceModel.NetMsmqSecurity
  langs:
  - csharp
  name: Transport
  nameWithType: NetMsmqSecurity.Transport
  fullName: System.ServiceModel.NetMsmqSecurity.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Obtém ou define o <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> que está associado a <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> associação."
  remarks: "Essa propriedade permite o acesso às configurações de segurança de transporte MSMQ."
  example:
  - >-
    [!code-cs[UENetMsmqSecurity#4](~/add/codesnippet/csharp/p-system.servicemodel.ne_19_1.cs)]
     [!code-vb[UENetMsmqSecurity#4](~/add/codesnippet/visualbasic/p-system.servicemodel.ne_19_1.vb)]
  syntax:
    content: public System.ServiceModel.MsmqTransportSecurity Transport { get; set; }
    return:
      type: System.ServiceModel.MsmqTransportSecurity
      description: "O <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> que está associado a <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> associação."
  overload: System.ServiceModel.NetMsmqSecurity.Transport*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.ServiceModel.NetMsmqSecurity.#ctor
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: NetMsmqSecurity()
  nameWithType: NetMsmqSecurity.NetMsmqSecurity()
  fullName: System.ServiceModel.NetMsmqSecurity.NetMsmqSecurity()
- uid: System.ServiceModel.NetMsmqSecurity.Message
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: Message
  nameWithType: NetMsmqSecurity.Message
  fullName: System.ServiceModel.NetMsmqSecurity.Message
- uid: System.ServiceModel.MessageSecurityOverMsmq
  parent: System.ServiceModel
  isExternal: false
  name: MessageSecurityOverMsmq
  nameWithType: MessageSecurityOverMsmq
  fullName: System.ServiceModel.MessageSecurityOverMsmq
- uid: System.ServiceModel.NetMsmqSecurity.Mode
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: Mode
  nameWithType: NetMsmqSecurity.Mode
  fullName: System.ServiceModel.NetMsmqSecurity.Mode
- uid: System.ServiceModel.NetMsmqSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: NetMsmqSecurityMode
  nameWithType: NetMsmqSecurityMode
  fullName: System.ServiceModel.NetMsmqSecurityMode
- uid: System.ServiceModel.NetMsmqSecurity.Transport
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: Transport
  nameWithType: NetMsmqSecurity.Transport
  fullName: System.ServiceModel.NetMsmqSecurity.Transport
- uid: System.ServiceModel.MsmqTransportSecurity
  parent: System.ServiceModel
  isExternal: false
  name: MsmqTransportSecurity
  nameWithType: MsmqTransportSecurity
  fullName: System.ServiceModel.MsmqTransportSecurity
- uid: System.ServiceModel.NetMsmqSecurity.#ctor*
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: NetMsmqSecurity
  nameWithType: NetMsmqSecurity.NetMsmqSecurity
- uid: System.ServiceModel.NetMsmqSecurity.Message*
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: Message
  nameWithType: NetMsmqSecurity.Message
- uid: System.ServiceModel.NetMsmqSecurity.Mode*
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: Mode
  nameWithType: NetMsmqSecurity.Mode
- uid: System.ServiceModel.NetMsmqSecurity.Transport*
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: Transport
  nameWithType: NetMsmqSecurity.Transport
