### YamlMime:ManagedReference
items:
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs
  id: SelectingProviderEventArgs
  children:
  - System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName
  - System.Web.ApplicationServices.SelectingProviderEventArgs.User
  langs:
  - csharp
  name: SelectingProviderEventArgs
  nameWithType: SelectingProviderEventArgs
  fullName: System.Web.ApplicationServices.SelectingProviderEventArgs
  type: Class
  summary: "Fornece dados para o <xref href=&quot;System.Web.ApplicationServices.RoleService.SelectingProvider&quot;> </xref> eventos."
  remarks: "A classe SelectingProviderEventArgs fornece valores para o <xref:System.Web.ApplicationServices.RoleService.SelectingProvider>manipulador de eventos.</xref:System.Web.ApplicationServices.RoleService.SelectingProvider> Você cria um <xref:System.Web.ApplicationServices.RoleService.SelectingProvider>manipulador de eventos para selecionar o provedor de função em tempo de execução.</xref:System.Web.ApplicationServices.RoleService.SelectingProvider>       O <xref:System.Web.ApplicationServices.RoleService>classe gera o <xref:System.Web.ApplicationServices.RoleService.SelectingProvider>eventos quando tanto o <xref:System.Web.ApplicationServices.RoleService.IsCurrentUserInRole%2A>método ou o <xref:System.Web.ApplicationServices.RoleService.GetRolesForCurrentUser%2A>método do <xref:System.Web.ApplicationServices.RoleService>classe é chamada.</xref:System.Web.ApplicationServices.RoleService> </xref:System.Web.ApplicationServices.RoleService.GetRolesForCurrentUser%2A> </xref:System.Web.ApplicationServices.RoleService.IsCurrentUserInRole%2A> </xref:System.Web.ApplicationServices.RoleService.SelectingProvider> </xref:System.Web.ApplicationServices.RoleService>       Você usa o <xref:System.Web.ApplicationServices.SelectingProviderEventArgs.User%2A>propriedade para recuperar informações sobre o usuário que fez logon.</xref:System.Web.ApplicationServices.SelectingProviderEventArgs.User%2A> Para recuperar informações de função através de um provedor de função não padrão, defina o <xref:System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName%2A>propriedade para o nome do provedor de função que você deseja o <xref:System.Web.ApplicationServices.RoleService>objeto a ser usado.</xref:System.Web.ApplicationServices.RoleService> </xref:System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName%2A>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event. The event handler uses the SelectingProviderEventArgs object to check the user name and to set the role provider to use. The event handler is bound to the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event in the `Application_Start` method of the Global.asax file.  \n  \n [!code-vb[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/visualbasic/t-system.web.application_0_1.asax)]\n [!code-cs[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/csharp/t-system.web.application_0_1.asax)]"
  syntax:
    content: 'public class SelectingProviderEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName
  id: ProviderName
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  langs:
  - csharp
  name: ProviderName
  nameWithType: SelectingProviderEventArgs.ProviderName
  fullName: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Obtém ou define o provedor de função a ser usado para recuperar as funções do usuário."
  remarks: "Use a propriedade ProviderName para definir o provedor de função durante a <xref:System.Web.ApplicationServices.RoleService.SelectingProvider>evento.</xref:System.Web.ApplicationServices.RoleService.SelectingProvider>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event. The event handler uses the <xref:System.Web.ApplicationServices.SelectingProviderEventArgs> object to check the user name and to set the role provider to use. The event handler is bound to the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event in the `Application_Start` method of the Global.asax file.  \n  \n [!code-vb[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/visualbasic/p-system.web.application_3_1.asax)]\n [!code-cs[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/csharp/p-system.web.application_3_1.asax)]"
  syntax:
    content: public string ProviderName { get; set; }
    return:
      type: System.String
      description: "O nome do provedor de função que é usado para obter as funções do usuário."
  overload: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.User
  id: User
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  langs:
  - csharp
  name: User
  nameWithType: SelectingProviderEventArgs.User
  fullName: System.Web.ApplicationServices.SelectingProviderEventArgs.User
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Obtém o usuário autenticado."
  remarks: "Use a propriedade do usuário para recuperar informações sobre o usuário durante o <xref:System.Web.ApplicationServices.RoleService.SelectingProvider>evento.</xref:System.Web.ApplicationServices.RoleService.SelectingProvider>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event. The event handler uses the <xref:System.Web.ApplicationServices.SelectingProviderEventArgs> object to check the user name and set the role provider to use. The event handler is bound to the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event in the `Application_Start` method of the Global.asax file.  \n  \n [!code-vb[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/visualbasic/p-system.web.application_9_1.asax)]\n [!code-cs[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/csharp/p-system.web.application_9_1.asax)]"
  syntax:
    content: public System.Security.Principal.IPrincipal User { get; }
    return:
      type: System.Security.Principal.IPrincipal
      description: "Um objeto que contém o usuário autenticado."
  overload: System.Web.ApplicationServices.SelectingProviderEventArgs.User*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  isExternal: false
  name: ProviderName
  nameWithType: SelectingProviderEventArgs.ProviderName
  fullName: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.User
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  isExternal: false
  name: User
  nameWithType: SelectingProviderEventArgs.User
  fullName: System.Web.ApplicationServices.SelectingProviderEventArgs.User
- uid: System.Security.Principal.IPrincipal
  parent: System.Security.Principal
  isExternal: true
  name: IPrincipal
  nameWithType: IPrincipal
  fullName: System.Security.Principal.IPrincipal
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName*
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  isExternal: false
  name: ProviderName
  nameWithType: SelectingProviderEventArgs.ProviderName
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.User*
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  isExternal: false
  name: User
  nameWithType: SelectingProviderEventArgs.User
