### YamlMime:ManagedReference
items:
- uid: System.Configuration.TimeSpanValidator
  id: TimeSpanValidator
  children:
  - System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan)
  - System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean)
  - System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean,System.Int64)
  - System.Configuration.TimeSpanValidator.CanValidate(System.Type)
  - System.Configuration.TimeSpanValidator.Validate(System.Object)
  langs:
  - csharp
  name: TimeSpanValidator
  nameWithType: TimeSpanValidator
  fullName: System.Configuration.TimeSpanValidator
  type: Class
  summary: "Fornece validação de um <xref:System.TimeSpan>objeto.</xref:System.TimeSpan>"
  remarks: "A classe TimeSpanValidator é usada para garantir que um <xref:System.TimeSpan>objeto atende a critérios específicos.</xref:System.TimeSpan> O <xref:System.Configuration.TimeSpanValidator.%23ctor%2A>construtor com dois parâmetros garante que um mínimo e máximo <xref:System.TimeSpan>valor sejam atendidas.</xref:System.TimeSpan> </xref:System.Configuration.TimeSpanValidator.%23ctor%2A> O <xref:System.Configuration.TimeSpanValidator.%23ctor%2A>construtor com três parâmetros verifica o mínimo e máximo <xref:System.TimeSpan>valores, bem como se o intervalo de validação é exclusivo.</xref:System.TimeSpan> </xref:System.Configuration.TimeSpanValidator.%23ctor%2A> O <xref:System.Configuration.TimeSpanValidator.%23ctor%2A>construtor com quatro parâmetros verifica a três parâmetros anteriores e também verifica se o <xref:System.TimeSpan>valor é igual a um número específico de segundos.</xref:System.TimeSpan> </xref:System.Configuration.TimeSpanValidator.%23ctor%2A>       O <xref:System.Configuration.TimeSpanValidator.CanValidate%2A>método determina se o tipo de objeto que está sendo validado corresponde ao tipo esperado.</xref:System.Configuration.TimeSpanValidator.CanValidate%2A> O objeto que está sendo validado é passado como um parâmetro de <xref:System.Configuration.TimeSpanValidator.Validate%2A>método.</xref:System.Configuration.TimeSpanValidator.Validate%2A>"
  example:
  - "The following code example demonstrates how to use the TimeSpanValidator type.  \n  \n [!code-cs[System.Configuration.TimeSpanValidator#1](~/add/codesnippet/csharp/t-system.configuration.t_2_1.cs)]\n [!code-vb[System.Configuration.TimeSpanValidator#1](~/add/codesnippet/visualbasic/t-system.configuration.t_2_1.vb)]"
  syntax:
    content: 'public class TimeSpanValidator : System.Configuration.ConfigurationValidatorBase'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationValidatorBase
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan)
  id: '#ctor(System.TimeSpan,System.TimeSpan)'
  parent: System.Configuration.TimeSpanValidator
  langs:
  - csharp
  name: TimeSpanValidator(TimeSpan,TimeSpan)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Configuration.TimeSpanValidator&quot;> </xref> classe, com base nos parâmetros fornecidos."
  remarks: "Quando o construtor TimeSpanValidator com dois parâmetros é usado, o <xref:System.Configuration.TimeSpanValidator>objeto confirma que um <xref:System.TimeSpan>valor adere a um intervalo específico.</xref:System.TimeSpan> </xref:System.Configuration.TimeSpanValidator>"
  syntax:
    content: public TimeSpanValidator (TimeSpan minValue, TimeSpan maxValue);
    parameters:
    - id: minValue
      type: System.TimeSpan
      description: "Um <xref:System.TimeSpan>o objeto que especifica o tempo mínimo permitido para transmitir a validação.</xref:System.TimeSpan>"
    - id: maxValue
      type: System.TimeSpan
      description: "Um <xref:System.TimeSpan>o objeto que especifica o tempo máximo permitido para transmitir a validação.</xref:System.TimeSpan>"
  overload: System.Configuration.TimeSpanValidator.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean)
  id: '#ctor(System.TimeSpan,System.TimeSpan,System.Boolean)'
  parent: System.Configuration.TimeSpanValidator
  langs:
  - csharp
  name: TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Configuration.TimeSpanValidator&quot;> </xref> classe, com base nos parâmetros fornecidos."
  remarks: "O construtor TimeSpanValidator verifica o mínimo e máximo <xref:System.TimeSpan>valores, bem como se o intervalo de validação é exclusivo.</xref:System.TimeSpan> Quando o `rangeIsExclusive` parâmetro está definido como `true`, o <xref:System.TimeSpan>valor não deve estar entre o `minValue` e `maxValue` valores.</xref:System.TimeSpan>"
  syntax:
    content: public TimeSpanValidator (TimeSpan minValue, TimeSpan maxValue, bool rangeIsExclusive);
    parameters:
    - id: minValue
      type: System.TimeSpan
      description: "Um <xref:System.TimeSpan>o objeto que especifica o tempo mínimo permitido para transmitir a validação.</xref:System.TimeSpan>"
    - id: maxValue
      type: System.TimeSpan
      description: "Um <xref:System.TimeSpan>o objeto que especifica o tempo máximo permitido para transmitir a validação.</xref:System.TimeSpan>"
    - id: rangeIsExclusive
      type: System.Boolean
      description: "Um <xref:System.Boolean>valor que especifica se o intervalo de validação é exclusivo.</xref:System.Boolean>"
  overload: System.Configuration.TimeSpanValidator.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean,System.Int64)
  id: '#ctor(System.TimeSpan,System.TimeSpan,System.Boolean,System.Int64)'
  parent: System.Configuration.TimeSpanValidator
  langs:
  - csharp
  name: TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Configuration.TimeSpanValidator&quot;> </xref> classe, com base nos parâmetros fornecidos."
  remarks: "Quando o `resolutionInSeconds` parâmetro for especificado, o <xref:System.TimeSpan>do objeto que está sendo validada deve ser igual a esse valor para passar pela validação.</xref:System.TimeSpan>"
  example:
  - "The following code example demonstrates how to use the TimeSpanValidator constructor. This code example is part of a larger example provided for the <xref:System.Configuration.TimeSpanValidator> class.  \n  \n [!code-cs[System.Configuration.TimeSpanValidator#2](~/add/codesnippet/csharp/5fd5fd48-b5cd-41a3-9e7a-_1.cs)]\n [!code-vb[System.Configuration.TimeSpanValidator#2](~/add/codesnippet/visualbasic/5fd5fd48-b5cd-41a3-9e7a-_1.vb)]"
  syntax:
    content: public TimeSpanValidator (TimeSpan minValue, TimeSpan maxValue, bool rangeIsExclusive, long resolutionInSeconds);
    parameters:
    - id: minValue
      type: System.TimeSpan
      description: "Um <xref:System.TimeSpan>o objeto que especifica o tempo mínimo permitido para transmitir a validação.</xref:System.TimeSpan>"
    - id: maxValue
      type: System.TimeSpan
      description: "Um <xref:System.TimeSpan>o objeto que especifica o tempo máximo permitido para transmitir a validação.</xref:System.TimeSpan>"
    - id: rangeIsExclusive
      type: System.Boolean
      description: "Um <xref:System.Boolean>valor que especifica se o intervalo de validação é exclusivo.</xref:System.Boolean>"
    - id: resolutionInSeconds
      type: System.Int64
      description: "Um <xref:System.Int64>valor que especifica um número de segundos.</xref:System.Int64>"
  overload: System.Configuration.TimeSpanValidator.#ctor*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "<code>resolutionInSeconds</code> is less than <xref uid=\"langword_csharp_0\" name=\"0\" href=\"\"></xref>.  \n  \n \\- or -  \n  \n <code>minValue</code> is greater than <code>maxValue</code>."
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidator.CanValidate(System.Type)
  id: CanValidate(System.Type)
  parent: System.Configuration.TimeSpanValidator
  langs:
  - csharp
  name: CanValidate(Type)
  nameWithType: TimeSpanValidator.CanValidate(Type)
  fullName: System.Configuration.TimeSpanValidator.CanValidate(Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Determina se o tipo de objeto pode ser validado."
  remarks: ''
  example:
  - "The following code example demonstrates how to use the CanValidate method. This code example is part of a larger example provided for the <xref:System.Configuration.TimeSpanValidator> class.  \n  \n [!code-cs[System.Configuration.TimeSpanValidator#3](~/add/codesnippet/csharp/m-system.configuration.t_1_1.cs)]\n [!code-vb[System.Configuration.TimeSpanValidator#3](~/add/codesnippet/visualbasic/m-system.configuration.t_1_1.vb)]"
  syntax:
    content: public override bool CanValidate (Type type);
    parameters:
    - id: type
      type: System.Type
      description: "O tipo do objeto."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se o <code> type </code> parâmetro corresponde a uma <xref:System.TimeSpan>valor; caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.TimeSpan>"
  overload: System.Configuration.TimeSpanValidator.CanValidate*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidator.Validate(System.Object)
  id: Validate(System.Object)
  parent: System.Configuration.TimeSpanValidator
  langs:
  - csharp
  name: Validate(Object)
  nameWithType: TimeSpanValidator.Validate(Object)
  fullName: System.Configuration.TimeSpanValidator.Validate(Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Determina se o valor de um objeto é válido."
  remarks: "O <xref:System.Configuration.TimeSpanValidator>objeto contém as regras necessárias para validar um <xref:System.TimeSpan>objeto.</xref:System.TimeSpan> </xref:System.Configuration.TimeSpanValidator> As regras são estabelecidas quando uma instância do <xref:System.Configuration.TimeSpanValidator>classe é criada.</xref:System.Configuration.TimeSpanValidator> O objeto para validar é passado como um parâmetro do método Validate."
  example:
  - "The following code example demonstrates how to use the Validate method. This code example is part of a larger example provided for the <xref:System.Configuration.TimeSpanValidator> class.  \n  \n [!code-cs[System.Configuration.TimeSpanValidator#4](~/add/codesnippet/csharp/m-system.configuration.t_2_1.cs)]\n [!code-vb[System.Configuration.TimeSpanValidator#4](~/add/codesnippet/visualbasic/m-system.configuration.t_2_1.vb)]"
  syntax:
    content: public override void Validate (object value);
    parameters:
    - id: value
      type: System.Object
      description: "O valor de um objeto."
  overload: System.Configuration.TimeSpanValidator.Validate*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: System.Configuration.ConfigurationValidatorBase
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan)
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: TimeSpanValidator(TimeSpan,TimeSpan)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan)
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean)
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean,System.Int64)
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Configuration.TimeSpanValidator.CanValidate(System.Type)
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: CanValidate(Type)
  nameWithType: TimeSpanValidator.CanValidate(Type)
  fullName: System.Configuration.TimeSpanValidator.CanValidate(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.TimeSpanValidator.Validate(System.Object)
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: Validate(Object)
  nameWithType: TimeSpanValidator.Validate(Object)
  fullName: System.Configuration.TimeSpanValidator.Validate(Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.TimeSpanValidator.#ctor*
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: TimeSpanValidator
  nameWithType: TimeSpanValidator.TimeSpanValidator
- uid: System.Configuration.TimeSpanValidator.CanValidate*
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: CanValidate
  nameWithType: TimeSpanValidator.CanValidate
- uid: System.Configuration.TimeSpanValidator.Validate*
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: Validate
  nameWithType: TimeSpanValidator.Validate
