### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsManageabilityAttribute
  id: SettingsManageabilityAttribute
  children:
  - System.Configuration.SettingsManageabilityAttribute.#ctor(System.Configuration.SettingsManageability)
  - System.Configuration.SettingsManageabilityAttribute.Manageability
  langs:
  - csharp
  name: SettingsManageabilityAttribute
  nameWithType: SettingsManageabilityAttribute
  fullName: System.Configuration.SettingsManageabilityAttribute
  type: Class
  summary: "Especifica os serviços especiais para propriedades de configurações do aplicativo. Essa classe não pode ser herdada."
  remarks: "O SettingsManageabilityAttribute indica que serviços predefinidos especiais devem ser fornecidos para propriedades de configurações de aplicativos individuais e grupos de propriedades. A maioria desses serviços será fornecida pelo sistema operacional Windows.       Para obter mais informações sobre propriedades de configurações do aplicativo e seu uso, consulte [configurações de aplicativo para o Windows Forms](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Property)]

      public sealed class SettingsManageabilityAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsManageabilityAttribute.#ctor(System.Configuration.SettingsManageability)
  id: '#ctor(System.Configuration.SettingsManageability)'
  parent: System.Configuration.SettingsManageabilityAttribute
  langs:
  - csharp
  name: SettingsManageabilityAttribute(SettingsManageability)
  nameWithType: SettingsManageabilityAttribute.SettingsManageabilityAttribute(SettingsManageability)
  fullName: System.Configuration.SettingsManageabilityAttribute.SettingsManageabilityAttribute(SettingsManageability)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Configuration.SettingsManageabilityAttribute&quot;> </xref> classe."
  remarks: "Vários serviços podem ser solicitados combinando valores definidos pelo <xref:System.Configuration.SettingsManageability>enumeração com a lógica `OR` operador.</xref:System.Configuration.SettingsManageability>"
  syntax:
    content: public SettingsManageabilityAttribute (System.Configuration.SettingsManageability manageability);
    parameters:
    - id: manageability
      type: System.Configuration.SettingsManageability
      description: "Um <xref href=&quot;System.Configuration.SettingsManageability&quot;> </xref> valor que enumera os serviços que está sendo solicitados."
  overload: System.Configuration.SettingsManageabilityAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsManageabilityAttribute.Manageability
  id: Manageability
  parent: System.Configuration.SettingsManageabilityAttribute
  langs:
  - csharp
  name: Manageability
  nameWithType: SettingsManageabilityAttribute.Manageability
  fullName: System.Configuration.SettingsManageabilityAttribute.Manageability
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Obtém o conjunto de serviços especiais que foram solicitadas."
  remarks: "Essa propriedade é definida no <xref:System.Configuration.SettingsManageabilityAttribute.%23ctor%2A>construtor.</xref:System.Configuration.SettingsManageabilityAttribute.%23ctor%2A>"
  syntax:
    content: public System.Configuration.SettingsManageability Manageability { get; }
    return:
      type: System.Configuration.SettingsManageability
      description: "Um valor resultante lógico <xref uid=&quot;langword_csharp_OR&quot; name=&quot;OR&quot; href=&quot;&quot;> </xref> operador para combinar todos o <xref href=&quot;System.Configuration.SettingsManageability&quot;> </xref> valores de enumeração correspondentes para os serviços solicitados."
  overload: System.Configuration.SettingsManageabilityAttribute.Manageability*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsManageabilityAttribute.#ctor(System.Configuration.SettingsManageability)
  parent: System.Configuration.SettingsManageabilityAttribute
  isExternal: false
  name: SettingsManageabilityAttribute(SettingsManageability)
  nameWithType: SettingsManageabilityAttribute.SettingsManageabilityAttribute(SettingsManageability)
  fullName: System.Configuration.SettingsManageabilityAttribute.SettingsManageabilityAttribute(SettingsManageability)
- uid: System.Configuration.SettingsManageability
  parent: System.Configuration
  isExternal: false
  name: SettingsManageability
  nameWithType: SettingsManageability
  fullName: System.Configuration.SettingsManageability
- uid: System.Configuration.SettingsManageabilityAttribute.Manageability
  parent: System.Configuration.SettingsManageabilityAttribute
  isExternal: false
  name: Manageability
  nameWithType: SettingsManageabilityAttribute.Manageability
  fullName: System.Configuration.SettingsManageabilityAttribute.Manageability
- uid: System.Configuration.SettingsManageabilityAttribute.#ctor*
  parent: System.Configuration.SettingsManageabilityAttribute
  isExternal: false
  name: SettingsManageabilityAttribute
  nameWithType: SettingsManageabilityAttribute.SettingsManageabilityAttribute
- uid: System.Configuration.SettingsManageabilityAttribute.Manageability*
  parent: System.Configuration.SettingsManageabilityAttribute
  isExternal: false
  name: Manageability
  nameWithType: SettingsManageabilityAttribute.Manageability
