### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingAttribute
  id: SettingAttribute
  children:
  - System.Configuration.SettingAttribute.#ctor
  langs:
  - csharp
  name: SettingAttribute
  nameWithType: SettingAttribute
  fullName: System.Configuration.SettingAttribute
  type: Class
  summary: "Representa um atributo de configurações personalizadas usado para associar a uma propriedade de configurações de informações de configuração."
  remarks: "A classe SettingAttribute associa informações de configuração de uma propriedade de configurações. O <xref:System.Configuration.ApplicationSettingsBase>classe irá ignorar todas as propriedades não marcadas com isso ou um atributo derivado.</xref:System.Configuration.ApplicationSettingsBase>"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public class SettingAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.SettingAttribute
  langs:
  - csharp
  name: SettingAttribute()
  nameWithType: SettingAttribute.SettingAttribute()
  fullName: System.Configuration.SettingAttribute.SettingAttribute()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Configuration.SettingAttribute&quot;> </xref> classe."
  syntax:
    content: public SettingAttribute ();
    parameters: []
  overload: System.Configuration.SettingAttribute.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingAttribute.#ctor
  parent: System.Configuration.SettingAttribute
  isExternal: false
  name: SettingAttribute()
  nameWithType: SettingAttribute.SettingAttribute()
  fullName: System.Configuration.SettingAttribute.SettingAttribute()
- uid: System.Configuration.SettingAttribute.#ctor*
  parent: System.Configuration.SettingAttribute
  isExternal: false
  name: SettingAttribute
  nameWithType: SettingAttribute.SettingAttribute
