### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.UnicodeDecodingConformance
  id: UnicodeDecodingConformance
  children:
  - System.Net.Configuration.UnicodeDecodingConformance.Auto
  - System.Net.Configuration.UnicodeDecodingConformance.Compat
  - System.Net.Configuration.UnicodeDecodingConformance.Loose
  - System.Net.Configuration.UnicodeDecodingConformance.Strict
  langs:
  - csharp
  name: UnicodeDecodingConformance
  nameWithType: UnicodeDecodingConformance
  fullName: System.Net.Configuration.UnicodeDecodingConformance
  type: Enum
  summary: "Controla como os caracteres Unicode são interpretados pelo <xref:System.Net.WebUtility.HtmlDecode*>métodos.</xref:System.Net.WebUtility.HtmlDecode*>"
  remarks: "Para obter mais informações sobre como caracteres Unicode devem ser codificada em HTML, consulte [usar o caractere de escape na marcação e CSS](http://go.microsoft.com/fwlink/?LinkId=256607)."
  syntax:
    content: public enum UnicodeDecodingConformance
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeDecodingConformance.Auto
  id: Auto
  parent: System.Net.Configuration.UnicodeDecodingConformance
  langs:
  - csharp
  name: Auto
  nameWithType: UnicodeDecodingConformance.Auto
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Auto
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Use o comportamento automático. O comportamento de decodificação depende do Framework de destino do aplicativo atual. Para [!INCLUDE[net_v45](~/add/includes/ajax-current-ext-md.md)] e posterior, a codificação de Unicode decodificação é estrita."
  syntax:
    content: Auto
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeDecodingConformance.Compat
  id: Compat
  parent: System.Net.Configuration.UnicodeDecodingConformance
  langs:
  - csharp
  name: Compat
  nameWithType: UnicodeDecodingConformance.Compat
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Compat
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Use o comportamento compatível. Especifica que os dados de entrada não são verificados para validade antes de ser decodificado. Por exemplo, uma cadeia de entrada &quot;&amp;amp; #xD84C;&quot; seria decodificar como U + D84C, que é um substituto não emparelhado. Além disso, o decodificador não compreender os pontos de código em SMP estão representadas como substitutos codificada em HTML, portanto o inputstring &quot;&amp;#144308;&quot; resultaria na cadeia de caracteres de saída &quot;&amp;#144308;&quot;."
  syntax:
    content: Compat
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeDecodingConformance.Loose
  id: Loose
  parent: System.Net.Configuration.UnicodeDecodingConformance
  langs:
  - csharp
  name: Loose
  nameWithType: UnicodeDecodingConformance.Loose
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Loose
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Use comportamento flexível. Semelhante a compatibilidade em que não há nenhuma verificação de validade, mas o decodificador também compreenda pontos de código. A cadeia de caracteres de entrada &quot;&amp;#144308;&quot; seria decodificar corretamente para o caractere U +&233;B4. Essa opção destina-se para fornecer interoperabilidade máxima, quando o decodificador não sabe qual formato que o provedor está usando para gerar a cadeia de caracteres codificada."
  syntax:
    content: Loose
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeDecodingConformance.Strict
  id: Strict
  parent: System.Net.Configuration.UnicodeDecodingConformance
  langs:
  - csharp
  name: Strict
  nameWithType: UnicodeDecodingConformance.Strict
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Strict
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Use comportamento estrito. Especifica que os dados codificados de entrada são verificados para validade antes de ser decodificado. Por exemplo, uma cadeia de entrada &quot;&amp;#144308;&quot; seria decodificar como U +&233;B4, mas uma cadeia de caracteres de entrada de &quot;&amp;#xD84C;&amp; #xDFB4;&quot;falharia decodificar corretamente. Já decodificar dados na cadeia de caracteres não são verificados para validade. Por exemplo, uma cadeia de caracteres de entrada de &quot;\\ud800&quot; resultará em uma cadeia de caracteres de saída de &quot;\\ud800&quot;, como o substituto decodificado já é ignorado durante a decodificação, apesar de não emparelhado."
  syntax:
    content: Strict
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Net.Configuration.UnicodeDecodingConformance.Auto
  parent: System.Net.Configuration.UnicodeDecodingConformance
  isExternal: false
  name: Auto
  nameWithType: UnicodeDecodingConformance.Auto
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Auto
- uid: System.Net.Configuration.UnicodeDecodingConformance
  parent: System.Net.Configuration
  isExternal: false
  name: UnicodeDecodingConformance
  nameWithType: UnicodeDecodingConformance
  fullName: System.Net.Configuration.UnicodeDecodingConformance
- uid: System.Net.Configuration.UnicodeDecodingConformance.Compat
  parent: System.Net.Configuration.UnicodeDecodingConformance
  isExternal: false
  name: Compat
  nameWithType: UnicodeDecodingConformance.Compat
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Compat
- uid: System.Net.Configuration.UnicodeDecodingConformance.Loose
  parent: System.Net.Configuration.UnicodeDecodingConformance
  isExternal: false
  name: Loose
  nameWithType: UnicodeDecodingConformance.Loose
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Loose
- uid: System.Net.Configuration.UnicodeDecodingConformance.Strict
  parent: System.Net.Configuration.UnicodeDecodingConformance
  isExternal: false
  name: Strict
  nameWithType: UnicodeDecodingConformance.Strict
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Strict
