### YamlMime:ManagedReference
items:
- uid: System.Web.ApplicationServices.ApplicationServicesHostFactory
  id: ApplicationServicesHostFactory
  children:
  - System.Web.ApplicationServices.ApplicationServicesHostFactory.#ctor
  - System.Web.ApplicationServices.ApplicationServicesHostFactory.CreateServiceHost(System.Type,System.Uri[])
  langs:
  - csharp
  name: ApplicationServicesHostFactory
  nameWithType: ApplicationServicesHostFactory
  fullName: System.Web.ApplicationServices.ApplicationServicesHostFactory
  type: Class
  summary: "Fornece uma classe de fábrica que cria instâncias do serviço de autenticação, o serviço de função e o serviço de perfil em ambientes de hospedagem gerenciados."
  remarks: "Essa classe de fábrica fornece uma maneira de criar instâncias de <xref:System.Web.ApplicationServices.AuthenticationService>, <xref:System.Web.ApplicationServices.ProfileService>, e <xref:System.Web.ApplicationServices.RoleService>classes.</xref:System.Web.ApplicationServices.RoleService> </xref:System.Web.ApplicationServices.ProfileService> </xref:System.Web.ApplicationServices.AuthenticationService>       Para usar essa classe de fábrica, crie um arquivo de serviço WCF (. svc) e especifique ApplicationServicesHostFactory no `ServiceHosting` atributo da `@ ServiceHost` diretiva."
  example:
  - "The following example shows how to specify ApplicationServicesHostFactory in the `@ ServiceHost` directive of a .svc file to configure the authentication service.  \n  \n```c#  \n<%@ ServiceHost   \n  Language=\"C#\"   \n  Service=\"System.Web.ApplicationServices.AuthenticationService\"   \n  Factory=\"System.Web.ApplicationServices.ApplicationServicesHostFactory\"   \n%>  \n  \n```  \n  \n```vb  \n<%@ ServiceHost   \n  Language=\"VB\"   \n  Service=\"System.Web.ApplicationServices.AuthenticationService\"   \n  Factory=\"System.Web.ApplicationServices.ApplicationServicesHostFactory\"   \n%>  \n```"
  syntax:
    content: 'public class ApplicationServicesHostFactory : System.ServiceModel.Activation.ServiceHostFactory'
  inheritance:
  - System.ServiceModel.Activation.ServiceHostFactory
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ApplicationServicesHostFactory.#ctor
  id: '#ctor'
  parent: System.Web.ApplicationServices.ApplicationServicesHostFactory
  langs:
  - csharp
  name: ApplicationServicesHostFactory()
  nameWithType: ApplicationServicesHostFactory.ApplicationServicesHostFactory()
  fullName: System.Web.ApplicationServices.ApplicationServicesHostFactory.ApplicationServicesHostFactory()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Web.ApplicationServices.ApplicationServicesHostFactory&quot;> </xref> classe."
  syntax:
    content: public ApplicationServicesHostFactory ();
    parameters: []
  overload: System.Web.ApplicationServices.ApplicationServicesHostFactory.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ApplicationServicesHostFactory.CreateServiceHost(System.Type,System.Uri[])
  id: CreateServiceHost(System.Type,System.Uri[])
  parent: System.Web.ApplicationServices.ApplicationServicesHostFactory
  langs:
  - csharp
  name: CreateServiceHost(Type,Uri[])
  nameWithType: ApplicationServicesHostFactory.CreateServiceHost(Type,Uri[])
  fullName: System.Web.ApplicationServices.ApplicationServicesHostFactory.CreateServiceHost(Type,Uri[])
  type: Method
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Cria uma instância da classe de serviço que tem o endereço base especificado ou endereços."
  remarks: "Geralmente este método é chamado automaticamente pelo [!INCLUDE[vsindigo](~/add/includes/vsindigo-md.md)] como parte do serviço de ativação e você não precisa chamar o método manualmente."
  syntax:
    content: protected override System.ServiceModel.ServiceHost CreateServiceHost (Type serviceType, Uri[] baseAddresses);
    parameters:
    - id: serviceType
      type: System.Type
      description: "O tipo de host de serviço para criar."
    - id: baseAddresses
      type: System.Uri[]
      description: "Uma matriz de endereços de base para o serviço."
    return:
      type: System.ServiceModel.ServiceHost
      description: "Um <xref href=&quot;System.ServiceModel.ServiceHost&quot;> </xref> instância para o tipo de serviço que tem o endereço base especificado ou endereços."
  overload: System.Web.ApplicationServices.ApplicationServicesHostFactory.CreateServiceHost*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Activation.ServiceHostFactory
  isExternal: false
  name: System.ServiceModel.Activation.ServiceHostFactory
- uid: System.Web.ApplicationServices.ApplicationServicesHostFactory.#ctor
  parent: System.Web.ApplicationServices.ApplicationServicesHostFactory
  isExternal: false
  name: ApplicationServicesHostFactory()
  nameWithType: ApplicationServicesHostFactory.ApplicationServicesHostFactory()
  fullName: System.Web.ApplicationServices.ApplicationServicesHostFactory.ApplicationServicesHostFactory()
- uid: System.Web.ApplicationServices.ApplicationServicesHostFactory.CreateServiceHost(System.Type,System.Uri[])
  parent: System.Web.ApplicationServices.ApplicationServicesHostFactory
  isExternal: false
  name: CreateServiceHost(Type,Uri[])
  nameWithType: ApplicationServicesHostFactory.CreateServiceHost(Type,Uri[])
  fullName: System.Web.ApplicationServices.ApplicationServicesHostFactory.CreateServiceHost(Type,Uri[])
- uid: System.ServiceModel.ServiceHost
  parent: System.ServiceModel
  isExternal: false
  name: ServiceHost
  nameWithType: ServiceHost
  fullName: System.ServiceModel.ServiceHost
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Uri[]
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri[]
  spec.csharp:
  - uid: System.Uri
    name: Uri
    nameWithType: Uri
    fullName: Uri[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Web.ApplicationServices.ApplicationServicesHostFactory.#ctor*
  parent: System.Web.ApplicationServices.ApplicationServicesHostFactory
  isExternal: false
  name: ApplicationServicesHostFactory
  nameWithType: ApplicationServicesHostFactory.ApplicationServicesHostFactory
- uid: System.Web.ApplicationServices.ApplicationServicesHostFactory.CreateServiceHost*
  parent: System.Web.ApplicationServices.ApplicationServicesHostFactory
  isExternal: false
  name: CreateServiceHost
  nameWithType: ApplicationServicesHostFactory.CreateServiceHost
