### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  id: NamedPipeConnectionPoolSettings
  children:
  - System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.GroupName
  - System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.IdleTimeout
  - System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
  langs:
  - csharp
  name: NamedPipeConnectionPoolSettings
  nameWithType: NamedPipeConnectionPoolSettings
  fullName: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  type: Class
  summary: "Representa as configurações que controlam o comportamento do pool de conexão de pipe nomeado."
  syntax:
    content: public sealed class NamedPipeConnectionPoolSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.GroupName
  id: GroupName
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  langs:
  - csharp
  name: GroupName
  nameWithType: NamedPipeConnectionPoolSettings.GroupName
  fullName: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.GroupName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Obtém ou define o nome do grupo do grupo de pool de conexão no cliente."
  remarks: "O valor padrão pode ser alterado para isolar as conexões para um determinado cliente em grupos separados."
  syntax:
    content: public string GroupName { get; set; }
    return:
      type: System.String
      description: "O nome do grupo de pool de conexão no cliente. O nome padrão é &quot;padrão&quot;."
  overload: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.GroupName*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "O valor é <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>."
  platform:
  - net462
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.IdleTimeout
  id: IdleTimeout
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  langs:
  - csharp
  name: IdleTimeout
  nameWithType: NamedPipeConnectionPoolSettings.IdleTimeout
  fullName: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.IdleTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Obtém ou define o tempo máximo que a conexão pode ficar ociosa no pool de conexão antes de ser desconectada."
  syntax:
    content: public TimeSpan IdleTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "Retorna um <xref:System.TimeSpan>estrutura que indica o tempo máximo que a conexão pode ficar ociosa no pool de conexão antes de ser desconectada.</xref:System.TimeSpan>"
  overload: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.IdleTimeout*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "O valor é menor que zero."
  platform:
  - net462
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
  id: MaxOutboundConnectionsPerEndpoint
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  langs:
  - csharp
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
  fullName: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Obtém ou define o número máximo de conexões de saída para cada ponto de extremidade que é armazenado em cache no pool de conexão."
  remarks: "Isso limita o número de conexões que são armazenados em cache para cada ponto de extremidade exclusivo. Se esse valor for excedido fazendo mais ativas conexões de cliente, em seguida, o serviço pode parecer não estar respondendo ao cliente e esse valor deve ser ajustado para exceder o número máximo de conexões esperados que são armazenados em cache para cada ponto de extremidade exclusivo."
  syntax:
    content: public int MaxOutboundConnectionsPerEndpoint { get; set; }
    return:
      type: System.Int32
      description: "O número máximo permitidos de conexões de saída para cada ponto de extremidade que é armazenado em cache no pool de conexão. O valor padrão é 10."
  overload: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "O valor é menor que ou igual a zero."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.GroupName
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  isExternal: false
  name: GroupName
  nameWithType: NamedPipeConnectionPoolSettings.GroupName
  fullName: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.GroupName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.IdleTimeout
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  isExternal: false
  name: IdleTimeout
  nameWithType: NamedPipeConnectionPoolSettings.IdleTimeout
  fullName: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.IdleTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  isExternal: false
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
  fullName: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.GroupName*
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  isExternal: false
  name: GroupName
  nameWithType: NamedPipeConnectionPoolSettings.GroupName
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.IdleTimeout*
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  isExternal: false
  name: IdleTimeout
  nameWithType: NamedPipeConnectionPoolSettings.IdleTimeout
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint*
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  isExternal: false
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
