### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationSaveMode
  id: ConfigurationSaveMode
  children:
  - System.Configuration.ConfigurationSaveMode.Full
  - System.Configuration.ConfigurationSaveMode.Minimal
  - System.Configuration.ConfigurationSaveMode.Modified
  langs:
  - csharp
  name: ConfigurationSaveMode
  nameWithType: ConfigurationSaveMode
  fullName: System.Configuration.ConfigurationSaveMode
  type: Enum
  summary: "Determina quais propriedades são gravadas em um arquivo de configuração."
  remarks: "Os valores de enumeração ConfigurationSaveMode identificam quais propriedades são gravadas em um arquivo de configuração ao chamar o <xref:System.Configuration.Configuration.Save%2A>e <xref:System.Configuration.Configuration.SaveAs%2A>métodos.</xref:System.Configuration.Configuration.SaveAs%2A> </xref:System.Configuration.Configuration.Save%2A>"
  syntax:
    content: public enum ConfigurationSaveMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.ConfigurationSaveMode.Full
  id: Full
  parent: System.Configuration.ConfigurationSaveMode
  langs:
  - csharp
  name: Full
  nameWithType: ConfigurationSaveMode.Full
  fullName: System.Configuration.ConfigurationSaveMode.Full
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Faz com que todas as propriedades a serem gravados para o arquivo de configuração. Isso é útil principalmente para criar arquivos de configuração de informações ou mover os valores de configuração de um computador para outro."
  syntax:
    content: Full
    return:
      type: System.Configuration.ConfigurationSaveMode
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationSaveMode.Minimal
  id: Minimal
  parent: System.Configuration.ConfigurationSaveMode
  langs:
  - csharp
  name: Minimal
  nameWithType: ConfigurationSaveMode.Minimal
  fullName: System.Configuration.ConfigurationSaveMode.Minimal
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Faz com que apenas as propriedades que são diferentes dos valores herdados a serem gravados para o arquivo de configuração."
  syntax:
    content: Minimal
    return:
      type: System.Configuration.ConfigurationSaveMode
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationSaveMode.Modified
  id: Modified
  parent: System.Configuration.ConfigurationSaveMode
  langs:
  - csharp
  name: Modified
  nameWithType: ConfigurationSaveMode.Modified
  fullName: System.Configuration.ConfigurationSaveMode.Modified
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Causas modificadas apenas as propriedades a serem gravados no arquivo de configuração, mesmo quando o valor é o mesmo que o valor herdado."
  syntax:
    content: Modified
    return:
      type: System.Configuration.ConfigurationSaveMode
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.ConfigurationSaveMode.Full
  parent: System.Configuration.ConfigurationSaveMode
  isExternal: false
  name: Full
  nameWithType: ConfigurationSaveMode.Full
  fullName: System.Configuration.ConfigurationSaveMode.Full
- uid: System.Configuration.ConfigurationSaveMode
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSaveMode
  nameWithType: ConfigurationSaveMode
  fullName: System.Configuration.ConfigurationSaveMode
- uid: System.Configuration.ConfigurationSaveMode.Minimal
  parent: System.Configuration.ConfigurationSaveMode
  isExternal: false
  name: Minimal
  nameWithType: ConfigurationSaveMode.Minimal
  fullName: System.Configuration.ConfigurationSaveMode.Minimal
- uid: System.Configuration.ConfigurationSaveMode.Modified
  parent: System.Configuration.ConfigurationSaveMode
  isExternal: false
  name: Modified
  nameWithType: ConfigurationSaveMode.Modified
  fullName: System.Configuration.ConfigurationSaveMode.Modified
