### YamlMime:ManagedReference
items:
- uid: System.Management.Instrumentation.ManagementConfigurationType
  id: ManagementConfigurationType
  children:
  - System.Management.Instrumentation.ManagementConfigurationType.Apply
  - System.Management.Instrumentation.ManagementConfigurationType.OnCommit
  langs:
  - csharp
  name: ManagementConfigurationType
  nameWithType: ManagementConfigurationType
  fullName: System.Management.Instrumentation.ManagementConfigurationType
  type: Enum
  summary: "Representa os comportamentos possíveis de confirmação de uma propriedade de leitura/gravação. Ele é usado como o valor de um parâmetro do <xref href=&quot;System.Management.Instrumentation.ManagementConfigurationAttribute&quot;> </xref> atributo.       Observação: as bibliotecas .NET do WMI são consideradas no estado final e não um desenvolvimento adicional, aprimoramentos ou atualizações estarão disponíveis não-relacionados para problemas de segurança que afetam essas bibliotecas. O [MI APIs](https://msdn.microsoft.com/en-us/library/jj152383%28v=vs.80%29.aspx) deve ser usado para todos os novos desenvolvimentos."
  remarks: "Este atributo é usado como um valor de parâmetro para o <xref:System.Management.Instrumentation.ManagementConfigurationAttribute>somente se do atributo de <xref:System.Management.Instrumentation.ManagementCommitAttribute>atributo é usado para identificar um método a ser executado para confirmar os valores.</xref:System.Management.Instrumentation.ManagementCommitAttribute> </xref:System.Management.Instrumentation.ManagementConfigurationAttribute> Caso contrário, os valores de propriedade de leitura/gravação são aplicados automaticamente."
  syntax:
    content: public enum ManagementConfigurationType
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Management.Instrumentation.ManagementConfigurationType.Apply
  id: Apply
  parent: System.Management.Instrumentation.ManagementConfigurationType
  langs:
  - csharp
  name: Apply
  nameWithType: ManagementConfigurationType.Apply
  fullName: System.Management.Instrumentation.ManagementConfigurationType.Apply
  type: Field
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "Definir valores entrarão em vigor somente quando é chamada de confirmação."
  syntax:
    content: Apply
    return:
      type: System.Management.Instrumentation.ManagementConfigurationType
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Management.Instrumentation.ManagementConfigurationType.OnCommit
  id: OnCommit
  parent: System.Management.Instrumentation.ManagementConfigurationType
  langs:
  - csharp
  name: OnCommit
  nameWithType: ManagementConfigurationType.OnCommit
  fullName: System.Management.Instrumentation.ManagementConfigurationType.OnCommit
  type: Field
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "Conjunto de valores são aplicados imediatamente."
  syntax:
    content: OnCommit
    return:
      type: System.Management.Instrumentation.ManagementConfigurationType
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Management.Instrumentation.ManagementConfigurationType.Apply
  parent: System.Management.Instrumentation.ManagementConfigurationType
  isExternal: false
  name: Apply
  nameWithType: ManagementConfigurationType.Apply
  fullName: System.Management.Instrumentation.ManagementConfigurationType.Apply
- uid: System.Management.Instrumentation.ManagementConfigurationType
  parent: System.Management.Instrumentation
  isExternal: false
  name: ManagementConfigurationType
  nameWithType: ManagementConfigurationType
  fullName: System.Management.Instrumentation.ManagementConfigurationType
- uid: System.Management.Instrumentation.ManagementConfigurationType.OnCommit
  parent: System.Management.Instrumentation.ManagementConfigurationType
  isExternal: false
  name: OnCommit
  nameWithType: ManagementConfigurationType.OnCommit
  fullName: System.Management.Instrumentation.ManagementConfigurationType.OnCommit
