### YamlMime:ManagedReference
items:
- uid: System.Configuration.StringValidatorAttribute
  id: StringValidatorAttribute
  children:
  - System.Configuration.StringValidatorAttribute.#ctor
  - System.Configuration.StringValidatorAttribute.InvalidCharacters
  - System.Configuration.StringValidatorAttribute.MaxLength
  - System.Configuration.StringValidatorAttribute.MinLength
  - System.Configuration.StringValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: StringValidatorAttribute
  nameWithType: StringValidatorAttribute
  fullName: System.Configuration.StringValidatorAttribute
  type: Class
  summary: "Declarativamente instrui o .NET Framework para executar a validação da cadeia de caracteres em uma propriedade de configuração. Essa classe não pode ser herdada."
  remarks: "Você pode usar o StringValidatorAttribute para decorar uma propriedade de configuração. Isso é para instruir o .NET Framework para validar a propriedade usando o <xref:System.Configuration.StringValidator>e passá-lo para o valor dos parâmetros de decoração.</xref:System.Configuration.StringValidator>       Você pode aplicar objetos StringValidatorAttribute a somente os tipos de propriedade."
  example:
  - "The following example shows how to decorate the properties of a custom <xref:System.Configuration.ConfigurationSection> object using the StringValidatorAttribute object.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/visualbasic/t-system.configuration.s_1_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/csharp/t-system.configuration.s_1_1.cs)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class StringValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net462
- uid: System.Configuration.StringValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.StringValidatorAttribute
  langs:
  - csharp
  name: StringValidatorAttribute()
  nameWithType: StringValidatorAttribute.StringValidatorAttribute()
  fullName: System.Configuration.StringValidatorAttribute.StringValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Configuration.StringValidatorAttribute&quot;> </xref> classe."
  remarks: "Você pode usar este construtor no modelo atribuído para garantir que o valor atribuído à propriedade de elemento de configuração é de um tipo de cadeia de caracteres."
  example:
  - "The following example shows how to use the StringValidatorAttribute constructor.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#3](~/add/codesnippet/visualbasic/m-system.configuration.s_2_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#3](~/add/codesnippet/csharp/m-system.configuration.s_2_1.cs)]"
  syntax:
    content: public StringValidatorAttribute ();
    parameters: []
  overload: System.Configuration.StringValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.StringValidatorAttribute.InvalidCharacters
  id: InvalidCharacters
  parent: System.Configuration.StringValidatorAttribute
  langs:
  - csharp
  name: InvalidCharacters
  nameWithType: StringValidatorAttribute.InvalidCharacters
  fullName: System.Configuration.StringValidatorAttribute.InvalidCharacters
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Obtém ou define os caracteres inválidos para a propriedade."
  remarks: ''
  example:
  - "The following example shows how to use the InvalidCharacters property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/visualbasic/p-system.configuration.s_15_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/csharp/p-system.configuration.s_15_1.cs)]"
  syntax:
    content: public string InvalidCharacters { get; set; }
    return:
      type: System.String
      description: "A cadeia de caracteres que contém o conjunto de caracteres que não são permitidos para a propriedade."
  overload: System.Configuration.StringValidatorAttribute.InvalidCharacters*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.StringValidatorAttribute.MaxLength
  id: MaxLength
  parent: System.Configuration.StringValidatorAttribute
  langs:
  - csharp
  name: MaxLength
  nameWithType: StringValidatorAttribute.MaxLength
  fullName: System.Configuration.StringValidatorAttribute.MaxLength
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Obtém ou define o comprimento máximo permitido para a cadeia de caracteres a ser atribuído à propriedade."
  remarks: ''
  example:
  - "The following example shows how to use the MaxLength property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/visualbasic/p-system.configuration.s_8_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/csharp/p-system.configuration.s_8_1.cs)]"
  syntax:
    content: public int MaxLength { get; set; }
    return:
      type: System.Int32
      description: "Um inteiro que indica o comprimento máximo permitido para a cadeia de caracteres a ser atribuído à propriedade."
  overload: System.Configuration.StringValidatorAttribute.MaxLength*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "O valor selecionado é menor que <xref:System.Configuration.StringValidatorAttribute.MinLength*>.</xref:System.Configuration.StringValidatorAttribute.MinLength*>"
  platform:
  - net462
- uid: System.Configuration.StringValidatorAttribute.MinLength
  id: MinLength
  parent: System.Configuration.StringValidatorAttribute
  langs:
  - csharp
  name: MinLength
  nameWithType: StringValidatorAttribute.MinLength
  fullName: System.Configuration.StringValidatorAttribute.MinLength
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Obtém ou define o valor mínimo permitido para a cadeia de caracteres a ser atribuído à propriedade."
  remarks: ''
  example:
  - "The following example shows how to use the MinLength property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/visualbasic/p-system.configuration.s_12_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/csharp/p-system.configuration.s_12_1.cs)]"
  syntax:
    content: public int MinLength { get; set; }
    return:
      type: System.Int32
      description: "Um inteiro que indica o comprimento mínimo permitido para a cadeia de caracteres a ser atribuído à propriedade."
  overload: System.Configuration.StringValidatorAttribute.MinLength*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "O valor selecionado é maior do que <xref:System.Configuration.StringValidatorAttribute.MaxLength*>.</xref:System.Configuration.StringValidatorAttribute.MaxLength*>"
  platform:
  - net462
- uid: System.Configuration.StringValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.StringValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: StringValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.StringValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Obtém uma instância do <xref href=&quot;System.Configuration.StringValidator&quot;> </xref> classe."
  remarks: "Use a propriedade ValidatorInstance para executar a validação da cadeia de caracteres chamando seu <xref:System.Configuration.StringValidator.Validate%2A>método.</xref:System.Configuration.StringValidator.Validate%2A>"
  example:
  - "The following example shows how to use the ValidatorInstance property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#14](~/add/codesnippet/visualbasic/p-system.configuration.s_4_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#14](~/add/codesnippet/csharp/p-system.configuration.s_4_1.cs)]"
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "Um atual <xref href=&quot;System.Configuration.StringValidator&quot;> </xref> configurações em um <xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref> instância de validador."
  overload: System.Configuration.StringValidatorAttribute.ValidatorInstance*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.Configuration.StringValidatorAttribute.#ctor
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: StringValidatorAttribute()
  nameWithType: StringValidatorAttribute.StringValidatorAttribute()
  fullName: System.Configuration.StringValidatorAttribute.StringValidatorAttribute()
- uid: System.Configuration.StringValidatorAttribute.InvalidCharacters
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: InvalidCharacters
  nameWithType: StringValidatorAttribute.InvalidCharacters
  fullName: System.Configuration.StringValidatorAttribute.InvalidCharacters
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.StringValidatorAttribute.MaxLength
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: MaxLength
  nameWithType: StringValidatorAttribute.MaxLength
  fullName: System.Configuration.StringValidatorAttribute.MaxLength
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.StringValidatorAttribute.MinLength
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: MinLength
  nameWithType: StringValidatorAttribute.MinLength
  fullName: System.Configuration.StringValidatorAttribute.MinLength
- uid: System.Configuration.StringValidatorAttribute.ValidatorInstance
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: StringValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.StringValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.StringValidatorAttribute.#ctor*
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: StringValidatorAttribute
  nameWithType: StringValidatorAttribute.StringValidatorAttribute
- uid: System.Configuration.StringValidatorAttribute.InvalidCharacters*
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: InvalidCharacters
  nameWithType: StringValidatorAttribute.InvalidCharacters
- uid: System.Configuration.StringValidatorAttribute.MaxLength*
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: MaxLength
  nameWithType: StringValidatorAttribute.MaxLength
- uid: System.Configuration.StringValidatorAttribute.MinLength*
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: MinLength
  nameWithType: StringValidatorAttribute.MinLength
- uid: System.Configuration.StringValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: StringValidatorAttribute.ValidatorInstance
