### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingChangingEventHandler
  id: SettingChangingEventHandler
  langs:
  - csharp
  name: SettingChangingEventHandler
  nameWithType: SettingChangingEventHandler
  fullName: System.Configuration.SettingChangingEventHandler
  type: Delegate
  summary: "Representa o método que manipulará o <xref href=&quot;System.Configuration.ApplicationSettingsBase.SettingChanging&quot;> </xref> eventos."
  remarks: "O <xref:System.Configuration.ApplicationSettingsBase.SettingChanging>evento ocorre antes do valor de uma propriedade de configurações do aplicativo é alterado, normalmente por meio de uma chamada para o <xref:System.Configuration.ApplicationSettingsBase.Item%2A>método.</xref:System.Configuration.ApplicationSettingsBase.Item%2A> </xref:System.Configuration.ApplicationSettingsBase.SettingChanging> <xref:System.Configuration.ApplicationSettingsBase.SettingChanging>pode ser cancelado por meio de <xref:System.Configuration.SettingChangingEventArgs>classe de dados de evento.</xref:System.Configuration.SettingChangingEventArgs></xref:System.Configuration.ApplicationSettingsBase.SettingChanging>"
  syntax:
    content: public delegate void SettingChangingEventHandler(object sender, SettingChangingEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
