### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlReaderSettings
  id: XamlReaderSettings
  children:
  - System.Xaml.XamlReaderSettings.#ctor
  - System.Xaml.XamlReaderSettings.#ctor(System.Xaml.XamlReaderSettings)
  - System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  - System.Xaml.XamlReaderSettings.BaseUri
  - System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  - System.Xaml.XamlReaderSettings.LocalAssembly
  - System.Xaml.XamlReaderSettings.ProvideLineInfo
  - System.Xaml.XamlReaderSettings.ValuesMustBeString
  langs:
  - csharp
  name: XamlReaderSettings
  nameWithType: XamlReaderSettings
  fullName: System.Xaml.XamlReaderSettings
  type: Class
  summary: "Especifica as regras de processamento ou configurações de opção para um <xref href=&quot;System.Xaml.XamlReader&quot;> </xref> implementação."
  remarks: "Por padrão, um objeto XamlReaderSettings inicializado usa valores para propriedades que correspondem ao esperado padrões, como `false` para propriedades Boolianas ou valores nulos para propriedades de tipo de referência. Inicialização padrão resulta nos seguintes valores: - o <xref:System.Xaml.XamlReaderSettings.BaseUri%2A>e <xref:System.Xaml.XamlReaderSettings.LocalAssembly%2A>são propriedades `null`.</xref:System.Xaml.XamlReaderSettings.LocalAssembly%2A> </xref:System.Xaml.XamlReaderSettings.BaseUri%2A>      -A <xref:System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements%2A>é de propriedade `false`.</xref:System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements%2A>      -A <xref:System.Xaml.XamlReaderSettings.ProvideLineInfo%2A>é de propriedade `false` no modelo de objeto; no entanto, ele pode ser definido como `true` em tempo de execução com base em executáveis carregado e suas configurações de depuração, ou pelo contexto de esquema XAML.</xref:System.Xaml.XamlReaderSettings.ProvideLineInfo%2A>"
  syntax:
    content: public class XamlReaderSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: XamlReaderSettings()
  nameWithType: XamlReaderSettings.XamlReaderSettings()
  fullName: System.Xaml.XamlReaderSettings.XamlReaderSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Xaml.XamlReaderSettings&quot;> </xref> classe."
  remarks: "Para obter mais informações sobre a inicialização de uma <xref:System.Xaml.XamlReaderSettings>instância padrão, consulte <xref:System.Xaml.XamlReaderSettings>.</xref:System.Xaml.XamlReaderSettings> </xref:System.Xaml.XamlReaderSettings>"
  syntax:
    content: public XamlReaderSettings ();
    parameters: []
  overload: System.Xaml.XamlReaderSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.#ctor(System.Xaml.XamlReaderSettings)
  id: '#ctor(System.Xaml.XamlReaderSettings)'
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: XamlReaderSettings(XamlReaderSettings)
  nameWithType: XamlReaderSettings.XamlReaderSettings(XamlReaderSettings)
  fullName: System.Xaml.XamlReaderSettings.XamlReaderSettings(XamlReaderSettings)
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Xaml.XamlReaderSettings&quot;> </xref> classe com base nos valores em outra <xref href=&quot;System.Xaml.XamlReaderSettings&quot;> </xref> objeto."
  remarks: "Este construtor oferece suporte a mesclagem de definições para os leitores XAML onde configurações adicionais também podem vir de outros participantes no processo do leitor."
  syntax:
    content: public XamlReaderSettings (System.Xaml.XamlReaderSettings settings);
    parameters:
    - id: settings
      type: System.Xaml.XamlReaderSettings
      description: "Um existente <xref href=&quot;System.Xaml.XamlReaderSettings&quot;> </xref> objeto."
  overload: System.Xaml.XamlReaderSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  id: AllowProtectedMembersOnRoot
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: AllowProtectedMembersOnRoot
  nameWithType: XamlReaderSettings.AllowProtectedMembersOnRoot
  fullName: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Obtém ou define um valor que indica se o objeto raiz pode incluir membros que têm um modelo de acesso protegido código quando ele informar a representação de tipo XAML."
  remarks: "Essa configuração é relevante para algumas implementações de XAML, como WPF onde o objeto raiz é geralmente &quot;fábrica&quot; para gerar uma instância de um tipo de padrão, quando esse tipo de padrão não é sempre uma instância de objeto prático. Por exemplo, uma raiz de `UserControl` tem um significado certo para modelos de aplicativo do WPF e do Silverlight, e `UserControl` pode ter protegido propriedades (`UserControl.Content`) que o analisador precisa acessar. Ferramentas e superfícies de design também precisam acessar essas propriedades. Nesses casos geralmente devem ser relatados para o sistema de tipo XAML como propriedades graváveis, embora eles têm acesso protegido no sistema de tipo de backup."
  syntax:
    content: public bool AllowProtectedMembersOnRoot { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se o objeto raiz pode incluir membros que têm um modelo de acesso protegido código; Caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.BaseUri
  id: BaseUri
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: BaseUri
  nameWithType: XamlReaderSettings.BaseUri
  fullName: System.Xaml.XamlReaderSettings.BaseUri
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Obtém ou define o URI de base que é usado para resolver os caminhos relativos."
  remarks: "Algumas propriedades relacionadas a URI na API de serviços do .NET Framework XAML tratam URIs para namespaces XAML como cadeias de caracteres; No entanto, essa propriedade usa o verdadeiro <xref:System.Uri>tipo.</xref:System.Uri>"
  syntax:
    content: public Uri BaseUri { get; set; }
    return:
      type: System.Uri
      description: "O URI de base a ser usado. O padrão é <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlReaderSettings.BaseUri*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  id: IgnoreUidsOnPropertyElements
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: IgnoreUidsOnPropertyElements
  nameWithType: XamlReaderSettings.IgnoreUidsOnPropertyElements
  fullName: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Obtém ou define um valor que especifica se o leitor XAML deve ignorar os valores para <xref uid=&quot;langword_csharp_x:Uid&quot; name=&quot;x:Uid&quot; href=&quot;&quot;> </xref> atributos que existem em elementos de propriedade."
  remarks: "Durante a localização, a `x:Uid` atributo é usado para identificar elementos na marcação para que as ferramentas de localização podem processar elementos XAML como entidades distintas para localização. Atributos não geralmente aparecem nos elementos de propriedade em XAML. No entanto, `x:Uid` é uma exceção porque alguns usos colocar o texto localizado em um elemento de propriedade como conteúdo, em vez de como um objeto separado que pode receber sua própria `x:Uid`. Definir um valor de IgnoreUidsOnPropertyElements `true` permite que um modo mais rígido. O valor padrão de `false` continua a processar o elemento de propriedade `x:Uid` atributos."
  syntax:
    content: public bool IgnoreUidsOnPropertyElements { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se o leitor deve ignorar os valores para <xref uid=&quot;langword_csharp_x:Uid&quot; name=&quot;x:Uid&quot; href=&quot;&quot;> </xref> atributos em elementos de propriedade. <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>Se o leitor deve processar <xref uid=&quot;langword_csharp_x:Uid&quot; name=&quot;x:Uid&quot; href=&quot;&quot;> </xref> atributos em elementos de propriedade. O padrão é <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.LocalAssembly
  id: LocalAssembly
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: LocalAssembly
  nameWithType: XamlReaderSettings.LocalAssembly
  fullName: System.Xaml.XamlReaderSettings.LocalAssembly
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Obtém ou define o objeto que representa o conjunto atual de local para processamento. Essas informações de assembly são usadas para chamadas a APIs auxiliares como &lt;xref:System.Xaml.XamlType.GetAllMembers%2A?displayProperty=fullName&gt;."
  syntax:
    content: public System.Reflection.Assembly LocalAssembly { get; set; }
    return:
      type: System.Reflection.Assembly
      description: "A reflexão de CLR <xref:System.Reflection.Assembly>objeto.</xref:System.Reflection.Assembly>"
  overload: System.Xaml.XamlReaderSettings.LocalAssembly*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.ProvideLineInfo
  id: ProvideLineInfo
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: ProvideLineInfo
  nameWithType: XamlReaderSettings.ProvideLineInfo
  fullName: System.Xaml.XamlReaderSettings.ProvideLineInfo
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Obtém ou define um valor que especifica se o leitor pode fornecer o número de linha e posição."
  remarks: "É ProvideLineInfo `false` no modelo de objeto; no entanto, ele pode ser definido como `true` em tempo de execução com base em executáveis carregado e suas configurações de depuração."
  syntax:
    content: public bool ProvideLineInfo { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se o leitor pode fornecer informações de número e a posição da linha; Caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlReaderSettings.ProvideLineInfo*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.ValuesMustBeString
  id: ValuesMustBeString
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: ValuesMustBeString
  nameWithType: XamlReaderSettings.ValuesMustBeString
  fullName: System.Xaml.XamlReaderSettings.ValuesMustBeString
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Obtém ou define um valor que especifica se o leitor impõe que todos os <xref uid=&quot;langword_csharp_Value&quot; name=&quot;Value&quot; href=&quot;&quot;> </xref> nós são processados como uma <xref uid=&quot;langword_csharp_String&quot; name=&quot;String&quot; href=&quot;&quot;> </xref> tipo."
  remarks: "Além <xref:System.String>, uma possível `Value` conteúdo em algumas implementações de XAML é <xref:System.Windows.Markup.XData>.</xref:System.Windows.Markup.XData> </xref:System.String>"
  syntax:
    content: public bool ValuesMustBeString { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se o leitor impõe que só <xref uid=&quot;langword_csharp_String&quot; name=&quot;String&quot; href=&quot;&quot;> </xref> está contida no <xref uid=&quot;langword_csharp_Value&quot; name=&quot;Value&quot; href=&quot;&quot;> </xref> nós; caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. O padrão é <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlReaderSettings.ValuesMustBeString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Xaml.XamlReaderSettings.#ctor
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: XamlReaderSettings()
  nameWithType: XamlReaderSettings.XamlReaderSettings()
  fullName: System.Xaml.XamlReaderSettings.XamlReaderSettings()
- uid: System.Xaml.XamlReaderSettings.#ctor(System.Xaml.XamlReaderSettings)
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: XamlReaderSettings(XamlReaderSettings)
  nameWithType: XamlReaderSettings.XamlReaderSettings(XamlReaderSettings)
  fullName: System.Xaml.XamlReaderSettings.XamlReaderSettings(XamlReaderSettings)
- uid: System.Xaml.XamlReaderSettings
  parent: System.Xaml
  isExternal: false
  name: XamlReaderSettings
  nameWithType: XamlReaderSettings
  fullName: System.Xaml.XamlReaderSettings
- uid: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: AllowProtectedMembersOnRoot
  nameWithType: XamlReaderSettings.AllowProtectedMembersOnRoot
  fullName: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xaml.XamlReaderSettings.BaseUri
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: BaseUri
  nameWithType: XamlReaderSettings.BaseUri
  fullName: System.Xaml.XamlReaderSettings.BaseUri
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: IgnoreUidsOnPropertyElements
  nameWithType: XamlReaderSettings.IgnoreUidsOnPropertyElements
  fullName: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
- uid: System.Xaml.XamlReaderSettings.LocalAssembly
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: LocalAssembly
  nameWithType: XamlReaderSettings.LocalAssembly
  fullName: System.Xaml.XamlReaderSettings.LocalAssembly
- uid: System.Reflection.Assembly
  parent: System.Reflection
  isExternal: true
  name: Assembly
  nameWithType: Assembly
  fullName: System.Reflection.Assembly
- uid: System.Xaml.XamlReaderSettings.ProvideLineInfo
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: ProvideLineInfo
  nameWithType: XamlReaderSettings.ProvideLineInfo
  fullName: System.Xaml.XamlReaderSettings.ProvideLineInfo
- uid: System.Xaml.XamlReaderSettings.ValuesMustBeString
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: ValuesMustBeString
  nameWithType: XamlReaderSettings.ValuesMustBeString
  fullName: System.Xaml.XamlReaderSettings.ValuesMustBeString
- uid: System.Xaml.XamlReaderSettings.#ctor*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: XamlReaderSettings
  nameWithType: XamlReaderSettings.XamlReaderSettings
- uid: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: AllowProtectedMembersOnRoot
  nameWithType: XamlReaderSettings.AllowProtectedMembersOnRoot
- uid: System.Xaml.XamlReaderSettings.BaseUri*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: BaseUri
  nameWithType: XamlReaderSettings.BaseUri
- uid: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: IgnoreUidsOnPropertyElements
  nameWithType: XamlReaderSettings.IgnoreUidsOnPropertyElements
- uid: System.Xaml.XamlReaderSettings.LocalAssembly*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: LocalAssembly
  nameWithType: XamlReaderSettings.LocalAssembly
- uid: System.Xaml.XamlReaderSettings.ProvideLineInfo*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: ProvideLineInfo
  nameWithType: XamlReaderSettings.ProvideLineInfo
- uid: System.Xaml.XamlReaderSettings.ValuesMustBeString*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: ValuesMustBeString
  nameWithType: XamlReaderSettings.ValuesMustBeString
