### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  id: TcpConnectionPoolSettingsElement
  children:
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.#ctor
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties
  langs:
  - csharp
  name: TcpConnectionPoolSettingsElement
  nameWithType: TcpConnectionPoolSettingsElement
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  type: Class
  summary: "Representa um elemento de configuração que especifica as configurações do pool de conexão adicionais para um transporte TCP. Essa classe não pode ser herdada."
  syntax:
    content: 'public sealed class TcpConnectionPoolSettingsElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: TcpConnectionPoolSettingsElement()
  nameWithType: TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement()
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement&quot;> </xref> classe."
  syntax:
    content: public TcpConnectionPoolSettingsElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName
  id: GroupName
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: GroupName
  nameWithType: TcpConnectionPoolSettingsElement.GroupName
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém ou define uma cadeia de caracteres que define o nome do pool de conexão usado para canais de saída."
  remarks: "No modo de fluxo, conexões não são compartilhados, o que significa que o pool de conexão está desabilitado. O padrão é uma cadeia de caracteres &quot;padrão&quot;. Você pode modificar esse valor para isolar as conexões para um determinado cliente em grupos separados."
  syntax:
    content: public string GroupName { get; set; }
    return:
      type: System.String
      description: "O nome do pool de conexão usado para canais de saída."
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
  id: IdleTimeout
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: IdleTimeout
  nameWithType: TcpConnectionPoolSettingsElement.IdleTimeout
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém ou define o tempo máximo que a conexão pode ficar ociosa antes de ser desconectada."
  syntax:
    content: public TimeSpan IdleTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "Um positivo <xref:System.TimeSpan>que especifica o tempo máximo que a conexão pode ficar ociosa antes de ser desconectada.</xref:System.TimeSpan> O padrão é 00:02:00."
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout
  id: LeaseTimeout
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: LeaseTimeout
  nameWithType: TcpConnectionPoolSettingsElement.LeaseTimeout
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém ou define o período de tempo após o qual uma conexão ativa é fechada."
  remarks: "Uma conexão é fechada depois que ele é retornado para o cache de conexão e não durante a transmissão de ativo. O cache de conexão usado pelo transporte TCP cria novas conexões conforme necessário para cada ponto de extremidade, até o limite de cache é definido por <xref:System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint%2A>.</xref:System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint%2A>"
  syntax:
    content: public TimeSpan LeaseTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "Um <xref:System.TimeSpan>estrutura que indica a duração após a qual a conexão TCP está fechado.</xref:System.TimeSpan>"
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  id: MaxOutboundConnectionsPerEndpoint
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém ou define o número máximo de conexões para um ponto de extremidade remoto iniciado pelo serviço."
  remarks: "Conexões ultrapassem o limite são enfileiradas até que um espaço abaixo do limite se torne disponível. Essa propriedade limita a duração em que conexões permanecem na fila antes de uma exceção será lançada.       Essa propriedade limita o número de conexões ativas simultâneas do cliente para um ponto de extremidade de serviço específico. Se esse valor for excedido fazendo mais ativas conexões de cliente, o serviço pode parecer não estar respondendo ao cliente. Nesse caso, esse valor deverá ser ajustado para exceder o número máximo de conexões de cliente simultâneas esperado para um ponto de extremidade específico.       Essa configuração também pode ser definida no lado do serviço, nesse caso o valor será usado para definir o <xref:System.ServiceModel.Channels.MaxPooledConnections%2A>em <xref:System.ServiceModel.Channels.TcpChannelListener>.</xref:System.ServiceModel.Channels.TcpChannelListener> </xref:System.ServiceModel.Channels.MaxPooledConnections%2A>"
  syntax:
    content: public int MaxOutboundConnectionsPerEndpoint { get; set; }
    return:
      type: System.Int32
      description: "O número máximo de conexões para um ponto de extremidade remoto iniciado pelo serviço. O padrão é 10."
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: Properties
  nameWithType: TcpConnectionPoolSettingsElement.Properties
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A ser adicionado."
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.#ctor
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: TcpConnectionPoolSettingsElement()
  nameWithType: TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement()
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement()
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: GroupName
  nameWithType: TcpConnectionPoolSettingsElement.GroupName
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: IdleTimeout
  nameWithType: TcpConnectionPoolSettingsElement.IdleTimeout
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: LeaseTimeout
  nameWithType: TcpConnectionPoolSettingsElement.LeaseTimeout
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: Properties
  nameWithType: TcpConnectionPoolSettingsElement.Properties
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.#ctor*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: TcpConnectionPoolSettingsElement
  nameWithType: TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: GroupName
  nameWithType: TcpConnectionPoolSettingsElement.GroupName
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: IdleTimeout
  nameWithType: TcpConnectionPoolSettingsElement.IdleTimeout
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: LeaseTimeout
  nameWithType: TcpConnectionPoolSettingsElement.LeaseTimeout
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: Properties
  nameWithType: TcpConnectionPoolSettingsElement.Properties
