### YamlMime:ManagedReference
items:
- uid: System.Configuration.NoSettingsVersionUpgradeAttribute
  id: NoSettingsVersionUpgradeAttribute
  children:
  - System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor
  langs:
  - csharp
  name: NoSettingsVersionUpgradeAttribute
  nameWithType: NoSettingsVersionUpgradeAttribute
  fullName: System.Configuration.NoSettingsVersionUpgradeAttribute
  type: Class
  summary: "Especifica que um provedor de configurações deve desativar qualquer lógica que é invocada quando uma atualização de aplicativo é detectada. Essa classe não pode ser herdada."
  remarks: "Para criar um provedor de configurações do aplicativo completo que dá suporte à versão do aplicativo, o provedor deve implementar a <xref:System.Configuration.IApplicationSettingsProvider>interface.</xref:System.Configuration.IApplicationSettingsProvider> Um dos membros nesta interface, o <xref:System.Configuration.IApplicationSettingsProvider.Upgrade%2A>método é chamado para notificar o provedor de que uma nova versão do aplicativo foi instalada.</xref:System.Configuration.IApplicationSettingsProvider.Upgrade%2A> Em resposta, o provedor deve executar uma ação adequada, normalmente migrando após as configurações do aplicativo.       O NoSettingsVersionUpgradeAttribute informa ao provedor para suprimir a lógica de atualização associada com a classe de configurações atuais. Portanto, o valor da versão anterior deste grupo de propriedade não deve ser migrado para a nova instalação.      > [!NOTE] > Esse atributo pode ser aplicado somente a propriedades de configurações de aplicativos individuais."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class NoSettingsVersionUpgradeAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.NoSettingsVersionUpgradeAttribute
  langs:
  - csharp
  name: NoSettingsVersionUpgradeAttribute()
  nameWithType: NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute()
  fullName: System.Configuration.NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Configuration.NoSettingsVersionUpgradeAttribute&quot;> </xref> classe."
  remarks: "Este é o construtor padrão fornecidos pelo compilador para a <xref:System.Configuration.NoSettingsVersionUpgradeAttribute>classe.</xref:System.Configuration.NoSettingsVersionUpgradeAttribute>"
  syntax:
    content: public NoSettingsVersionUpgradeAttribute ();
    parameters: []
  overload: System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor
  parent: System.Configuration.NoSettingsVersionUpgradeAttribute
  isExternal: false
  name: NoSettingsVersionUpgradeAttribute()
  nameWithType: NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute()
  fullName: System.Configuration.NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute()
- uid: System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor*
  parent: System.Configuration.NoSettingsVersionUpgradeAttribute
  isExternal: false
  name: NoSettingsVersionUpgradeAttribute
  nameWithType: NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute
