### YamlMime:ManagedReference
items:
- uid: System.Web.UI.Design.AppSettingsExpressionEditor
  id: AppSettingsExpressionEditor
  children:
  - System.Web.UI.Design.AppSettingsExpressionEditor.#ctor
  - System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(System.String,System.Object,System.Type,System.IServiceProvider)
  - System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(System.String,System.IServiceProvider)
  langs:
  - csharp
  name: AppSettingsExpressionEditor
  nameWithType: AppSettingsExpressionEditor
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor
  type: Class
  summary: "Fornece propriedades e métodos para avaliar e editar uma expressão de configuração de aplicativo em um arquivo de configuração em tempo de design."
  remarks: "A classe AppSettingsExpressionEditor é derivada de <xref:System.Web.UI.Design.ExpressionEditor>classe e fornece uma implementação para avaliar e associar uma referência de configuração do aplicativo com uma propriedade de controle em tempo de design.</xref:System.Web.UI.Design.ExpressionEditor> Por exemplo, você pode associar o valor de uma propriedade de controle para a expressão de configuração do aplicativo `AppSettings:mySettingKeyName`, que indica que o valor de propriedade do controle é definido usando o `mySettingKeyName` valor o `appSettings` seção do arquivo de configuração da Web.       Hospedar um designer visual, como [!INCLUDE[vsprvslong](~/add/includes/ajax-current-ext-md.md)], usa a classe AppSettingsExpressionEditor para selecionar uma configuração de aplicativo do `appSettings` seção de configuração e, em seguida, avalia a expressão selecionada para a renderização de tempo de design.       Quando você navega para o <xref:System.Web.UI.Design.HtmlControlDesigner.Expressions%2A>propriedade para um controle na grade de propriedades de tempo de design, o designer visual exibe uma caixa de diálogo para expressões de conjunto que fornecem o valor de tempo de execução para uma propriedade de controle.</xref:System.Web.UI.Design.HtmlControlDesigner.Expressions%2A> Você pode selecionar o tipo de expressão com base em uma lista de prefixos de expressão. Quando você seleciona o **AppSettings** usa o prefixo de expressão da lista, o host de designer visual associado <xref:System.Web.UI.Design.ExpressionEditorSheet>objeto para fornecer a funcionalidade de edição em tempo de design `appSettings` expressões e usa métodos AppSettingsExpressionEditor para avaliar e converter a cadeia de caracteres de expressão com base na sintaxe para uma expressão de configuração do aplicativo.</xref:System.Web.UI.Design.ExpressionEditorSheet> O host de designer visual usa o resultado da expressão avaliada para atribuir valores de propriedade são renderizados na superfície de design de controle.       O <xref:System.Web.UI.Design.ExpressionEditor.ExpressionPrefix%2A>propriedade para um objeto AppSettingsExpressionEditor retorna a cadeia de caracteres `AppSettings`.</xref:System.Web.UI.Design.ExpressionEditor.ExpressionPrefix%2A> O <xref:System.Web.Compilation.AppSettingsExpressionBuilder>classe está associada com o prefixo de expressão `AppSettings` e a implementação de AppSettingsExpressionEditor.</xref:System.Web.Compilation.AppSettingsExpressionBuilder>       O <xref:System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression%2A>método avalia uma cadeia de caracteres de expressão de configuração do aplicativo de entrada.</xref:System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression%2A> O <xref:System.Web.UI.Design.ExpressionEditor.GetExpressionEditorSheet%2A>método retorna o <xref:System.Web.UI.Design.ExpressionEditorSheet>implementação que é usada para inserir e editar expressões de configuração do aplicativo.</xref:System.Web.UI.Design.ExpressionEditorSheet> </xref:System.Web.UI.Design.ExpressionEditor.GetExpressionEditorSheet%2A>"
  example:
  - "The following code example demonstrates how to bind the <xref:System.Web.UI.WebControls.HyperLink.NavigateUrl%2A> property of a <xref:System.Web.UI.WebControls.HyperLink> control to an application setting expression using the AppSettingsExpressionEditor object.  \n  \n1.  In a Web Forms project, add `MyHyperLinkSetting` to the `<appSettings>` section of the web.config file.  \n  \n     [!code-xml[ControlsUsingExpressions#5](~/add/codesnippet/xml/t-system.web.ui.design.a_1.xml)]  \n  \n2.  On a Web Forms page, add a <xref:System.Web.UI.WebControls.HyperLink> control.  \n  \n3.  For the `Hyperlink` control, in Properties, click **Expressions**, and then click the ellipsis button (**...**).  \n  \n     The `<Hyperlinkname>`**Expression** dialog box appears.  \n  \n4.  Under **Bindable properties**, click **NavigateUrl**, in the **Expression type** list, click **AppSettings**, and then under **Expression properties**, in the **AppSetting** box, type **MyHyperLinkSetting**.  \n  \n The visual designer uses the AppSettingsExpressionEditor to assign the expression for the `NavigateUrl` property.  \n  \n The following aspx source shows an example of a property value set using an application setting expression.  \n  \n [!code-vb[ControlsUsingExpressions#2](~/add/codesnippet/visualbasic/t-system.web.ui.design.a_2.aspx)]\n [!code-cs[ControlsUsingExpressions#2](~/add/codesnippet/csharp/t-system.web.ui.design.a_2.aspx)]\n [!code-xml[ControlsUsingExpressions#2](~/add/codesnippet/xml/t-system.web.ui.design.a_2.xml)]"
  syntax:
    content: 'public class AppSettingsExpressionEditor : System.Web.UI.Design.ExpressionEditor'
  inheritance:
  - System.Object
  - System.Web.UI.Design.ExpressionEditor
  implements: []
  inheritedMembers:
  - System.Web.UI.Design.ExpressionEditor.ExpressionPrefix
  - System.Web.UI.Design.ExpressionEditor.GetExpressionEditor(System.String,System.IServiceProvider)
  - System.Web.UI.Design.ExpressionEditor.GetExpressionEditor(System.Type,System.IServiceProvider)
  platform:
  - net462
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.#ctor
  id: '#ctor'
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  langs:
  - csharp
  name: AppSettingsExpressionEditor()
  nameWithType: AppSettingsExpressionEditor.AppSettingsExpressionEditor()
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.AppSettingsExpressionEditor()
  type: Constructor
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Web.UI.Design.AppSettingsExpressionEditor&quot;> </xref> classe."
  remarks: "Uma instância do <xref:System.Web.UI.Design.AppSettingsExpressionEditor>classe é configurada pela classe base junto com o <xref:System.Web.UI.Design.ExpressionEditor.ExpressionPrefix%2A>propriedade definida como `AppSettings`.</xref:System.Web.UI.Design.ExpressionEditor.ExpressionPrefix%2A> </xref:System.Web.UI.Design.AppSettingsExpressionEditor>"
  syntax:
    content: public AppSettingsExpressionEditor ();
    parameters: []
  overload: System.Web.UI.Design.AppSettingsExpressionEditor.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(System.String,System.Object,System.Type,System.IServiceProvider)
  id: EvaluateExpression(System.String,System.Object,System.Type,System.IServiceProvider)
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  langs:
  - csharp
  name: EvaluateExpression(String,Object,Type,IServiceProvider)
  nameWithType: AppSettingsExpressionEditor.EvaluateExpression(String,Object,Type,IServiceProvider)
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(String,Object,Type,IServiceProvider)
  type: Method
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  summary: "Avalia uma cadeia de caracteres de expressão de configuração do aplicativo e fornece o valor de tempo de design para uma propriedade de controle."
  remarks: "O método EvaluateExpression procura a configuração de aplicativo que é especificada pelo `expression`e, em seguida, retorna o valor da configuração do aplicativo.       O designer visual usa o método de EvaluateExpression para avaliar uma expressão de configuração de aplicativo e fornecer o valor de tempo de design para uma propriedade do controle associado. O visual designer chama o método EvaluateExpression com a cadeia de caracteres de expressão e usa o resultado da expressão avaliada para atribuir valores de propriedade são renderizados na superfície de design de controle.       Em tempo de execução, o analisador de página usa o <xref:System.Web.Compilation.AppSettingsExpressionBuilder.EvaluateExpression%2A>e <xref:System.Web.Compilation.AppSettingsExpressionBuilder.GetCodeExpression%2A>métodos do <xref:System.Web.Compilation.AppSettingsExpressionBuilder>implementação para avaliar uma expressão e forneça o valor de tempo de execução para uma propriedade do controle associado.</xref:System.Web.Compilation.AppSettingsExpressionBuilder> </xref:System.Web.Compilation.AppSettingsExpressionBuilder.GetCodeExpression%2A> </xref:System.Web.Compilation.AppSettingsExpressionBuilder.EvaluateExpression%2A>"
  syntax:
    content: public override object EvaluateExpression (string expression, object parseTimeData, Type propertyType, IServiceProvider serviceProvider);
    parameters:
    - id: expression
      type: System.String
      description: "Uma cadeia de expressão de configuração de aplicativo para avaliar. `expression`não inclui o <xref uid=&quot;langword_csharp_AppSettings&quot; name=&quot;AppSettings&quot; href=&quot;&quot;> </xref> prefixo de expressão."
    - id: parseTimeData
      type: System.Object
      description: "Um objeto que contém informações de análise adicionais para avaliar `expression`."
    - id: propertyType
      type: System.Type
      description: "O tipo de propriedade do controle."
    - id: serviceProvider
      type: System.IServiceProvider
      description: "Uma implementação de provedor de serviço fornecida pelo host do designer, usado para obter os serviços de tempo de design adicionais."
    return:
      type: System.Object
      description: "O objeto referenciado por <code> expression </code>, se a avaliação da expressão for bem-sucedida; caso contrário, <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(System.String,System.IServiceProvider)
  id: GetExpressionEditorSheet(System.String,System.IServiceProvider)
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  langs:
  - csharp
  name: GetExpressionEditorSheet(String,IServiceProvider)
  nameWithType: AppSettingsExpressionEditor.GetExpressionEditorSheet(String,IServiceProvider)
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(String,IServiceProvider)
  type: Method
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  summary: "Retorna uma folha de editor de expressão para uma expressão de configuração do aplicativo."
  remarks: "O método GetExpressionEditorSheet retorna um editor simples implementação de folha, que usa uma única cadeia de caracteres de entrada para formar a expressão."
  syntax:
    content: public override System.Web.UI.Design.ExpressionEditorSheet GetExpressionEditorSheet (string expression, IServiceProvider serviceProvider);
    parameters:
    - id: expression
      type: System.String
      description: "A cadeia de caracteres de expressão definida para uma propriedade de controle, usada para inicializar a folha de editor de expressão. `expression`não inclui o <xref uid=&quot;langword_csharp_AppSettings&quot; name=&quot;AppSettings&quot; href=&quot;&quot;> </xref> prefixo de expressão."
    - id: serviceProvider
      type: System.IServiceProvider
      description: "Uma implementação de provedor de serviço fornecida pelo host do designer, usado para obter os serviços de tempo de design adicionais."
    return:
      type: System.Web.UI.Design.ExpressionEditorSheet
      description: "Um <xref href=&quot;System.Web.UI.Design.ExpressionEditorSheet&quot;> </xref> implementação que define as propriedades de expressão de configuração do aplicativo."
  overload: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.UI.Design.ExpressionEditor
  isExternal: false
  name: System.Web.UI.Design.ExpressionEditor
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.#ctor
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: AppSettingsExpressionEditor()
  nameWithType: AppSettingsExpressionEditor.AppSettingsExpressionEditor()
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.AppSettingsExpressionEditor()
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(System.String,System.Object,System.Type,System.IServiceProvider)
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: EvaluateExpression(String,Object,Type,IServiceProvider)
  nameWithType: AppSettingsExpressionEditor.EvaluateExpression(String,Object,Type,IServiceProvider)
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(String,Object,Type,IServiceProvider)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.IServiceProvider
  parent: System
  isExternal: true
  name: IServiceProvider
  nameWithType: IServiceProvider
  fullName: System.IServiceProvider
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(System.String,System.IServiceProvider)
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: GetExpressionEditorSheet(String,IServiceProvider)
  nameWithType: AppSettingsExpressionEditor.GetExpressionEditorSheet(String,IServiceProvider)
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(String,IServiceProvider)
- uid: System.Web.UI.Design.ExpressionEditorSheet
  parent: System.Web.UI.Design
  isExternal: false
  name: ExpressionEditorSheet
  nameWithType: ExpressionEditorSheet
  fullName: System.Web.UI.Design.ExpressionEditorSheet
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.#ctor*
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: AppSettingsExpressionEditor
  nameWithType: AppSettingsExpressionEditor.AppSettingsExpressionEditor
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression*
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: EvaluateExpression
  nameWithType: AppSettingsExpressionEditor.EvaluateExpression
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet*
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: GetExpressionEditorSheet
  nameWithType: AppSettingsExpressionEditor.GetExpressionEditorSheet
