### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlXmlWriterSettings
  id: XamlXmlWriterSettings
  children:
  - System.Xaml.XamlXmlWriterSettings.#ctor
  - System.Xaml.XamlXmlWriterSettings.AssumeValidInput
  - System.Xaml.XamlXmlWriterSettings.CloseOutput
  - System.Xaml.XamlXmlWriterSettings.Copy
  langs:
  - csharp
  name: XamlXmlWriterSettings
  nameWithType: XamlXmlWriterSettings
  fullName: System.Xaml.XamlXmlWriterSettings
  type: Class
  summary: "Fornece configurações de inicialização para o <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> implementação do gravador XAML."
  remarks: "Os padrões para todos os valores de XamlXmlWriterSettings são `false`."
  syntax:
    content: 'public class XamlXmlWriterSettings : System.Xaml.XamlWriterSettings'
  inheritance:
  - System.Object
  - System.Xaml.XamlWriterSettings
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlWriterSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlXmlWriterSettings
  langs:
  - csharp
  name: XamlXmlWriterSettings()
  nameWithType: XamlXmlWriterSettings.XamlXmlWriterSettings()
  fullName: System.Xaml.XamlXmlWriterSettings.XamlXmlWriterSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Xaml.XamlXmlWriterSettings&quot;> </xref> classe."
  syntax:
    content: public XamlXmlWriterSettings ();
    parameters: []
  overload: System.Xaml.XamlXmlWriterSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlWriterSettings.AssumeValidInput
  id: AssumeValidInput
  parent: System.Xaml.XamlXmlWriterSettings
  langs:
  - csharp
  name: AssumeValidInput
  nameWithType: XamlXmlWriterSettings.AssumeValidInput
  fullName: System.Xaml.XamlXmlWriterSettings.AssumeValidInput
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Obtém ou define um valor que especifica se o <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> deve sempre considerar a entrada XAML válida para fins de resolução duplicada ou outra verificação de erro."
  syntax:
    content: public bool AssumeValidInput { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se o <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> ignorará determinadas verificações de validação ou erro, como lançar exceções em membros duplicados. <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>Se o <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> lança exceções quando XAML inválido é encontrado. O padrão é <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlXmlWriterSettings.AssumeValidInput*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlWriterSettings.CloseOutput
  id: CloseOutput
  parent: System.Xaml.XamlXmlWriterSettings
  langs:
  - csharp
  name: CloseOutput
  nameWithType: XamlXmlWriterSettings.CloseOutput
  fullName: System.Xaml.XamlXmlWriterSettings.CloseOutput
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Obtém ou define um valor que especifica se o <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> deve fechar imediatamente em <xref uid=&quot;langword_csharp_Dispose&quot; name=&quot;Dispose&quot; href=&quot;&quot;> </xref> ou outras operações, ou se o gravador XAML em vez disso, deve gravar a saída do buffer antes de fechar. Use essa configuração com cuidado; fechar imediatamente pode resultar em XAML inválido que não pode ser carregado novamente."
  remarks: "Essa configuração influencia a lógica de <xref:System.Xaml.XamlXmlWriter.Dispose%2A?displayProperty=fullName>, que chama `Close` em subjacente <xref:System.Xml.XmlWriter>ou <xref:System.IO.TextWriter>quando CloseOutput é `true`; ou ele chama <xref:System.Xaml.XamlXmlWriter.Flush%2A>(novamente ligado ao subjacente <xref:System.Xml.XmlWriter>ou <xref:System.IO.TextWriter>) se for CloseOutput `false`.</xref:System.IO.TextWriter> </xref:System.Xml.XmlWriter> </xref:System.Xaml.XamlXmlWriter.Flush%2A> </xref:System.IO.TextWriter> </xref:System.Xml.XmlWriter> </xref:System.Xaml.XamlXmlWriter.Dispose%2A?displayProperty=fullName>"
  syntax:
    content: public bool CloseOutput { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> fecha imediatamente em uma <xref uid=&quot;langword_csharp_Dispose&quot; name=&quot;Dispose&quot; href=&quot;&quot;> </xref> ou operações semelhantes. <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>Se a saída de buffer restante é gravada antes do <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> é liberado. O padrão é <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlXmlWriterSettings.CloseOutput*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlWriterSettings.Copy
  id: Copy
  parent: System.Xaml.XamlXmlWriterSettings
  langs:
  - csharp
  name: Copy()
  nameWithType: XamlXmlWriterSettings.Copy()
  fullName: System.Xaml.XamlXmlWriterSettings.Copy()
  type: Method
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Retorna uma cópia deste <xref href=&quot;System.Xaml.XamlXmlWriterSettings&quot;> </xref> instância."
  syntax:
    content: public System.Xaml.XamlXmlWriterSettings Copy ();
    parameters: []
    return:
      type: System.Xaml.XamlXmlWriterSettings
      description: "A cópia retornada."
  overload: System.Xaml.XamlXmlWriterSettings.Copy*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Xaml.XamlWriterSettings
  isExternal: false
  name: System.Xaml.XamlWriterSettings
- uid: System.Xaml.XamlXmlWriterSettings.#ctor
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: XamlXmlWriterSettings()
  nameWithType: XamlXmlWriterSettings.XamlXmlWriterSettings()
  fullName: System.Xaml.XamlXmlWriterSettings.XamlXmlWriterSettings()
- uid: System.Xaml.XamlXmlWriterSettings.AssumeValidInput
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: AssumeValidInput
  nameWithType: XamlXmlWriterSettings.AssumeValidInput
  fullName: System.Xaml.XamlXmlWriterSettings.AssumeValidInput
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xaml.XamlXmlWriterSettings.CloseOutput
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: CloseOutput
  nameWithType: XamlXmlWriterSettings.CloseOutput
  fullName: System.Xaml.XamlXmlWriterSettings.CloseOutput
- uid: System.Xaml.XamlXmlWriterSettings.Copy
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: Copy()
  nameWithType: XamlXmlWriterSettings.Copy()
  fullName: System.Xaml.XamlXmlWriterSettings.Copy()
- uid: System.Xaml.XamlXmlWriterSettings
  parent: System.Xaml
  isExternal: false
  name: XamlXmlWriterSettings
  nameWithType: XamlXmlWriterSettings
  fullName: System.Xaml.XamlXmlWriterSettings
- uid: System.Xaml.XamlXmlWriterSettings.#ctor*
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: XamlXmlWriterSettings
  nameWithType: XamlXmlWriterSettings.XamlXmlWriterSettings
- uid: System.Xaml.XamlXmlWriterSettings.AssumeValidInput*
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: AssumeValidInput
  nameWithType: XamlXmlWriterSettings.AssumeValidInput
- uid: System.Xaml.XamlXmlWriterSettings.CloseOutput*
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: CloseOutput
  nameWithType: XamlXmlWriterSettings.CloseOutput
- uid: System.Xaml.XamlXmlWriterSettings.Copy*
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: Copy
  nameWithType: XamlXmlWriterSettings.Copy
