### YamlMime:ManagedReference
items:
- uid: System.Configuration.SpecialSetting
  id: SpecialSetting
  children:
  - System.Configuration.SpecialSetting.ConnectionString
  - System.Configuration.SpecialSetting.WebServiceUrl
  langs:
  - csharp
  name: SpecialSetting
  nameWithType: SpecialSetting
  fullName: System.Configuration.SpecialSetting
  type: Enum
  summary: "Especifica a categoria de configuração especiais de uma propriedade de configurações do aplicativo."
  remarks: "A enumeração SpecialSetting define um conjunto de categorias especiais que são aplicados às propriedades de configurações do aplicativo com a classe ttribute.      > [!CAUTION] > O provedor de configurações padrão, <xref:System.Configuration.LocalFileSettingsProvider>, não criptografar ou protegem cadeias de caracteres de conexão.</xref:System.Configuration.LocalFileSettingsProvider> Simples armazena esse tipo de configurações em um separado `<connectionstrings>` seção no arquivo de configuração apropriado."
  syntax:
    content: public enum SpecialSetting
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.SpecialSetting.ConnectionString
  id: ConnectionString
  parent: System.Configuration.SpecialSetting
  langs:
  - csharp
  name: ConnectionString
  nameWithType: SpecialSetting.ConnectionString
  fullName: System.Configuration.SpecialSetting.ConnectionString
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "A propriedade de configuração representa uma cadeia de caracteres de conexão, normalmente para dados de um loja ou recursos de rede."
  syntax:
    content: ConnectionString
    return:
      type: System.Configuration.SpecialSetting
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SpecialSetting.WebServiceUrl
  id: WebServiceUrl
  parent: System.Configuration.SpecialSetting
  langs:
  - csharp
  name: WebServiceUrl
  nameWithType: SpecialSetting.WebServiceUrl
  fullName: System.Configuration.SpecialSetting.WebServiceUrl
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "A propriedade de configuração representa um localizador URL (Uniform Resource) para um serviço Web."
  syntax:
    content: WebServiceUrl
    return:
      type: System.Configuration.SpecialSetting
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.SpecialSetting.ConnectionString
  parent: System.Configuration.SpecialSetting
  isExternal: false
  name: ConnectionString
  nameWithType: SpecialSetting.ConnectionString
  fullName: System.Configuration.SpecialSetting.ConnectionString
- uid: System.Configuration.SpecialSetting
  parent: System.Configuration
  isExternal: false
  name: SpecialSetting
  nameWithType: SpecialSetting
  fullName: System.Configuration.SpecialSetting
- uid: System.Configuration.SpecialSetting.WebServiceUrl
  parent: System.Configuration.SpecialSetting
  isExternal: false
  name: WebServiceUrl
  nameWithType: SpecialSetting.WebServiceUrl
  fullName: System.Configuration.SpecialSetting.WebServiceUrl
