### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlObjectReaderSettings
  id: XamlObjectReaderSettings
  children:
  - System.Xaml.XamlObjectReaderSettings.#ctor
  - System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
  langs:
  - csharp
  name: XamlObjectReaderSettings
  nameWithType: XamlObjectReaderSettings
  fullName: System.Xaml.XamlObjectReaderSettings
  type: Class
  summary: "Especifica as regras de processamento ou configurações de opção para um <xref href=&quot;System.Xaml.XamlObjectReader&quot;> </xref>."
  syntax:
    content: 'public class XamlObjectReaderSettings : System.Xaml.XamlReaderSettings'
  inheritance:
  - System.Object
  - System.Xaml.XamlReaderSettings
  implements: []
  inheritedMembers:
  - System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  - System.Xaml.XamlReaderSettings.BaseUri
  - System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  - System.Xaml.XamlReaderSettings.LocalAssembly
  - System.Xaml.XamlReaderSettings.ProvideLineInfo
  - System.Xaml.XamlReaderSettings.ValuesMustBeString
  platform:
  - net462
- uid: System.Xaml.XamlObjectReaderSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlObjectReaderSettings
  langs:
  - csharp
  name: XamlObjectReaderSettings()
  nameWithType: XamlObjectReaderSettings.XamlObjectReaderSettings()
  fullName: System.Xaml.XamlObjectReaderSettings.XamlObjectReaderSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Xaml.XamlObjectReaderSettings&quot;> </xref> classe."
  syntax:
    content: public XamlObjectReaderSettings ();
    parameters: []
  overload: System.Xaml.XamlObjectReaderSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
  id: RequireExplicitContentVisibility
  parent: System.Xaml.XamlObjectReaderSettings
  langs:
  - csharp
  name: RequireExplicitContentVisibility
  nameWithType: XamlObjectReaderSettings.RequireExplicitContentVisibility
  fullName: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Obtém ou define um valor que determina se os gravadores usar associado <xref href=&quot;System.Xaml.XamlObjectReader&quot;> </xref> de contexto deve usar as configurações do designer para gravar o conteúdo explicitamente."
  remarks: "Essa configuração é consultada internamente. Ela influencia o comportamento a seguir para o contexto que um <xref:System.Xaml.XamlObjectReader>passa a qualquer <xref:System.Xaml.XamlWriter>:-RequireExplicitContentVisibility o comportamento se aplica somente propriedades onde <xref:System.Xaml.XamlMember.IsWritePublic%2A>é `false`e quando um `ShouldSerialize` padrão não está disponível para o valor da propriedade.</xref:System.Xaml.XamlMember.IsWritePublic%2A> </xref:System.Xaml.XamlWriter> </xref:System.Xaml.XamlObjectReader>      -Se a instrução no primeiro ponto de marcador é verdadeira e RequireExplicitContentVisibility é `true`, as configurações do designer, determine se a propriedade grava sua saída como conteúdo ou a propriedade é considerada implícita. Acesse as configurações do designer é por meio de APIs interno em serviços XAML do .NET Framework e se baseia na leitura <xref:System.ComponentModel.DesignerSerializationVisibilityAttribute>de conjuntos de backup.</xref:System.ComponentModel.DesignerSerializationVisibilityAttribute> Nesse caso, o código interno verifica o valor <xref:System.ComponentModel.DesignerSerializationVisibility?displayProperty=fullName>e grava a saída para a propriedade.</xref:System.ComponentModel.DesignerSerializationVisibility?displayProperty=fullName> Caso contrário, o conteúdo é considerado implícita.      -Se a instrução no primeiro marcador é `true`, RequireExplicitContentVisibility e é `false`, a propriedade sempre grava sua saída, e <xref:System.ComponentModel.DesignerSerializationVisibilityAttribute>de conjuntos de backup é irrelevante.</xref:System.ComponentModel.DesignerSerializationVisibilityAttribute>"
  syntax:
    content: public bool RequireExplicitContentVisibility { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>para especificar que os gravadores que usam esse contexto devem usar as configurações do designer para gravação qualquer saída conteúdo nos casos em que relata <xref:System.Xaml.XamlMember.IsWritePublic*> <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>; <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> se as configurações do designer devem ser ignoradas.</xref:System.Xaml.XamlMember.IsWritePublic*>"
  overload: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Xaml.XamlReaderSettings
  isExternal: false
  name: System.Xaml.XamlReaderSettings
- uid: System.Xaml.XamlObjectReaderSettings.#ctor
  parent: System.Xaml.XamlObjectReaderSettings
  isExternal: false
  name: XamlObjectReaderSettings()
  nameWithType: XamlObjectReaderSettings.XamlObjectReaderSettings()
  fullName: System.Xaml.XamlObjectReaderSettings.XamlObjectReaderSettings()
- uid: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
  parent: System.Xaml.XamlObjectReaderSettings
  isExternal: false
  name: RequireExplicitContentVisibility
  nameWithType: XamlObjectReaderSettings.RequireExplicitContentVisibility
  fullName: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xaml.XamlObjectReaderSettings.#ctor*
  parent: System.Xaml.XamlObjectReaderSettings
  isExternal: false
  name: XamlObjectReaderSettings
  nameWithType: XamlObjectReaderSettings.XamlObjectReaderSettings
- uid: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility*
  parent: System.Xaml.XamlObjectReaderSettings
  isExternal: false
  name: RequireExplicitContentVisibility
  nameWithType: XamlObjectReaderSettings.RequireExplicitContentVisibility
