### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.MachineKeyCompatibilityMode
  id: MachineKeyCompatibilityMode
  children:
  - System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
  - System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
  - System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
  langs:
  - csharp
  name: MachineKeyCompatibilityMode
  nameWithType: MachineKeyCompatibilityMode
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode
  type: Enum
  summary: "Especifica quais métodos de criptografia podem ser usados."
  remarks: "Use os valores de MachineKeyCompatibilityMode quando você define o <xref:System.Web.Configuration.MachineKeySection.CompatibilityMode%2A>propriedade.</xref:System.Web.Configuration.MachineKeySection.CompatibilityMode%2A>"
  syntax:
    content: public enum MachineKeyCompatibilityMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
  id: Framework20SP1
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  langs:
  - csharp
  name: Framework20SP1
  nameWithType: MachineKeyCompatibilityMode.Framework20SP1
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Use os métodos de criptografia que foram implementados no .NET Framework versões anteriores à versão 2.0 Service Pack 2. Vetores de inicialização (IVs) são usados para todas as operações de criptografia, exceto para armazenar senhas criptografadas no banco de dados de associação ASP.NET."
  syntax:
    content: Framework20SP1
    return:
      type: System.Web.Configuration.MachineKeyCompatibilityMode
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
  id: Framework20SP2
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  langs:
  - csharp
  name: Framework20SP2
  nameWithType: MachineKeyCompatibilityMode.Framework20SP2
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Use os métodos de criptografia mais fortes que estão disponíveis no .NET Framework versão 2.0 SP2 e versões posteriores. Vetores de inicialização (IVs) são usados para todas as operações de criptografia."
  syntax:
    content: Framework20SP2
    return:
      type: System.Web.Configuration.MachineKeyCompatibilityMode
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
  id: Framework45
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  langs:
  - csharp
  name: Framework45
  nameWithType: MachineKeyCompatibilityMode.Framework45
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Use os métodos de criptografia estão disponíveis na versão do .NET Framework 4.5 e versões posteriores. Em comparação com os métodos de criptografia que são usados para Framework20SP1 e Framework20SP2, o texto cifrado que é gerado pelas rotinas de criptografia padrão é ligeiramente menor e seja mais resiliente contra determinadas classes de ataques teóricos. Ele também se integrar com [!INCLUDE[win8](~/add/includes/ajax-current-ext-md.md)] gerenciamento de chaves do diretório para obter as chaves de criptografia necessárias. Essa opção também permite que você especifique rotinas criptográficas personalizadas, escrevendo uma classe que deriva de <xref href=&quot;System.Security.Cryptography.DataProtector&quot;> </xref> e especificando o nome da classe no &lt;xref:System.Web.Configuration.MachineKeySection.DataProtectorType%2A?displayProperty=fullName&gt; propriedade.       Os requisitos de configuração a seguir se aplicam a essa opção: 1. Se o &lt;xref:System.Web.Configuration.MachineKeySection.DataProtectorType%2A?displayProperty=fullName&gt; propriedade tem um valor, o &lt;xref:System.Web.Configuration.MachineKeySection.ApplicationName%2A?displayProperty=fullName&gt; propriedade também deve ter um valor.       2. O &lt;xref:System.Web.Configuration.MachineKeySection.Validation%2A?displayProperty=fullName&gt; atributo deve especificar um algoritmo de validação definido pelo sistema (como MD5, SHA1, HMACSHA256, HMACSHA384 ou HMACSHA512) ou um algoritmo de validação personalizada em uma classe que deriva de <xref href=&quot;System.Security.Cryptography.KeyedHashAlgorithm&quot;> </xref> classe. Os valores AES e 3DES não são algoritmos de validação.       Quando você especificar essa opção, tíquetes de autenticação de formulários são sempre tanto criptografados e assinados, independentemente do valor especificado para o &lt;xref:System.Web.Configuration.FormsAuthenticationConfiguration.Protection%2A?displayProperty=fullName&gt; propriedade. Exibição de estado é também criptografado e assinado, se uma página <> </> *> é de propriedade <code> true </code> ou <> </> *> é de propriedade <xref:System.Web.UI.ViewStateEncryptionMode.Always>.</xref:System.Web.UI.ViewStateEncryptionMode.Always>"
  syntax:
    content: Framework45
    return:
      type: System.Web.Configuration.MachineKeyCompatibilityMode
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  isExternal: false
  name: Framework20SP1
  nameWithType: MachineKeyCompatibilityMode.Framework20SP1
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
- uid: System.Web.Configuration.MachineKeyCompatibilityMode
  parent: System.Web.Configuration
  isExternal: false
  name: MachineKeyCompatibilityMode
  nameWithType: MachineKeyCompatibilityMode
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  isExternal: false
  name: Framework20SP2
  nameWithType: MachineKeyCompatibilityMode.Framework20SP2
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  isExternal: false
  name: Framework45
  nameWithType: MachineKeyCompatibilityMode.Framework45
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
