### YamlMime:ManagedReference
items:
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  id: ApplicationChangedEventArgs
  children:
  - System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication
  - System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType
  - System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact
  - System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint
  langs:
  - csharp
  name: ApplicationChangedEventArgs
  nameWithType: ApplicationChangedEventArgs
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  type: Class
  summary: "Fornece informações de qualificação para um método de retorno de chamada quando uma <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication.ApplicationChanged&quot;> </xref> evento ocorre."
  remarks: "Um <xref:System.Net.PeerToPeer.Collaboration.ContactManager.ApplicationChanged>é gerado quando: - um par inicia um aplicativo dentro de uma colaboração - um par termina um aplicativo dentro de uma colaboração - o <xref:System.Net.PeerToPeer.Collaboration.PeerContact>objeto que representa um par de colaboração tem uma alteração em suas propriedades, como o apelido associado - o escopo do aplicativo é alterado no computador do contato par - um par move para um endereço IP diferente na rede - todas as classes que usa a classe ApplicationChangedEventArgs requer um <xref:System.Security.Permissions.PermissionState>irrestrito.</xref:System.Security.Permissions.PermissionState> </xref:System.Net.PeerToPeer.Collaboration.PeerContact> </xref:System.Net.PeerToPeer.Collaboration.ContactManager.ApplicationChanged> Esse estado é criado quando o <xref:System.Net.PeerToPeer.Collaboration.PeerCollaboration>objeto for construído.</xref:System.Net.PeerToPeer.Collaboration.PeerCollaboration>"
  syntax:
    content: 'public class ApplicationChangedEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication
  id: PeerApplication
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  langs:
  - csharp
  name: PeerApplication
  nameWithType: ApplicationChangedEventArgs.PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Obtém o <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> para que o evento foi gerado."
  remarks: "A menos que especificado, o valor padrão dessa propriedade é `null`."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerApplication PeerApplication { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerApplication
      description: "O <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> instância que foi atualizada."
  overload: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType
  id: PeerChangeType
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  langs:
  - csharp
  name: PeerChangeType
  nameWithType: ApplicationChangedEventArgs.PeerChangeType
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Obtém o tipo de alteração para o <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> que ocorreu."
  remarks: "A menos que especificado, o valor padrão dessa propriedade é `null`."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerChangeType PeerChangeType { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerChangeType
      description: "O <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerChangeType&quot;> </xref> valor de enumeração que especifica o tipo de alteração que foi executada no <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref>."
  overload: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact
  id: PeerContact
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  langs:
  - csharp
  name: PeerContact
  nameWithType: ApplicationChangedEventArgs.PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Obtém o <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerContact&quot;> </xref> associados a <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref>."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerContact PeerContact { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerContact
      description: "<xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerContact&quot;></xref>associado a <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref>."
  overload: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint
  id: PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  langs:
  - csharp
  name: PeerEndPoint
  nameWithType: ApplicationChangedEventArgs.PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Obtém o ponto de extremidade para o qual <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> informações foram alteradas."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerEndPoint PeerEndPoint { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerEndPoint
      description: "O <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerEndPoint&quot;> </xref> que contém o ponto de extremidade para qual aplicativo informações foram alteradas. A menos que explicitamente especificado, o valor padrão para todas as propriedades é <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> para tipos de referência e zero (0) para propriedades do tipo <xref uid=&quot;langword_csharp_int&quot; name=&quot;int&quot; href=&quot;&quot;> </xref>."
  overload: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerApplication
  nameWithType: ApplicationChangedEventArgs.PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.PeerApplication
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerApplication
  nameWithType: PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerChangeType
  nameWithType: ApplicationChangedEventArgs.PeerChangeType
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType
- uid: System.Net.PeerToPeer.Collaboration.PeerChangeType
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerChangeType
  nameWithType: PeerChangeType
  fullName: System.Net.PeerToPeer.Collaboration.PeerChangeType
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerContact
  nameWithType: ApplicationChangedEventArgs.PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.PeerContact
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerContact
  nameWithType: PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerEndPoint
  nameWithType: ApplicationChangedEventArgs.PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint
- uid: System.Net.PeerToPeer.Collaboration.PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerEndPoint
  nameWithType: PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.PeerEndPoint
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication*
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerApplication
  nameWithType: ApplicationChangedEventArgs.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType*
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerChangeType
  nameWithType: ApplicationChangedEventArgs.PeerChangeType
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact*
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerContact
  nameWithType: ApplicationChangedEventArgs.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint*
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerEndPoint
  nameWithType: ApplicationChangedEventArgs.PeerEndPoint
