### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  id: PartialTrustVisibleAssembliesSection
  children:
  - System.Web.Configuration.PartialTrustVisibleAssembliesSection.#ctor
  - System.Web.Configuration.PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies
  - System.Web.Configuration.PartialTrustVisibleAssembliesSection.Properties
  langs:
  - csharp
  name: PartialTrustVisibleAssembliesSection
  nameWithType: PartialTrustVisibleAssembliesSection
  fullName: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  type: Class
  summary: "Define um conjunto de assemblies de confiança parcial. Essa classe não pode ser herdada."
  remarks: "Por padrão, o ASP.NET internamente define um conjunto conhecido de assemblies que são marcados com o parcialmente confiável chamadores atributo (APTCA) para uso em aplicativos ASP.NET de confiança parcial. O PartialTrustVisibleAssembliesSection permite adicionar assemblies marcados APTCA à lista.       Para configurar um assembly, você precisa a representação de cadeia de caracteres hexadecimal de sua chave pública. Você pode obter essa chave usando a ferramenta de nome forte (Sn.exe). Essa ferramenta gera a representação de cadeia de caracteres hexadecimal de chave pública que você usa para a configuração e também produz o token de chave pública.       Para obter mais informações sobre a ferramenta de nome forte, consulte [Sn.exe (ferramenta de nome forte)](~/add/includes/ajax-current-ext-md.md)."
  example:
  - "The following example shows how to configure a partial trust assembly by using the `partialTrustVisibleAssemblies` section in a configuration file.  \n  \n```  \n<partialTrustVisibleAssemblies>  \n  <add assemblyName=\"MyAssembly\"   \n    publicKey=\"hex_key_representation\"/>  \n</partialTrustVisibleAssemblies>  \n```"
  syntax:
    content: 'public sealed class PartialTrustVisibleAssembliesSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  langs:
  - csharp
  name: PartialTrustVisibleAssembliesSection()
  nameWithType: PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssembliesSection()
  fullName: System.Web.Configuration.PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssembliesSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Web.Configuration.PartialTrustVisibleAssembliesSection&quot;> </xref> classe."
  syntax:
    content: public PartialTrustVisibleAssembliesSection ();
    parameters: []
  overload: System.Web.Configuration.PartialTrustVisibleAssembliesSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies
  id: PartialTrustVisibleAssemblies
  parent: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  langs:
  - csharp
  name: PartialTrustVisibleAssemblies
  nameWithType: PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies
  fullName: System.Web.Configuration.PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Obtém o <xref href=&quot;System.Web.Configuration.PartialTrustVisibleAssembliesSection&quot;> </xref> coleção de assemblies marcados APTCA para usar em aplicativos ASP.NET de confiança parcial."
  syntax:
    content: public System.Web.Configuration.PartialTrustVisibleAssemblyCollection PartialTrustVisibleAssemblies { get; }
    return:
      type: System.Web.Configuration.PartialTrustVisibleAssemblyCollection
      description: "Uma coleção dos assemblies marcados APTCA para usar em aplicativos ASP.NET de confiança parcial."
  overload: System.Web.Configuration.PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection.Properties
  id: Properties
  parent: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  langs:
  - csharp
  name: Properties
  nameWithType: PartialTrustVisibleAssembliesSection.Properties
  fullName: System.Web.Configuration.PartialTrustVisibleAssembliesSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A ser adicionado."
  overload: System.Web.Configuration.PartialTrustVisibleAssembliesSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection.#ctor
  parent: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  isExternal: false
  name: PartialTrustVisibleAssembliesSection()
  nameWithType: PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssembliesSection()
  fullName: System.Web.Configuration.PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssembliesSection()
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies
  parent: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  isExternal: false
  name: PartialTrustVisibleAssemblies
  nameWithType: PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies
  fullName: System.Web.Configuration.PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies
- uid: System.Web.Configuration.PartialTrustVisibleAssemblyCollection
  parent: System.Web.Configuration
  isExternal: false
  name: PartialTrustVisibleAssemblyCollection
  nameWithType: PartialTrustVisibleAssemblyCollection
  fullName: System.Web.Configuration.PartialTrustVisibleAssemblyCollection
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection.Properties
  parent: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  isExternal: false
  name: Properties
  nameWithType: PartialTrustVisibleAssembliesSection.Properties
  fullName: System.Web.Configuration.PartialTrustVisibleAssembliesSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection.#ctor*
  parent: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  isExternal: false
  name: PartialTrustVisibleAssembliesSection
  nameWithType: PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssembliesSection
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies*
  parent: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  isExternal: false
  name: PartialTrustVisibleAssemblies
  nameWithType: PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection.Properties*
  parent: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  isExternal: false
  name: Properties
  nameWithType: PartialTrustVisibleAssembliesSection.Properties
