### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute
  id: ApplicationAccessControlAttribute
  children:
  - System.EnterpriseServices.ApplicationAccessControlAttribute.#ctor
  - System.EnterpriseServices.ApplicationAccessControlAttribute.#ctor(System.Boolean)
  - System.EnterpriseServices.ApplicationAccessControlAttribute.AccessChecksLevel
  - System.EnterpriseServices.ApplicationAccessControlAttribute.Authentication
  - System.EnterpriseServices.ApplicationAccessControlAttribute.ImpersonationLevel
  - System.EnterpriseServices.ApplicationAccessControlAttribute.Value
  langs:
  - csharp
  name: ApplicationAccessControlAttribute
  nameWithType: ApplicationAccessControlAttribute
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute
  type: Class
  summary: "Especifica os controles de acesso para um assembly contendo <xref href=&quot;System.EnterpriseServices.ServicedComponent&quot;> </xref> classes."
  remarks: "No .NET Framework versão 1.1, se esse atributo não estiver presente no assembly, a configuração de segurança COM+ é habilitada por padrão. Essa é uma alteração no comportamento do .NET Framework versão 1.0."
  example:
  - "The following code example demonstrates the use of this attribute to control access to an assembly containing <xref:System.EnterpriseServices.ServicedComponent> classes.  \n  \n [!code-cpp[EnterpriseServices_Security#2](~/add/codesnippet/cpp/t-system.enterpriseservi_25_1.cpp)]\n [!code-cs[EnterpriseServices_Security#2](~/add/codesnippet/csharp/t-system.enterpriseservi_25_1.cs)]\n [!code-vb[EnterpriseServices_Security#2](~/add/codesnippet/visualbasic/t-system.enterpriseservi_25_1.vb)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Assembly, Inherited=true)]

      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class ApplicationAccessControlAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.#ctor
  id: '#ctor'
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  langs:
  - csharp
  name: ApplicationAccessControlAttribute()
  nameWithType: ApplicationAccessControlAttribute.ApplicationAccessControlAttribute()
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.ApplicationAccessControlAttribute()
  type: Constructor
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Inicializa uma nova instância do <xref href=&quot;System.EnterpriseServices.ApplicationAccessControlAttribute&quot;> </xref> classe, habilitando a configuração de segurança do COM+."
  remarks: ''
  example:
  - "The following code example demonstrates the use of this attribute to control access to an assembly containing <xref:System.EnterpriseServices.ServicedComponent> classes.  \n  \n [!code-cpp[EnterpriseServices_Security#2](~/add/codesnippet/cpp/m-system.enterpriseservi_23_1.cpp)]\n [!code-cs[EnterpriseServices_Security#2](~/add/codesnippet/csharp/m-system.enterpriseservi_23_1.cs)]\n [!code-vb[EnterpriseServices_Security#2](~/add/codesnippet/visualbasic/m-system.enterpriseservi_23_1.vb)]"
  syntax:
    content: public ApplicationAccessControlAttribute ();
    parameters: []
  overload: System.EnterpriseServices.ApplicationAccessControlAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.#ctor(System.Boolean)
  id: '#ctor(System.Boolean)'
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  langs:
  - csharp
  name: ApplicationAccessControlAttribute(Boolean)
  nameWithType: ApplicationAccessControlAttribute.ApplicationAccessControlAttribute(Boolean)
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.ApplicationAccessControlAttribute(Boolean)
  type: Constructor
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Inicializa uma nova instância do <xref href=&quot;System.EnterpriseServices.ApplicationAccessControlAttribute&quot;> </xref> classe e define o <xref:System.EnterpriseServices.ApplicationAccessControlAttribute.Value*>propriedade que indica se deseja habilitar a configuração de segurança COM.</xref:System.EnterpriseServices.ApplicationAccessControlAttribute.Value*>"
  syntax:
    content: public ApplicationAccessControlAttribute (bool val);
    parameters:
    - id: val
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>para permitir a configuração de segurança. Caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.EnterpriseServices.ApplicationAccessControlAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.AccessChecksLevel
  id: AccessChecksLevel
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  langs:
  - csharp
  name: AccessChecksLevel
  nameWithType: ApplicationAccessControlAttribute.AccessChecksLevel
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.AccessChecksLevel
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Obtém ou define o nível para nível de processo ou para o nível de componente de verificação de acesso."
  remarks: "Essa propriedade tem suporte apenas no Windows 2000 e posterior."
  example:
  - "The following code example demonstrates the use of this property.  \n  \n [!code-cpp[EnterpriseServices_Security#2](~/add/codesnippet/cpp/p-system.enterpriseservi_33_1.cpp)]\n [!code-cs[EnterpriseServices_Security#2](~/add/codesnippet/csharp/p-system.enterpriseservi_33_1.cs)]\n [!code-vb[EnterpriseServices_Security#2](~/add/codesnippet/visualbasic/p-system.enterpriseservi_33_1.vb)]"
  syntax:
    content: public System.EnterpriseServices.AccessChecksLevelOption AccessChecksLevel { get; set; }
    return:
      type: System.EnterpriseServices.AccessChecksLevelOption
      description: "Uma da <xref href=&quot;System.EnterpriseServices.AccessChecksLevelOption&quot;> </xref> valores."
  overload: System.EnterpriseServices.ApplicationAccessControlAttribute.AccessChecksLevel*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.Authentication
  id: Authentication
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  langs:
  - csharp
  name: Authentication
  nameWithType: ApplicationAccessControlAttribute.Authentication
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.Authentication
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Obtém ou define o nível de autenticação de RPC (chamada) de procedimento remoto."
  remarks: ''
  example:
  - "The following example illustrates the use of this property.  \n  \n [!code-cpp[EnterpriseServices_Security#2](~/add/codesnippet/cpp/p-system.enterpriseservi_17_1.cpp)]\n [!code-cs[EnterpriseServices_Security#2](~/add/codesnippet/csharp/p-system.enterpriseservi_17_1.cs)]\n [!code-vb[EnterpriseServices_Security#2](~/add/codesnippet/visualbasic/p-system.enterpriseservi_17_1.vb)]"
  syntax:
    content: public System.EnterpriseServices.AuthenticationOption Authentication { get; set; }
    return:
      type: System.EnterpriseServices.AuthenticationOption
      description: "Uma da <xref href=&quot;System.EnterpriseServices.AuthenticationOption&quot;> </xref> valores."
  overload: System.EnterpriseServices.ApplicationAccessControlAttribute.Authentication*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.ImpersonationLevel
  id: ImpersonationLevel
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  langs:
  - csharp
  name: ImpersonationLevel
  nameWithType: ApplicationAccessControlAttribute.ImpersonationLevel
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.ImpersonationLevel
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Obtém ou define o nível de representação que é permitido para chamar destinos desse aplicativo."
  remarks: "Essa propriedade tem suporte apenas no Windows 2000 e posterior."
  example:
  - "The following code example demonstrates the use of this property.  \n  \n [!code-cpp[EnterpriseServices_Security#2](~/add/codesnippet/cpp/f57469cf-7d93-405f-ae99-_1.cpp)]\n [!code-cs[EnterpriseServices_Security#2](~/add/codesnippet/csharp/f57469cf-7d93-405f-ae99-_1.cs)]\n [!code-vb[EnterpriseServices_Security#2](~/add/codesnippet/visualbasic/f57469cf-7d93-405f-ae99-_1.vb)]"
  syntax:
    content: public System.EnterpriseServices.ImpersonationLevelOption ImpersonationLevel { get; set; }
    return:
      type: System.EnterpriseServices.ImpersonationLevelOption
      description: "Uma da <xref href=&quot;System.EnterpriseServices.ImpersonationLevelOption&quot;> </xref> valores."
  overload: System.EnterpriseServices.ApplicationAccessControlAttribute.ImpersonationLevel*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.Value
  id: Value
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  langs:
  - csharp
  name: Value
  nameWithType: ApplicationAccessControlAttribute.Value
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.Value
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Obtém ou define um valor que indica se deseja habilitar a configuração de segurança do COM+."
  syntax:
    content: public bool Value { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se a configuração de segurança COM+ está ativada. Caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.EnterpriseServices.ApplicationAccessControlAttribute.Value*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.#ctor
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: ApplicationAccessControlAttribute()
  nameWithType: ApplicationAccessControlAttribute.ApplicationAccessControlAttribute()
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.ApplicationAccessControlAttribute()
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.#ctor(System.Boolean)
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: ApplicationAccessControlAttribute(Boolean)
  nameWithType: ApplicationAccessControlAttribute.ApplicationAccessControlAttribute(Boolean)
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.ApplicationAccessControlAttribute(Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.AccessChecksLevel
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: AccessChecksLevel
  nameWithType: ApplicationAccessControlAttribute.AccessChecksLevel
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.AccessChecksLevel
- uid: System.EnterpriseServices.AccessChecksLevelOption
  parent: System.EnterpriseServices
  isExternal: false
  name: AccessChecksLevelOption
  nameWithType: AccessChecksLevelOption
  fullName: System.EnterpriseServices.AccessChecksLevelOption
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.Authentication
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: Authentication
  nameWithType: ApplicationAccessControlAttribute.Authentication
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.Authentication
- uid: System.EnterpriseServices.AuthenticationOption
  parent: System.EnterpriseServices
  isExternal: false
  name: AuthenticationOption
  nameWithType: AuthenticationOption
  fullName: System.EnterpriseServices.AuthenticationOption
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.ImpersonationLevel
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: ImpersonationLevel
  nameWithType: ApplicationAccessControlAttribute.ImpersonationLevel
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.ImpersonationLevel
- uid: System.EnterpriseServices.ImpersonationLevelOption
  parent: System.EnterpriseServices
  isExternal: false
  name: ImpersonationLevelOption
  nameWithType: ImpersonationLevelOption
  fullName: System.EnterpriseServices.ImpersonationLevelOption
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.Value
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: Value
  nameWithType: ApplicationAccessControlAttribute.Value
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.Value
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.#ctor*
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: ApplicationAccessControlAttribute
  nameWithType: ApplicationAccessControlAttribute.ApplicationAccessControlAttribute
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.AccessChecksLevel*
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: AccessChecksLevel
  nameWithType: ApplicationAccessControlAttribute.AccessChecksLevel
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.Authentication*
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: Authentication
  nameWithType: ApplicationAccessControlAttribute.Authentication
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.ImpersonationLevel*
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: ImpersonationLevel
  nameWithType: ApplicationAccessControlAttribute.ImpersonationLevel
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.Value*
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: Value
  nameWithType: ApplicationAccessControlAttribute.Value
