### YamlMime:ManagedReference
items:
- uid: System.Data.Services.IDataServiceConfiguration
  id: IDataServiceConfiguration
  children:
  - System.Data.Services.IDataServiceConfiguration.MaxBatchCount
  - System.Data.Services.IDataServiceConfiguration.MaxChangesetCount
  - System.Data.Services.IDataServiceConfiguration.MaxExpandCount
  - System.Data.Services.IDataServiceConfiguration.MaxExpandDepth
  - System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert
  - System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection
  - System.Data.Services.IDataServiceConfiguration.RegisterKnownType(System.Type)
  - System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule(System.String,System.Data.Services.EntitySetRights)
  - System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule(System.String,System.Data.Services.ServiceOperationRights)
  - System.Data.Services.IDataServiceConfiguration.UseVerboseErrors
  langs:
  - csharp
  name: IDataServiceConfiguration
  nameWithType: IDataServiceConfiguration
  fullName: System.Data.Services.IDataServiceConfiguration
  type: Interface
  summary: "O IDataServiceConfiguration é usado pelo [!INCLUDE[ssAstoria](~/add/includes/ssastoria-md.md)] configurar o comportamento do serviço, incluindo os direitos sobre conjuntos de entidades e operações de serviço, limitando as solicitações permitidas, registrar tipos não podem ser descobertos por padrão e o nível de detalhes padrão no tratamento de erros."
  remarks: "Esse tipo é usado pelo <xref:System.Data.Services.DataService%601>classes para configurar o serviço com a implementação de um método estático chamado InitializeService, retornar void e dê um único argumento do tipo IDataServiceConfiguration.</xref:System.Data.Services.DataService%601> O objeto de configuração só pode ser usado durante a chamada para a inicialização do serviço."
  syntax:
    content: public interface IDataServiceConfiguration
  implements: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.MaxBatchCount
  id: MaxBatchCount
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxBatchCount
  nameWithType: IDataServiceConfiguration.MaxBatchCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxBatchCount
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Obtém o número máximo de solicitações que podem ser tratados em um lote."
  syntax:
    content: public int MaxBatchCount { get; set; }
    return:
      type: System.Int32
      description: "Valor inteiro que indica o número máximo de solicitações que podem ser tratados em um lote."
  overload: System.Data.Services.IDataServiceConfiguration.MaxBatchCount*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount
  id: MaxChangesetCount
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxChangesetCount
  nameWithType: IDataServiceConfiguration.MaxChangesetCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Obtém o número máximo de conjuntos de alterações que podem ser tratados em um lote."
  syntax:
    content: public int MaxChangesetCount { get; set; }
    return:
      type: System.Int32
      description: "Valor inteiro que indica o número máximo de conjuntos de alterações que podem ser tratados em um lote."
  overload: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandCount
  id: MaxExpandCount
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxExpandCount
  nameWithType: IDataServiceConfiguration.MaxExpandCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxExpandCount
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Obtém ou define o número máximo de segmentos que podem ser expandidos de $expanda a opção para todas as solicitações para o serviço de dados de consulta."
  remarks: "Se o limite for excedido, um código de status 400 Solicitação incorreta é retornado. O valor especificado deve estar entre 0 e `int.MaxValue`; caso contrário, um `ArgumentOutOfRangeException` é gerada.       O exemplo de cadeia de caracteres de consulta a seguir tem dois segmentos:"
  syntax:
    content: public int MaxExpandCount { get; set; }
    return:
      type: System.Int32
      description: "O número máximo de segmentos para expandir."
  overload: System.Data.Services.IDataServiceConfiguration.MaxExpandCount*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth
  id: MaxExpandDepth
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxExpandDepth
  nameWithType: IDataServiceConfiguration.MaxExpandDepth
  fullName: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Obtém ou define um número máximo de segmentos de suporte em um único `$expand` caminho para todas as solicitações para o serviço de dados."
  remarks: "Se o limite for excedido, um código de status 400 Solicitação incorreta é retornado. O valor especificado deve estar entre 0 e `int.MaxValue`; caso contrário, um `ArgumentOutOfRangeException` é gerada.       O exemplo de cadeia de caracteres de consulta a seguir tem dois segmentos na primeira `$expand` caminho e um no segundo `$expand` caminho:"
  syntax:
    content: public int MaxExpandDepth { get; set; }
    return:
      type: System.Int32
      description: "Suporte de inteiro que representa o número máximo de segmentos no `$expand` caminho."
  overload: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert
  id: MaxObjectCountOnInsert
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxObjectCountOnInsert
  nameWithType: IDataServiceConfiguration.MaxObjectCountOnInsert
  fullName: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Obtém ou define o número máximo de objetos que podem ser inseridos em uma única solicitação."
  syntax:
    content: public int MaxObjectCountOnInsert { get; set; }
    return:
      type: System.Int32
      description: "O valor de inteiro que contém o número máximo de objetos que podem ser inseridos em uma única solicitação."
  overload: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection
  id: MaxResultsPerCollection
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxResultsPerCollection
  nameWithType: IDataServiceConfiguration.MaxResultsPerCollection
  fullName: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Obtém o número máximo de resultados por coleção."
  syntax:
    content: public int MaxResultsPerCollection { get; set; }
    return:
      type: System.Int32
      description: "O valor de inteiro que indica o número máximo de resultados por coleção."
  overload: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.RegisterKnownType(System.Type)
  id: RegisterKnownType(System.Type)
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: RegisterKnownType(Type)
  nameWithType: IDataServiceConfiguration.RegisterKnownType(Type)
  fullName: System.Data.Services.IDataServiceConfiguration.RegisterKnownType(Type)
  type: Method
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Registra um tipo de recurso para uso pelo serviço de dados."
  syntax:
    content: public void RegisterKnownType (Type type);
    parameters:
    - id: type
      type: System.Type
      description: "O tipo de recurso para registrar."
  overload: System.Data.Services.IDataServiceConfiguration.RegisterKnownType*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule(System.String,System.Data.Services.EntitySetRights)
  id: SetEntitySetAccessRule(System.String,System.Data.Services.EntitySetRights)
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: SetEntitySetAccessRule(String,EntitySetRights)
  nameWithType: IDataServiceConfiguration.SetEntitySetAccessRule(String,EntitySetRights)
  fullName: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule(String,EntitySetRights)
  type: Method
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Define as regras de acesso para a entidade especificada do conjunto."
  remarks: "A configuração padrão é negar o acesso aos recursos. Quando um serviço é inicializado, os direitos de acesso devem ser habilitados."
  syntax:
    content: public void SetEntitySetAccessRule (string name, System.Data.Services.EntitySetRights rights);
    parameters:
    - id: name
      type: System.String
      description: "O nome da entidade definida para acesso configurado."
    - id: rights
      type: System.Data.Services.EntitySetRights
      description: "Os direitos permitidos para o conjunto de entidades."
  overload: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule(System.String,System.Data.Services.ServiceOperationRights)
  id: SetServiceOperationAccessRule(System.String,System.Data.Services.ServiceOperationRights)
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: SetServiceOperationAccessRule(String,ServiceOperationRights)
  nameWithType: IDataServiceConfiguration.SetServiceOperationAccessRule(String,ServiceOperationRights)
  fullName: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule(String,ServiceOperationRights)
  type: Method
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Define as regras de acesso para a operação de serviço especificado."
  remarks: "A configuração padrão é negar o acesso aos recursos. Quando um serviço é inicializado, os direitos de acesso devem ser habilitados."
  syntax:
    content: public void SetServiceOperationAccessRule (string name, System.Data.Services.ServiceOperationRights rights);
    parameters:
    - id: name
      type: System.String
      description: "O nome da operação de serviço no qual definir direitos de acesso."
    - id: rights
      type: System.Data.Services.ServiceOperationRights
      description: "Os direitos de permissão de acordo com a <xref href=&quot;System.Data.Services.ServiceOperationRights&quot;> </xref> enumeração."
  overload: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors
  id: UseVerboseErrors
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: UseVerboseErrors
  nameWithType: IDataServiceConfiguration.UseVerboseErrors
  fullName: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Obtém ou define se erros detalhados são usados por padrão para todas as respostas do serviço de dados."
  remarks: "A resposta de uma solicitação especificada pode ser substituída pelo desenvolvedor de serviço de dados, substituindo o `HandleException` método. Erros detalhados devem ser habilitados apenas durante o desenvolvimento, não em ambientes de produção, por motivos de segurança."
  syntax:
    content: public bool UseVerboseErrors { get; set; }
    return:
      type: System.Boolean
      description: "Um valor booliano que indica se erros detalhados são retornados."
  overload: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Data.Services.IDataServiceConfiguration.MaxBatchCount
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxBatchCount
  nameWithType: IDataServiceConfiguration.MaxBatchCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxBatchCount
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxChangesetCount
  nameWithType: IDataServiceConfiguration.MaxChangesetCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandCount
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxExpandCount
  nameWithType: IDataServiceConfiguration.MaxExpandCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxExpandCount
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxExpandDepth
  nameWithType: IDataServiceConfiguration.MaxExpandDepth
  fullName: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth
- uid: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxObjectCountOnInsert
  nameWithType: IDataServiceConfiguration.MaxObjectCountOnInsert
  fullName: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert
- uid: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxResultsPerCollection
  nameWithType: IDataServiceConfiguration.MaxResultsPerCollection
  fullName: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection
- uid: System.Data.Services.IDataServiceConfiguration.RegisterKnownType(System.Type)
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: RegisterKnownType(Type)
  nameWithType: IDataServiceConfiguration.RegisterKnownType(Type)
  fullName: System.Data.Services.IDataServiceConfiguration.RegisterKnownType(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule(System.String,System.Data.Services.EntitySetRights)
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: SetEntitySetAccessRule(String,EntitySetRights)
  nameWithType: IDataServiceConfiguration.SetEntitySetAccessRule(String,EntitySetRights)
  fullName: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule(String,EntitySetRights)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Data.Services.EntitySetRights
  parent: System.Data.Services
  isExternal: false
  name: EntitySetRights
  nameWithType: EntitySetRights
  fullName: System.Data.Services.EntitySetRights
- uid: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule(System.String,System.Data.Services.ServiceOperationRights)
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: SetServiceOperationAccessRule(String,ServiceOperationRights)
  nameWithType: IDataServiceConfiguration.SetServiceOperationAccessRule(String,ServiceOperationRights)
  fullName: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule(String,ServiceOperationRights)
- uid: System.Data.Services.ServiceOperationRights
  parent: System.Data.Services
  isExternal: false
  name: ServiceOperationRights
  nameWithType: ServiceOperationRights
  fullName: System.Data.Services.ServiceOperationRights
- uid: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: UseVerboseErrors
  nameWithType: IDataServiceConfiguration.UseVerboseErrors
  fullName: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Data.Services.IDataServiceConfiguration.MaxBatchCount*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxBatchCount
  nameWithType: IDataServiceConfiguration.MaxBatchCount
- uid: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxChangesetCount
  nameWithType: IDataServiceConfiguration.MaxChangesetCount
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandCount*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxExpandCount
  nameWithType: IDataServiceConfiguration.MaxExpandCount
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxExpandDepth
  nameWithType: IDataServiceConfiguration.MaxExpandDepth
- uid: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxObjectCountOnInsert
  nameWithType: IDataServiceConfiguration.MaxObjectCountOnInsert
- uid: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxResultsPerCollection
  nameWithType: IDataServiceConfiguration.MaxResultsPerCollection
- uid: System.Data.Services.IDataServiceConfiguration.RegisterKnownType*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: RegisterKnownType
  nameWithType: IDataServiceConfiguration.RegisterKnownType
- uid: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: SetEntitySetAccessRule
  nameWithType: IDataServiceConfiguration.SetEntitySetAccessRule
- uid: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: SetServiceOperationAccessRule
  nameWithType: IDataServiceConfiguration.SetServiceOperationAccessRule
- uid: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: UseVerboseErrors
  nameWithType: IDataServiceConfiguration.UseVerboseErrors
