### YamlMime:ManagedReference
items:
- uid: System.Printing.PrintJobSettings
  id: PrintJobSettings
  children:
  - System.Printing.PrintJobSettings.CurrentPrintTicket
  - System.Printing.PrintJobSettings.Description
  langs:
  - csharp
  name: PrintJobSettings
  nameWithType: PrintJobSettings
  fullName: System.Printing.PrintJobSettings
  type: Class
  summary: "Descreve um trabalho de impressão."
  remarks: "O <xref:System.Printing.PrintTicket>objeto, que é o valor da <xref:System.Printing.PrintJobSettings.CurrentPrintTicket%2A>propriedade mantém todas as configurações detalhadas para um trabalho de impressão.</xref:System.Printing.PrintJobSettings.CurrentPrintTicket%2A> </xref:System.Printing.PrintTicket> O pai, PrintJobSettings, adiciona apenas uma descrição.      > [!CAUTION] > Classes dentro de <xref:System.Printing>namespace não têm suporte para uso dentro de um serviço do Windows ou serviço ou aplicativo ASP.NET.</xref:System.Printing> Tentativa de usar essas classes de dentro de um desses tipos de aplicativo pode gerar problemas inesperados, como diminuído exceções de desempenho e tempo de execução de serviço.       Se você quiser imprimir a partir de um aplicativo Windows Forms, consulte o <xref:System.Drawing.Printing>namespace.</xref:System.Drawing.Printing>"
  syntax:
    content: public class PrintJobSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Printing.PrintJobSettings.CurrentPrintTicket
  id: CurrentPrintTicket
  parent: System.Printing.PrintJobSettings
  langs:
  - csharp
  name: CurrentPrintTicket
  nameWithType: PrintJobSettings.CurrentPrintTicket
  fullName: System.Printing.PrintJobSettings.CurrentPrintTicket
  type: Property
  assemblies:
  - System.Printing
  namespace: System.Printing
  summary: "Obtém ou define um <xref href=&quot;System.Printing.PrintTicket&quot;> </xref> objeto que contém todas as configurações detalhadas para o trabalho de impressão."
  remarks: "A definição dessa propriedade CurrentPrintTicket não validar ou modificar o especificado <xref:System.Printing.PrintTicket>para um determinado <xref:System.Printing.PrintQueue>.</xref:System.Printing.PrintQueue> </xref:System.Printing.PrintTicket>  Se necessário, use o <xref:System.Printing.PrintQueue.MergeAndValidatePrintTicket%2A>método para criar um <xref:System.Printing.PrintQueue>-específico <xref:System.Printing.PrintTicket>que é válido para uma determinada impressora.</xref:System.Printing.PrintTicket> </xref:System.Printing.PrintQueue> </xref:System.Printing.PrintQueue.MergeAndValidatePrintTicket%2A>"
  syntax:
    content: public System.Printing.PrintTicket CurrentPrintTicket { get; set; }
    return:
      type: System.Printing.PrintTicket
      description: "Um <xref href=&quot;System.Printing.PrintTicket&quot;> </xref> do objeto que contém todos os detalhes sobre o trabalho de impressão, como o número de cópias a serem impressas, e se grampeamento ou impressão duplex for usado."
  overload: System.Printing.PrintJobSettings.CurrentPrintTicket*
  exceptions: []
  platform:
  - net462
- uid: System.Printing.PrintJobSettings.Description
  id: Description
  parent: System.Printing.PrintJobSettings
  langs:
  - csharp
  name: Description
  nameWithType: PrintJobSettings.Description
  fullName: System.Printing.PrintJobSettings.Description
  type: Property
  assemblies:
  - System.Printing
  namespace: System.Printing
  summary: "Obtém ou define uma descrição de um trabalho de impressão."
  syntax:
    content: public string Description { get; set; }
    return:
      type: System.String
      description: "Um <xref:System.String>que descreve o trabalho de impressão, por exemplo, &quot;relatório trimestral.&quot;</xref:System.String>"
  overload: System.Printing.PrintJobSettings.Description*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Printing.PrintJobSettings.CurrentPrintTicket
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: CurrentPrintTicket
  nameWithType: PrintJobSettings.CurrentPrintTicket
  fullName: System.Printing.PrintJobSettings.CurrentPrintTicket
- uid: System.Printing.PrintTicket
  parent: System.Printing
  isExternal: false
  name: PrintTicket
  nameWithType: PrintTicket
  fullName: System.Printing.PrintTicket
- uid: System.Printing.PrintJobSettings.Description
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: Description
  nameWithType: PrintJobSettings.Description
  fullName: System.Printing.PrintJobSettings.Description
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Printing.PrintJobSettings.CurrentPrintTicket*
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: CurrentPrintTicket
  nameWithType: PrintJobSettings.CurrentPrintTicket
- uid: System.Printing.PrintJobSettings.Description*
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: Description
  nameWithType: PrintJobSettings.Description
