### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.HttpConfigurationContext
  id: HttpConfigurationContext
  children:
  - System.Web.Configuration.HttpConfigurationContext.VirtualPath
  langs:
  - csharp
  name: HttpConfigurationContext
  nameWithType: HttpConfigurationContext
  fullName: System.Web.Configuration.HttpConfigurationContext
  type: Class
  summary: "Fornece informações de contexto atual para manipuladores de seção de configuração em aplicativos ASP.NET."
  remarks: "As informações de contexto fornecidas por esta classe são para a solicitação HTTP atual."
  syntax:
    content: public class HttpConfigurationContext
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpConfigurationContext.VirtualPath
  id: VirtualPath
  parent: System.Web.Configuration.HttpConfigurationContext
  langs:
  - csharp
  name: VirtualPath
  nameWithType: HttpConfigurationContext.VirtualPath
  fullName: System.Web.Configuration.HttpConfigurationContext.VirtualPath
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Obtém o caminho virtual para o arquivo de configuração Web. config."
  syntax:
    content: public string VirtualPath { get; }
    return:
      type: System.String
      description: "O caminho virtual para o arquivo Web. config. <xref uid=&quot;langword_csharp_Null&quot; name=&quot;Null&quot; href=&quot;&quot;></xref>ao avaliar o Machine. config; uma cadeia de caracteres vazia (&quot;&quot;) ao avaliar o arquivo Web. config de raiz para o site."
  overload: System.Web.Configuration.HttpConfigurationContext.VirtualPath*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Configuration.HttpConfigurationContext.VirtualPath
  parent: System.Web.Configuration.HttpConfigurationContext
  isExternal: false
  name: VirtualPath
  nameWithType: HttpConfigurationContext.VirtualPath
  fullName: System.Web.Configuration.HttpConfigurationContext.VirtualPath
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.HttpConfigurationContext.VirtualPath*
  parent: System.Web.Configuration.HttpConfigurationContext
  isExternal: false
  name: VirtualPath
  nameWithType: HttpConfigurationContext.VirtualPath
