### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.FcnMode
  id: FcnMode
  children:
  - System.Web.Configuration.FcnMode.Default
  - System.Web.Configuration.FcnMode.Disabled
  - System.Web.Configuration.FcnMode.NotSet
  - System.Web.Configuration.FcnMode.Single
  langs:
  - csharp
  name: FcnMode
  nameWithType: FcnMode
  fullName: System.Web.Configuration.FcnMode
  type: Enum
  summary: "Especifica o comportamento de notificação de alteração de arquivo (FCN) no aplicativo."
  syntax:
    content: public enum FcnMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.FcnMode.Default
  id: Default
  parent: System.Web.Configuration.FcnMode
  langs:
  - csharp
  name: Default
  nameWithType: FcnMode.Default
  fullName: System.Web.Configuration.FcnMode.Default
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Para cada subpasta, o aplicativo cria um objeto que monitora o subdiretório. Este é o comportamento padrão."
  syntax:
    content: Default
    return:
      type: System.Web.Configuration.FcnMode
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FcnMode.Disabled
  id: Disabled
  parent: System.Web.Configuration.FcnMode
  langs:
  - csharp
  name: Disabled
  nameWithType: FcnMode.Disabled
  fullName: System.Web.Configuration.FcnMode.Disabled
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Notificação de alteração de arquivo está desabilitada."
  syntax:
    content: Disabled
    return:
      type: System.Web.Configuration.FcnMode
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FcnMode.NotSet
  id: NotSet
  parent: System.Web.Configuration.FcnMode
  langs:
  - csharp
  name: NotSet
  nameWithType: FcnMode.NotSet
  fullName: System.Web.Configuration.FcnMode.NotSet
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Notificação de alteração de arquivo não está definida para que o aplicativo cria um objeto que monitora cada subpasta. Este é o comportamento padrão."
  syntax:
    content: NotSet
    return:
      type: System.Web.Configuration.FcnMode
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FcnMode.Single
  id: Single
  parent: System.Web.Configuration.FcnMode
  langs:
  - csharp
  name: Single
  nameWithType: FcnMode.Single
  fullName: System.Web.Configuration.FcnMode.Single
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "O aplicativo cria um objeto para monitorar o diretório principal e usa esse objeto para monitorar cada subpasta."
  syntax:
    content: Single
    return:
      type: System.Web.Configuration.FcnMode
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.FcnMode.Default
  parent: System.Web.Configuration.FcnMode
  isExternal: false
  name: Default
  nameWithType: FcnMode.Default
  fullName: System.Web.Configuration.FcnMode.Default
- uid: System.Web.Configuration.FcnMode
  parent: System.Web.Configuration
  isExternal: false
  name: FcnMode
  nameWithType: FcnMode
  fullName: System.Web.Configuration.FcnMode
- uid: System.Web.Configuration.FcnMode.Disabled
  parent: System.Web.Configuration.FcnMode
  isExternal: false
  name: Disabled
  nameWithType: FcnMode.Disabled
  fullName: System.Web.Configuration.FcnMode.Disabled
- uid: System.Web.Configuration.FcnMode.NotSet
  parent: System.Web.Configuration.FcnMode
  isExternal: false
  name: NotSet
  nameWithType: FcnMode.NotSet
  fullName: System.Web.Configuration.FcnMode.NotSet
- uid: System.Web.Configuration.FcnMode.Single
  parent: System.Web.Configuration.FcnMode
  isExternal: false
  name: Single
  nameWithType: FcnMode.Single
  fullName: System.Web.Configuration.FcnMode.Single
