### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.UpdateCheckInfo
  id: UpdateCheckInfo
  children:
  - System.Deployment.Application.UpdateCheckInfo.AvailableVersion
  - System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired
  - System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion
  - System.Deployment.Application.UpdateCheckInfo.UpdateAvailable
  - System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes
  langs:
  - csharp
  name: UpdateCheckInfo
  nameWithType: UpdateCheckInfo
  fullName: System.Deployment.Application.UpdateCheckInfo
  type: Class
  summary: "Representa informações de atualização detalhada obtidas por meio de uma chamada para <xref:System.Deployment.Application.ApplicationDeployment.CheckForDetailedUpdate*>.</xref:System.Deployment.Application.ApplicationDeployment.CheckForDetailedUpdate*>"
  remarks: "Com UpdateCheckInfo, você pode decidir se deseja atualizar seu aplicativo ClickOnce com base nas informações sobre a versão mais recente. <xref:System.Deployment.Application.UpdateCheckInfo.UpdateAvailable%2A>Retorna um valor booliano que indica se há uma nova atualização em todos os.</xref:System.Deployment.Application.UpdateCheckInfo.UpdateAvailable%2A> O <xref:System.Deployment.Application.UpdateCheckInfo.AvailableVersion%2A>propriedade fornece o número de versão da nova versão, enquanto <xref:System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion%2A>fornece a versão mais antiga que o usuário deve ter instalado.</xref:System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion%2A> </xref:System.Deployment.Application.UpdateCheckInfo.AvailableVersion%2A> <xref:System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired%2A>expressa se a atualização mais recente é exigida do usuário.</xref:System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired%2A> Por fim, <xref:System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes%2A>expressa o tamanho total da atualização.</xref:System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes%2A>      > [!NOTE] > Visual Studio adiciona o `<deploymentProvider>` elemento para o manifesto somente se o aplicativo é configurado para verificar se há atualizações, para que seja necessário verificar **o aplicativo deve verificar se há atualizações** ou especifique uma URL de atualização no **atualizar local** no [caixa de diálogo de atualizações de aplicativo](http://msdn.microsoft.com/en-us/8eca8743-8e68-4d04-bfd5-4dc0a9b2934f)."
  example:
  - "The following code example uses <xref:System.Deployment.Application.UpdateCheckInfo.UpdateAvailable%2A> to determine if there is a new application update, and <xref:System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired%2A> to determine whether to ask the user to install the update.  \n  \n [!code-cs[ClickOnceAPI#6](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#6)]\n [!code-cpp[ClickOnceAPI#6](~/add/codesnippet/cpp/t-system.deployment.appl_8_1.cpp)]\n [!code-vb[ClickOnceAPI#6](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#6)]"
  syntax:
    content: public class UpdateCheckInfo
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Deployment.Application.UpdateCheckInfo.AvailableVersion
  id: AvailableVersion
  parent: System.Deployment.Application.UpdateCheckInfo
  langs:
  - csharp
  name: AvailableVersion
  nameWithType: UpdateCheckInfo.AvailableVersion
  fullName: System.Deployment.Application.UpdateCheckInfo.AvailableVersion
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Obtém o número de versão da versão mais recente instalado."
  remarks: "Você pode usar AvailableVersion para decidir se deseja instalar a atualização com base na gravidade da atualização. Por exemplo, se apenas o <xref:System.Version.Build%2A>ou <xref:System.Version.Revision%2A>Propriedades de versão foram alteradas, o aplicativo não seja necessário atualizar até que o <xref:System.Version.Minor%2A>ou <xref:System.Version.Major%2A>alteração de propriedades.</xref:System.Version.Major%2A> </xref:System.Version.Minor%2A> </xref:System.Version.Revision%2A> </xref:System.Version.Build%2A>"
  syntax:
    content: public Version AvailableVersion { get; }
    return:
      type: System.Version
      description: "O <xref:System.Version>expressar os números de compilação e revisão principais e secundários da versão mais recente.</xref:System.Version>"
  overload: System.Deployment.Application.UpdateCheckInfo.AvailableVersion*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired
  id: IsUpdateRequired
  parent: System.Deployment.Application.UpdateCheckInfo
  langs:
  - csharp
  name: IsUpdateRequired
  nameWithType: UpdateCheckInfo.IsUpdateRequired
  fullName: System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Obtém um valor que indica se a atualização deve ser instalada."
  remarks: "Quando você implanta uma atualização para o seu aplicativo ClickOnce, você pode ser marcado como atualização obrigatória, sinalização para seu aplicativo, deve atualizar imediatamente. Você deseja marcar o aplicativo se a versão mais recente contém uma atualização crítica, ou se ele é incompatível com formatos de arquivo ou fontes de dados de back-end usados por versões anteriores."
  example:
  - "The following code example uses IsUpdateRequired to determine whether to ask the user to install the update, or to install it without prompting.  \n  \n [!code-cs[ClickOnceAPI#6](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#6)]\n [!code-cpp[ClickOnceAPI#6](~/add/codesnippet/cpp/p-system.deployment.appl_6_1.cpp)]\n [!code-vb[ClickOnceAPI#6](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#6)]"
  syntax:
    content: public bool IsUpdateRequired { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se a atualização é necessária; Caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion
  id: MinimumRequiredVersion
  parent: System.Deployment.Application.UpdateCheckInfo
  langs:
  - csharp
  name: MinimumRequiredVersion
  nameWithType: UpdateCheckInfo.MinimumRequiredVersion
  fullName: System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Obtém a versão mínima que o usuário deve ter instalado no computador."
  remarks: "Aplicativos podem perder atualizações necessárias quando o usuário assume uma atribuição especial ou está longe do computador para semanas ou meses. Use MinimumRequiredVersion para determinar se o usuário não tiver atualizado o aplicativo em um tempo e perdeu uma ou mais atualizações necessárias."
  example:
  - "The following code example demonstrates displaying the MinimumRequiredVersion property to the user when there is a required update available.  \n  \n [!code-cs[ClickOnceAPI#6](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#6)]\n [!code-cpp[ClickOnceAPI#6](~/add/codesnippet/cpp/p-system.deployment.appl_1_1.cpp)]\n [!code-vb[ClickOnceAPI#6](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#6)]"
  syntax:
    content: public Version MinimumRequiredVersion { get; }
    return:
      type: System.Version
      description: "Um <xref:System.Version>expressar a mínimo a versão que o usuário instale.</xref:System.Version>"
  overload: System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion*
  exceptions:
  - type: System.InvalidOperationException
    commentId: T:System.InvalidOperationException
    description: "Não há nenhuma nova versão disponível para instalação."
  platform:
  - net462
- uid: System.Deployment.Application.UpdateCheckInfo.UpdateAvailable
  id: UpdateAvailable
  parent: System.Deployment.Application.UpdateCheckInfo
  langs:
  - csharp
  name: UpdateAvailable
  nameWithType: UpdateCheckInfo.UpdateAvailable
  fullName: System.Deployment.Application.UpdateCheckInfo.UpdateAvailable
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Determina se uma atualização desinstalada está disponível."
  remarks: ''
  example:
  - "The following code example inspects UpdateAvailable to determine whether there is an update to install.  \n  \n [!code-cs[ClickOnceAPI#6](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#6)]\n [!code-cpp[ClickOnceAPI#6](~/add/codesnippet/cpp/p-system.deployment.appl_10_1.cpp)]\n [!code-vb[ClickOnceAPI#6](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#6)]"
  syntax:
    content: public bool UpdateAvailable { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se a nova versão do aplicativo está disponível. Caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Deployment.Application.UpdateCheckInfo.UpdateAvailable*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes
  id: UpdateSizeBytes
  parent: System.Deployment.Application.UpdateCheckInfo
  langs:
  - csharp
  name: UpdateSizeBytes
  nameWithType: UpdateCheckInfo.UpdateSizeBytes
  fullName: System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Obtém o tamanho da atualização disponível."
  syntax:
    content: public long UpdateSizeBytes { get; }
    return:
      type: System.Int64
      description: "Um <xref:System.Int64>que descreve o tamanho, em bytes, da atualização disponível.</xref:System.Int64> Se nenhuma atualização estiver disponível, retornará 0."
  overload: System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.InvalidOperationException
  isExternal: true
  name: System.InvalidOperationException
- uid: System.Deployment.Application.UpdateCheckInfo.AvailableVersion
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: AvailableVersion
  nameWithType: UpdateCheckInfo.AvailableVersion
  fullName: System.Deployment.Application.UpdateCheckInfo.AvailableVersion
- uid: System.Version
  parent: System
  isExternal: true
  name: Version
  nameWithType: Version
  fullName: System.Version
- uid: System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: IsUpdateRequired
  nameWithType: UpdateCheckInfo.IsUpdateRequired
  fullName: System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: MinimumRequiredVersion
  nameWithType: UpdateCheckInfo.MinimumRequiredVersion
  fullName: System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion
- uid: System.Deployment.Application.UpdateCheckInfo.UpdateAvailable
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: UpdateAvailable
  nameWithType: UpdateCheckInfo.UpdateAvailable
  fullName: System.Deployment.Application.UpdateCheckInfo.UpdateAvailable
- uid: System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: UpdateSizeBytes
  nameWithType: UpdateCheckInfo.UpdateSizeBytes
  fullName: System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Deployment.Application.UpdateCheckInfo.AvailableVersion*
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: AvailableVersion
  nameWithType: UpdateCheckInfo.AvailableVersion
- uid: System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired*
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: IsUpdateRequired
  nameWithType: UpdateCheckInfo.IsUpdateRequired
- uid: System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion*
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: MinimumRequiredVersion
  nameWithType: UpdateCheckInfo.MinimumRequiredVersion
- uid: System.Deployment.Application.UpdateCheckInfo.UpdateAvailable*
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: UpdateAvailable
  nameWithType: UpdateCheckInfo.UpdateAvailable
- uid: System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes*
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: UpdateSizeBytes
  nameWithType: UpdateCheckInfo.UpdateSizeBytes
