### YamlMime:ManagedReference
items:
- uid: System.AddIn.Hosting.AddInEnvironment
  id: AddInEnvironment
  children:
  - System.AddIn.Hosting.AddInEnvironment.#ctor(System.AppDomain)
  - System.AddIn.Hosting.AddInEnvironment.Process
  langs:
  - csharp
  name: AddInEnvironment
  nameWithType: AddInEnvironment
  fullName: System.AddIn.Hosting.AddInEnvironment
  type: Class
  summary: "Fornece acesso ao domínio de aplicativo e o processo de um suplemento."
  remarks: "Use esta classe para carregar os suplementos em um ambiente desejado, que pode ser um dos seguintes:-um domínio de aplicativo existente para o qual você tem o <xref:System.AppDomain>objeto.</xref:System.AppDomain>      -Um domínio de aplicativo que foi gerado automaticamente para ativar um suplemento.      -Um processo externo existente.       Para obter o objeto AddInEnvironment para um suplemento, passe domínio de aplicativo do suplemento para o construtor da classe AddInEnvironment. Como alternativa, você pode usar o <xref:System.AddIn.Hosting.AddInController.AddInEnvironment%2A>propriedade o <xref:System.AddIn.Hosting.AddInController>classe para obter objeto de AddInEnvironment do suplemento.</xref:System.AddIn.Hosting.AddInController> </xref:System.AddIn.Hosting.AddInController.AddInEnvironment%2A>       Depois de obter o objeto AddInEnvironment, você pode fazer o seguinte:-passa o objeto AddInEnvironment ao apropriado <xref:System.AddIn.Hosting.AddInToken.Activate%2A>sobrecarga de método.</xref:System.AddIn.Hosting.AddInToken.Activate%2A> O suplemento será ativado no domínio de aplicativo e o processo que é representado pelo objeto AddInEnvironment.      -Usar o <xref:System.AddIn.Hosting.AddInEnvironment.Process%2A>propriedade para obter um <xref:System.AddIn.Hosting.AddInProcess>objeto.</xref:System.AddIn.Hosting.AddInProcess> </xref:System.AddIn.Hosting.AddInEnvironment.Process%2A> Em seguida, passa o objeto ao apropriado <xref:System.AddIn.Hosting.AddInToken.Activate%2A>sobrecarga de método.</xref:System.AddIn.Hosting.AddInToken.Activate%2A> O suplemento será ativado no processo que é representado pelo <xref:System.AddIn.Hosting.AddInProcess>objeto, mas em um novo domínio de aplicativo.</xref:System.AddIn.Hosting.AddInProcess>"
  syntax:
    content: public sealed class AddInEnvironment
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.AddIn.Hosting.AddInEnvironment.#ctor(System.AppDomain)
  id: '#ctor(System.AppDomain)'
  parent: System.AddIn.Hosting.AddInEnvironment
  langs:
  - csharp
  name: AddInEnvironment(AppDomain)
  nameWithType: AddInEnvironment.AddInEnvironment(AppDomain)
  fullName: System.AddIn.Hosting.AddInEnvironment.AddInEnvironment(AppDomain)
  type: Constructor
  assemblies:
  - System.AddIn
  namespace: System.AddIn.Hosting
  summary: "Inicializa uma nova instância do <xref href=&quot;System.AddIn.Hosting.AddInEnvironment&quot;> </xref> classe."
  remarks: "Se você tiver acesso ao domínio do aplicativo que contém o suplemento que você precisa, você pode usar esse construtor para obter o suplemento <xref:System.AddIn.Hosting.AddInEnvironment>objeto.</xref:System.AddIn.Hosting.AddInEnvironment> Caso contrário, você pode usar o <xref:System.AddIn.Hosting.AddInController.AddInEnvironment%2A>propriedade o <xref:System.AddIn.Hosting.AddInController>classe para obter o <xref:System.AddIn.Hosting.AddInEnvironment>objeto.</xref:System.AddIn.Hosting.AddInEnvironment> </xref:System.AddIn.Hosting.AddInController> </xref:System.AddIn.Hosting.AddInController.AddInEnvironment%2A>"
  syntax:
    content: public AddInEnvironment (AppDomain appDomain);
    parameters:
    - id: appDomain
      type: System.AppDomain
      description: "O domínio de aplicativo que contém o suplemento."
  overload: System.AddIn.Hosting.AddInEnvironment.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>appDomain</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.Security.SecurityException
    commentId: T:System.Security.SecurityException
    description: "Permissão de confiança total é exigida. Um chamador na cadeia de chamada não tem permissão suficiente."
  platform:
  - net462
- uid: System.AddIn.Hosting.AddInEnvironment.Process
  id: Process
  parent: System.AddIn.Hosting.AddInEnvironment
  langs:
  - csharp
  name: Process
  nameWithType: AddInEnvironment.Process
  fullName: System.AddIn.Hosting.AddInEnvironment.Process
  type: Property
  assemblies:
  - System.AddIn
  namespace: System.AddIn.Hosting
  summary: "Obtém o <xref href=&quot;System.AddIn.Hosting.AddInProcess&quot;> </xref> objeto que representa o processo no qual o suplemento está sendo executado."
  remarks: "Você pode usar essa propriedade para ativar vários suplementos no mesmo processo, mas em domínios diferentes.       Passar o <xref:System.AddIn.Hosting.AddInProcess>objeto obtido com essa propriedade ao apropriado <xref:System.AddIn.Hosting.AddInToken.Activate%2A>sobrecarga de método.</xref:System.AddIn.Hosting.AddInToken.Activate%2A> </xref:System.AddIn.Hosting.AddInProcess>       Se você deseja ativá-los no mesmo domínio em um processo externo deve passar o <xref:System.AddIn.Hosting.AddInEnvironment>objeto diretamente para o <xref:System.AddIn.Hosting.AddInToken.Activate%60%601%28System.AddIn.Hosting.AddInEnvironment%29?displayProperty=fullName>sobrecarga de método.</xref:System.AddIn.Hosting.AddInToken.Activate%60%601%28System.AddIn.Hosting.AddInEnvironment%29?displayProperty=fullName> </xref:System.AddIn.Hosting.AddInEnvironment>"
  syntax:
    content: public System.AddIn.Hosting.AddInProcess Process { get; }
    return:
      type: System.AddIn.Hosting.AddInProcess
      description: "O processo no qual o suplemento está sendo executado."
  overload: System.AddIn.Hosting.AddInEnvironment.Process*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Security.SecurityException
  isExternal: true
  name: System.Security.SecurityException
- uid: System.AddIn.Hosting.AddInEnvironment.#ctor(System.AppDomain)
  parent: System.AddIn.Hosting.AddInEnvironment
  isExternal: false
  name: AddInEnvironment(AppDomain)
  nameWithType: AddInEnvironment.AddInEnvironment(AppDomain)
  fullName: System.AddIn.Hosting.AddInEnvironment.AddInEnvironment(AppDomain)
- uid: System.AppDomain
  parent: System
  isExternal: false
  name: AppDomain
  nameWithType: AppDomain
  fullName: System.AppDomain
- uid: System.AddIn.Hosting.AddInEnvironment.Process
  parent: System.AddIn.Hosting.AddInEnvironment
  isExternal: false
  name: Process
  nameWithType: AddInEnvironment.Process
  fullName: System.AddIn.Hosting.AddInEnvironment.Process
- uid: System.AddIn.Hosting.AddInProcess
  parent: System.AddIn.Hosting
  isExternal: false
  name: AddInProcess
  nameWithType: AddInProcess
  fullName: System.AddIn.Hosting.AddInProcess
- uid: System.AddIn.Hosting.AddInEnvironment.#ctor*
  parent: System.AddIn.Hosting.AddInEnvironment
  isExternal: false
  name: AddInEnvironment
  nameWithType: AddInEnvironment.AddInEnvironment
- uid: System.AddIn.Hosting.AddInEnvironment.Process*
  parent: System.AddIn.Hosting.AddInEnvironment
  isExternal: false
  name: Process
  nameWithType: AddInEnvironment.Process
