### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationPermissionAttribute
  id: ConfigurationPermissionAttribute
  children:
  - System.Configuration.ConfigurationPermissionAttribute.#ctor(System.Security.Permissions.SecurityAction)
  - System.Configuration.ConfigurationPermissionAttribute.CreatePermission
  langs:
  - csharp
  name: ConfigurationPermissionAttribute
  nameWithType: ConfigurationPermissionAttribute
  fullName: System.Configuration.ConfigurationPermissionAttribute
  type: Class
  summary: "Cria um <xref href=&quot;System.Configuration.ConfigurationPermission&quot;> </xref> objeto que concede ou nega a permissão de destino marcado para acesso de seções de arquivos de configuração."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.All, AllowMultiple=true, Inherited=false)]

      public sealed class ConfigurationPermissionAttribute : System.Security.Permissions.CodeAccessSecurityAttribute
  inheritance:
  - System.Attribute
  - System.Security.Permissions.SecurityAttribute
  - System.Security.Permissions.CodeAccessSecurityAttribute
  implements: []
  inheritedMembers:
  - System.Security.Permissions.SecurityAttribute.Action
  - System.Security.Permissions.SecurityAttribute.Unrestricted
  platform:
  - net462
- uid: System.Configuration.ConfigurationPermissionAttribute.#ctor(System.Security.Permissions.SecurityAction)
  id: '#ctor(System.Security.Permissions.SecurityAction)'
  parent: System.Configuration.ConfigurationPermissionAttribute
  langs:
  - csharp
  name: ConfigurationPermissionAttribute(SecurityAction)
  nameWithType: ConfigurationPermissionAttribute.ConfigurationPermissionAttribute(SecurityAction)
  fullName: System.Configuration.ConfigurationPermissionAttribute.ConfigurationPermissionAttribute(SecurityAction)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Configuration.ConfigurationPermissionAttribute&quot;> </xref> classe."
  syntax:
    content: public ConfigurationPermissionAttribute (System.Security.Permissions.SecurityAction action);
    parameters:
    - id: action
      type: System.Security.Permissions.SecurityAction
      description: "A ação de segurança representada por um membro de enumeração de <xref href=&quot;System.Security.Permissions.SecurityAction&quot;> </xref>. Determina o estado da permissão do atributo."
  overload: System.Configuration.ConfigurationPermissionAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationPermissionAttribute.CreatePermission
  id: CreatePermission
  parent: System.Configuration.ConfigurationPermissionAttribute
  langs:
  - csharp
  name: CreatePermission()
  nameWithType: ConfigurationPermissionAttribute.CreatePermission()
  fullName: System.Configuration.ConfigurationPermissionAttribute.CreatePermission()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Cria e retorna um objeto que implementa o <xref href=&quot;System.Security.IPermission&quot;> </xref> interface."
  remarks: "Esse método retorna um novo <xref:System.Configuration.ConfigurationPermission>objeto.</xref:System.Configuration.ConfigurationPermission>"
  syntax:
    content: public override System.Security.IPermission CreatePermission ();
    parameters: []
    return:
      type: System.Security.IPermission
      description: "Retorna um objeto que implementa <xref href=&quot;System.Security.IPermission&quot;> </xref>."
  overload: System.Configuration.ConfigurationPermissionAttribute.CreatePermission*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Security.Permissions.CodeAccessSecurityAttribute
  isExternal: false
  name: System.Security.Permissions.CodeAccessSecurityAttribute
- uid: System.Configuration.ConfigurationPermissionAttribute.#ctor(System.Security.Permissions.SecurityAction)
  parent: System.Configuration.ConfigurationPermissionAttribute
  isExternal: false
  name: ConfigurationPermissionAttribute(SecurityAction)
  nameWithType: ConfigurationPermissionAttribute.ConfigurationPermissionAttribute(SecurityAction)
  fullName: System.Configuration.ConfigurationPermissionAttribute.ConfigurationPermissionAttribute(SecurityAction)
- uid: System.Security.Permissions.SecurityAction
  parent: System.Security.Permissions
  isExternal: false
  name: SecurityAction
  nameWithType: SecurityAction
  fullName: System.Security.Permissions.SecurityAction
- uid: System.Configuration.ConfigurationPermissionAttribute.CreatePermission
  parent: System.Configuration.ConfigurationPermissionAttribute
  isExternal: false
  name: CreatePermission()
  nameWithType: ConfigurationPermissionAttribute.CreatePermission()
  fullName: System.Configuration.ConfigurationPermissionAttribute.CreatePermission()
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  name: IPermission
  nameWithType: IPermission
  fullName: System.Security.IPermission
- uid: System.Configuration.ConfigurationPermissionAttribute.#ctor*
  parent: System.Configuration.ConfigurationPermissionAttribute
  isExternal: false
  name: ConfigurationPermissionAttribute
  nameWithType: ConfigurationPermissionAttribute.ConfigurationPermissionAttribute
- uid: System.Configuration.ConfigurationPermissionAttribute.CreatePermission*
  parent: System.Configuration.ConfigurationPermissionAttribute
  isExternal: false
  name: CreatePermission
  nameWithType: ConfigurationPermissionAttribute.CreatePermission
