### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ScriptingProfileServiceSection
  id: ScriptingProfileServiceSection
  children:
  - System.Web.Configuration.ScriptingProfileServiceSection.#ctor
  - System.Web.Configuration.ScriptingProfileServiceSection.Enabled
  - System.Web.Configuration.ScriptingProfileServiceSection.Properties
  - System.Web.Configuration.ScriptingProfileServiceSection.ReadAccessProperties
  - System.Web.Configuration.ScriptingProfileServiceSection.WriteAccessProperties
  langs:
  - csharp
  name: ScriptingProfileServiceSection
  nameWithType: ScriptingProfileServiceSection
  fullName: System.Web.Configuration.ScriptingProfileServiceSection
  type: Class
  summary: "Representa a seção de configuração para as configurações de perfil de serviço. Essa classe não pode ser herdada."
  remarks: "A classe ScriptingProfileServiceSection permite acessar e modificar programaticamente o `profileService` elemento da seção de configuração para aplicativos ASP.NET que usam a funcionalidade AJAX.       O serviço de perfil é usado para obter e definir propriedades de perfil para a identidade do usuário que está associado com a solicitação atual. Isso significa que o serviço de perfil funciona para usuários autenticados. Também funciona para usuários anônimos quando o recurso de identificação anônima está habilitada (ou disponível) no arquivo de configuração."
  example:
  - "The following example shows how to declaratively specify values for properties of the ScriptingProfileServiceSection class in a configuration file.  \n  \n```  \n<system.web.extensions>  \n  <scripting>  \n    <webServices>  \n      <profileService enabled=\"true\"   \n        readAccessProperties=\"FirstName,LastName\"   \n        writeAccessProperties=\"FirstName,LastName\" />  \n    </webServices>  \n  </scripting>  \n</system.web.extensions>  \n```  \n  \n The following example shows how to access the ScriptingProfileServiceSection section programmatically.  \n  \n [!code-cs[System.Web.Configuration#2](~/add/codesnippet/csharp/t-system.web.configurati_50_1.cs)]\n [!code-vb[System.Web.Configuration#2](~/add/codesnippet/visualbasic/t-system.web.configurati_50_1.vb)]"
  syntax:
    content: 'public sealed class ScriptingProfileServiceSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingProfileServiceSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  langs:
  - csharp
  name: ScriptingProfileServiceSection()
  nameWithType: ScriptingProfileServiceSection.ScriptingProfileServiceSection()
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.ScriptingProfileServiceSection()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Web.Configuration.ScriptingProfileServiceSection&quot;> </xref> classe."
  syntax:
    content: public ScriptingProfileServiceSection ();
    parameters: []
  overload: System.Web.Configuration.ScriptingProfileServiceSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingProfileServiceSection.Enabled
  id: Enabled
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  langs:
  - csharp
  name: Enabled
  nameWithType: ScriptingProfileServiceSection.Enabled
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.Enabled
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Obtém ou define um valor que indica se o serviço de perfil está disponível no aplicativo habilitado para AJAX ASP.NET."
  syntax:
    content: public bool Enabled { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se o serviço de perfil estiver habilitado; Caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. O padrão é <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.ScriptingProfileServiceSection.Enabled*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingProfileServiceSection.Properties
  id: Properties
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  langs:
  - csharp
  name: Properties
  nameWithType: ScriptingProfileServiceSection.Properties
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.Properties
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A ser adicionado."
  overload: System.Web.Configuration.ScriptingProfileServiceSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingProfileServiceSection.ReadAccessProperties
  id: ReadAccessProperties
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  langs:
  - csharp
  name: ReadAccessProperties
  nameWithType: ScriptingProfileServiceSection.ReadAccessProperties
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.ReadAccessProperties
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Obtém ou define as propriedades do perfil de acesso de leitura."
  remarks: "Para usar propriedades de perfil de acesso de leitura em aplicativos habilitados para AJAX, adicione um ou mais nomes de propriedade de perfil para a propriedade ReadAccessProperties.       Você pode definir ReadAccessProperties como uma matriz de cadeia de caracteres vazia. Isso significa que nenhuma propriedade de perfil podem ser lidas a partir do script de cliente."
  syntax:
    content: public string[] ReadAccessProperties { get; set; }
    return:
      type: System.String[]
      description: "Uma matriz que contém os nomes das propriedades do perfil de acesso de leitura."
  overload: System.Web.Configuration.ScriptingProfileServiceSection.ReadAccessProperties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingProfileServiceSection.WriteAccessProperties
  id: WriteAccessProperties
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  langs:
  - csharp
  name: WriteAccessProperties
  nameWithType: ScriptingProfileServiceSection.WriteAccessProperties
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.WriteAccessProperties
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Obtém ou define o acesso de gravação de propriedades de perfil."
  remarks: "Para usar propriedades de perfil de acesso de gravação em aplicativos habilitados para AJAX, adicione um ou mais nomes de propriedade de perfil para a propriedade WriteAccessProperties.       Você pode definir WriteAccessProperties para uma matriz de cadeia de caracteres vazia. Isso significa que nenhuma propriedade de perfil podem ser definidas a partir do script de cliente."
  syntax:
    content: public string[] WriteAccessProperties { get; set; }
    return:
      type: System.String[]
      description: "Uma matriz que contém os nomes das propriedades de perfil de acesso de gravação."
  overload: System.Web.Configuration.ScriptingProfileServiceSection.WriteAccessProperties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.ScriptingProfileServiceSection.#ctor
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: ScriptingProfileServiceSection()
  nameWithType: ScriptingProfileServiceSection.ScriptingProfileServiceSection()
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.ScriptingProfileServiceSection()
- uid: System.Web.Configuration.ScriptingProfileServiceSection.Enabled
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: Enabled
  nameWithType: ScriptingProfileServiceSection.Enabled
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.Enabled
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.ScriptingProfileServiceSection.Properties
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: Properties
  nameWithType: ScriptingProfileServiceSection.Properties
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.ScriptingProfileServiceSection.ReadAccessProperties
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: ReadAccessProperties
  nameWithType: ScriptingProfileServiceSection.ReadAccessProperties
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.ReadAccessProperties
- uid: System.String[]
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String[]
  spec.csharp:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Web.Configuration.ScriptingProfileServiceSection.WriteAccessProperties
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: WriteAccessProperties
  nameWithType: ScriptingProfileServiceSection.WriteAccessProperties
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.WriteAccessProperties
- uid: System.Web.Configuration.ScriptingProfileServiceSection.#ctor*
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: ScriptingProfileServiceSection
  nameWithType: ScriptingProfileServiceSection.ScriptingProfileServiceSection
- uid: System.Web.Configuration.ScriptingProfileServiceSection.Enabled*
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: Enabled
  nameWithType: ScriptingProfileServiceSection.Enabled
- uid: System.Web.Configuration.ScriptingProfileServiceSection.Properties*
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: Properties
  nameWithType: ScriptingProfileServiceSection.Properties
- uid: System.Web.Configuration.ScriptingProfileServiceSection.ReadAccessProperties*
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: ReadAccessProperties
  nameWithType: ScriptingProfileServiceSection.ReadAccessProperties
- uid: System.Web.Configuration.ScriptingProfileServiceSection.WriteAccessProperties*
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: WriteAccessProperties
  nameWithType: ScriptingProfileServiceSection.WriteAccessProperties
