### YamlMime:ManagedReference
items:
- uid: System.Configuration.UserScopedSettingAttribute
  id: UserScopedSettingAttribute
  children:
  - System.Configuration.UserScopedSettingAttribute.#ctor
  langs:
  - csharp
  name: UserScopedSettingAttribute
  nameWithType: UserScopedSettingAttribute
  fullName: System.Configuration.UserScopedSettingAttribute
  type: Class
  summary: "Especifica que um grupo de configurações do aplicativo ou a propriedade contém valores distintos para cada usuário de um aplicativo. Essa classe não pode ser herdada."
  remarks: "Propriedades de configurações do aplicativo tem um escopo que é baseado no aplicativo ou no nível do usuário. Como as categorias implicam, propriedades do escopo do aplicativo apresentam valores uniformes para todos os usuários do aplicativo, enquanto as propriedades do escopo do usuário têm dedicados valores para cada usuário do aplicativo.       O UserScopedSettingAttribute indica que uma propriedade deve ser considerada uma configuração de nível de usuário, e que as decisões de armazenamento apropriado devem ser feitas adequadamente pelo provedor de configurações.       Um atributo de escopo é necessário para cada propriedade de configurações do aplicativo. Se uma propriedade não é aplicada com o um <xref:System.Configuration.ApplicationScopedSettingAttribute>ou UserScopedSettingAttribute, a propriedade será ignorada pelo provedor de configurações — não é serializado.</xref:System.Configuration.ApplicationScopedSettingAttribute> No entanto, é inválido, se aplicam a ambos os atributos para a mesma propriedade de configurações. Uma tentativa de fazer isso fará com que um <xref:System.Configuration.ConfigurationErrorsException>seja gerada.</xref:System.Configuration.ConfigurationErrorsException>"
  example:
  - "The following code example demonstrates the use of the UserScopedSettingAttribute applied to all four properties of the `FormSettings` wrapper class, which is derived from the <xref:System.Configuration.ApplicationSettingsBase> class. This class is used to persist the location, size, background color, and text of form. The full code example is listed in the <xref:System.Configuration.ApplicationSettingsBase> class overview.  \n  \n [!code-cpp[AppSettingsSample#9](~/add/codesnippet/cpp/t-system.configuration.u_1.cpp)]\n [!code-cs[AppSettingsSample#9](~/add/codesnippet/csharp/t-system.configuration.u_1.cs)]\n [!code-vb[AppSettingsSample#9](~/add/codesnippet/visualbasic/AppSettingsSample/Form1.vb#9)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class UserScopedSettingAttribute : System.Configuration.SettingAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.SettingAttribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.UserScopedSettingAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.UserScopedSettingAttribute
  langs:
  - csharp
  name: UserScopedSettingAttribute()
  nameWithType: UserScopedSettingAttribute.UserScopedSettingAttribute()
  fullName: System.Configuration.UserScopedSettingAttribute.UserScopedSettingAttribute()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Configuration.UserScopedSettingAttribute&quot;> </xref> classe."
  remarks: "Cada propriedade de configurações do aplicativo deve ser aplicada com um único atributo de escopo para que ele seja reconhecido e serializado pelo provedor de configurações."
  syntax:
    content: public UserScopedSettingAttribute ();
    parameters: []
  overload: System.Configuration.UserScopedSettingAttribute.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.SettingAttribute
  isExternal: false
  name: System.Configuration.SettingAttribute
- uid: System.Configuration.UserScopedSettingAttribute.#ctor
  parent: System.Configuration.UserScopedSettingAttribute
  isExternal: false
  name: UserScopedSettingAttribute()
  nameWithType: UserScopedSettingAttribute.UserScopedSettingAttribute()
  fullName: System.Configuration.UserScopedSettingAttribute.UserScopedSettingAttribute()
- uid: System.Configuration.UserScopedSettingAttribute.#ctor*
  parent: System.Configuration.UserScopedSettingAttribute
  isExternal: false
  name: UserScopedSettingAttribute
  nameWithType: UserScopedSettingAttribute.UserScopedSettingAttribute
