### YamlMime:ManagedReference
items:
- uid: System.Configuration.ExeConfigurationFileMap
  id: ExeConfigurationFileMap
  children:
  - System.Configuration.ExeConfigurationFileMap.#ctor
  - System.Configuration.ExeConfigurationFileMap.#ctor(System.String)
  - System.Configuration.ExeConfigurationFileMap.Clone
  - System.Configuration.ExeConfigurationFileMap.ExeConfigFilename
  - System.Configuration.ExeConfigurationFileMap.LocalUserConfigFilename
  - System.Configuration.ExeConfigurationFileMap.RoamingUserConfigFilename
  langs:
  - csharp
  name: ExeConfigurationFileMap
  nameWithType: ExeConfigurationFileMap
  fullName: System.Configuration.ExeConfigurationFileMap
  type: Class
  summary: "Define o mapeamento do arquivo de configuração para um aplicativo .exe. Essa classe não pode ser herdada."
  remarks: "A classe ExeConfigurationFileMap fornece um meio para definir uma hierarquia de arquivos de configuração personalizada de aplicativos .exe. A classe ExeConfigurationFileMap pode especificar um caminho único ou vários caminhos relacionados aos arquivos de configuração."
  example:
  - For an example that shows how to use this class, see the <xref:System.Configuration.ConfigurationManager.OpenMappedExeConfiguration%2A?displayProperty=fullName> method.
  syntax:
    content: 'public sealed class ExeConfigurationFileMap : System.Configuration.ConfigurationFileMap'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationFileMap
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationFileMap.MachineConfigFilename
  platform:
  - net462
- uid: System.Configuration.ExeConfigurationFileMap.#ctor
  id: '#ctor'
  parent: System.Configuration.ExeConfigurationFileMap
  langs:
  - csharp
  name: ExeConfigurationFileMap()
  nameWithType: ExeConfigurationFileMap.ExeConfigurationFileMap()
  fullName: System.Configuration.ExeConfigurationFileMap.ExeConfigurationFileMap()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Configuration.ExeConfigurationFileMap&quot;> </xref> classe."
  syntax:
    content: public ExeConfigurationFileMap ();
    parameters: []
  overload: System.Configuration.ExeConfigurationFileMap.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ExeConfigurationFileMap.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.ExeConfigurationFileMap
  langs:
  - csharp
  name: ExeConfigurationFileMap(String)
  nameWithType: ExeConfigurationFileMap.ExeConfigurationFileMap(String)
  fullName: System.Configuration.ExeConfigurationFileMap.ExeConfigurationFileMap(String)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Configuration.ExeConfigurationFileMap&quot;> </xref> classe usando o nome de arquivo de configuração do computador especificado."
  remarks: "Use este construtor quando você direcionar uma versão do [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] que seja anterior na última vez em que está instalada no computador. Este construtor permite que você especifique um arquivo de configuração de máquina é apropriado para a versão do [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] de destino."
  syntax:
    content: public ExeConfigurationFileMap (string machineConfigFileName);
    parameters:
    - id: machineConfigFileName
      type: System.String
      description: "O nome do arquivo de configuração de máquina que inclui o caminho físico completo (por exemplo, `c:\\Windows\\Microsoft.NET\\Framework\\v2.0.50727\\CONFIG\\machine.config`)."
  overload: System.Configuration.ExeConfigurationFileMap.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ExeConfigurationFileMap.Clone
  id: Clone
  parent: System.Configuration.ExeConfigurationFileMap
  langs:
  - csharp
  name: Clone()
  nameWithType: ExeConfigurationFileMap.Clone()
  fullName: System.Configuration.ExeConfigurationFileMap.Clone()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Cria uma cópia do existente <xref href=&quot;System.Configuration.ExeConfigurationFileMap&quot;> </xref> objeto."
  syntax:
    content: public override object Clone ();
    parameters: []
    return:
      type: System.Object
      description: "Um <xref href=&quot;System.Configuration.ExeConfigurationFileMap&quot;> </xref> objeto."
  overload: System.Configuration.ExeConfigurationFileMap.Clone*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ExeConfigurationFileMap.ExeConfigFilename
  id: ExeConfigFilename
  parent: System.Configuration.ExeConfigurationFileMap
  langs:
  - csharp
  name: ExeConfigFilename
  nameWithType: ExeConfigurationFileMap.ExeConfigFilename
  fullName: System.Configuration.ExeConfigurationFileMap.ExeConfigFilename
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Obtém ou define o nome do arquivo de configuração."
  syntax:
    content: public string ExeConfigFilename { get; set; }
    return:
      type: System.String
      description: "O nome do arquivo de configuração."
  overload: System.Configuration.ExeConfigurationFileMap.ExeConfigFilename*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ExeConfigurationFileMap.LocalUserConfigFilename
  id: LocalUserConfigFilename
  parent: System.Configuration.ExeConfigurationFileMap
  langs:
  - csharp
  name: LocalUserConfigFilename
  nameWithType: ExeConfigurationFileMap.LocalUserConfigFilename
  fullName: System.Configuration.ExeConfigurationFileMap.LocalUserConfigFilename
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Obtém ou define o nome do arquivo de configuração para o usuário local."
  syntax:
    content: public string LocalUserConfigFilename { get; set; }
    return:
      type: System.String
      description: "O nome do arquivo de configuração."
  overload: System.Configuration.ExeConfigurationFileMap.LocalUserConfigFilename*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ExeConfigurationFileMap.RoamingUserConfigFilename
  id: RoamingUserConfigFilename
  parent: System.Configuration.ExeConfigurationFileMap
  langs:
  - csharp
  name: RoamingUserConfigFilename
  nameWithType: ExeConfigurationFileMap.RoamingUserConfigFilename
  fullName: System.Configuration.ExeConfigurationFileMap.RoamingUserConfigFilename
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Obtém ou define o nome do arquivo de configuração para o usuário móvel."
  syntax:
    content: public string RoamingUserConfigFilename { get; set; }
    return:
      type: System.String
      description: "O nome do arquivo de configuração."
  overload: System.Configuration.ExeConfigurationFileMap.RoamingUserConfigFilename*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationFileMap
  isExternal: false
  name: System.Configuration.ConfigurationFileMap
- uid: System.Configuration.ExeConfigurationFileMap.#ctor
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: ExeConfigurationFileMap()
  nameWithType: ExeConfigurationFileMap.ExeConfigurationFileMap()
  fullName: System.Configuration.ExeConfigurationFileMap.ExeConfigurationFileMap()
- uid: System.Configuration.ExeConfigurationFileMap.#ctor(System.String)
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: ExeConfigurationFileMap(String)
  nameWithType: ExeConfigurationFileMap.ExeConfigurationFileMap(String)
  fullName: System.Configuration.ExeConfigurationFileMap.ExeConfigurationFileMap(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ExeConfigurationFileMap.Clone
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: Clone()
  nameWithType: ExeConfigurationFileMap.Clone()
  fullName: System.Configuration.ExeConfigurationFileMap.Clone()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.ExeConfigurationFileMap.ExeConfigFilename
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: ExeConfigFilename
  nameWithType: ExeConfigurationFileMap.ExeConfigFilename
  fullName: System.Configuration.ExeConfigurationFileMap.ExeConfigFilename
- uid: System.Configuration.ExeConfigurationFileMap.LocalUserConfigFilename
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: LocalUserConfigFilename
  nameWithType: ExeConfigurationFileMap.LocalUserConfigFilename
  fullName: System.Configuration.ExeConfigurationFileMap.LocalUserConfigFilename
- uid: System.Configuration.ExeConfigurationFileMap.RoamingUserConfigFilename
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: RoamingUserConfigFilename
  nameWithType: ExeConfigurationFileMap.RoamingUserConfigFilename
  fullName: System.Configuration.ExeConfigurationFileMap.RoamingUserConfigFilename
- uid: System.Configuration.ExeConfigurationFileMap.#ctor*
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: ExeConfigurationFileMap
  nameWithType: ExeConfigurationFileMap.ExeConfigurationFileMap
- uid: System.Configuration.ExeConfigurationFileMap.Clone*
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: Clone
  nameWithType: ExeConfigurationFileMap.Clone
- uid: System.Configuration.ExeConfigurationFileMap.ExeConfigFilename*
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: ExeConfigFilename
  nameWithType: ExeConfigurationFileMap.ExeConfigFilename
- uid: System.Configuration.ExeConfigurationFileMap.LocalUserConfigFilename*
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: LocalUserConfigFilename
  nameWithType: ExeConfigurationFileMap.LocalUserConfigFilename
- uid: System.Configuration.ExeConfigurationFileMap.RoamingUserConfigFilename*
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: RoamingUserConfigFilename
  nameWithType: ExeConfigurationFileMap.RoamingUserConfigFilename
