### YamlMime:ManagedReference
items:
- uid: System.Configuration.ProtectedConfigurationProviderCollection
  id: ProtectedConfigurationProviderCollection
  children:
  - System.Configuration.ProtectedConfigurationProviderCollection.#ctor
  - System.Configuration.ProtectedConfigurationProviderCollection.Add(System.Configuration.Provider.ProviderBase)
  - System.Configuration.ProtectedConfigurationProviderCollection.Item(System.String)
  langs:
  - csharp
  name: ProtectedConfigurationProviderCollection
  nameWithType: ProtectedConfigurationProviderCollection
  fullName: System.Configuration.ProtectedConfigurationProviderCollection
  type: Class
  summary: "Fornece uma coleção de <xref href=&quot;System.Configuration.ProtectedConfigurationProvider&quot;> </xref> objetos."
  remarks: "O <xref:System.Configuration.ProtectedConfiguration.Providers%2A>propriedade o <xref:System.Configuration.ProtectedConfiguration>classe é uma coleção de ProtectedConfigurationProviderCollection de todos os provedores de configuração protegida disponíveis para seu aplicativo.</xref:System.Configuration.ProtectedConfiguration> </xref:System.Configuration.ProtectedConfiguration.Providers%2A>       Você pode criptografar seções de um arquivo de configuração para proteger informações confidenciais usadas pelo seu aplicativo. Isso melhora a segurança, dificultando o acesso não autorizado, mesmo se um invasor obtiver acesso ao seu arquivo de configuração.       O .NET Framework inclui dois provedores de configuração protegida que podem ser usados para criptografar as seções de um arquivo de configuração: o <xref:System.Configuration.RsaProtectedConfigurationProvider>de classe, que usa o <xref:System.Security.Cryptography.RSACryptoServiceProvider>classe para criptografar as seções de configuração e o <xref:System.Configuration.DpapiProtectedConfigurationProvider>classe, que usa a API de proteção de dados Windows (DPAPI) para criptografar as seções de configuração.</xref:System.Configuration.DpapiProtectedConfigurationProvider> </xref:System.Security.Cryptography.RSACryptoServiceProvider> </xref:System.Configuration.RsaProtectedConfigurationProvider>       Você pode ter um requisito para criptografar informações confidenciais usando um algoritmo que não sejam os provedores de RSA ou DPAPI. Nesse caso, você pode criar seu próprio provedor de configuração protegida personalizado. O <xref:System.Configuration.ProtectedConfigurationProvider>classe é uma classe base abstrata que você deve herdar de criar seu próprio provedor de configuração protegida.</xref:System.Configuration.ProtectedConfigurationProvider>       Para obter mais informações sobre configuração protegida, consulte [Criptografando informações de configuração usando configuração protegida](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: 'public class ProtectedConfigurationProviderCollection : System.Configuration.Provider.ProviderCollection'
  inheritance:
  - System.Object
  - System.Configuration.Provider.ProviderCollection
  implements: []
  inheritedMembers:
  - System.Configuration.Provider.ProviderCollection.Clear
  - System.Configuration.Provider.ProviderCollection.CopyTo(System.Configuration.Provider.ProviderBase[],System.Int32)
  - System.Configuration.Provider.ProviderCollection.Count
  - System.Configuration.Provider.ProviderCollection.GetEnumerator
  - System.Configuration.Provider.ProviderCollection.IsSynchronized
  - System.Configuration.Provider.ProviderCollection.Remove(System.String)
  - System.Configuration.Provider.ProviderCollection.SetReadOnly
  - System.Configuration.Provider.ProviderCollection.SyncRoot
  - System.Configuration.Provider.ProviderCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  platform:
  - net462
- uid: System.Configuration.ProtectedConfigurationProviderCollection.#ctor
  id: '#ctor'
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  langs:
  - csharp
  name: ProtectedConfigurationProviderCollection()
  nameWithType: ProtectedConfigurationProviderCollection.ProtectedConfigurationProviderCollection()
  fullName: System.Configuration.ProtectedConfigurationProviderCollection.ProtectedConfigurationProviderCollection()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Configuration.ProtectedConfigurationProviderCollection&quot;> </xref> classe usando as configurações padrão."
  remarks: "O construtor ProtectedConfigurationProviderCollection não se destina a ser usado diretamente no seu código. Ele é chamado pelo sistema de configuração do ASP.NET. Obter uma instância da <xref:System.Configuration.ProtectedConfigurationProviderCollection>classe usando a <xref:System.Configuration.ProtectedConfiguration.Providers%2A>propriedade de <xref:System.Configuration.ProtectedConfiguration>classe.</xref:System.Configuration.ProtectedConfiguration> </xref:System.Configuration.ProtectedConfiguration.Providers%2A> </xref:System.Configuration.ProtectedConfigurationProviderCollection>"
  syntax:
    content: public ProtectedConfigurationProviderCollection ();
    parameters: []
  overload: System.Configuration.ProtectedConfigurationProviderCollection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ProtectedConfigurationProviderCollection.Add(System.Configuration.Provider.ProviderBase)
  id: Add(System.Configuration.Provider.ProviderBase)
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  langs:
  - csharp
  name: Add(ProviderBase)
  nameWithType: ProtectedConfigurationProviderCollection.Add(ProviderBase)
  fullName: System.Configuration.ProtectedConfigurationProviderCollection.Add(ProviderBase)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Adiciona um <xref href=&quot;System.Configuration.ProtectedConfigurationProvider&quot;> </xref> objeto à coleção."
  syntax:
    content: public override void Add (System.Configuration.Provider.ProviderBase provider);
    parameters:
    - id: provider
      type: System.Configuration.Provider.ProviderBase
      description: "Um <xref href=&quot;System.Configuration.ProtectedConfigurationProvider&quot;> </xref> objeto a ser adicionado à coleção."
  overload: System.Configuration.ProtectedConfigurationProviderCollection.Add*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>provider</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "<code>provider</code>não é um <xref href=&quot;System.Configuration.ProtectedConfigurationProvider&quot;> </xref> objeto."
  - type: System.Configuration.ConfigurationException
    commentId: T:System.Configuration.ConfigurationException
    description: "The <xref href=\"System.Configuration.ProtectedConfigurationProvider\"></xref> object to add already exists in the collection.  \n  \n \\- or -  \n  \n The collection is read-only."
  platform:
  - net462
- uid: System.Configuration.ProtectedConfigurationProviderCollection.Item(System.String)
  id: Item(System.String)
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  langs:
  - csharp
  name: Item(String)
  nameWithType: ProtectedConfigurationProviderCollection.Item(String)
  fullName: System.Configuration.ProtectedConfigurationProviderCollection.Item(String)
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Obtém um <xref href=&quot;System.Configuration.ProtectedConfigurationProvider&quot;> </xref> objeto na coleção com o nome especificado."
  syntax:
    content: public System.Configuration.ProtectedConfigurationProvider this[string name] { get; }
    parameters:
    - id: name
      type: System.String
      description: "O nome de um <xref href=&quot;System.Configuration.ProtectedConfigurationProvider&quot;> </xref> objeto na coleção."
    return:
      type: System.Configuration.ProtectedConfigurationProvider
      description: "O <xref href=&quot;System.Configuration.ProtectedConfigurationProvider&quot;> </xref> objeto com o nome especificado, ou <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> se não houver nenhum objeto com esse nome."
  overload: System.Configuration.ProtectedConfigurationProviderCollection.Item*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: System.Configuration.Provider.ProviderCollection
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Configuration.ConfigurationException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationException
  nameWithType: ConfigurationException
  fullName: System.Configuration.ConfigurationException
- uid: System.Configuration.ProtectedConfigurationProviderCollection.#ctor
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  isExternal: false
  name: ProtectedConfigurationProviderCollection()
  nameWithType: ProtectedConfigurationProviderCollection.ProtectedConfigurationProviderCollection()
  fullName: System.Configuration.ProtectedConfigurationProviderCollection.ProtectedConfigurationProviderCollection()
- uid: System.Configuration.ProtectedConfigurationProviderCollection.Add(System.Configuration.Provider.ProviderBase)
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  isExternal: false
  name: Add(ProviderBase)
  nameWithType: ProtectedConfigurationProviderCollection.Add(ProviderBase)
  fullName: System.Configuration.ProtectedConfigurationProviderCollection.Add(ProviderBase)
- uid: System.Configuration.Provider.ProviderBase
  parent: System.Configuration.Provider
  isExternal: false
  name: ProviderBase
  nameWithType: ProviderBase
  fullName: System.Configuration.Provider.ProviderBase
- uid: System.Configuration.ProtectedConfigurationProviderCollection.Item(System.String)
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  isExternal: false
  name: Item(String)
  nameWithType: ProtectedConfigurationProviderCollection.Item(String)
  fullName: System.Configuration.ProtectedConfigurationProviderCollection.Item(String)
- uid: System.Configuration.ProtectedConfigurationProvider
  parent: System.Configuration
  isExternal: false
  name: ProtectedConfigurationProvider
  nameWithType: ProtectedConfigurationProvider
  fullName: System.Configuration.ProtectedConfigurationProvider
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ProtectedConfigurationProviderCollection.#ctor*
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  isExternal: false
  name: ProtectedConfigurationProviderCollection
  nameWithType: ProtectedConfigurationProviderCollection.ProtectedConfigurationProviderCollection
- uid: System.Configuration.ProtectedConfigurationProviderCollection.Add*
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  isExternal: false
  name: Add
  nameWithType: ProtectedConfigurationProviderCollection.Add
- uid: System.Configuration.ProtectedConfigurationProviderCollection.Item*
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  isExternal: false
  name: Item
  nameWithType: ProtectedConfigurationProviderCollection.Item
