### YamlMime:ManagedReference
items:
- uid: System.Activities.XamlIntegration.IValueSerializableExpression
  id: IValueSerializableExpression
  children:
  - System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString(System.Windows.Markup.IValueSerializerContext)
  - System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString(System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: IValueSerializableExpression
  nameWithType: IValueSerializableExpression
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression
  type: Interface
  summary: "Fornece métodos para converter expressões em cadeias de caracteres."
  remarks: "Os autores de atividades de expressão que desejam oferecer uma forma abreviada textual de expressões as atividades devem implementar essa interface."
  syntax:
    content: public interface IValueSerializableExpression
  implements: []
  platform:
  - net462
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString(System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  langs:
  - csharp
  name: CanConvertToString(IValueSerializerContext)
  nameWithType: IValueSerializableExpression.CanConvertToString(IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString(IValueSerializerContext)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: "Determina se a expressão pode ser convertida em uma cadeia de caracteres."
  syntax:
    content: public bool CanConvertToString (System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Informações de contexto que são usadas para conversão."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se a expressão pode ser convertida em uma cadeia de caracteres; Caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString(System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  langs:
  - csharp
  name: ConvertToString(IValueSerializerContext)
  nameWithType: IValueSerializableExpression.ConvertToString(IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString(IValueSerializerContext)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: "Converte uma expressão em uma cadeia de caracteres."
  syntax:
    content: public string ConvertToString (System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Informações de contexto que são usadas para conversão."
    return:
      type: System.String
      description: "Uma representação de cadeia de caracteres da expressão."
  overload: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString(System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  isExternal: false
  name: CanConvertToString(IValueSerializerContext)
  nameWithType: IValueSerializableExpression.CanConvertToString(IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString(IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString(System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  isExternal: false
  name: ConvertToString(IValueSerializerContext)
  nameWithType: IValueSerializableExpression.ConvertToString(IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString(IValueSerializerContext)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString*
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  isExternal: false
  name: CanConvertToString
  nameWithType: IValueSerializableExpression.CanConvertToString
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString*
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  isExternal: false
  name: ConvertToString
  nameWithType: IValueSerializableExpression.ConvertToString
