### YamlMime:ManagedReference
items:
- uid: System.Web.Hosting.IApplicationPreloadManager
  id: IApplicationPreloadManager
  children:
  - System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState(System.String,System.String,System.Boolean)
  - System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil(System.Web.Hosting.IApplicationPreloadUtil)
  langs:
  - csharp
  name: IApplicationPreloadManager
  nameWithType: IApplicationPreloadManager
  fullName: System.Web.Hosting.IApplicationPreloadManager
  type: Interface
  summary: "Fornece métodos que o ASP.NET usa para invocar o recurso de pré-carregamento do aplicativo em [!INCLUDE[iisver](~/add/includes/ajax-current-ext-md.md)]."
  syntax:
    content: >-
      [System.Runtime.InteropServices.Guid("AE54F424-71BC-4da5-AA2F-8C0CD53496FC")]

      [System.Runtime.InteropServices.InterfaceType(System.Runtime.InteropServices.ComInterfaceType.InterfaceIsIUnknown)]

      public interface IApplicationPreloadManager
  implements: []
  platform:
  - net462
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState(System.String,System.String,System.Boolean)
  id: SetApplicationPreloadState(System.String,System.String,System.Boolean)
  parent: System.Web.Hosting.IApplicationPreloadManager
  langs:
  - csharp
  name: SetApplicationPreloadState(String,String,Boolean)
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadState(String,String,Boolean)
  fullName: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState(String,String,Boolean)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Chamado por [!INCLUDE[iisver](~/add/includes/ajax-current-ext-md.md)] para notificar o ASP.NET se um aplicativo deve ser pré-carregados."
  syntax:
    content: public void SetApplicationPreloadState (string context, string appId, bool enabled);
    parameters:
    - id: context
      type: System.String
      description: "O contexto do aplicativo."
    - id: appId
      type: System.String
      description: "A ID exclusiva do aplicativo."
    - id: enabled
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>para indicar que o aplicativo deve ser pré-carregada; Caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil(System.Web.Hosting.IApplicationPreloadUtil)
  id: SetApplicationPreloadUtil(System.Web.Hosting.IApplicationPreloadUtil)
  parent: System.Web.Hosting.IApplicationPreloadManager
  langs:
  - csharp
  name: SetApplicationPreloadUtil(IApplicationPreloadUtil)
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadUtil(IApplicationPreloadUtil)
  fullName: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil(IApplicationPreloadUtil)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Chamadas [!INCLUDE[iisver](~/add/includes/ajax-current-ext-md.md)] para obter as informações necessárias para pré-carregar um aplicativo."
  remarks: "O IIS chama ASP.NET por meio dessa interface, fornecendo uma referência a um objeto que implementa o <xref:System.Web.Hosting.IApplicationPreloadUtil>interface.</xref:System.Web.Hosting.IApplicationPreloadUtil> O ASP.NET usa essa interface posteriormente para executar um retorno de chamada no IIS para obter informações de pré-carregamento de aplicativos individuais."
  syntax:
    content: public void SetApplicationPreloadUtil (System.Web.Hosting.IApplicationPreloadUtil preloadUtil);
    parameters:
    - id: preloadUtil
      type: System.Web.Hosting.IApplicationPreloadUtil
      description: "O identificador para uma interface não gerenciado em [!INCLUDE[iisver](~/add/includes/ajax-current-ext-md.md)] que o ASP.NET chamadas para obter informações."
  overload: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState(System.String,System.String,System.Boolean)
  parent: System.Web.Hosting.IApplicationPreloadManager
  isExternal: false
  name: SetApplicationPreloadState(String,String,Boolean)
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadState(String,String,Boolean)
  fullName: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState(String,String,Boolean)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil(System.Web.Hosting.IApplicationPreloadUtil)
  parent: System.Web.Hosting.IApplicationPreloadManager
  isExternal: false
  name: SetApplicationPreloadUtil(IApplicationPreloadUtil)
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadUtil(IApplicationPreloadUtil)
  fullName: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil(IApplicationPreloadUtil)
- uid: System.Web.Hosting.IApplicationPreloadUtil
  parent: System.Web.Hosting
  isExternal: false
  name: IApplicationPreloadUtil
  nameWithType: IApplicationPreloadUtil
  fullName: System.Web.Hosting.IApplicationPreloadUtil
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState*
  parent: System.Web.Hosting.IApplicationPreloadManager
  isExternal: false
  name: SetApplicationPreloadState
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadState
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil*
  parent: System.Web.Hosting.IApplicationPreloadManager
  isExternal: false
  name: SetApplicationPreloadUtil
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadUtil
