### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Channels.IReceiveContextSettings
  id: IReceiveContextSettings
  children:
  - System.ServiceModel.Channels.IReceiveContextSettings.Enabled
  - System.ServiceModel.Channels.IReceiveContextSettings.ValidityDuration
  langs:
  - csharp
  name: IReceiveContextSettings
  nameWithType: IReceiveContextSettings
  fullName: System.ServiceModel.Channels.IReceiveContextSettings
  type: Interface
  summary: "Uma interface que permite que você defina receber configurações de contexto."
  remarks: "Receber contexto permite confirmação controlada ao usar um canal de mensagem unidirecional e leituras não destrutiva ao usar um canal em fila."
  syntax:
    content: public interface IReceiveContextSettings
  implements: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.IReceiveContextSettings.Enabled
  id: Enabled
  parent: System.ServiceModel.Channels.IReceiveContextSettings
  langs:
  - csharp
  name: Enabled
  nameWithType: IReceiveContextSettings.Enabled
  fullName: System.ServiceModel.Channels.IReceiveContextSettings.Enabled
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Obtém ou define um valor que especifica se receber contexto está habilitado."
  syntax:
    content: public bool Enabled { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se receber contexto estiver habilitado; Caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Channels.IReceiveContextSettings.Enabled*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.IReceiveContextSettings.ValidityDuration
  id: ValidityDuration
  parent: System.ServiceModel.Channels.IReceiveContextSettings
  langs:
  - csharp
  name: ValidityDuration
  nameWithType: IReceiveContextSettings.ValidityDuration
  fullName: System.ServiceModel.Channels.IReceiveContextSettings.ValidityDuration
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Obtém um valor que especifica um tempo limite de conexão quando usado com canais diretos e duração de bloqueio de mensagem quando usado com canais na fila."
  remarks: >-
    > [!IMPORTANT]

    >  If ValidityDurationexpires for a message, any transaction that may be used for its processing, will be aborted along with the workflow instance if the expiration occurs during the transaction.
  syntax:
    content: public TimeSpan ValidityDuration { get; }
    return:
      type: System.TimeSpan
      description: "Um valor de tempo limite."
  overload: System.ServiceModel.Channels.IReceiveContextSettings.ValidityDuration*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Channels.IReceiveContextSettings.Enabled
  parent: System.ServiceModel.Channels.IReceiveContextSettings
  isExternal: false
  name: Enabled
  nameWithType: IReceiveContextSettings.Enabled
  fullName: System.ServiceModel.Channels.IReceiveContextSettings.Enabled
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Channels.IReceiveContextSettings.ValidityDuration
  parent: System.ServiceModel.Channels.IReceiveContextSettings
  isExternal: false
  name: ValidityDuration
  nameWithType: IReceiveContextSettings.ValidityDuration
  fullName: System.ServiceModel.Channels.IReceiveContextSettings.ValidityDuration
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Channels.IReceiveContextSettings.Enabled*
  parent: System.ServiceModel.Channels.IReceiveContextSettings
  isExternal: false
  name: Enabled
  nameWithType: IReceiveContextSettings.Enabled
- uid: System.ServiceModel.Channels.IReceiveContextSettings.ValidityDuration*
  parent: System.ServiceModel.Channels.IReceiveContextSettings
  isExternal: false
  name: ValidityDuration
  nameWithType: IReceiveContextSettings.ValidityDuration
