### YamlMime:ManagedReference
items:
- uid: System.Configuration.LongValidatorAttribute
  id: LongValidatorAttribute
  children:
  - System.Configuration.LongValidatorAttribute.#ctor
  - System.Configuration.LongValidatorAttribute.ExcludeRange
  - System.Configuration.LongValidatorAttribute.MaxValue
  - System.Configuration.LongValidatorAttribute.MinValue
  - System.Configuration.LongValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: LongValidatorAttribute
  nameWithType: LongValidatorAttribute
  fullName: System.Configuration.LongValidatorAttribute
  type: Class
  summary: "Declarativamente instrui o .NET Framework para executar a validação de inteiros longos em uma propriedade de configuração. Essa classe não pode ser herdada."
  remarks: "Você pode usar o atributo LongValidatorAttribute para decorar uma propriedade de configuração. Isso é para instruir o .NET Framework para validar a propriedade usando um <xref:System.Configuration.LongValidator>de objeto e passá-lo para o valor dos parâmetros de decoração.</xref:System.Configuration.LongValidator>       Você pode aplicar o atributo LongValidatorAttribute para somente os tipos de propriedade."
  example:
  - "The following example shows how to decorate the properties of a custom <xref:System.Configuration.ConfigurationSection> object using the LongValidatorAttribute attribute.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/visualbasic/t-system.configuration.l_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/csharp/t-system.configuration.l_0_1.cs)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class LongValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net462
- uid: System.Configuration.LongValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.LongValidatorAttribute
  langs:
  - csharp
  name: LongValidatorAttribute()
  nameWithType: LongValidatorAttribute.LongValidatorAttribute()
  fullName: System.Configuration.LongValidatorAttribute.LongValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Configuration.LongValidatorAttribute&quot;> </xref> classe."
  remarks: "Você pode usar este construtor no modelo atribuído para garantir que o valor atribuído à propriedade relacionada é um inteiro longo."
  syntax:
    content: public LongValidatorAttribute ();
    parameters: []
  overload: System.Configuration.LongValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.LongValidatorAttribute.ExcludeRange
  id: ExcludeRange
  parent: System.Configuration.LongValidatorAttribute
  langs:
  - csharp
  name: ExcludeRange
  nameWithType: LongValidatorAttribute.ExcludeRange
  fullName: System.Configuration.LongValidatorAttribute.ExcludeRange
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Obtém ou define um valor que indica se deve incluir ou excluir os inteiros no intervalo definido pelo <> </> *> e <> </> *> valores de propriedade."
  remarks: "O intervalo é inclusivo do <xref:System.Configuration.LongValidatorAttribute.MinValue%2A>e <xref:System.Configuration.LongValidatorAttribute.MaxValue%2A>valores de propriedade.</xref:System.Configuration.LongValidatorAttribute.MaxValue%2A> </xref:System.Configuration.LongValidatorAttribute.MinValue%2A> Quando o valor da propriedade ExcludeRange é `false`, os valores permitidos estão fora do intervalo."
  example:
  - "The following example shows how to use the <xref:System.Configuration.IntegerValidatorAttribute.ExcludeRange%2A> property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/visualbasic/p-system.configuration.l_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/csharp/p-system.configuration.l_0_1.cs)]"
  syntax:
    content: public bool ExcludeRange { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se o valor deve ser excluído; Caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. O padrão é <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.LongValidatorAttribute.ExcludeRange*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.LongValidatorAttribute.MaxValue
  id: MaxValue
  parent: System.Configuration.LongValidatorAttribute
  langs:
  - csharp
  name: MaxValue
  nameWithType: LongValidatorAttribute.MaxValue
  fullName: System.Configuration.LongValidatorAttribute.MaxValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Obtém ou define o valor máximo permitido para a propriedade."
  remarks: "O valor da propriedade MaxValue está incluído no intervalo permitido."
  example:
  - "The following example shows how to use the MaxValue property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/visualbasic/p-system.configuration.l_1_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/csharp/p-system.configuration.l_1_1.cs)]"
  syntax:
    content: public long MaxValue { get; set; }
    return:
      type: System.Int64
      description: "Um inteiro longo que indica o valor máximo permitido."
  overload: System.Configuration.LongValidatorAttribute.MaxValue*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "O valor selecionado é menor que <xref:System.Configuration.LongValidatorAttribute.MinValue*>.</xref:System.Configuration.LongValidatorAttribute.MinValue*>"
  platform:
  - net462
- uid: System.Configuration.LongValidatorAttribute.MinValue
  id: MinValue
  parent: System.Configuration.LongValidatorAttribute
  langs:
  - csharp
  name: MinValue
  nameWithType: LongValidatorAttribute.MinValue
  fullName: System.Configuration.LongValidatorAttribute.MinValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Obtém ou define o valor mínimo permitido para a propriedade."
  remarks: "O valor da propriedade MinValue está incluído no intervalo permitido."
  example:
  - "The following example shows how to use the MinValue property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/visualbasic/p-system.configuration.l_2_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/csharp/p-system.configuration.l_2_1.cs)]"
  syntax:
    content: public long MinValue { get; set; }
    return:
      type: System.Int64
      description: "Um inteiro que indica o valor mínimo permitido."
  overload: System.Configuration.LongValidatorAttribute.MinValue*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "O valor selecionado é maior do que <xref:System.Configuration.LongValidatorAttribute.MaxValue*>.</xref:System.Configuration.LongValidatorAttribute.MaxValue*>"
  platform:
  - net462
- uid: System.Configuration.LongValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.LongValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: LongValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.LongValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Obtém uma instância do <xref href=&quot;System.Configuration.LongValidator&quot;> </xref> classe."
  remarks: "Use o valor da propriedade ValidatorInstance para executar a validação da cadeia de caracteres chamando seu <xref:System.Configuration.LongValidator.Validate%2A>método.</xref:System.Configuration.LongValidator.Validate%2A>"
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "O <xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref> instância de validador."
  overload: System.Configuration.LongValidatorAttribute.ValidatorInstance*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.Configuration.LongValidatorAttribute.#ctor
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: LongValidatorAttribute()
  nameWithType: LongValidatorAttribute.LongValidatorAttribute()
  fullName: System.Configuration.LongValidatorAttribute.LongValidatorAttribute()
- uid: System.Configuration.LongValidatorAttribute.ExcludeRange
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: ExcludeRange
  nameWithType: LongValidatorAttribute.ExcludeRange
  fullName: System.Configuration.LongValidatorAttribute.ExcludeRange
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.LongValidatorAttribute.MaxValue
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: MaxValue
  nameWithType: LongValidatorAttribute.MaxValue
  fullName: System.Configuration.LongValidatorAttribute.MaxValue
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Configuration.LongValidatorAttribute.MinValue
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: MinValue
  nameWithType: LongValidatorAttribute.MinValue
  fullName: System.Configuration.LongValidatorAttribute.MinValue
- uid: System.Configuration.LongValidatorAttribute.ValidatorInstance
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: LongValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.LongValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.LongValidatorAttribute.#ctor*
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: LongValidatorAttribute
  nameWithType: LongValidatorAttribute.LongValidatorAttribute
- uid: System.Configuration.LongValidatorAttribute.ExcludeRange*
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: ExcludeRange
  nameWithType: LongValidatorAttribute.ExcludeRange
- uid: System.Configuration.LongValidatorAttribute.MaxValue*
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: MaxValue
  nameWithType: LongValidatorAttribute.MaxValue
- uid: System.Configuration.LongValidatorAttribute.MinValue*
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: MinValue
  nameWithType: LongValidatorAttribute.MinValue
- uid: System.Configuration.LongValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: LongValidatorAttribute.ValidatorInstance
