### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.Converter
  id: Converter
  children:
  - System.Web.Configuration.Converter.#ctor
  - System.Web.Configuration.Converter.Name
  - System.Web.Configuration.Converter.Properties
  - System.Web.Configuration.Converter.Type
  langs:
  - csharp
  name: Converter
  nameWithType: Converter
  fullName: System.Web.Configuration.Converter
  type: Class
  summary: "Representa um elemento de configuração em um arquivo de configuração."
  remarks: "A classe de conversor permite acessar e modificar as configurações relacionadas a conversores que são usados por aplicativos habilitados para AJAX ASP.NET de forma programática.       Para criar a funcionalidade de conversão personalizada, você pode criar uma classe que herda da <xref:System.Web.Script.Serialization.JavaScriptConverter>classe</xref:System.Web.Script.Serialization.JavaScriptConverter> de Depois que o conversor tiver sido criado, você pode registrá-lo para uso no arquivo de configuração do seu aplicativo Web."
  example:
  - "The following configuration file excerpt shows how to declaratively specify values for properties of the Converter class.  \n  \n```  \n<system.web.extensions>  \n  <scripting>  \n    <webServices>  \n      <jsonSerialization>  \n        <converters>  \n          <add name=\"ConvertMe\" type=\"Acme.SubAcme.ConvertMeTypeConverter\" />  \n        </converters>  \n      </jsonSerialization>  \n    </webServices>  \n  </scripting>  \n</system.web.extensions>  \n```  \n  \n The following example demonstrates how to access Converter programmatically.  \n  \n [!code-cs[System.Web.Configuration#3](~/add/codesnippet/csharp/t-system.web.configurati_34_1.cs)]\n [!code-vb[System.Web.Configuration#3](~/add/codesnippet/visualbasic/t-system.web.configurati_34_1.vb)]"
  syntax:
    content: 'public class Converter : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.Converter.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.Converter
  langs:
  - csharp
  name: Converter()
  nameWithType: Converter.Converter()
  fullName: System.Web.Configuration.Converter.Converter()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Web.Configuration.Converter&quot;> </xref> classe."
  syntax:
    content: public Converter ();
    parameters: []
  overload: System.Web.Configuration.Converter.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Converter.Name
  id: Name
  parent: System.Web.Configuration.Converter
  langs:
  - csharp
  name: Name
  nameWithType: Converter.Name
  fullName: System.Web.Configuration.Converter.Name
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Obtém ou define o identificador exclusivo para o conversor."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "O identificador exclusivo para o conversor."
  overload: System.Web.Configuration.Converter.Name*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Converter.Properties
  id: Properties
  parent: System.Web.Configuration.Converter
  langs:
  - csharp
  name: Properties
  nameWithType: Converter.Properties
  fullName: System.Web.Configuration.Converter.Properties
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Obtém uma coleção de propriedades de elemento de configuração."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;></xref> object."
  overload: System.Web.Configuration.Converter.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Converter.Type
  id: Type
  parent: System.Web.Configuration.Converter
  langs:
  - csharp
  name: Type
  nameWithType: Converter.Type
  fullName: System.Web.Configuration.Converter.Type
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Obtém ou define o nome de tipo totalmente qualificado do <xref href=&quot;System.Web.Script.Serialization.JavaScriptConverter&quot;> </xref> objeto."
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "O nome de tipo totalmente qualificado do <xref href=&quot;System.Web.Script.Serialization.JavaScriptConverter&quot;> </xref> objeto."
  overload: System.Web.Configuration.Converter.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.Converter.#ctor
  parent: System.Web.Configuration.Converter
  isExternal: false
  name: Converter()
  nameWithType: Converter.Converter()
  fullName: System.Web.Configuration.Converter.Converter()
- uid: System.Web.Configuration.Converter.Name
  parent: System.Web.Configuration.Converter
  isExternal: false
  name: Name
  nameWithType: Converter.Name
  fullName: System.Web.Configuration.Converter.Name
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.Converter.Properties
  parent: System.Web.Configuration.Converter
  isExternal: false
  name: Properties
  nameWithType: Converter.Properties
  fullName: System.Web.Configuration.Converter.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.Converter.Type
  parent: System.Web.Configuration.Converter
  isExternal: false
  name: Type
  nameWithType: Converter.Type
  fullName: System.Web.Configuration.Converter.Type
- uid: System.Web.Configuration.Converter.#ctor*
  parent: System.Web.Configuration.Converter
  isExternal: false
  name: Converter
  nameWithType: Converter.Converter
- uid: System.Web.Configuration.Converter.Name*
  parent: System.Web.Configuration.Converter
  isExternal: false
  name: Name
  nameWithType: Converter.Name
- uid: System.Web.Configuration.Converter.Properties*
  parent: System.Web.Configuration.Converter
  isExternal: false
  name: Properties
  nameWithType: Converter.Properties
- uid: System.Web.Configuration.Converter.Type*
  parent: System.Web.Configuration.Converter
  isExternal: false
  name: Type
  nameWithType: Converter.Type
