### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.IConfigErrorInfo
  id: IConfigErrorInfo
  children:
  - System.Configuration.Internal.IConfigErrorInfo.Filename
  - System.Configuration.Internal.IConfigErrorInfo.LineNumber
  langs:
  - csharp
  name: IConfigErrorInfo
  nameWithType: IConfigErrorInfo
  fullName: System.Configuration.Internal.IConfigErrorInfo
  type: Interface
  summary: "Define uma interface usada pelo .NET Framework para oferecer suporte a registros de configuração de erros de criação."
  syntax:
    content: public interface IConfigErrorInfo
  implements: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigErrorInfo.Filename
  id: Filename
  parent: System.Configuration.Internal.IConfigErrorInfo
  langs:
  - csharp
  name: Filename
  nameWithType: IConfigErrorInfo.Filename
  fullName: System.Configuration.Internal.IConfigErrorInfo.Filename
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Obtém uma cadeia de caracteres especificando o nome do arquivo relacionado para os detalhes de configuração."
  syntax:
    content: public string Filename { get; }
    return:
      type: System.String
      description: "Uma cadeia de caracteres especificando um nome de arquivo."
  overload: System.Configuration.Internal.IConfigErrorInfo.Filename*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigErrorInfo.LineNumber
  id: LineNumber
  parent: System.Configuration.Internal.IConfigErrorInfo
  langs:
  - csharp
  name: LineNumber
  nameWithType: IConfigErrorInfo.LineNumber
  fullName: System.Configuration.Internal.IConfigErrorInfo.LineNumber
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Obtém um inteiro que especifica o número de linha relacionado aos detalhes de configuração."
  syntax:
    content: public int LineNumber { get; }
    return:
      type: System.Int32
      description: "Um inteiro que especifica um número de linha."
  overload: System.Configuration.Internal.IConfigErrorInfo.LineNumber*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.Internal.IConfigErrorInfo.Filename
  parent: System.Configuration.Internal.IConfigErrorInfo
  isExternal: false
  name: Filename
  nameWithType: IConfigErrorInfo.Filename
  fullName: System.Configuration.Internal.IConfigErrorInfo.Filename
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IConfigErrorInfo.LineNumber
  parent: System.Configuration.Internal.IConfigErrorInfo
  isExternal: false
  name: LineNumber
  nameWithType: IConfigErrorInfo.LineNumber
  fullName: System.Configuration.Internal.IConfigErrorInfo.LineNumber
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.Internal.IConfigErrorInfo.Filename*
  parent: System.Configuration.Internal.IConfigErrorInfo
  isExternal: false
  name: Filename
  nameWithType: IConfigErrorInfo.Filename
- uid: System.Configuration.Internal.IConfigErrorInfo.LineNumber*
  parent: System.Configuration.Internal.IConfigErrorInfo
  isExternal: false
  name: LineNumber
  nameWithType: IConfigErrorInfo.LineNumber
