### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.SystemWebCachingSectionGroup
  id: SystemWebCachingSectionGroup
  children:
  - System.Web.Configuration.SystemWebCachingSectionGroup.#ctor
  - System.Web.Configuration.SystemWebCachingSectionGroup.Cache
  - System.Web.Configuration.SystemWebCachingSectionGroup.OutputCache
  - System.Web.Configuration.SystemWebCachingSectionGroup.OutputCacheSettings
  - System.Web.Configuration.SystemWebCachingSectionGroup.SqlCacheDependency
  langs:
  - csharp
  name: SystemWebCachingSectionGroup
  nameWithType: SystemWebCachingSectionGroup
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup
  type: Class
  summary: "Configura o <xref uid=&quot;langword_csharp_caching&quot; name=&quot;caching&quot; href=&quot;&quot;> </xref> grupo dentro de um arquivo de configuração. Essa classe não pode ser herdada."
  remarks: "A classe SystemWebCachingSectionGroup fornece uma maneira de acessar e modificar programaticamente o `caching` seção de um arquivo de configuração.       A classe SystemWebCachingSectionGroup e o `caching` seção fornece controle centralizado do mecanismo de cache para um site ou aplicativo. Isso torna possível para o cache para ser implantado, modificado e desabilitado sem modificar páginas individuais no aplicativo.       O mecanismo de cache do ASP.NET é implementado pela <xref:System.Web.Caching.Cache>classe.</xref:System.Web.Caching.Cache> Para obter mais informações, consulte [visão geral de cache ASP.NET](~/add/includes/ajax-current-ext-md.md) a lista a seguir descreve os dois tipos de cache ASP.NET fornece.      -O primeiro é chamado de cache de saída, que permite que você armazene página dinâmica e respostas de controle de usuário. Em solicitações subsequentes, o código de controle de página ou o usuário não seja executado; a saída do cache é usada para atender à solicitação. Você pode acessar as configurações de cache de saída usando o <xref:System.Web.Configuration.SystemWebCachingSectionGroup.OutputCache%2A>e <xref:System.Web.Configuration.SystemWebCachingSectionGroup.OutputCacheSettings%2A>Propriedades.</xref:System.Web.Configuration.SystemWebCachingSectionGroup.OutputCacheSettings%2A> </xref:System.Web.Configuration.SystemWebCachingSectionGroup.OutputCache%2A>      -O segundo tipo de armazenamento em cache é um aplicativo tradicional cache de dados, que pode ser usado para armazenar programaticamente objetos arbitrários à memória do servidor para que seu aplicativo pode economizar o tempo e recursos que leva para recriá-los. Você pode acessar essas configurações de cache usando o <xref:System.Web.Configuration.SystemWebCachingSectionGroup.Cache%2A>propriedade.</xref:System.Web.Configuration.SystemWebCachingSectionGroup.Cache%2A>"
  example:
  - "The following code example shows how to obtain the SystemWebCachingSectionGroup object from the configuration file associated with an existing Web application. You can use this object to access the sections contained in the `caching` group.  \n  \n [!code-cs[System.Web.Configuration.SystemWebCachingSectionGroup#1](~/add/codesnippet/csharp/t-system.web.configurati_82_1.cs)]\n [!code-vb[System.Web.Configuration.SystemWebCachingSectionGroup#1](~/add/codesnippet/visualbasic/t-system.web.configurati_82_1.vb)]"
  syntax:
    content: 'public sealed class SystemWebCachingSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  platform:
  - net462
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  langs:
  - csharp
  name: SystemWebCachingSectionGroup()
  nameWithType: SystemWebCachingSectionGroup.SystemWebCachingSectionGroup()
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.SystemWebCachingSectionGroup()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Cria uma nova instância da <xref href=&quot;System.Web.Configuration.SystemWebCachingSectionGroup&quot;> </xref>."
  remarks: "O construtor SystemWebCachingSectionGroup não se destina a ser usado diretamente no seu código. Ele é chamado pelo sistema de configuração do ASP.NET. Obter uma instância de <xref:System.Web.Configuration.SystemWebCachingSectionGroup>classe usando o <xref:System.Configuration.Configuration.GetSection%2A>método.</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.SystemWebCachingSectionGroup>"
  syntax:
    content: public SystemWebCachingSectionGroup ();
    parameters: []
  overload: System.Web.Configuration.SystemWebCachingSectionGroup.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.Cache
  id: Cache
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  langs:
  - csharp
  name: Cache
  nameWithType: SystemWebCachingSectionGroup.Cache
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.Cache
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Obtém o <xref uid=&quot;langword_csharp_cache&quot; name=&quot;cache&quot; href=&quot;&quot;> </xref> seção contida dentro da configuração."
  remarks: "O <xref:System.Web.Configuration.CacheSection>objeto se refere a `cache` seção do arquivo de configuração.</xref:System.Web.Configuration.CacheSection> Você pode usar o <xref:System.Web.Configuration.CacheSection>classe para modificar o `cache` seção programaticamente.</xref:System.Web.Configuration.CacheSection>"
  example:
  - "The following code example shows how to obtain the <xref:System.Web.Configuration.CacheSection> object from the configuration file of an existing Web application.  \n  \n [!code-cs[System.Web.Configuration.SystemWebCachingSectionGroup#2](~/add/codesnippet/csharp/p-system.web.configurati_388_1.cs)]\n [!code-vb[System.Web.Configuration.SystemWebCachingSectionGroup#2](~/add/codesnippet/visualbasic/p-system.web.configurati_388_1.vb)]"
  syntax:
    content: public System.Web.Configuration.CacheSection Cache { get; }
    return:
      type: System.Web.Configuration.CacheSection
      description: "O <xref href=&quot;System.Web.Configuration.CacheSection&quot;> </xref> objeto."
  overload: System.Web.Configuration.SystemWebCachingSectionGroup.Cache*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCache
  id: OutputCache
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  langs:
  - csharp
  name: OutputCache
  nameWithType: SystemWebCachingSectionGroup.OutputCache
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCache
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Obtém o <xref uid=&quot;langword_csharp_outputCache&quot; name=&quot;outputCache&quot; href=&quot;&quot;> </xref> seção contida dentro da configuração."
  remarks: "O <xref:System.Web.Configuration.OutputCacheSection>objeto se refere a `outputCache` seção do arquivo de configuração.</xref:System.Web.Configuration.OutputCacheSection>"
  example:
  - "The following code example shows how to obtain the <xref:System.Web.Configuration.OutputCacheSection> object from the configuration file of an existing Web application.  \n  \n [!code-cs[System.Web.Configuration.SystemWebCachingSectionGroup#3](~/add/codesnippet/csharp/p-system.web.configurati_104_1.cs)]\n [!code-vb[System.Web.Configuration.SystemWebCachingSectionGroup#3](~/add/codesnippet/visualbasic/p-system.web.configurati_104_1.vb)]"
  syntax:
    content: public System.Web.Configuration.OutputCacheSection OutputCache { get; }
    return:
      type: System.Web.Configuration.OutputCacheSection
      description: "O <xref href=&quot;System.Web.Configuration.OutputCacheSection&quot;> </xref> objeto."
  overload: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCache*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCacheSettings
  id: OutputCacheSettings
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  langs:
  - csharp
  name: OutputCacheSettings
  nameWithType: SystemWebCachingSectionGroup.OutputCacheSettings
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCacheSettings
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Obtém o <xref uid=&quot;langword_csharp_outputCacheSettings&quot; name=&quot;outputCacheSettings&quot; href=&quot;&quot;> </xref> seção contida dentro da configuração."
  remarks: "O <xref:System.Web.Configuration.OutputCacheSettingsSection>objeto se refere a `outputCacheSettings` seção do arquivo de configuração.</xref:System.Web.Configuration.OutputCacheSettingsSection>       As configurações de cache de saída habilitar ou desabilitar o cache de saída persistente baseada em disco, definem o local para persistir os dados sejam armazenados em cache e especifique o tamanho máximo do cache por aplicativo.       O ASP.NET permite armazenar em cache várias versões de uma resposta de página declarativamente usando atributos da diretiva e programaticamente usando as propriedades e métodos para a <xref:System.Web.HttpCachePolicy>classe.</xref:System.Web.HttpCachePolicy>       Você pode obter os mesmos resultados por meio da configuração do aplicativo usando o <xref:System.Web.Configuration.OutputCacheSettingsSection>ou o <xref:System.Web.Configuration.OutputCacheProfile>tipo.</xref:System.Web.Configuration.OutputCacheProfile> </xref:System.Web.Configuration.OutputCacheSettingsSection>"
  example:
  - "The following code example shows how to obtain the <xref:System.Web.Configuration.OutputCacheSettingsSection> object from the configuration file of an existing Web application.  \n  \n [!code-cs[System.Web.Configuration.SystemWebCachingSectionGroup#4](~/add/codesnippet/csharp/p-system.web.configurati_173_1.cs)]\n [!code-vb[System.Web.Configuration.SystemWebCachingSectionGroup#4](~/add/codesnippet/visualbasic/p-system.web.configurati_173_1.vb)]"
  syntax:
    content: public System.Web.Configuration.OutputCacheSettingsSection OutputCacheSettings { get; }
    return:
      type: System.Web.Configuration.OutputCacheSettingsSection
      description: "O <xref href=&quot;System.Web.Configuration.OutputCacheSettingsSection&quot;> </xref> objeto."
  overload: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCacheSettings*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.SqlCacheDependency
  id: SqlCacheDependency
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  langs:
  - csharp
  name: SqlCacheDependency
  nameWithType: SystemWebCachingSectionGroup.SqlCacheDependency
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.SqlCacheDependency
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Obtém o <xref uid=&quot;langword_csharp_sqlCacheDependency&quot; name=&quot;sqlCacheDependency&quot; href=&quot;&quot;> </xref> seção contida dentro da configuração."
  remarks: "O <xref:System.Web.Configuration.SqlCacheDependencySection>objeto se refere a `sqlCacheDependency` seção do arquivo de configuração.</xref:System.Web.Configuration.SqlCacheDependencySection>       A dependência de cache SQL estabelece uma relação entre um item armazenado em cache de um aplicativo ASP.NET e uma tabela de banco de dados específica do SQL Server. Uma instância do <xref:System.Web.Caching.SqlCacheDependency>classe deve monitorar a tabela para que quando a tabela altera o item será removido automaticamente do cache.</xref:System.Web.Caching.SqlCacheDependency>"
  example:
  - "The following code example shows how to obtain the <xref:System.Web.Configuration.SqlCacheDependencySection> object from the configuration file of an existing Web application.  \n  \n [!code-cs[System.Web.Configuration.SystemWebCachingSectionGroup#5](~/add/codesnippet/csharp/p-system.web.configurati_8_1.cs)]\n [!code-vb[System.Web.Configuration.SystemWebCachingSectionGroup#5](~/add/codesnippet/visualbasic/p-system.web.configurati_8_1.vb)]"
  syntax:
    content: public System.Web.Configuration.SqlCacheDependencySection SqlCacheDependency { get; }
    return:
      type: System.Web.Configuration.SqlCacheDependencySection
      description: "O <xref href=&quot;System.Web.Configuration.SqlCacheDependencySection&quot;> </xref> objeto."
  overload: System.Web.Configuration.SystemWebCachingSectionGroup.SqlCacheDependency*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: System.Configuration.ConfigurationSectionGroup
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.#ctor
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: SystemWebCachingSectionGroup()
  nameWithType: SystemWebCachingSectionGroup.SystemWebCachingSectionGroup()
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.SystemWebCachingSectionGroup()
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.Cache
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: Cache
  nameWithType: SystemWebCachingSectionGroup.Cache
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.Cache
- uid: System.Web.Configuration.CacheSection
  parent: System.Web.Configuration
  isExternal: false
  name: CacheSection
  nameWithType: CacheSection
  fullName: System.Web.Configuration.CacheSection
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCache
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: OutputCache
  nameWithType: SystemWebCachingSectionGroup.OutputCache
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCache
- uid: System.Web.Configuration.OutputCacheSection
  parent: System.Web.Configuration
  isExternal: false
  name: OutputCacheSection
  nameWithType: OutputCacheSection
  fullName: System.Web.Configuration.OutputCacheSection
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCacheSettings
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: OutputCacheSettings
  nameWithType: SystemWebCachingSectionGroup.OutputCacheSettings
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCacheSettings
- uid: System.Web.Configuration.OutputCacheSettingsSection
  parent: System.Web.Configuration
  isExternal: false
  name: OutputCacheSettingsSection
  nameWithType: OutputCacheSettingsSection
  fullName: System.Web.Configuration.OutputCacheSettingsSection
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.SqlCacheDependency
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: SqlCacheDependency
  nameWithType: SystemWebCachingSectionGroup.SqlCacheDependency
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.SqlCacheDependency
- uid: System.Web.Configuration.SqlCacheDependencySection
  parent: System.Web.Configuration
  isExternal: false
  name: SqlCacheDependencySection
  nameWithType: SqlCacheDependencySection
  fullName: System.Web.Configuration.SqlCacheDependencySection
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.#ctor*
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: SystemWebCachingSectionGroup
  nameWithType: SystemWebCachingSectionGroup.SystemWebCachingSectionGroup
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.Cache*
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: Cache
  nameWithType: SystemWebCachingSectionGroup.Cache
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCache*
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: OutputCache
  nameWithType: SystemWebCachingSectionGroup.OutputCache
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCacheSettings*
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: OutputCacheSettings
  nameWithType: SystemWebCachingSectionGroup.OutputCacheSettings
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.SqlCacheDependency*
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: SqlCacheDependency
  nameWithType: SystemWebCachingSectionGroup.SqlCacheDependency
