### YamlMime:ManagedReference
items:
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  id: TimeSpanMinutesOrInfiniteConverter
  children:
  - System.Configuration.TimeSpanMinutesOrInfiniteConverter.#ctor
  - System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: TimeSpanMinutesOrInfiniteConverter
  nameWithType: TimeSpanMinutesOrInfiniteConverter
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  type: Class
  summary: "Converte um <xref:System.TimeSpan>expresso em minutos ou como um padrão de infinito tempo span.</xref:System.TimeSpan>"
  remarks: "Este tipo, como todos os outros conversor tipos de configuração, converte cadeias de caracteres encontradas no arquivo de configuração de e para as propriedades com rigidez de tipos relacionadas.       Em particular, a classe TimeSpanMinutesOrInfiniteConverter converte <xref:System.String>minutos, atribuídos a uma propriedade de configuração, a <xref:System.TimeSpan>minutos e vice-versa.</xref:System.TimeSpan> </xref:System.String> Se a propriedade de configuração tem um <xref:System.String>valor de &quot;infinito&quot;, ele converte esse valor para <xref:System.TimeSpan>e vice-versa.</xref:System.TimeSpan> </xref:System.String>       O infinito <xref:System.TimeSpan>valor é representado pelo <xref:System.TimeSpan.MaxValue>valor de enumeração.</xref:System.TimeSpan.MaxValue> </xref:System.TimeSpan>"
  example:
  - Refer to the code examples in the <xref:System.Configuration.InfiniteTimeSpanConverter> and <xref:System.Configuration.TimeSpanMinutesConverter> classes.
  syntax:
    content: 'public sealed class TimeSpanMinutesOrInfiniteConverter : System.Configuration.TimeSpanMinutesConverter'
  inheritance:
  - System.Object
  - System.ComponentModel.TypeConverter
  - System.Configuration.ConfigurationConverterBase
  - System.Configuration.TimeSpanMinutesConverter
  implements: []
  inheritedMembers:
  - System.ComponentModel.TypeConverter.CanConvertFrom(System.Type)
  - System.ComponentModel.TypeConverter.CanConvertTo(System.Type)
  - System.ComponentModel.TypeConverter.ConvertFrom(System.Object)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.String)
  - System.ComponentModel.TypeConverter.ConvertTo(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.Object)
  - System.ComponentModel.TypeConverter.CreateInstance(System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.CreateInstance(System.ComponentModel.ITypeDescriptorContext,System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.GetConvertFromException(System.Object)
  - System.ComponentModel.TypeConverter.GetConvertToException(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object,System.Attribute[])
  - System.ComponentModel.TypeConverter.GetProperties(System.Object)
  - System.ComponentModel.TypeConverter.GetPropertiesSupported
  - System.ComponentModel.TypeConverter.GetPropertiesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValues
  - System.ComponentModel.TypeConverter.GetStandardValues(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.IsValid(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.IsValid(System.Object)
  - System.ComponentModel.TypeConverter.SortProperties(System.ComponentModel.PropertyDescriptorCollection,System.String[])
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  platform:
  - net462
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.#ctor
  id: '#ctor'
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  langs:
  - csharp
  name: TimeSpanMinutesOrInfiniteConverter()
  nameWithType: TimeSpanMinutesOrInfiniteConverter.TimeSpanMinutesOrInfiniteConverter()
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter.TimeSpanMinutesOrInfiniteConverter()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Configuration.TimeSpanMinutesOrInfiniteConverter&quot;> </xref> classe."
  remarks: "Normalmente, você usa os tipos de conversor fornecidos pelo sistema. A única vez em que você precisa usar o construtor de TimeSpanMinutesOrInfiniteConverter é quando você cria seu próprio tipo de conversão."
  syntax:
    content: public TimeSpanMinutesOrInfiniteConverter ();
    parameters: []
  overload: System.Configuration.TimeSpanMinutesOrInfiniteConverter.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: TimeSpanMinutesOrInfiniteConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Converte um <xref:System.String>um <xref:System.TimeSpan>.</xref:System.TimeSpan> </xref:System.String>"
  remarks: "O sistema usa o método ConvertFrom durante a leitura de um arquivo de configuração para converter um <xref:System.String>valor <xref:System.TimeSpan>, ou o <xref:System.String>&quot;infinito&quot; para <xref:System.TimeSpan.MaxValue>.</xref:System.TimeSpan.MaxValue> </xref:System.String> </xref:System.TimeSpan> </xref:System.String>"
  example:
  - Refer to the code examples in the <xref:System.Configuration.InfiniteTimeSpanConverter> and <xref:System.Configuration.TimeSpanMinutesConverter> classes.
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object data);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "O <xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> usado para conversões de tipo de objeto."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "O <xref:System.Globalization.CultureInfo>objeto usado durante a conversão.</xref:System.Globalization.CultureInfo>"
    - id: data
      type: System.Object
      description: "O <xref:System.String>objeto converter.</xref:System.String>"
    return:
      type: System.Object
      description: "O <xref:System.TimeSpan.MaxValue>, se o <code> data </code> parâmetro é o <xref:System.String>&quot;infinito&quot;; caso contrário, o <xref:System.TimeSpan>que representa o <code> data </code> parâmetro em minutos.</xref:System.TimeSpan> </xref:System.String> </xref:System.TimeSpan.MaxValue>"
  overload: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: TimeSpanMinutesOrInfiniteConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Converte um <xref:System.TimeSpan>um <xref:System.String>.</xref:System.String> </xref:System.TimeSpan>"
  remarks: "O sistema usa o método ConvertTo ao gravar em um arquivo de configuração para converter um <xref:System.TimeSpan>valor ou <xref:System.TimeSpan.MaxValue>a <xref:System.String>.</xref:System.String> </xref:System.TimeSpan.MaxValue> </xref:System.TimeSpan>"
  example:
  - Refer to the code examples in the <xref:System.Configuration.InfiniteTimeSpanConverter> and <xref:System.Configuration.TimeSpanMinutesConverter> classes.
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object value, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "O <xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> usado para conversões de tipo de objeto."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "O <xref:System.Globalization.CultureInfo>objeto usado durante a conversão.</xref:System.Globalization.CultureInfo>"
    - id: value
      type: System.Object
      description: "O valor a converter."
    - id: type
      type: System.Type
      description: "O tipo de conversão."
    return:
      type: System.Object
      description: "O <xref:System.String>&quot;infinito&quot;, se o <code> value </code> parâmetro é <xref:System.TimeSpan.MaxValue>; caso contrário, o <xref:System.String>que representa o <code> value </code> parâmetro em minutos.</xref:System.String> </xref:System.TimeSpan.MaxValue> </xref:System.String>"
  overload: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.TimeSpanMinutesConverter
  isExternal: false
  name: System.Configuration.TimeSpanMinutesConverter
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.#ctor
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  isExternal: false
  name: TimeSpanMinutesOrInfiniteConverter()
  nameWithType: TimeSpanMinutesOrInfiniteConverter.TimeSpanMinutesOrInfiniteConverter()
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter.TimeSpanMinutesOrInfiniteConverter()
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: TimeSpanMinutesOrInfiniteConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: false
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: true
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: TimeSpanMinutesOrInfiniteConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.#ctor*
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  isExternal: false
  name: TimeSpanMinutesOrInfiniteConverter
  nameWithType: TimeSpanMinutesOrInfiniteConverter.TimeSpanMinutesOrInfiniteConverter
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom*
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  isExternal: false
  name: ConvertFrom
  nameWithType: TimeSpanMinutesOrInfiniteConverter.ConvertFrom
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo*
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  isExternal: false
  name: ConvertTo
  nameWithType: TimeSpanMinutesOrInfiniteConverter.ConvertTo
