### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement
  id: TokenReplayDetectionElement
  children:
  - System.IdentityModel.Configuration.TokenReplayDetectionElement.#ctor
  - System.IdentityModel.Configuration.TokenReplayDetectionElement.Enabled
  - System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod
  - System.IdentityModel.Configuration.TokenReplayDetectionElement.Properties
  langs:
  - csharp
  name: TokenReplayDetectionElement
  nameWithType: TokenReplayDetectionElement
  fullName: System.IdentityModel.Configuration.TokenReplayDetectionElement
  type: Class
  summary: "Representa um <xref uid=&quot;langword_csharp_&lt;tokenReplayDetection&gt;&quot; name=&quot;&lt;tokenReplayDetection&gt;&quot; href=&quot;&quot;> </xref> elemento em um arquivo de configuração. Essa classe não pode ser herdada."
  remarks: "O `<tokenReplayDetection>` elemento permite que você habilite a lógica de detecção de repetição de token. Quando habilitado, o WIF armazena em cache os tokens de segurança que foram recebidos para a autenticação e usa o cache para detecção de repetição. Um token permanece no cache até que o período de expiração especificado pelo <xref:System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod%2A>propriedade expira.</xref:System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod%2A>       O cache de reprodução de token que o WIF usa for especificado o `<caches>` elemento, que é representado pela classe TokenReplayDetectionElement. O cache de reprodução de token é configurado por meio de <xref:System.IdentityModel.Configuration.IdentityModelCachesElement.TokenReplayCache%2A>propriedade.</xref:System.IdentityModel.Configuration.IdentityModelCachesElement.TokenReplayCache%2A>"
  syntax:
    content: 'public sealed class TokenReplayDetectionElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  langs:
  - csharp
  name: TokenReplayDetectionElement()
  nameWithType: TokenReplayDetectionElement.TokenReplayDetectionElement()
  fullName: System.IdentityModel.Configuration.TokenReplayDetectionElement.TokenReplayDetectionElement()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.IdentityModel.Configuration.TokenReplayDetectionElement&quot;> </xref> classe"
  syntax:
    content: public TokenReplayDetectionElement ();
    parameters: []
  overload: System.IdentityModel.Configuration.TokenReplayDetectionElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.Enabled
  id: Enabled
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  langs:
  - csharp
  name: Enabled
  nameWithType: TokenReplayDetectionElement.Enabled
  fullName: System.IdentityModel.Configuration.TokenReplayDetectionElement.Enabled
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Obtém ou define um valor que indica se a detecção de repetição deve ser executada."
  remarks: "Essa propriedade é opcional. Representa o `enabled` atributo o `<tokenReplayDetection>` elemento."
  syntax:
    content: public bool Enabled { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>para executar a detecção de reprodução; Caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.IdentityModel.Configuration.TokenReplayDetectionElement.Enabled*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod
  id: ExpirationPeriod
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  langs:
  - csharp
  name: ExpirationPeriod
  nameWithType: TokenReplayDetectionElement.ExpirationPeriod
  fullName: System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Obtém ou define a quantidade máxima de tempo antes que um item é considerado expirado e removido do cache."
  remarks: "Essa propriedade é opcional. Representa o `expirationPeriod` atributo o `<tokenReplayDetection>` elemento."
  syntax:
    content: public TimeSpan ExpirationPeriod { get; set; }
    return:
      type: System.TimeSpan
      description: "A quantidade máxima de tempo antes que um item é considerado expirado e removido do cache."
  overload: System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.Properties
  id: Properties
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  langs:
  - csharp
  name: Properties
  nameWithType: TokenReplayDetectionElement.Properties
  fullName: System.IdentityModel.Configuration.TokenReplayDetectionElement.Properties
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A ser adicionado."
  overload: System.IdentityModel.Configuration.TokenReplayDetectionElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.#ctor
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: TokenReplayDetectionElement()
  nameWithType: TokenReplayDetectionElement.TokenReplayDetectionElement()
  fullName: System.IdentityModel.Configuration.TokenReplayDetectionElement.TokenReplayDetectionElement()
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.Enabled
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: Enabled
  nameWithType: TokenReplayDetectionElement.Enabled
  fullName: System.IdentityModel.Configuration.TokenReplayDetectionElement.Enabled
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: ExpirationPeriod
  nameWithType: TokenReplayDetectionElement.ExpirationPeriod
  fullName: System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.Properties
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: Properties
  nameWithType: TokenReplayDetectionElement.Properties
  fullName: System.IdentityModel.Configuration.TokenReplayDetectionElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.#ctor*
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: TokenReplayDetectionElement
  nameWithType: TokenReplayDetectionElement.TokenReplayDetectionElement
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.Enabled*
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: Enabled
  nameWithType: TokenReplayDetectionElement.Enabled
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod*
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: ExpirationPeriod
  nameWithType: TokenReplayDetectionElement.ExpirationPeriod
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.Properties*
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: Properties
  nameWithType: TokenReplayDetectionElement.Properties
