### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.WSFederationHttpSecurity
  id: WSFederationHttpSecurity
  children:
  - System.ServiceModel.WSFederationHttpSecurity.#ctor
  - System.ServiceModel.WSFederationHttpSecurity.Message
  - System.ServiceModel.WSFederationHttpSecurity.Mode
  - System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMessage
  - System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMode
  langs:
  - csharp
  name: WSFederationHttpSecurity
  nameWithType: WSFederationHttpSecurity
  fullName: System.ServiceModel.WSFederationHttpSecurity
  type: Class
  summary: "Especifica as configurações de segurança para o <xref href=&quot;System.ServiceModel.WSFederationHttpBinding&quot;> </xref>. Essa classe não pode ser herdada."
  remarks: "Esta classe especifica o tipo de segurança a serem aplicadas para o `wsFederationHttpBinding` de associação e as configurações de segurança específico."
  syntax:
    content: public sealed class WSFederationHttpSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.WSFederationHttpSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.WSFederationHttpSecurity
  langs:
  - csharp
  name: WSFederationHttpSecurity()
  nameWithType: WSFederationHttpSecurity.WSFederationHttpSecurity()
  fullName: System.ServiceModel.WSFederationHttpSecurity.WSFederationHttpSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Inicializa uma nova instância do <xref href=&quot;System.ServiceModel.WSFederationHttpSecurity&quot;> </xref> classe."
  syntax:
    content: public WSFederationHttpSecurity ();
    parameters: []
  overload: System.ServiceModel.WSFederationHttpSecurity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WSFederationHttpSecurity.Message
  id: Message
  parent: System.ServiceModel.WSFederationHttpSecurity
  langs:
  - csharp
  name: Message
  nameWithType: WSFederationHttpSecurity.Message
  fullName: System.ServiceModel.WSFederationHttpSecurity.Message
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Indica as configurações de segurança de mensagem para o <xref href=&quot;System.ServiceModel.WSFederationHttpBinding&quot;> </xref>."
  remarks: "O objeto retornado especifica as propriedades de segurança de nível de mensagem detalhada para o `wsFederationHttpBinding`."
  example:
  - "The following code shows how to access this property and use it to set properties of the `wsFederationHttpBinding`.  \n  \n [!code-vb[WSFederationHttpSecurity#2](~/add/codesnippet/visualbasic/p-system.servicemodel.ws_6_1.vb)]\n [!code-cs[WSFederationHttpSecurity#2](~/add/codesnippet/csharp/p-system.servicemodel.ws_6_1.cs)]"
  syntax:
    content: public System.ServiceModel.FederatedMessageSecurityOverHttp Message { get; set; }
    return:
      type: System.ServiceModel.FederatedMessageSecurityOverHttp
      description: "A <xref href=&quot;System.ServiceModel.FederatedMessageSecurityOverHttp&quot;></xref> value."
  overload: System.ServiceModel.WSFederationHttpSecurity.Message*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WSFederationHttpSecurity.Mode
  id: Mode
  parent: System.ServiceModel.WSFederationHttpSecurity
  langs:
  - csharp
  name: Mode
  nameWithType: WSFederationHttpSecurity.Mode
  fullName: System.ServiceModel.WSFederationHttpSecurity.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Obtém ou define o tipo de segurança a ser aplicado."
  remarks: "O membro de enumeração retornado especifica tipo geral de segurança a ser aplicado.       Os valores permitidos são <xref:System.ServiceModel.WSFederationHttpSecurityMode>e <xref:System.ServiceModel.WSFederationHttpSecurityMode>.</xref:System.ServiceModel.WSFederationHttpSecurityMode> </xref:System.ServiceModel.WSFederationHttpSecurityMode>       No <xref:System.ServiceModel.WSFederationHttpSecurityMode>modo de segurança, a mensagem é enviada por HTTP e segurança de mensagens SOAP é usada para proteger a mensagem.</xref:System.ServiceModel.WSFederationHttpSecurityMode> Autenticação de cliente é executada com base no token emitido obtido do serviço de token de segurança. Autenticação de servidor baseia-se no certificado do servidor.       No <xref:System.ServiceModel.WSFederationHttpSecurityMode>modo de segurança, a mensagem é enviada por HTTPS.</xref:System.ServiceModel.WSFederationHttpSecurityMode> Autenticação de cliente é executada, incluindo o token emitido obtido do serviço de token de segurança na mensagem SOAP. Autenticação de servidor, com base em certificado do servidor, é executada como parte da configuração de conexão HTTPS."
  example:
  - "The following code shows how to set this property.  \n  \n [!code-vb[WSFederationHttpSecurity#3](~/add/codesnippet/visualbasic/p-system.servicemodel.ws_5_1.vb)]\n [!code-cs[WSFederationHttpSecurity#3](~/add/codesnippet/csharp/p-system.servicemodel.ws_5_1.cs)]"
  syntax:
    content: public System.ServiceModel.WSFederationHttpSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.WSFederationHttpSecurityMode
      description: "A <xref href=&quot;System.ServiceModel.WSFederationHttpSecurityMode&quot;></xref>. O padrão é <xref href=&quot;System.ServiceModel.WSFederationHttpSecurityMode&quot;> </xref>."
  overload: System.ServiceModel.WSFederationHttpSecurity.Mode*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMessage
  id: ShouldSerializeMessage
  parent: System.ServiceModel.WSFederationHttpSecurity
  langs:
  - csharp
  name: ShouldSerializeMessage()
  nameWithType: WSFederationHttpSecurity.ShouldSerializeMessage()
  fullName: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMessage()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Retorna um valor que indica se o <xref:System.ServiceModel.WSFederationHttpSecurity.Message*>propriedade foi alterado do valor padrão e deve ser serializada.</xref:System.ServiceModel.WSFederationHttpSecurity.Message*>"
  syntax:
    content: public bool ShouldSerializeMessage ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se o <xref:System.ServiceModel.WSFederationHttpSecurity.Message*>o valor da propriedade deve ser serializado; caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.ServiceModel.WSFederationHttpSecurity.Message*>"
  overload: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMessage*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMode
  id: ShouldSerializeMode
  parent: System.ServiceModel.WSFederationHttpSecurity
  langs:
  - csharp
  name: ShouldSerializeMode()
  nameWithType: WSFederationHttpSecurity.ShouldSerializeMode()
  fullName: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMode()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Retorna um valor que indica se o <xref:System.ServiceModel.WSFederationHttpSecurity.Mode*>propriedade foi alterado do valor padrão e deve ser serializada.</xref:System.ServiceModel.WSFederationHttpSecurity.Mode*>"
  syntax:
    content: public bool ShouldSerializeMode ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se o <xref:System.ServiceModel.WSFederationHttpSecurity.Mode*>o valor da propriedade deve ser serializado; caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.ServiceModel.WSFederationHttpSecurity.Mode*>"
  overload: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMode*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.WSFederationHttpSecurity.#ctor
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: WSFederationHttpSecurity()
  nameWithType: WSFederationHttpSecurity.WSFederationHttpSecurity()
  fullName: System.ServiceModel.WSFederationHttpSecurity.WSFederationHttpSecurity()
- uid: System.ServiceModel.WSFederationHttpSecurity.Message
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: Message
  nameWithType: WSFederationHttpSecurity.Message
  fullName: System.ServiceModel.WSFederationHttpSecurity.Message
- uid: System.ServiceModel.FederatedMessageSecurityOverHttp
  parent: System.ServiceModel
  isExternal: false
  name: FederatedMessageSecurityOverHttp
  nameWithType: FederatedMessageSecurityOverHttp
  fullName: System.ServiceModel.FederatedMessageSecurityOverHttp
- uid: System.ServiceModel.WSFederationHttpSecurity.Mode
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: Mode
  nameWithType: WSFederationHttpSecurity.Mode
  fullName: System.ServiceModel.WSFederationHttpSecurity.Mode
- uid: System.ServiceModel.WSFederationHttpSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: WSFederationHttpSecurityMode
  nameWithType: WSFederationHttpSecurityMode
  fullName: System.ServiceModel.WSFederationHttpSecurityMode
- uid: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMessage
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: ShouldSerializeMessage()
  nameWithType: WSFederationHttpSecurity.ShouldSerializeMessage()
  fullName: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMessage()
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMode
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: ShouldSerializeMode()
  nameWithType: WSFederationHttpSecurity.ShouldSerializeMode()
  fullName: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMode()
- uid: System.ServiceModel.WSFederationHttpSecurity.#ctor*
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: WSFederationHttpSecurity
  nameWithType: WSFederationHttpSecurity.WSFederationHttpSecurity
- uid: System.ServiceModel.WSFederationHttpSecurity.Message*
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: Message
  nameWithType: WSFederationHttpSecurity.Message
- uid: System.ServiceModel.WSFederationHttpSecurity.Mode*
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: Mode
  nameWithType: WSFederationHttpSecurity.Mode
- uid: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMessage*
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: ShouldSerializeMessage
  nameWithType: WSFederationHttpSecurity.ShouldSerializeMessage
- uid: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMode*
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: ShouldSerializeMode
  nameWithType: WSFederationHttpSecurity.ShouldSerializeMode
