### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsGroupDescriptionAttribute
  id: SettingsGroupDescriptionAttribute
  children:
  - System.Configuration.SettingsGroupDescriptionAttribute.#ctor(System.String)
  - System.Configuration.SettingsGroupDescriptionAttribute.Description
  langs:
  - csharp
  name: SettingsGroupDescriptionAttribute
  nameWithType: SettingsGroupDescriptionAttribute
  fullName: System.Configuration.SettingsGroupDescriptionAttribute
  type: Class
  summary: "Fornece uma cadeia de caracteres que descreve um grupo de propriedades de configurações do aplicativo. Essa classe não pode ser herdada."
  remarks: "Derivado de uma classe de configurações do aplicativo, <xref:System.Configuration.ApplicationSettingsBase>, define uma ou mais propriedades que pertencem ao mesmo grupo de propriedade do aplicativo.</xref:System.Configuration.ApplicationSettingsBase> SettingsGroupDescriptionAttribute é um atributo opcional que você pode usar para fornecer um texto descritivo para um grupo de propriedade de configurações. Esse texto destina-se a ajudar ferramentas de tempo de design e ferramentas administrativas de tempo de execução na identificação e descrição do grupo de propriedades associado.      > [!NOTE] > Esse atributo só pode ser aplicado no nível de classe wrapper."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class)]

      public sealed class SettingsGroupDescriptionAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsGroupDescriptionAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  langs:
  - csharp
  name: SettingsGroupDescriptionAttribute(String)
  nameWithType: SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute(String)
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Configuration.SettingsGroupDescriptionAttribute&quot;> </xref> classe."
  remarks: "Embora o comprimento máximo teórico do `description` parâmetro é restrita por limites superiores de um <xref:System.Int32>, limites práticos, determinados pelo uso e limitações de cota impostas pelo provedor de configurações, será muito menores.</xref:System.Int32>"
  syntax:
    content: public SettingsGroupDescriptionAttribute (string description);
    parameters:
    - id: description
      type: System.String
      description: "Um <xref:System.String>que contém o texto descritivo para o grupo de configurações do aplicativo.</xref:System.String>"
  overload: System.Configuration.SettingsGroupDescriptionAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsGroupDescriptionAttribute.Description
  id: Description
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  langs:
  - csharp
  name: Description
  nameWithType: SettingsGroupDescriptionAttribute.Description
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.Description
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "O texto descritivo para o grupo de propriedades de configurações do aplicativo."
  remarks: "O valor da propriedade de descrição é definido <xref:System.Configuration.SettingsGroupDescriptionAttribute.%23ctor%2A>construtor.</xref:System.Configuration.SettingsGroupDescriptionAttribute.%23ctor%2A>"
  syntax:
    content: public string Description { get; }
    return:
      type: System.String
      description: "Um <xref:System.String>que contém o texto descritivo para o grupo de configurações do aplicativo.</xref:System.String>"
  overload: System.Configuration.SettingsGroupDescriptionAttribute.Description*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsGroupDescriptionAttribute.#ctor(System.String)
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  isExternal: false
  name: SettingsGroupDescriptionAttribute(String)
  nameWithType: SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute(String)
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsGroupDescriptionAttribute.Description
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  isExternal: false
  name: Description
  nameWithType: SettingsGroupDescriptionAttribute.Description
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.Description
- uid: System.Configuration.SettingsGroupDescriptionAttribute.#ctor*
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  isExternal: false
  name: SettingsGroupDescriptionAttribute
  nameWithType: SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute
- uid: System.Configuration.SettingsGroupDescriptionAttribute.Description*
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  isExternal: false
  name: Description
  nameWithType: SettingsGroupDescriptionAttribute.Description
