### YamlMime:ManagedReference
items:
- uid: System.Transactions.Configuration.DefaultSettingsSection
  id: DefaultSettingsSection
  children:
  - System.Transactions.Configuration.DefaultSettingsSection.#ctor
  - System.Transactions.Configuration.DefaultSettingsSection.DistributedTransactionManagerName
  - System.Transactions.Configuration.DefaultSettingsSection.Properties
  - System.Transactions.Configuration.DefaultSettingsSection.Timeout
  langs:
  - csharp
  name: DefaultSettingsSection
  nameWithType: DefaultSettingsSection
  fullName: System.Transactions.Configuration.DefaultSettingsSection
  type: Class
  summary: "Representa uma seção XML em um arquivo de configuração que contém os valores padrão de uma transação. Essa classe não pode ser herdada."
  remarks: ''
  example:
  - "An example configuration file used by your transaction application can be as follows,  \n  \n `<configuration>`  \n  \n `<system.transactions>`  \n  \n `<defaultSettings distributedTransactionManagerName=\"F04M25\" timeout=\"02:00:00\"/>`  \n  \n `<machineSettings maxTimeout=\"02:00:00\"/>`  \n  \n `</system.transactions>`  \n  \n `</configuration>`  \n  \n This example specifies the default values of a transaction. Specifically, it sets the the computer name of the Distributed Transaction Coordinator (MSDTC) that is responsible for coordinating all distributed transactions started locally, and the default time after which a transaction times out. In addition, it specifies a setting that can only be modified at the machine level, which is the maximum amount of time allowed before a transaction times out."
  syntax:
    content: 'public sealed class DefaultSettingsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Transactions.Configuration.DefaultSettingsSection.#ctor
  id: '#ctor'
  parent: System.Transactions.Configuration.DefaultSettingsSection
  langs:
  - csharp
  name: DefaultSettingsSection()
  nameWithType: DefaultSettingsSection.DefaultSettingsSection()
  fullName: System.Transactions.Configuration.DefaultSettingsSection.DefaultSettingsSection()
  type: Constructor
  assemblies:
  - System.Transactions
  namespace: System.Transactions.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Transactions.Configuration.DefaultSettingsSection&quot;> </xref> classe."
  syntax:
    content: public DefaultSettingsSection ();
    parameters: []
  overload: System.Transactions.Configuration.DefaultSettingsSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Transactions.Configuration.DefaultSettingsSection.DistributedTransactionManagerName
  id: DistributedTransactionManagerName
  parent: System.Transactions.Configuration.DefaultSettingsSection
  langs:
  - csharp
  name: DistributedTransactionManagerName
  nameWithType: DefaultSettingsSection.DistributedTransactionManagerName
  fullName: System.Transactions.Configuration.DefaultSettingsSection.DistributedTransactionManagerName
  type: Property
  assemblies:
  - System.Transactions
  namespace: System.Transactions.Configuration
  summary: "Obtém o nome do Gerenciador de transações."
  remarks: "Esta propriedade contém o nome do computador que está executando o Microsoft Distributed Transaction MSDTC (coordenador) e é responsável por coordenar todas as transações distribuídas iniciadas localmente.       Você pode definir o valor dessa propriedade para habilitar os gerenciadores de transações remoto sob <xref:System.Transactions>.</xref:System.Transactions> Se essa propriedade for `null` ou contém uma cadeia de caracteres vazia, o Gerenciador de transação local é usado como o Gerenciador de transações remoto. Se você definir essa propriedade como um valor diferente de cadeia de caracteres vazia padrão, você deve instalar o Windows Server 2003 Service Pack 1. Caso contrário, qualquer operação transacional falhará com <xref:System.NotSupportedException>.</xref:System.NotSupportedException> Uma transação que é escalada para ser gerenciado pelo MSDTC não usar o MSDTC local, mas em vez disso, use no computador especificado por essa propriedade. Se o Gerenciador de transações não estiver disponível por algum motivo, uma exceção será lançada.       Essa propriedade não diferencia maiusculas de minúsculas e deve conter apenas o nome curto do computador.  Ela não aceita nomes de domínio totalmente qualificado, localhost ou endereços IP. Se esta propriedade contém um nome inválido de computador remoto, é gerada uma exceção &quot;não é possível ler informações de configuração&quot;.       Você deve ter a permissão de segurança apropriada para usar um MSDTC remoto. Para obter mais informações sobre como definir as configurações de segurança do DTC, consulte o [propriedades de segurança do MSDTC configurando](http://msdn.microsoft.com/library/cossdk/html/2627a956-60b3-4d26-bc04-e0676ec97786.asp?frame=true) tópico."
  syntax:
    content: public string DistributedTransactionManagerName { get; set; }
    return:
      type: System.String
      description: "O nome do Gerenciador de transações. O valor padrão é uma cadeia de caracteres vazia."
  overload: System.Transactions.Configuration.DefaultSettingsSection.DistributedTransactionManagerName*
  exceptions:
  - type: System.NotSupportedException
    commentId: T:System.NotSupportedException
    description: "Uma tentativa de definir esta propriedade para endereços IP ou nomes de domínio totalmente qualificado."
  - type: System.Transactions.TransactionAbortedException
    commentId: T:System.Transactions.TransactionAbortedException
    description: "Uma tentativa de definir essa propriedade como localhost."
  platform:
  - net462
- uid: System.Transactions.Configuration.DefaultSettingsSection.Properties
  id: Properties
  parent: System.Transactions.Configuration.DefaultSettingsSection
  langs:
  - csharp
  name: Properties
  nameWithType: DefaultSettingsSection.Properties
  fullName: System.Transactions.Configuration.DefaultSettingsSection.Properties
  type: Property
  assemblies:
  - System.Transactions
  namespace: System.Transactions.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A ser adicionado."
  overload: System.Transactions.Configuration.DefaultSettingsSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Transactions.Configuration.DefaultSettingsSection.Timeout
  id: Timeout
  parent: System.Transactions.Configuration.DefaultSettingsSection
  langs:
  - csharp
  name: Timeout
  nameWithType: DefaultSettingsSection.Timeout
  fullName: System.Transactions.Configuration.DefaultSettingsSection.Timeout
  type: Property
  assemblies:
  - System.Transactions
  namespace: System.Transactions.Configuration
  summary: "Obtém ou define um tempo padrão após o qual uma transação de tempo limite."
  remarks: "Essa propriedade recupera o valor do valor de tempo limite padrão no arquivo de configuração. Ele é automaticamente ajustado pelo <xref:System.Transactions.Configuration.MachineSettingsSection.MaxTimeout%2A>valor em tempo de execução.</xref:System.Transactions.Configuration.MachineSettingsSection.MaxTimeout%2A>       Um valor de 00:00:00 (ou zero) é interpretado como infinito."
  syntax:
    content: public TimeSpan Timeout { get; set; }
    return:
      type: System.TimeSpan
      description: "Um <xref:System.TimeSpan>objeto.</xref:System.TimeSpan> A propriedade padrão é 00:01:00."
  overload: System.Transactions.Configuration.DefaultSettingsSection.Timeout*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Uma tentativa de definir essa propriedade para valores negativos."
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.NotSupportedException
  isExternal: true
  name: System.NotSupportedException
- uid: System.Transactions.TransactionAbortedException
  parent: System.Transactions
  isExternal: false
  name: TransactionAbortedException
  nameWithType: TransactionAbortedException
  fullName: System.Transactions.TransactionAbortedException
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.Transactions.Configuration.DefaultSettingsSection.#ctor
  parent: System.Transactions.Configuration.DefaultSettingsSection
  isExternal: false
  name: DefaultSettingsSection()
  nameWithType: DefaultSettingsSection.DefaultSettingsSection()
  fullName: System.Transactions.Configuration.DefaultSettingsSection.DefaultSettingsSection()
- uid: System.Transactions.Configuration.DefaultSettingsSection.DistributedTransactionManagerName
  parent: System.Transactions.Configuration.DefaultSettingsSection
  isExternal: false
  name: DistributedTransactionManagerName
  nameWithType: DefaultSettingsSection.DistributedTransactionManagerName
  fullName: System.Transactions.Configuration.DefaultSettingsSection.DistributedTransactionManagerName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Transactions.Configuration.DefaultSettingsSection.Properties
  parent: System.Transactions.Configuration.DefaultSettingsSection
  isExternal: false
  name: Properties
  nameWithType: DefaultSettingsSection.Properties
  fullName: System.Transactions.Configuration.DefaultSettingsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Transactions.Configuration.DefaultSettingsSection.Timeout
  parent: System.Transactions.Configuration.DefaultSettingsSection
  isExternal: false
  name: Timeout
  nameWithType: DefaultSettingsSection.Timeout
  fullName: System.Transactions.Configuration.DefaultSettingsSection.Timeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Transactions.Configuration.DefaultSettingsSection.#ctor*
  parent: System.Transactions.Configuration.DefaultSettingsSection
  isExternal: false
  name: DefaultSettingsSection
  nameWithType: DefaultSettingsSection.DefaultSettingsSection
- uid: System.Transactions.Configuration.DefaultSettingsSection.DistributedTransactionManagerName*
  parent: System.Transactions.Configuration.DefaultSettingsSection
  isExternal: false
  name: DistributedTransactionManagerName
  nameWithType: DefaultSettingsSection.DistributedTransactionManagerName
- uid: System.Transactions.Configuration.DefaultSettingsSection.Properties*
  parent: System.Transactions.Configuration.DefaultSettingsSection
  isExternal: false
  name: Properties
  nameWithType: DefaultSettingsSection.Properties
- uid: System.Transactions.Configuration.DefaultSettingsSection.Timeout*
  parent: System.Transactions.Configuration.DefaultSettingsSection
  isExternal: false
  name: Timeout
  nameWithType: DefaultSettingsSection.Timeout
