### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs
  id: DownloadProgressChangedEventArgs
  children:
  - System.Deployment.Application.DownloadProgressChangedEventArgs.BytesDownloaded
  - System.Deployment.Application.DownloadProgressChangedEventArgs.State
  - System.Deployment.Application.DownloadProgressChangedEventArgs.TotalBytesToDownload
  langs:
  - csharp
  name: DownloadProgressChangedEventArgs
  nameWithType: DownloadProgressChangedEventArgs
  fullName: System.Deployment.Application.DownloadProgressChangedEventArgs
  type: Class
  summary: "Fornece dados para o <xref href=&quot;System.Deployment.Application.InPlaceHostingManager.DownloadProgressChanged&quot;> </xref> eventos."
  remarks: "Em um aplicativo de console, como eventos são atribuídos a threads fora de um pool de threads, você pode receber os eventos do progresso de atualização fora de ordem, com um evento subsequente mostrando uma redução em comparação comparada um evento anterior. Você não verá esse comportamento em um aplicativo do Windows Forms, porque eventos em formulários do Windows são processados sequencialmente fora da fila de mensagens do thread da interface do usuário."
  example:
  - "The following code example demonstrates the use of DownloadProgressChangedEventArgs in the context of an application that uses <xref:System.Deployment.Application.InPlaceHostingManager> to download and install a ClickOnce application programmatically.  \n  \n [!code-vb[System.Deployment.Application.InPlaceHostingManager#1](~/add/codesnippet/visualbasic/InPlaceHostingManagerProjectVB/Form1.vb#1)]\n [!code-cs[System.Deployment.Application.InPlaceHostingManager#1](~/add/codesnippet/csharp/InPlaceHostingManagerProject/Form1.cs#1)]"
  syntax:
    content: 'public class DownloadProgressChangedEventArgs : System.ComponentModel.ProgressChangedEventArgs'
  inheritance:
  - System.ComponentModel.ProgressChangedEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.BytesDownloaded
  id: BytesDownloaded
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  langs:
  - csharp
  name: BytesDownloaded
  nameWithType: DownloadProgressChangedEventArgs.BytesDownloaded
  fullName: System.Deployment.Application.DownloadProgressChangedEventArgs.BytesDownloaded
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Obtém o número de bytes baixados para o computador local."
  syntax:
    content: public long BytesDownloaded { get; }
    return:
      type: System.Int64
      description: "Um <xref:System.Int64>representando o número de bytes de download.</xref:System.Int64>"
  overload: System.Deployment.Application.DownloadProgressChangedEventArgs.BytesDownloaded*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.State
  id: State
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  langs:
  - csharp
  name: State
  nameWithType: DownloadProgressChangedEventArgs.State
  fullName: System.Deployment.Application.DownloadProgressChangedEventArgs.State
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Obtém o estado de progresso do download."
  syntax:
    content: public System.Deployment.Application.DeploymentProgressState State { get; }
    return:
      type: System.Deployment.Application.DeploymentProgressState
      description: "Um <xref href=&quot;System.Deployment.Application.DeploymentProgressState&quot;> </xref> valor que descreve qual parte do aplicativo ClickOnce está sendo descarregado."
  overload: System.Deployment.Application.DownloadProgressChangedEventArgs.State*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.TotalBytesToDownload
  id: TotalBytesToDownload
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  langs:
  - csharp
  name: TotalBytesToDownload
  nameWithType: DownloadProgressChangedEventArgs.TotalBytesToDownload
  fullName: System.Deployment.Application.DownloadProgressChangedEventArgs.TotalBytesToDownload
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Obtém o número total de bytes para a operação de download."
  syntax:
    content: public long TotalBytesToDownload { get; }
    return:
      type: System.Int64
      description: "Um <xref:System.Int64>que representa o tamanho total do download, em bytes.</xref:System.Int64>"
  overload: System.Deployment.Application.DownloadProgressChangedEventArgs.TotalBytesToDownload*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ComponentModel.ProgressChangedEventArgs
  isExternal: false
  name: System.ComponentModel.ProgressChangedEventArgs
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.BytesDownloaded
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  isExternal: false
  name: BytesDownloaded
  nameWithType: DownloadProgressChangedEventArgs.BytesDownloaded
  fullName: System.Deployment.Application.DownloadProgressChangedEventArgs.BytesDownloaded
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.State
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  isExternal: false
  name: State
  nameWithType: DownloadProgressChangedEventArgs.State
  fullName: System.Deployment.Application.DownloadProgressChangedEventArgs.State
- uid: System.Deployment.Application.DeploymentProgressState
  parent: System.Deployment.Application
  isExternal: false
  name: DeploymentProgressState
  nameWithType: DeploymentProgressState
  fullName: System.Deployment.Application.DeploymentProgressState
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.TotalBytesToDownload
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  isExternal: false
  name: TotalBytesToDownload
  nameWithType: DownloadProgressChangedEventArgs.TotalBytesToDownload
  fullName: System.Deployment.Application.DownloadProgressChangedEventArgs.TotalBytesToDownload
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.BytesDownloaded*
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  isExternal: false
  name: BytesDownloaded
  nameWithType: DownloadProgressChangedEventArgs.BytesDownloaded
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.State*
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  isExternal: false
  name: State
  nameWithType: DownloadProgressChangedEventArgs.State
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.TotalBytesToDownload*
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  isExternal: false
  name: TotalBytesToDownload
  nameWithType: DownloadProgressChangedEventArgs.TotalBytesToDownload
