### YamlMime:ManagedReference
items:
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm
  id: AssemblyHashAlgorithm
  children:
  - System.Configuration.Assemblies.AssemblyHashAlgorithm.MD5
  - System.Configuration.Assemblies.AssemblyHashAlgorithm.None
  - System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA1
  - System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA256
  - System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA384
  - System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA512
  langs:
  - csharp
  name: AssemblyHashAlgorithm
  nameWithType: AssemblyHashAlgorithm
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm
  type: Enum
  summary: "Especifica todos os algoritmos de hash usados para arquivos de hash e para gerar o nome forte."
  remarks: "Um `hash function``H` é uma transformação que usa uma entrada `m` e retorna uma cadeia de caracteres de tamanho fixo, que é chamada de valor de hash `h` (ou seja, `h`  =  `H` (`m`)). Funções de hash com apenas essa propriedade tem uma variedade de usos gerais de computação, mas quando utilizada em criptografia, as funções de hash são normalmente escolhidas tenha algumas propriedades adicionais.       Os requisitos básicos para uma função de hash criptográfico são:-a entrada pode ser de qualquer comprimento.      -A saída tem um comprimento fixo.      - `H` (`x)` é relativamente fácil de computação para qualquer determinado x.      -   `H` (`x`) is one-way.      - `H` (`x`) é livre de colisão.       O valor de hash representa de forma concisa a mensagem ou o documento do qual ele foi calculado; mais Esse valor é chamado de resumo da mensagem. Você pode pensar em um resumo da mensagem como uma impressão digital do documento maior. Exemplos de funções de hash conhecidas são MD2 e e SHA."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public enum AssemblyHashAlgorithm
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.MD5
  id: MD5
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  langs:
  - csharp
  name: MD5
  nameWithType: AssemblyHashAlgorithm.MD5
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.MD5
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "Recupera o algoritmo MD5 message-digest. MD5 foi desenvolvido por Rivest 1991. Ele é basicamente MD4 com segurança belts e enquanto ele é um pouco mais lento do que MD4, ele ajuda a fornecer mais segurança. O algoritmo consiste em quatro turnos distintos, que tem um design ligeiramente diferente da MD4. Tamanho do conteúdo da mensagem, bem como preenchimento requisitos, permanece os mesmos."
  syntax:
    content: MD5
    return:
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.None
  id: None
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  langs:
  - csharp
  name: None
  nameWithType: AssemblyHashAlgorithm.None
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.None
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "Uma máscara que indica que não há nenhum algoritmo de hash. Se você especificar <xref uid=&quot;langword_csharp_None&quot; name=&quot;None&quot; href=&quot;&quot;> </xref> para um assembly de vários módulo, o common language runtime é padronizado como o algoritmo SHA1, já que os assemblies de vários módulos gerar um hash."
  syntax:
    content: None
    return:
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA1
  id: SHA1
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  langs:
  - csharp
  name: SHA1
  nameWithType: AssemblyHashAlgorithm.SHA1
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA1
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "Uma máscara usada para recuperar uma revisão do algoritmo de Hash seguro que corrige uma falha não publicada no SHA."
  syntax:
    content: SHA1
    return:
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA256
  id: SHA256
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  langs:
  - csharp
  name: SHA256
  nameWithType: AssemblyHashAlgorithm.SHA256
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA256
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "Uma máscara usada para recuperar uma versão do algoritmo de Hash seguro com um tamanho de hash de 256 bits."
  syntax:
    content: SHA256
    return:
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA384
  id: SHA384
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  langs:
  - csharp
  name: SHA384
  nameWithType: AssemblyHashAlgorithm.SHA384
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA384
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "Uma máscara usada para recuperar uma versão do algoritmo de Hash seguro com um tamanho de hash de 384 bits."
  syntax:
    content: SHA384
    return:
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA512
  id: SHA512
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  langs:
  - csharp
  name: SHA512
  nameWithType: AssemblyHashAlgorithm.SHA512
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA512
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "Uma máscara usada para recuperar uma versão do algoritmo de Hash seguro com um tamanho de hash de 512 bits."
  syntax:
    content: SHA512
    return:
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.MD5
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  isExternal: false
  name: MD5
  nameWithType: AssemblyHashAlgorithm.MD5
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.MD5
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm
  parent: System.Configuration.Assemblies
  isExternal: false
  name: AssemblyHashAlgorithm
  nameWithType: AssemblyHashAlgorithm
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.None
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  isExternal: false
  name: None
  nameWithType: AssemblyHashAlgorithm.None
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.None
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA1
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  isExternal: false
  name: SHA1
  nameWithType: AssemblyHashAlgorithm.SHA1
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA1
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA256
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  isExternal: false
  name: SHA256
  nameWithType: AssemblyHashAlgorithm.SHA256
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA256
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA384
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  isExternal: false
  name: SHA384
  nameWithType: AssemblyHashAlgorithm.SHA384
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA384
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA512
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  isExternal: false
  name: SHA512
  nameWithType: AssemblyHashAlgorithm.SHA512
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA512
