### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig
  id: ClientRemotingConfig
  children:
  - System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor
  - System.EnterpriseServices.Internal.ClientRemotingConfig.Write(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)
  langs:
  - csharp
  name: ClientRemotingConfig
  nameWithType: ClientRemotingConfig
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig
  type: Class
  summary: "Define um estático <xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write*>método que cria um arquivo de configuração de comunicação remota do cliente para uma biblioteca de tipos de cliente.</xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write*>"
  remarks: "O <xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write%2A>método é usado pela <xref:System.EnterpriseServices.Internal.Publish>classe ao gerar uma interface COM de uma biblioteca de tipos de cliente (com uma extensão. tlb).</xref:System.EnterpriseServices.Internal.Publish> </xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write%2A> O <xref:System.EnterpriseServices.Internal.Publish>classe publica interfaces COM em um aplicativo habilitado para SOAP COM+.</xref:System.EnterpriseServices.Internal.Publish> Um dos parâmetros do método é o nome de um assembly que contém metadados de runtime (CLR) de linguagem comum que <xref:System.EnterpriseServices.Internal.Publish>já foi gerado para a biblioteca de tipos de cliente.</xref:System.EnterpriseServices.Internal.Publish>       <xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write%2A>não precisa ser chamado diretamente.</xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write%2A> Em vez disso, chame o <xref:System.EnterpriseServices.Internal.Publish.ProcessClientTlb%2A>método de <xref:System.EnterpriseServices.Internal.Publish>classe.</xref:System.EnterpriseServices.Internal.Publish> </xref:System.EnterpriseServices.Internal.Publish.ProcessClientTlb%2A>       ClientRemotingConfig é usado internamente pelo .NET Framework. Você não precisa usar a classe diretamente no seu código."
  syntax:
    content: public class ClientRemotingConfig
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor
  id: '#ctor'
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  langs:
  - csharp
  name: ClientRemotingConfig()
  nameWithType: ClientRemotingConfig.ClientRemotingConfig()
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig.ClientRemotingConfig()
  type: Constructor
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Inicializa uma nova instância do <xref href=&quot;System.EnterpriseServices.Internal.ClientRemotingConfig&quot;> </xref> classe."
  syntax:
    content: public ClientRemotingConfig ();
    parameters: []
  overload: System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.Write(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)
  id: Write(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  langs:
  - csharp
  name: Write(String,String,String,String,String,String,String,String)
  nameWithType: ClientRemotingConfig.Write(String,String,String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig.Write(String,String,String,String,String,String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Cria um arquivo de configuração de comunicação remota do cliente para uma biblioteca de tipos de cliente em um aplicativo habilitado para SOAP COM+."
  remarks: "O método estático de gravação é chamado pelo <xref:System.EnterpriseServices.Internal.Publish>classe ao gerar uma interface COM de uma biblioteca de tipos de cliente (com uma extensão. tlb).</xref:System.EnterpriseServices.Internal.Publish> O <xref:System.EnterpriseServices.Internal.Publish>classe publica interfaces COM em um aplicativo habilitado para SOAP COM+.</xref:System.EnterpriseServices.Internal.Publish>       Gravação não precisa ser chamado diretamente. Em vez disso, chame o <xref:System.EnterpriseServices.Internal.Publish.ProcessClientTlb%2A>método de <xref:System.EnterpriseServices.Internal.Publish>classe.</xref:System.EnterpriseServices.Internal.Publish> </xref:System.EnterpriseServices.Internal.Publish.ProcessClientTlb%2A>       O `BaseUrl` e `VRoot` valores de parâmetro são concatenados (com um separador de caminho, se necessário) para o elemento de cliente do formulário `URL` valor do atributo.       O `AssemblyName` parâmetro identifica um assembly que contém metadados do CLR que <xref:System.EnterpriseServices.Internal.Publish>, usando o <xref:System.EnterpriseServices.Internal.GenerateMetadata>da classe, já foi gerado para a biblioteca de tipos de cliente.</xref:System.EnterpriseServices.Internal.GenerateMetadata> </xref:System.EnterpriseServices.Internal.Publish>"
  syntax:
    content: public static bool Write (string DestinationDirectory, string VRoot, string BaseUrl, string AssemblyName, string TypeName, string ProgId, string Mode, string Transport);
    parameters:
    - id: DestinationDirectory
      type: System.String
      description: "A pasta na qual criar o arquivo de configuração."
    - id: VRoot
      type: System.String
      description: "O nome da raiz virtual."
    - id: BaseUrl
      type: System.String
      description: "A URL base que contém a raiz virtual."
    - id: AssemblyName
      type: System.String
      description: "O nome para exibição do assembly que contém metadados comuns de tempo de execução (CLR) idioma correspondente para a biblioteca de tipos."
    - id: TypeName
      type: System.String
      description: "O nome totalmente qualificado do assembly que contém metadados do CLR correspondente à biblioteca de tipos."
    - id: ProgId
      type: System.String
      description: "O identificador programático da classe."
    - id: Mode
      type: System.String
      description: "O modo de ativação."
    - id: Transport
      type: System.String
      description: "Não usado. Especifique <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> para esse parâmetro."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se o arquivo de configuração de comunicação remota do cliente foi criado com êxito; Caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.EnterpriseServices.Internal.ClientRemotingConfig.Write*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  isExternal: false
  name: ClientRemotingConfig()
  nameWithType: ClientRemotingConfig.ClientRemotingConfig()
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig.ClientRemotingConfig()
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.Write(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  isExternal: false
  name: Write(String,String,String,String,String,String,String,String)
  nameWithType: ClientRemotingConfig.Write(String,String,String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig.Write(String,String,String,String,String,String,String,String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor*
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  isExternal: false
  name: ClientRemotingConfig
  nameWithType: ClientRemotingConfig.ClientRemotingConfig
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.Write*
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  isExternal: false
  name: Write
  nameWithType: ClientRemotingConfig.Write
