### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.IConfigMapPath
  id: IConfigMapPath
  children:
  - System.Web.Configuration.IConfigMapPath.GetAppPathForPath(System.String,System.String)
  - System.Web.Configuration.IConfigMapPath.GetDefaultSiteNameAndID(System.String@,System.String@)
  - System.Web.Configuration.IConfigMapPath.GetMachineConfigFilename
  - System.Web.Configuration.IConfigMapPath.GetPathConfigFilename(System.String,System.String,System.String@,System.String@)
  - System.Web.Configuration.IConfigMapPath.GetRootWebConfigFilename
  - System.Web.Configuration.IConfigMapPath.MapPath(System.String,System.String)
  - System.Web.Configuration.IConfigMapPath.ResolveSiteArgument(System.String,System.String@,System.String@)
  langs:
  - csharp
  name: IConfigMapPath
  nameWithType: IConfigMapPath
  fullName: System.Web.Configuration.IConfigMapPath
  type: Interface
  summary: "Fornece acesso para o mapeamento entre o arquivo de configuração de caminhos virtuais e físicos."
  remarks: "IConfigMapPath é introduzido no .NET Framework versão 3.5.  Para obter mais informações, consulte [versões e dependências](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public interface IConfigMapPath
  implements: []
  platform:
  - net462
- uid: System.Web.Configuration.IConfigMapPath.GetAppPathForPath(System.String,System.String)
  id: GetAppPathForPath(System.String,System.String)
  parent: System.Web.Configuration.IConfigMapPath
  langs:
  - csharp
  name: GetAppPathForPath(String,String)
  nameWithType: IConfigMapPath.GetAppPathForPath(String,String)
  fullName: System.Web.Configuration.IConfigMapPath.GetAppPathForPath(String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Obtém o nome do diretório virtual associado a um site específico."
  remarks: "GetAppPathForPath é introduzido no .NET Framework versão 3.5.  Para obter mais informações, consulte [versões e dependências](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public string GetAppPathForPath (string siteID, string path);
    parameters:
    - id: siteID
      type: System.String
      description: "Um identificador exclusivo para o site."
    - id: path
      type: System.String
      description: "A URL associada com o site."
    return:
      type: System.String
      description: "O <code> siteID </code> devem ser exclusivos. Não há dois sites compartilham a mesma id. O <code> siteID </code> distingue sites que têm o mesmo nome."
  overload: System.Web.Configuration.IConfigMapPath.GetAppPathForPath*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IConfigMapPath.GetDefaultSiteNameAndID(System.String@,System.String@)
  id: GetDefaultSiteNameAndID(System.String@,System.String@)
  parent: System.Web.Configuration.IConfigMapPath
  langs:
  - csharp
  name: GetDefaultSiteNameAndID(String,String)
  nameWithType: IConfigMapPath.GetDefaultSiteNameAndID(String,String)
  fullName: System.Web.Configuration.IConfigMapPath.GetDefaultSiteNameAndID(String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Preenche o nome do site padrão e a ID do site."
  remarks: "GetDefaultSiteNameAndID é introduzido no .NET Framework versão 3.5.  Para obter mais informações, consulte [versões e dependências](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public void GetDefaultSiteNameAndID (out string siteName, out string siteID);
    parameters:
    - id: siteName
      type: System.String
      description: "O nome do site padrão."
    - id: siteID
      type: System.String
      description: "Um identificador exclusivo para o site."
  overload: System.Web.Configuration.IConfigMapPath.GetDefaultSiteNameAndID*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IConfigMapPath.GetMachineConfigFilename
  id: GetMachineConfigFilename
  parent: System.Web.Configuration.IConfigMapPath
  langs:
  - csharp
  name: GetMachineConfigFilename()
  nameWithType: IConfigMapPath.GetMachineConfigFilename()
  fullName: System.Web.Configuration.IConfigMapPath.GetMachineConfigFilename()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Obtém o nome do arquivo de configuração da máquina."
  remarks: "GetMachineConfigFilename é introduzido no .NET Framework versão 3.5.  Para obter mais informações, consulte [versões e dependências](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public string GetMachineConfigFilename ();
    parameters: []
    return:
      type: System.String
      description: "O nome do arquivo de configuração da máquina."
  overload: System.Web.Configuration.IConfigMapPath.GetMachineConfigFilename*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IConfigMapPath.GetPathConfigFilename(System.String,System.String,System.String@,System.String@)
  id: GetPathConfigFilename(System.String,System.String,System.String@,System.String@)
  parent: System.Web.Configuration.IConfigMapPath
  langs:
  - csharp
  name: GetPathConfigFilename(String,String,String,String)
  nameWithType: IConfigMapPath.GetPathConfigFilename(String,String,String,String)
  fullName: System.Web.Configuration.IConfigMapPath.GetPathConfigFilename(String,String,String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Preenche o diretório e o nome do arquivo de configuração com base na ID de site e o caminho de site."
  remarks: "GetPathConfigFilename é introduzido no .NET Framework versão 3.5.  Para obter mais informações, consulte [versões e dependências](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public void GetPathConfigFilename (string siteID, string path, out string directory, out string baseName);
    parameters:
    - id: siteID
      type: System.String
      description: "Um identificador exclusivo para o site."
    - id: path
      type: System.String
      description: "A URL associada com o site."
    - id: directory
      type: System.String
      description: "O diretório físico do caminho de configuração."
    - id: baseName
      type: System.String
      description: "O nome do arquivo de configuração."
  overload: System.Web.Configuration.IConfigMapPath.GetPathConfigFilename*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IConfigMapPath.GetRootWebConfigFilename
  id: GetRootWebConfigFilename
  parent: System.Web.Configuration.IConfigMapPath
  langs:
  - csharp
  name: GetRootWebConfigFilename()
  nameWithType: IConfigMapPath.GetRootWebConfigFilename()
  fullName: System.Web.Configuration.IConfigMapPath.GetRootWebConfigFilename()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Obtém o nome do arquivo de configuração na raiz da Web."
  remarks: "GetRootWebConfigFilename é introduzido no .NET Framework versão 3.5.  Para obter mais informações, consulte [versões e dependências](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public string GetRootWebConfigFilename ();
    parameters: []
    return:
      type: System.String
      description: "O nome do arquivo de configuração na raiz da Web."
  overload: System.Web.Configuration.IConfigMapPath.GetRootWebConfigFilename*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IConfigMapPath.MapPath(System.String,System.String)
  id: MapPath(System.String,System.String)
  parent: System.Web.Configuration.IConfigMapPath
  langs:
  - csharp
  name: MapPath(String,String)
  nameWithType: IConfigMapPath.MapPath(String,String)
  fullName: System.Web.Configuration.IConfigMapPath.MapPath(String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Obtém o caminho do diretório físico com base na ID de site e URL associado ao site."
  remarks: "MapPath é introduzido no .NET Framework versão 3.5.  Para obter mais informações, consulte [versões e dependências](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public string MapPath (string siteID, string path);
    parameters:
    - id: siteID
      type: System.String
      description: "Um identificador exclusivo para o site."
    - id: path
      type: System.String
      description: "A URL associada com o site."
    return:
      type: System.String
      description: "O caminho do diretório físico."
  overload: System.Web.Configuration.IConfigMapPath.MapPath*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IConfigMapPath.ResolveSiteArgument(System.String,System.String@,System.String@)
  id: ResolveSiteArgument(System.String,System.String@,System.String@)
  parent: System.Web.Configuration.IConfigMapPath
  langs:
  - csharp
  name: ResolveSiteArgument(String,String,String)
  nameWithType: IConfigMapPath.ResolveSiteArgument(String,String,String)
  fullName: System.Web.Configuration.IConfigMapPath.ResolveSiteArgument(String,String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Preenche o nome do site e a ID de site com base em um valor de argumento do site."
  remarks: "Se `siteArgument` é `null`, é igual ao nome do site padrão ou é igual ao identificador de site padrão, o `siteName` e `siteID` são preenchidos com os valores de site padrão.       ResolveSiteArgument é introduzido no .NET Framework versão 3.5.  Para obter mais informações, consulte [versões e dependências](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public void ResolveSiteArgument (string siteArgument, out string siteName, out string siteID);
    parameters:
    - id: siteArgument
      type: System.String
      description: "O nome do site ou o identificador de site."
    - id: siteName
      type: System.String
      description: "O nome do site padrão."
    - id: siteID
      type: System.String
      description: "Um identificador exclusivo para o site."
  overload: System.Web.Configuration.IConfigMapPath.ResolveSiteArgument*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.Configuration.IConfigMapPath.GetAppPathForPath(System.String,System.String)
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetAppPathForPath(String,String)
  nameWithType: IConfigMapPath.GetAppPathForPath(String,String)
  fullName: System.Web.Configuration.IConfigMapPath.GetAppPathForPath(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.IConfigMapPath.GetDefaultSiteNameAndID(System.String@,System.String@)
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetDefaultSiteNameAndID(String,String)
  nameWithType: IConfigMapPath.GetDefaultSiteNameAndID(String,String)
  fullName: System.Web.Configuration.IConfigMapPath.GetDefaultSiteNameAndID(String,String)
- uid: System.Web.Configuration.IConfigMapPath.GetMachineConfigFilename
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetMachineConfigFilename()
  nameWithType: IConfigMapPath.GetMachineConfigFilename()
  fullName: System.Web.Configuration.IConfigMapPath.GetMachineConfigFilename()
- uid: System.Web.Configuration.IConfigMapPath.GetPathConfigFilename(System.String,System.String,System.String@,System.String@)
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetPathConfigFilename(String,String,String,String)
  nameWithType: IConfigMapPath.GetPathConfigFilename(String,String,String,String)
  fullName: System.Web.Configuration.IConfigMapPath.GetPathConfigFilename(String,String,String,String)
- uid: System.Web.Configuration.IConfigMapPath.GetRootWebConfigFilename
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetRootWebConfigFilename()
  nameWithType: IConfigMapPath.GetRootWebConfigFilename()
  fullName: System.Web.Configuration.IConfigMapPath.GetRootWebConfigFilename()
- uid: System.Web.Configuration.IConfigMapPath.MapPath(System.String,System.String)
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: MapPath(String,String)
  nameWithType: IConfigMapPath.MapPath(String,String)
  fullName: System.Web.Configuration.IConfigMapPath.MapPath(String,String)
- uid: System.Web.Configuration.IConfigMapPath.ResolveSiteArgument(System.String,System.String@,System.String@)
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: ResolveSiteArgument(String,String,String)
  nameWithType: IConfigMapPath.ResolveSiteArgument(String,String,String)
  fullName: System.Web.Configuration.IConfigMapPath.ResolveSiteArgument(String,String,String)
- uid: System.Web.Configuration.IConfigMapPath.GetAppPathForPath*
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetAppPathForPath
  nameWithType: IConfigMapPath.GetAppPathForPath
- uid: System.Web.Configuration.IConfigMapPath.GetDefaultSiteNameAndID*
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetDefaultSiteNameAndID
  nameWithType: IConfigMapPath.GetDefaultSiteNameAndID
- uid: System.Web.Configuration.IConfigMapPath.GetMachineConfigFilename*
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetMachineConfigFilename
  nameWithType: IConfigMapPath.GetMachineConfigFilename
- uid: System.Web.Configuration.IConfigMapPath.GetPathConfigFilename*
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetPathConfigFilename
  nameWithType: IConfigMapPath.GetPathConfigFilename
- uid: System.Web.Configuration.IConfigMapPath.GetRootWebConfigFilename*
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetRootWebConfigFilename
  nameWithType: IConfigMapPath.GetRootWebConfigFilename
- uid: System.Web.Configuration.IConfigMapPath.MapPath*
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: MapPath
  nameWithType: IConfigMapPath.MapPath
- uid: System.Web.Configuration.IConfigMapPath.ResolveSiteArgument*
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: ResolveSiteArgument
  nameWithType: IConfigMapPath.ResolveSiteArgument
