### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.Internal.IInternalConfigWebHost
  id: IInternalConfigWebHost
  children:
  - System.Web.Configuration.Internal.IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(System.String,System.String)
  - System.Web.Configuration.Internal.IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(System.String,System.String@,System.String@)
  langs:
  - csharp
  name: IInternalConfigWebHost
  nameWithType: IInternalConfigWebHost
  fullName: System.Web.Configuration.Internal.IInternalConfigWebHost
  type: Interface
  summary: "Define as interfaces usadas pela infraestrutura interna do .NET Framework para acessar e manipular arquivos de configuração do Host."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public interface IInternalConfigWebHost
  implements: []
  platform:
  - net462
- uid: System.Web.Configuration.Internal.IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(System.String,System.String)
  id: GetConfigPathFromSiteIDAndVPath(System.String,System.String)
  parent: System.Web.Configuration.Internal.IInternalConfigWebHost
  langs:
  - csharp
  name: GetConfigPathFromSiteIDAndVPath(String,String)
  nameWithType: IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(String,String)
  fullName: System.Web.Configuration.Internal.IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration.Internal
  summary: "Retorna um valor que representa o caminho para um arquivo de configuração associado com o identificador de site fornecido e o caminho virtual do aplicativo."
  syntax:
    content: public string GetConfigPathFromSiteIDAndVPath (string siteID, string vpath);
    parameters:
    - id: siteID
      type: System.String
      description: "Identificador de site do aplicativo. Para obter mais informações, consulte Visão geral sobre a configuração do ASP.NET."
    - id: vpath
      type: System.String
      description: "O caminho do aplicativo virtual como uma cadeia de caracteres. Para obter mais informações, consulte caminhos de Site da Web do ASP.NET."
    return:
      type: System.String
      description: "Uma cadeia de caracteres que representa o caminho para um arquivo de configuração."
  overload: System.Web.Configuration.Internal.IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Internal.IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(System.String,System.String@,System.String@)
  id: GetSiteIDAndVPathFromConfigPath(System.String,System.String@,System.String@)
  parent: System.Web.Configuration.Internal.IInternalConfigWebHost
  langs:
  - csharp
  name: GetSiteIDAndVPathFromConfigPath(String,String,String)
  nameWithType: IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(String,String,String)
  fullName: System.Web.Configuration.Internal.IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(String,String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration.Internal
  summary: "Define o identificador de site atual de um objeto de configuração com base no caminho virtual do aplicativo e o caminho de configuração do aplicativo."
  syntax:
    content: public void GetSiteIDAndVPathFromConfigPath (string configPath, out string siteID, out string vpath);
    parameters:
    - id: configPath
      type: System.String
      description: "Uma cadeia de caracteres que representa o caminho para o arquivo de configuração do aplicativo."
    - id: siteID
      type: System.String
      description: "Identificador de site do aplicativo. Para obter mais informações, consulte Visão geral sobre a configuração do ASP.NET."
    - id: vpath
      type: System.String
      description: "O caminho do aplicativo virtual como uma cadeia de caracteres. Para obter mais informações, consulte caminhos de Site da Web do ASP.NET."
  overload: System.Web.Configuration.Internal.IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.Configuration.Internal.IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(System.String,System.String)
  parent: System.Web.Configuration.Internal.IInternalConfigWebHost
  isExternal: false
  name: GetConfigPathFromSiteIDAndVPath(String,String)
  nameWithType: IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(String,String)
  fullName: System.Web.Configuration.Internal.IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.Internal.IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(System.String,System.String@,System.String@)
  parent: System.Web.Configuration.Internal.IInternalConfigWebHost
  isExternal: false
  name: GetSiteIDAndVPathFromConfigPath(String,String,String)
  nameWithType: IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(String,String,String)
  fullName: System.Web.Configuration.Internal.IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(String,String,String)
- uid: System.Web.Configuration.Internal.IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath*
  parent: System.Web.Configuration.Internal.IInternalConfigWebHost
  isExternal: false
  name: GetConfigPathFromSiteIDAndVPath
  nameWithType: IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath
- uid: System.Web.Configuration.Internal.IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath*
  parent: System.Web.Configuration.Internal.IInternalConfigWebHost
  isExternal: false
  name: GetSiteIDAndVPathFromConfigPath
  nameWithType: IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath
