### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  id: MessageSecurityOverMsmqElement
  children:
  - System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.#ctor
  - System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite
  - System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType
  - System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties
  langs:
  - csharp
  name: MessageSecurityOverMsmqElement
  nameWithType: MessageSecurityOverMsmqElement
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  type: Class
  summary: "Permite configurar as propriedades de segurança de nível de mensagem a <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> associação."
  syntax:
    content: 'public sealed class MessageSecurityOverMsmqElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  langs:
  - csharp
  name: MessageSecurityOverMsmqElement()
  nameWithType: MessageSecurityOverMsmqElement.MessageSecurityOverMsmqElement()
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.MessageSecurityOverMsmqElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.ServiceModel.Configuration.MessageSecurityOverMsmqElement&quot;> </xref> classe."
  syntax:
    content: public MessageSecurityOverMsmqElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite
  id: AlgorithmSuite
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  langs:
  - csharp
  name: AlgorithmSuite
  nameWithType: MessageSecurityOverMsmqElement.AlgorithmSuite
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Especifica o conjunto de algoritmos usado para mensagens de segurança no nível de SOAP."
  remarks: "<xref:System.ServiceModel.Security.SecurityAlgorithmSuite>define uma variedade de algoritmos como canonização, Digest, KeyWrap, assinatura, criptografia e KeyDerivation.</xref:System.ServiceModel.Security.SecurityAlgorithmSuite> Essa propriedade é mais relevante ao trabalhar com uma plataforma que usa um conjunto de algoritmos diferentes do padrão. Você deve conhecer as vantagens e desvantagens dos algoritmos relevantes ao fazer modificações para essa propriedade."
  syntax:
    content: public System.ServiceModel.Security.SecurityAlgorithmSuite AlgorithmSuite { get; set; }
    return:
      type: System.ServiceModel.Security.SecurityAlgorithmSuite
      description: "O <xref href=&quot;System.ServiceModel.Security.SecurityAlgorithmSuite&quot;> </xref> configuração para mensagens enviadas pelo <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> associação."
  overload: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType
  id: ClientCredentialType
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  langs:
  - csharp
  name: ClientCredentialType
  nameWithType: MessageSecurityOverMsmqElement.ClientCredentialType
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém ou define o <xref:System.ServiceModel.MessageCredentialType>configuração de segurança para mensagens enviadas por meio do transporte MSMQ.</xref:System.ServiceModel.MessageCredentialType>"
  remarks: "Essa propriedade pode ser definida para um dos seguintes valores:-None: Isso permite que o serviço interaja com clientes anônimos. O serviço, nem o cliente requer uma credencial.      -Windows: Isso permite que as trocas SOAP estar sob o contexto autenticado de uma credencial do Windows. Isso sempre realiza a autenticação Kerberos.      -Nome de usuário: Isso permite que o serviço exigir que o cliente seja autenticado usando uma credencial de nome de usuário. Essa credencial precisa ser especificado usando a <xref:System.ServiceModel.Description.ClientCredentials>classe.</xref:System.ServiceModel.Description.ClientCredentials>          > [!NOTE]      >   [!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)] não oferece suporte para enviar uma senha digest ou derivação de chaves usando a senha e essas chaves para segurança de mensagem. Como tal, [!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)] impõe que o exchange é protegido ao usar credenciais de nome de usuário. Esse modo requer que o certificado de serviço seja especificado no lado do cliente usando serviceCertificate e o comportamento de ClientCredential.      -O certificado: Isso permite que o serviço exigir que o cliente seja autenticado usando um certificado. A credencial do cliente nesse caso deve ser especificado usando o <xref:System.ServiceModel.Description.ClientCredentials>classe ou comportamento ClientCredentials.</xref:System.ServiceModel.Description.ClientCredentials> A credencial de serviço nesse caso deve ser especificado usando o <xref:System.ServiceModel.Description.ClientCredentials>classe ou comportamento ClientCredentials especificando o serviceCertificate.</xref:System.ServiceModel.Description.ClientCredentials>      -CardSpace: Isso permite que o serviço exigir que o cliente seja autenticado usando um [!INCLUDE[infocard1](~/add/includes/infocard1-md.md)]. O serviceCertiifcate deve ser provisionado no comportamento ClientCredential.       A credencial de certificado para o `MessageSecurityOverMsmq` é relevante apenas quando o modo de segurança é definido como `Both` ou `Message`."
  syntax:
    content: public System.ServiceModel.MessageCredentialType ClientCredentialType { get; set; }
    return:
      type: System.ServiceModel.MessageCredentialType
      description: "O <xref:System.ServiceModel.MessageCredentialType>configuração de segurança para mensagens enviadas por meio do transporte MSMQ.</xref:System.ServiceModel.MessageCredentialType>"
  overload: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  langs:
  - csharp
  name: Properties
  nameWithType: MessageSecurityOverMsmqElement.Properties
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A ser adicionado."
  overload: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.#ctor
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: MessageSecurityOverMsmqElement()
  nameWithType: MessageSecurityOverMsmqElement.MessageSecurityOverMsmqElement()
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.MessageSecurityOverMsmqElement()
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: AlgorithmSuite
  nameWithType: MessageSecurityOverMsmqElement.AlgorithmSuite
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite
- uid: System.ServiceModel.Security.SecurityAlgorithmSuite
  parent: System.ServiceModel.Security
  isExternal: false
  name: SecurityAlgorithmSuite
  nameWithType: SecurityAlgorithmSuite
  fullName: System.ServiceModel.Security.SecurityAlgorithmSuite
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: ClientCredentialType
  nameWithType: MessageSecurityOverMsmqElement.ClientCredentialType
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType
- uid: System.ServiceModel.MessageCredentialType
  parent: System.ServiceModel
  isExternal: true
  name: MessageCredentialType
  nameWithType: MessageCredentialType
  fullName: System.ServiceModel.MessageCredentialType
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: Properties
  nameWithType: MessageSecurityOverMsmqElement.Properties
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.#ctor*
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: MessageSecurityOverMsmqElement
  nameWithType: MessageSecurityOverMsmqElement.MessageSecurityOverMsmqElement
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite*
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: AlgorithmSuite
  nameWithType: MessageSecurityOverMsmqElement.AlgorithmSuite
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType*
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: ClientCredentialType
  nameWithType: MessageSecurityOverMsmqElement.ClientCredentialType
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties*
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: Properties
  nameWithType: MessageSecurityOverMsmqElement.Properties
