### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.HttpModulesSection
  id: HttpModulesSection
  children:
  - System.Web.Configuration.HttpModulesSection.#ctor
  - System.Web.Configuration.HttpModulesSection.Modules
  - System.Web.Configuration.HttpModulesSection.Properties
  langs:
  - csharp
  name: HttpModulesSection
  nameWithType: HttpModulesSection
  fullName: System.Web.Configuration.HttpModulesSection
  type: Class
  summary: "Configura um módulo HTTP para um aplicativo Web. Essa classe não pode ser herdada."
  remarks: "A classe HttpModulesSection fornece uma maneira de acessar e modificar programaticamente o `httpModules` seção de um arquivo de configuração.       Esse tipo é parte de um grupo que inclui o <xref:System.Web.Configuration.HttpModuleAction>e o <xref:System.Web.Configuration.HttpModuleActionCollection>tipos.</xref:System.Web.Configuration.HttpModuleActionCollection> </xref:System.Web.Configuration.HttpModuleAction>      > [!NOTE] > HttpModulesSection o pode ler e gravar informações de e para a seção correspondente do arquivo de configuração de acordo com a propriedade de seção <xref:System.Configuration.SectionInformation.AllowDefinition%2A>cujo valor é <xref:System.Configuration.ConfigurationAllowDefinition>.</xref:System.Configuration.ConfigurationAllowDefinition> </xref:System.Configuration.SectionInformation.AllowDefinition%2A>"
  example:
  - "This example demonstrates how to specify values declaratively for attributes of the `add` element within the `httpModules` section, which can also be accessed as members of the HttpModulesSection class.  \n  \n The following configuration file example shows how to specify values declaratively for the [httpModules Element (ASP.NET Settings Schema)](http://msdn.microsoft.com/en-us/5e28e921-ab9b-4584-a2f9-0f9aa08372e3) section.  \n  \n```  \n<httpModules>  \n    <add name=\"TimerModule\"   \n      type=\"Samples.Aspnet.Configuration.RequestTimeInterval, RequestTimeInterval Version=1.0.1557.23158, Culture=neutral,  \n      PublicKeyToken=7bfb33146a87b52e, processorArchitecture=MSIL\"/>  \n</httpModules>  \n```  \n  \n The following code example demonstrates how to use the HttpModulesSection class.  \n  \n [!code-cs[System.Web.Configuration.HttpModulesSection#1](~/add/codesnippet/csharp/t-system.web.configurati_66_1.cs)]\n [!code-vb[System.Web.Configuration.HttpModulesSection#1](~/add/codesnippet/visualbasic/t-system.web.configurati_66_1.vb)]"
  syntax:
    content: 'public sealed class HttpModulesSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.HttpModulesSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.HttpModulesSection
  langs:
  - csharp
  name: HttpModulesSection()
  nameWithType: HttpModulesSection.HttpModulesSection()
  fullName: System.Web.Configuration.HttpModulesSection.HttpModulesSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Web.Configuration.HttpModulesSection&quot;> </xref> classe."
  remarks: "O construtor HttpModulesSection não se destina a ser usado diretamente no seu código. Ele é chamado pelo sistema de configuração do ASP.NET. Obter uma instância de <xref:System.Web.Configuration.HttpModulesSection>classe usando o <xref:System.Configuration.Configuration.GetSection%2A>método.</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.HttpModulesSection>"
  syntax:
    content: public HttpModulesSection ();
    parameters: []
  overload: System.Web.Configuration.HttpModulesSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpModulesSection.Modules
  id: Modules
  parent: System.Web.Configuration.HttpModulesSection
  langs:
  - csharp
  name: Modules
  nameWithType: HttpModulesSection.Modules
  fullName: System.Web.Configuration.HttpModulesSection.Modules
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Obtém o <xref href=&quot;System.Web.Configuration.HttpModuleActionCollection&quot;> </xref> de <xref href=&quot;System.Web.Configuration.HttpModuleAction&quot;> </xref> módulos contidos pelo <xref href=&quot;System.Web.Configuration.HttpModulesSection&quot;> </xref>."
  remarks: "A coleção retornada por este método não faz referência a qualquer elemento no arquivo de configuração subjacentes. É uma construção de infraestrutura do ASP.NET que permite o fácil acesso para os módulos que ele contém. Este é um padrão comum para lidar com os elementos de um arquivo de configuração."
  example:
  - "The following code example shows how to access the <xref:System.Web.Configuration.HttpModuleAction> modules.  \n  \n [!code-cs[System.Web.Configuration.HttpModulesSection#3](~/add/codesnippet/csharp/p-system.web.configurati_383_1.cs)]\n [!code-vb[System.Web.Configuration.HttpModulesSection#3](~/add/codesnippet/visualbasic/p-system.web.configurati_383_1.vb)]"
  syntax:
    content: public System.Web.Configuration.HttpModuleActionCollection Modules { get; }
    return:
      type: System.Web.Configuration.HttpModuleActionCollection
      description: "Um <xref href=&quot;System.Web.Configuration.HttpModuleActionCollection&quot;> </xref> que contém o <xref href=&quot;System.Web.Configuration.HttpModuleAction&quot;> </xref> objetos ou módulos, definidos pelo <xref href=&quot;System.Web.Configuration.HttpModulesSection&quot;> </xref>."
  overload: System.Web.Configuration.HttpModulesSection.Modules*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpModulesSection.Properties
  id: Properties
  parent: System.Web.Configuration.HttpModulesSection
  langs:
  - csharp
  name: Properties
  nameWithType: HttpModulesSection.Properties
  fullName: System.Web.Configuration.HttpModulesSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A ser adicionado."
  overload: System.Web.Configuration.HttpModulesSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.HttpModulesSection.#ctor
  parent: System.Web.Configuration.HttpModulesSection
  isExternal: false
  name: HttpModulesSection()
  nameWithType: HttpModulesSection.HttpModulesSection()
  fullName: System.Web.Configuration.HttpModulesSection.HttpModulesSection()
- uid: System.Web.Configuration.HttpModulesSection.Modules
  parent: System.Web.Configuration.HttpModulesSection
  isExternal: false
  name: Modules
  nameWithType: HttpModulesSection.Modules
  fullName: System.Web.Configuration.HttpModulesSection.Modules
- uid: System.Web.Configuration.HttpModuleActionCollection
  parent: System.Web.Configuration
  isExternal: false
  name: HttpModuleActionCollection
  nameWithType: HttpModuleActionCollection
  fullName: System.Web.Configuration.HttpModuleActionCollection
- uid: System.Web.Configuration.HttpModulesSection.Properties
  parent: System.Web.Configuration.HttpModulesSection
  isExternal: false
  name: Properties
  nameWithType: HttpModulesSection.Properties
  fullName: System.Web.Configuration.HttpModulesSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.HttpModulesSection.#ctor*
  parent: System.Web.Configuration.HttpModulesSection
  isExternal: false
  name: HttpModulesSection
  nameWithType: HttpModulesSection.HttpModulesSection
- uid: System.Web.Configuration.HttpModulesSection.Modules*
  parent: System.Web.Configuration.HttpModulesSection
  isExternal: false
  name: Modules
  nameWithType: HttpModulesSection.Modules
- uid: System.Web.Configuration.HttpModulesSection.Properties*
  parent: System.Web.Configuration.HttpModulesSection
  isExternal: false
  name: Properties
  nameWithType: HttpModulesSection.Properties
