### YamlMime:ManagedReference
items:
- uid: System.Configuration.ContextInformation
  id: ContextInformation
  children:
  - System.Configuration.ContextInformation.GetSection(System.String)
  - System.Configuration.ContextInformation.HostingContext
  - System.Configuration.ContextInformation.IsMachineLevel
  langs:
  - csharp
  name: ContextInformation
  nameWithType: ContextInformation
  fullName: System.Configuration.ContextInformation
  type: Class
  summary: "Encapsula as informações de contexto que estão associadas com um <xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref> objeto. Essa classe não pode ser herdada."
  remarks: "O objeto ContextInformation fornece detalhes relacionados a um elemento da configuração do ambiente. Por exemplo, você pode usar o <xref:System.Configuration.ContextInformation.IsMachineLevel%2A>para determinar se um <xref:System.Configuration.ConfigurationElement>foi definida em Machine. config, ou você pode determinar qual hierarquia um <xref:System.Configuration.ConfigurationElement>pertence a usando o <xref:System.Configuration.ContextInformation.HostingContext%2A>propriedade.</xref:System.Configuration.ContextInformation.HostingContext%2A> </xref:System.Configuration.ConfigurationElement> </xref:System.Configuration.ConfigurationElement> </xref:System.Configuration.ContextInformation.IsMachineLevel%2A>"
  example:
  - "The following code example demonstrates how to use the ContextInformation type.  \n  \n [!code-vb[System.Configuration.ContextInformation#1](~/add/codesnippet/visualbasic/t-system.configuration.c_0_1.vb)]\n [!code-cs[System.Configuration.ContextInformation#1](~/add/codesnippet/csharp/t-system.configuration.c_0_1.cs)]"
  syntax:
    content: public sealed class ContextInformation
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ContextInformation.GetSection(System.String)
  id: GetSection(System.String)
  parent: System.Configuration.ContextInformation
  langs:
  - csharp
  name: GetSection(String)
  nameWithType: ContextInformation.GetSection(String)
  fullName: System.Configuration.ContextInformation.GetSection(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Fornece um objeto que contém informações de seção de configuração com base no nome da seção especificada."
  remarks: "Ao especificar uma seção dentro da configuração, observe que o nome da seção de configuração diferencia maiusculas de minúsculas."
  syntax:
    content: public object GetSection (string sectionName);
    parameters:
    - id: sectionName
      type: System.String
      description: "O nome da seção de configuração."
    return:
      type: System.Object
      description: "Um objeto que contém a seção especificada na configuração."
  overload: System.Configuration.ContextInformation.GetSection*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ContextInformation.HostingContext
  id: HostingContext
  parent: System.Configuration.ContextInformation
  langs:
  - csharp
  name: HostingContext
  nameWithType: ContextInformation.HostingContext
  fullName: System.Configuration.ContextInformation.HostingContext
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Obtém o contexto do ambiente onde a propriedade de configuração está sendo avaliada."
  remarks: "O valor de HostingContext possível é <xref:System.Web.Configuration.WebContext>, <xref:System.Configuration.ExeContext>, ou `null`.</xref:System.Configuration.ExeContext> </xref:System.Web.Configuration.WebContext>"
  example:
  - "The following code example demonstrates how to use the HostingContext property.  \n  \n [!code-vb[System.Configuration.ContextInformation#3](~/add/codesnippet/visualbasic/p-system.configuration.c_46_1.vb)]\n [!code-cs[System.Configuration.ContextInformation#3](~/add/codesnippet/csharp/p-system.configuration.c_46_1.cs)]"
  syntax:
    content: public object HostingContext { get; }
    return:
      type: System.Object
      description: "Um objeto que especifica o ambiente em que a propriedade de configuração está sendo avaliada."
  overload: System.Configuration.ContextInformation.HostingContext*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ContextInformation.IsMachineLevel
  id: IsMachineLevel
  parent: System.Configuration.ContextInformation
  langs:
  - csharp
  name: IsMachineLevel
  nameWithType: ContextInformation.IsMachineLevel
  fullName: System.Configuration.ContextInformation.IsMachineLevel
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Obtém um valor que especifica se a propriedade de configuração está sendo avaliada no nível de configuração do computador."
  remarks: "Quando o valor retornado de IsMachineLevel é `false`, use o <xref:System.Configuration.ContextInformation.HostingContext%2A>propriedade para determinar o nível dentro da hierarquia de configuração.</xref:System.Configuration.ContextInformation.HostingContext%2A>"
  example:
  - "The following code example demonstrates how to use the <xref:System.Configuration.ContextInformation.HostingContext%2A> property.  \n  \n [!code-vb[System.Configuration.ContextInformation#2](~/add/codesnippet/visualbasic/p-system.configuration.c_7_1.vb)]\n [!code-cs[System.Configuration.ContextInformation#2](~/add/codesnippet/csharp/p-system.configuration.c_7_1.cs)]"
  syntax:
    content: public bool IsMachineLevel { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se a propriedade de configuração está sendo avaliada no nível de configuração do computador; Caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.ContextInformation.IsMachineLevel*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ContextInformation.GetSection(System.String)
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: GetSection(String)
  nameWithType: ContextInformation.GetSection(String)
  fullName: System.Configuration.ContextInformation.GetSection(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ContextInformation.HostingContext
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: HostingContext
  nameWithType: ContextInformation.HostingContext
  fullName: System.Configuration.ContextInformation.HostingContext
- uid: System.Configuration.ContextInformation.IsMachineLevel
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: IsMachineLevel
  nameWithType: ContextInformation.IsMachineLevel
  fullName: System.Configuration.ContextInformation.IsMachineLevel
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.ContextInformation.GetSection*
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: GetSection
  nameWithType: ContextInformation.GetSection
- uid: System.Configuration.ContextInformation.HostingContext*
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: HostingContext
  nameWithType: ContextInformation.HostingContext
- uid: System.Configuration.ContextInformation.IsMachineLevel*
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: IsMachineLevel
  nameWithType: ContextInformation.IsMachineLevel
