### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationElementCollectionType
  id: ConfigurationElementCollectionType
  children:
  - System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMap
  - System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMapAlternate
  - System.Configuration.ConfigurationElementCollectionType.BasicMap
  - System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate
  langs:
  - csharp
  name: ConfigurationElementCollectionType
  nameWithType: ConfigurationElementCollectionType
  fullName: System.Configuration.ConfigurationElementCollectionType
  type: Enum
  summary: "Especifica o tipo de um objeto ConfigurationElementCollectionType."
  remarks: "Esta enumeração contém todos os possíveis valores de retorno para o <xref:System.Configuration.ConfigurationElementCollection.CollectionType%2A>propriedade.</xref:System.Configuration.ConfigurationElementCollection.CollectionType%2A> Ele é usado pelo sistema de configuração durante o tempo de execução para mesclar corretamente as definições de configuração. Ele também é usado quando a criação de uma classe personalizada que estende o <xref:System.Configuration.ConfigurationElementCollection>.</xref:System.Configuration.ConfigurationElementCollection>       Por padrão, o tipo de um <xref:System.Configuration.ConfigurationElementCollection>objeto é AddRemoveClearMap.</xref:System.Configuration.ConfigurationElementCollection> Se um BasicMap for necessário, substitua a propriedade de ConfigurationElementCollectionType ao estender <xref:System.Configuration.ConfigurationElementCollection>.</xref:System.Configuration.ConfigurationElementCollection>"
  syntax:
    content: public enum ConfigurationElementCollectionType
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMap
  id: AddRemoveClearMap
  parent: System.Configuration.ConfigurationElementCollectionType
  langs:
  - csharp
  name: AddRemoveClearMap
  nameWithType: ConfigurationElementCollectionType.AddRemoveClearMap
  fullName: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMap
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "O tipo padrão de <xref href=&quot;System.Configuration.ConfigurationElementCollection&quot;> </xref>. Coleções desse tipo contenham elementos que podem ser mesclados em uma hierarquia de arquivos de configuração. Em qualquer nível específico na hierarquia, <xref uid=&quot;langword_csharp_add&quot; name=&quot;add&quot; href=&quot;&quot;> </xref>, <xref uid=&quot;langword_csharp_remove&quot; name=&quot;remove&quot; href=&quot;&quot;> </xref>, e <xref uid=&quot;langword_csharp_clear&quot; name=&quot;clear&quot; href=&quot;&quot;> </xref> as diretivas são usadas para modificar as propriedades herdadas e especificar novos."
  syntax:
    content: AddRemoveClearMap
    return:
      type: System.Configuration.ConfigurationElementCollectionType
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMapAlternate
  id: AddRemoveClearMapAlternate
  parent: System.Configuration.ConfigurationElementCollectionType
  langs:
  - csharp
  name: AddRemoveClearMapAlternate
  nameWithType: ConfigurationElementCollectionType.AddRemoveClearMapAlternate
  fullName: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMapAlternate
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Mesmo que AddRemoveClearMap, exceto que faz com que esse tipo de <xref href=&quot;System.Configuration.ConfigurationElementCollection&quot;> </xref> objeto para classificar o seu conteúdo, de modo que os elementos herdados são listados por último."
  syntax:
    content: AddRemoveClearMapAlternate
    return:
      type: System.Configuration.ConfigurationElementCollectionType
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationElementCollectionType.BasicMap
  id: BasicMap
  parent: System.Configuration.ConfigurationElementCollectionType
  langs:
  - csharp
  name: BasicMap
  nameWithType: ConfigurationElementCollectionType.BasicMap
  fullName: System.Configuration.ConfigurationElementCollectionType.BasicMap
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Coleções desse tipo contêm elementos que se aplicam ao nível no qual eles são especificados e a todos os níveis filho. Um nível filho não é possível modificar as propriedades especificadas por um elemento pai desse tipo."
  syntax:
    content: BasicMap
    return:
      type: System.Configuration.ConfigurationElementCollectionType
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate
  id: BasicMapAlternate
  parent: System.Configuration.ConfigurationElementCollectionType
  langs:
  - csharp
  name: BasicMapAlternate
  nameWithType: ConfigurationElementCollectionType.BasicMapAlternate
  fullName: System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Mesmo que BasicMap, exceto que faz com que esse tipo de <xref href=&quot;System.Configuration.ConfigurationElementCollection&quot;> </xref> objeto para classificar o seu conteúdo, de modo que os elementos herdados são listados por último."
  syntax:
    content: BasicMapAlternate
    return:
      type: System.Configuration.ConfigurationElementCollectionType
      description: "A ser adicionado."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMap
  parent: System.Configuration.ConfigurationElementCollectionType
  isExternal: false
  name: AddRemoveClearMap
  nameWithType: ConfigurationElementCollectionType.AddRemoveClearMap
  fullName: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMap
- uid: System.Configuration.ConfigurationElementCollectionType
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElementCollectionType
  nameWithType: ConfigurationElementCollectionType
  fullName: System.Configuration.ConfigurationElementCollectionType
- uid: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMapAlternate
  parent: System.Configuration.ConfigurationElementCollectionType
  isExternal: false
  name: AddRemoveClearMapAlternate
  nameWithType: ConfigurationElementCollectionType.AddRemoveClearMapAlternate
  fullName: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMapAlternate
- uid: System.Configuration.ConfigurationElementCollectionType.BasicMap
  parent: System.Configuration.ConfigurationElementCollectionType
  isExternal: false
  name: BasicMap
  nameWithType: ConfigurationElementCollectionType.BasicMap
  fullName: System.Configuration.ConfigurationElementCollectionType.BasicMap
- uid: System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate
  parent: System.Configuration.ConfigurationElementCollectionType
  isExternal: false
  name: BasicMapAlternate
  nameWithType: ConfigurationElementCollectionType.BasicMapAlternate
  fullName: System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate
