### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingChangingEventArgs
  id: SettingChangingEventArgs
  children:
  - System.Configuration.SettingChangingEventArgs.#ctor(System.String,System.String,System.String,System.Object,System.Boolean)
  - System.Configuration.SettingChangingEventArgs.NewValue
  - System.Configuration.SettingChangingEventArgs.SettingClass
  - System.Configuration.SettingChangingEventArgs.SettingKey
  - System.Configuration.SettingChangingEventArgs.SettingName
  langs:
  - csharp
  name: SettingChangingEventArgs
  nameWithType: SettingChangingEventArgs
  fullName: System.Configuration.SettingChangingEventArgs
  type: Class
  summary: "Fornece dados para o <xref href=&quot;System.Configuration.ApplicationSettingsBase.SettingChanging&quot;> </xref> eventos."
  remarks: "A classe SettingChangingEventArgs fornece dados para o <xref:System.Configuration.ApplicationSettingsBase.SettingChanging>evento, que indica que o valor de uma propriedade de configurações do aplicativo está prestes a ser alterada.</xref:System.Configuration.ApplicationSettingsBase.SettingChanging> A origem mais comum para esse evento é o `get` acessador do <xref:System.Configuration.ApplicationSettingsBase.Item%2A>método de <xref:System.Configuration.ApplicationSettingsBase>classe.</xref:System.Configuration.ApplicationSettingsBase> </xref:System.Configuration.ApplicationSettingsBase.Item%2A>       Porque SettingChangingEventArgs é derivado de <xref:System.ComponentModel.CancelEventArgs>, o manipulador tem a opção de cancelar a operação de gravação.</xref:System.ComponentModel.CancelEventArgs>"
  syntax:
    content: 'public class SettingChangingEventArgs : System.ComponentModel.CancelEventArgs'
  inheritance:
  - System.ComponentModel.CancelEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingChangingEventArgs.#ctor(System.String,System.String,System.String,System.Object,System.Boolean)
  id: '#ctor(System.String,System.String,System.String,System.Object,System.Boolean)'
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: SettingChangingEventArgs(String,String,String,Object,Boolean)
  nameWithType: SettingChangingEventArgs.SettingChangingEventArgs(String,String,String,Object,Boolean)
  fullName: System.Configuration.SettingChangingEventArgs.SettingChangingEventArgs(String,String,String,Object,Boolean)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicializa uma instância do <xref href=&quot;System.Configuration.SettingChangingEventArgs&quot;> </xref> classe."
  remarks: "O construtor SettingChangingEventArgs apenas atribui os valores dos parâmetros para as propriedades correspondentes na <xref:System.Configuration.SettingChangingEventArgs>classe.</xref:System.Configuration.SettingChangingEventArgs>"
  syntax:
    content: public SettingChangingEventArgs (string settingName, string settingClass, string settingKey, object newValue, bool cancel);
    parameters:
    - id: settingName
      type: System.String
      description: "Um <xref:System.String>que contém o nome da configuração do aplicativo.</xref:System.String>"
    - id: settingClass
      type: System.String
      description: "Um <xref:System.String>que contém uma descrição da categoria da configuração.</xref:System.String> Geralmente, esse parâmetro é definido para o nome de grupo de configurações do aplicativo."
    - id: settingKey
      type: System.String
      description: "Um <xref:System.String>que contém a chave de configurações do aplicativo.</xref:System.String>"
    - id: newValue
      type: System.Object
      description: "Um <xref:System.Object>que contém o novo valor a ser atribuído à propriedade de configurações de aplicativo.</xref:System.Object>"
    - id: cancel
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Para cancelar o evento; Caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.SettingChangingEventArgs.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingChangingEventArgs.NewValue
  id: NewValue
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: NewValue
  nameWithType: SettingChangingEventArgs.NewValue
  fullName: System.Configuration.SettingChangingEventArgs.NewValue
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Obtém o novo valor que está sendo atribuído à propriedade de configurações do aplicativo."
  remarks: "O tipo real da propriedade NewValue deve ser compatível com a propriedade de configurações está sendo definida. Este último está disponível por meio de <xref:System.Configuration.SettingsProperty.PropertyType%2A>propriedade de <xref:System.Configuration.SettingsProperty>classe.</xref:System.Configuration.SettingsProperty> </xref:System.Configuration.SettingsProperty.PropertyType%2A>"
  syntax:
    content: public object NewValue { get; }
    return:
      type: System.Object
      description: "Um <xref:System.Object>que contém o novo valor a ser atribuído à propriedade de configurações de aplicativo.</xref:System.Object>"
  overload: System.Configuration.SettingChangingEventArgs.NewValue*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingChangingEventArgs.SettingClass
  id: SettingClass
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: SettingClass
  nameWithType: SettingChangingEventArgs.SettingClass
  fullName: System.Configuration.SettingChangingEventArgs.SettingClass
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Obtém a categoria de propriedade de configurações do aplicativo."
  remarks: "Todas as configurações de aplicativo pertencem a um grupo de configurações do aplicativo. O nome do grupo pode ser fornecido explicitamente decorando a classe com um <xref:System.Configuration.SettingsGroupNameAttribute>caso contrário, um é gerado usando o nome da classe de invólucro de configurações.</xref:System.Configuration.SettingsGroupNameAttribute>"
  syntax:
    content: public string SettingClass { get; }
    return:
      type: System.String
      description: "Um <xref:System.String>que contém uma descrição da categoria da configuração.</xref:System.String> Normalmente, esse parâmetro é definido como o nome de grupo de configurações do aplicativo."
  overload: System.Configuration.SettingChangingEventArgs.SettingClass*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingChangingEventArgs.SettingKey
  id: SettingKey
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: SettingKey
  nameWithType: SettingChangingEventArgs.SettingKey
  fullName: System.Configuration.SettingChangingEventArgs.SettingKey
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Obtém a chave de configurações do aplicativo associada à propriedade."
  remarks: "Cada classe de wrapper de configurações, derivada de <xref:System.Configuration.ApplicationSettingsBase>, tem uma chave de configurações associadas, que é uma cadeia de caracteres que ajuda a resolver a ambiguidade de instâncias diferentes do mesmo wrapper em um único aplicativo.</xref:System.Configuration.ApplicationSettingsBase> Como cada classe wrapper define um conjunto de propriedades que representam as configurações do aplicativo, a chave de configurações da mesma forma pode ajudar a resolver a ambiguidade de seu uso."
  syntax:
    content: public string SettingKey { get; }
    return:
      type: System.String
      description: "Um <xref:System.String>que contém a chave de configurações do aplicativo.</xref:System.String>"
  overload: System.Configuration.SettingChangingEventArgs.SettingKey*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingChangingEventArgs.SettingName
  id: SettingName
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: SettingName
  nameWithType: SettingChangingEventArgs.SettingName
  fullName: System.Configuration.SettingChangingEventArgs.SettingName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Obtém o nome da configuração do aplicativo associado à propriedade de configurações do aplicativo."
  remarks: "Normalmente a classe de invólucro de configurações, é derivada de <xref:System.Configuration.ApplicationSettingsBase>, será construído para que o nome da propriedade de configurações do aplicativo será o mesmo que sua configuração de aplicativo associado.</xref:System.Configuration.ApplicationSettingsBase>"
  syntax:
    content: public string SettingName { get; }
    return:
      type: System.String
      description: "Um <xref:System.String>que contém o nome da configuração do aplicativo.</xref:System.String>"
  overload: System.Configuration.SettingChangingEventArgs.SettingName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ComponentModel.CancelEventArgs
  isExternal: false
  name: System.ComponentModel.CancelEventArgs
- uid: System.Configuration.SettingChangingEventArgs.#ctor(System.String,System.String,System.String,System.Object,System.Boolean)
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingChangingEventArgs(String,String,String,Object,Boolean)
  nameWithType: SettingChangingEventArgs.SettingChangingEventArgs(String,String,String,Object,Boolean)
  fullName: System.Configuration.SettingChangingEventArgs.SettingChangingEventArgs(String,String,String,Object,Boolean)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.SettingChangingEventArgs.NewValue
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: NewValue
  nameWithType: SettingChangingEventArgs.NewValue
  fullName: System.Configuration.SettingChangingEventArgs.NewValue
- uid: System.Configuration.SettingChangingEventArgs.SettingClass
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingClass
  nameWithType: SettingChangingEventArgs.SettingClass
  fullName: System.Configuration.SettingChangingEventArgs.SettingClass
- uid: System.Configuration.SettingChangingEventArgs.SettingKey
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingKey
  nameWithType: SettingChangingEventArgs.SettingKey
  fullName: System.Configuration.SettingChangingEventArgs.SettingKey
- uid: System.Configuration.SettingChangingEventArgs.SettingName
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingName
  nameWithType: SettingChangingEventArgs.SettingName
  fullName: System.Configuration.SettingChangingEventArgs.SettingName
- uid: System.Configuration.SettingChangingEventArgs.#ctor*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingChangingEventArgs
  nameWithType: SettingChangingEventArgs.SettingChangingEventArgs
- uid: System.Configuration.SettingChangingEventArgs.NewValue*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: NewValue
  nameWithType: SettingChangingEventArgs.NewValue
- uid: System.Configuration.SettingChangingEventArgs.SettingClass*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingClass
  nameWithType: SettingChangingEventArgs.SettingClass
- uid: System.Configuration.SettingChangingEventArgs.SettingKey*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingKey
  nameWithType: SettingChangingEventArgs.SettingKey
- uid: System.Configuration.SettingChangingEventArgs.SettingName*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingName
  nameWithType: SettingChangingEventArgs.SettingName
