### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs
  id: DeploymentProgressChangedEventArgs
  children:
  - System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
  - System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
  - System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
  - System.Deployment.Application.DeploymentProgressChangedEventArgs.State
  langs:
  - csharp
  name: DeploymentProgressChangedEventArgs
  nameWithType: DeploymentProgressChangedEventArgs
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs
  type: Class
  summary: "Representa dados de progresso relatados em uma operação assíncrona."
  remarks: "Essa classe contém propriedades que descrevem o andamento para o <xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged>, <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>, e <xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged>eventos.</xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged> </xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged> </xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged> Não todas as propriedades desta classe se aplica a cada evento.       <xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted%2A>e <xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal%2A>representam o número total de bytes baixados para data e o número total de bytes na operação de download, respectivamente; elas se aplicam a todos os três eventos.</xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal%2A></xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted%2A> <xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.Group%2A>nomes de grupo de arquivos correspondente ao atual <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>evento, e <xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.State%2A>reflete o estágio atual da operação de download.</xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.State%2A> </xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged></xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.Group%2A>"
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!code-cs[ClickOnceAPI#8](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#8)]\n [!code-cpp[ClickOnceAPI#8](~/add/codesnippet/cpp/t-system.deployment.appl_5_1.cpp)]\n [!code-vb[ClickOnceAPI#8](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#8)]"
  syntax:
    content: 'public class DeploymentProgressChangedEventArgs : System.ComponentModel.ProgressChangedEventArgs'
  inheritance:
  - System.ComponentModel.ProgressChangedEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
  id: BytesCompleted
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  langs:
  - csharp
  name: BytesCompleted
  nameWithType: DeploymentProgressChangedEventArgs.BytesCompleted
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Obtém o número de bytes já baixados por essa operação."
  remarks: "Para <xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged>, a propriedade BytesCompleted refere-se para o download do manifesto de implantação.</xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged> Para <xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged>, a propriedade refere-se para o andamento do download de toda a atualização, incluído os arquivos de dados, assemblies e manifestos.</xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged> Para <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>, a propriedade se refere ao andamento do download de todo o conjunto de arquivos que fazem parte de um grupo nomeado.</xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>"
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!code-cs[ClickOnceAPI#8](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#8)]\n [!code-cpp[ClickOnceAPI#8](~/add/codesnippet/cpp/c5260b60-c259-429d-9763-_1.cpp)]\n [!code-vb[ClickOnceAPI#8](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#8)]"
  syntax:
    content: public long BytesCompleted { get; }
    return:
      type: System.Int64
      description: "Um <xref:System.Int64>que representa os dados já transferidos, em bytes.</xref:System.Int64>"
  overload: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
  id: BytesTotal
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  langs:
  - csharp
  name: BytesTotal
  nameWithType: DeploymentProgressChangedEventArgs.BytesTotal
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Obtém o número total de bytes na operação de download."
  remarks: "Para <xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged>, a propriedade BytesTotal refere-se para o download do manifesto de implantação.</xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged> Para <xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged>, a propriedade refere-se para o andamento do download de toda a atualização, incluído os arquivos de dados, assemblies e manifestos.</xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged> Para <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>, a propriedade se refere ao andamento do download de todo o conjunto de arquivos que fazem parte de um grupo nomeado.</xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>"
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!code-cs[ClickOnceAPI#8](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#8)]\n [!code-cpp[ClickOnceAPI#8](~/add/codesnippet/cpp/p-system.deployment.appl_3_1.cpp)]\n [!code-vb[ClickOnceAPI#8](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#8)]"
  syntax:
    content: public long BytesTotal { get; }
    return:
      type: System.Int64
      description: "Um <xref:System.Int64>que representa o tamanho total do download, em bytes.</xref:System.Int64>"
  overload: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
  id: Group
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  langs:
  - csharp
  name: Group
  nameWithType: DeploymentProgressChangedEventArgs.Group
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Obtém o nome do grupo de arquivos que estão sendo baixado."
  remarks: "Você pode iniciar várias chamadas para <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupAsync%2A>e baixar vários grupos de arquivos simultaneamente.</xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupAsync%2A> Usar o grupo para determinar quais retornos de chamada do evento corresponde a qual grupo."
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!code-cs[ClickOnceAPI#8](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#8)]\n [!code-cpp[ClickOnceAPI#8](~/add/codesnippet/cpp/p-system.deployment.appl_4_1.cpp)]\n [!code-vb[ClickOnceAPI#8](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#8)]"
  syntax:
    content: public string Group { get; }
    return:
      type: System.String
      description: "Um <xref:System.String>que contém o nome do grupo de arquivos, se o evento ocorreu como resultado de uma chamada para <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupAsync*>; caso contrário, uma cadeia de caracteres de comprimento zero.</xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupAsync*> </xref:System.String>"
  overload: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.State
  id: State
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  langs:
  - csharp
  name: State
  nameWithType: DeploymentProgressChangedEventArgs.State
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.State
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Obtém a ação que o processo está em execução atualmente."
  remarks: ''
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!code-cs[ClickOnceAPI#8](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#8)]\n [!code-cpp[ClickOnceAPI#8](~/add/codesnippet/cpp/p-system.deployment.appl_11_1.cpp)]\n [!code-vb[ClickOnceAPI#8](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#8)]"
  syntax:
    content: public System.Deployment.Application.DeploymentProgressState State { get; }
    return:
      type: System.Deployment.Application.DeploymentProgressState
      description: "Um <xref href=&quot;System.Deployment.Application.DeploymentProgressState&quot;> </xref> valor, indicando que o elemento ou elementos a operação está baixando."
  overload: System.Deployment.Application.DeploymentProgressChangedEventArgs.State*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ComponentModel.ProgressChangedEventArgs
  isExternal: false
  name: System.ComponentModel.ProgressChangedEventArgs
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: BytesCompleted
  nameWithType: DeploymentProgressChangedEventArgs.BytesCompleted
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: BytesTotal
  nameWithType: DeploymentProgressChangedEventArgs.BytesTotal
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: Group
  nameWithType: DeploymentProgressChangedEventArgs.Group
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.State
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: State
  nameWithType: DeploymentProgressChangedEventArgs.State
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.State
- uid: System.Deployment.Application.DeploymentProgressState
  parent: System.Deployment.Application
  isExternal: false
  name: DeploymentProgressState
  nameWithType: DeploymentProgressState
  fullName: System.Deployment.Application.DeploymentProgressState
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted*
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: BytesCompleted
  nameWithType: DeploymentProgressChangedEventArgs.BytesCompleted
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal*
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: BytesTotal
  nameWithType: DeploymentProgressChangedEventArgs.BytesTotal
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group*
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: Group
  nameWithType: DeploymentProgressChangedEventArgs.Group
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.State*
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: State
  nameWithType: DeploymentProgressChangedEventArgs.State
