### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement
  id: X509CertificateTrustedIssuerElement
  children:
  - System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.#ctor
  - System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.Copy(System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement)
  - System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.FindValue
  - System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.Properties
  - System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.StoreLocation
  - System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.StoreName
  - System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.X509FindType
  langs:
  - csharp
  name: X509CertificateTrustedIssuerElement
  nameWithType: X509CertificateTrustedIssuerElement
  fullName: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement
  type: Class
  summary: "Representa um elemento de configuração que especifica um certificado emitido por um emissor confiável. Essa classe não pode ser herdada."
  syntax:
    content: 'public sealed class X509CertificateTrustedIssuerElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement
  langs:
  - csharp
  name: X509CertificateTrustedIssuerElement()
  nameWithType: X509CertificateTrustedIssuerElement.X509CertificateTrustedIssuerElement()
  fullName: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.X509CertificateTrustedIssuerElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement&quot;> </xref> classe."
  syntax:
    content: public X509CertificateTrustedIssuerElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.Copy(System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement)
  id: Copy(System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement)
  parent: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement
  langs:
  - csharp
  name: Copy(X509CertificateTrustedIssuerElement)
  nameWithType: X509CertificateTrustedIssuerElement.Copy(X509CertificateTrustedIssuerElement)
  fullName: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.Copy(X509CertificateTrustedIssuerElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Copia o conteúdo do elemento de configuração especificado para este elemento de configuração."
  syntax:
    content: public void Copy (System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement
      description: "O elemento de configuração a serem copiados."
  overload: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.Copy*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>from</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "O arquivo de configuração é somente leitura."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.FindValue
  id: FindValue
  parent: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement
  langs:
  - csharp
  name: FindValue
  nameWithType: X509CertificateTrustedIssuerElement.FindValue
  fullName: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.FindValue
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém ou define uma cadeia de caracteres que especifica o valor para pesquisar no repositório de certificados x.&509;."
  remarks: "O tipo contido na propriedade deve satisfazer os requisitos de especificado <xref:System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.X509FindType%2A>valor.</xref:System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.X509FindType%2A> O padrão é uma cadeia de caracteres vazia."
  syntax:
    content: public string FindValue { get; set; }
    return:
      type: System.String
      description: "O valor para pesquisar no repositório de certificados x.&509;."
  overload: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.FindValue*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement
  langs:
  - csharp
  name: Properties
  nameWithType: X509CertificateTrustedIssuerElement.Properties
  fullName: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A ser adicionado."
  overload: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.StoreLocation
  id: StoreLocation
  parent: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement
  langs:
  - csharp
  name: StoreLocation
  nameWithType: X509CertificateTrustedIssuerElement.StoreLocation
  fullName: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.StoreLocation
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém ou define um valor que especifica que o local do repositório de certificados do cliente pode usar para validar o certificado do servidor."
  syntax:
    content: public System.Security.Cryptography.X509Certificates.StoreLocation StoreLocation { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.StoreLocation
      description: "Um <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreLocation&quot;> </xref> que especifica o local do repositório de certificados do cliente pode usar para validar o certificado do servidor. O valor padrão é <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreLocation&quot;> </xref>."
  overload: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.StoreLocation*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.StoreName
  id: StoreName
  parent: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement
  langs:
  - csharp
  name: StoreName
  nameWithType: X509CertificateTrustedIssuerElement.StoreName
  fullName: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.StoreName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém ou define o nome do repositório de certificados x.&509; para abrir."
  syntax:
    content: public System.Security.Cryptography.X509Certificates.StoreName StoreName { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.StoreName
      description: "Um <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreName&quot;> </xref> que contém o nome do repositório de certificados x.&509; para abrir."
  overload: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.StoreName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.X509FindType
  id: X509FindType
  parent: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement
  langs:
  - csharp
  name: X509FindType
  nameWithType: X509CertificateTrustedIssuerElement.X509FindType
  fullName: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.X509FindType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém ou define o tipo de pesquisa x.&509; a ser executado."
  remarks: "O tipo contido <xref:System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.FindValue%2A>devem satisfazer os requisitos dessa propriedade.</xref:System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.FindValue%2A>"
  syntax:
    content: public System.Security.Cryptography.X509Certificates.X509FindType X509FindType { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.X509FindType
      description: "Um <xref href=&quot;System.Security.Cryptography.X509Certificates.X509FindType&quot;> </xref> que especifica o tipo de pesquisa x.&509; a ser executado."
  overload: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.X509FindType*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.#ctor
  parent: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement
  isExternal: false
  name: X509CertificateTrustedIssuerElement()
  nameWithType: X509CertificateTrustedIssuerElement.X509CertificateTrustedIssuerElement()
  fullName: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.X509CertificateTrustedIssuerElement()
- uid: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.Copy(System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement)
  parent: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement
  isExternal: false
  name: Copy(X509CertificateTrustedIssuerElement)
  nameWithType: X509CertificateTrustedIssuerElement.Copy(X509CertificateTrustedIssuerElement)
  fullName: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.Copy(X509CertificateTrustedIssuerElement)
- uid: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: X509CertificateTrustedIssuerElement
  nameWithType: X509CertificateTrustedIssuerElement
  fullName: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement
- uid: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.FindValue
  parent: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement
  isExternal: false
  name: FindValue
  nameWithType: X509CertificateTrustedIssuerElement.FindValue
  fullName: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.FindValue
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.Properties
  parent: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement
  isExternal: false
  name: Properties
  nameWithType: X509CertificateTrustedIssuerElement.Properties
  fullName: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.StoreLocation
  parent: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement
  isExternal: false
  name: StoreLocation
  nameWithType: X509CertificateTrustedIssuerElement.StoreLocation
  fullName: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.StoreLocation
- uid: System.Security.Cryptography.X509Certificates.StoreLocation
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: StoreLocation
  nameWithType: StoreLocation
  fullName: System.Security.Cryptography.X509Certificates.StoreLocation
- uid: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.StoreName
  parent: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement
  isExternal: false
  name: StoreName
  nameWithType: X509CertificateTrustedIssuerElement.StoreName
  fullName: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.StoreName
- uid: System.Security.Cryptography.X509Certificates.StoreName
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: StoreName
  nameWithType: StoreName
  fullName: System.Security.Cryptography.X509Certificates.StoreName
- uid: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.X509FindType
  parent: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement
  isExternal: false
  name: X509FindType
  nameWithType: X509CertificateTrustedIssuerElement.X509FindType
  fullName: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.X509FindType
- uid: System.Security.Cryptography.X509Certificates.X509FindType
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: X509FindType
  nameWithType: X509FindType
  fullName: System.Security.Cryptography.X509Certificates.X509FindType
- uid: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.#ctor*
  parent: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement
  isExternal: false
  name: X509CertificateTrustedIssuerElement
  nameWithType: X509CertificateTrustedIssuerElement.X509CertificateTrustedIssuerElement
- uid: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.Copy*
  parent: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement
  isExternal: false
  name: Copy
  nameWithType: X509CertificateTrustedIssuerElement.Copy
- uid: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.FindValue*
  parent: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement
  isExternal: false
  name: FindValue
  nameWithType: X509CertificateTrustedIssuerElement.FindValue
- uid: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.Properties*
  parent: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement
  isExternal: false
  name: Properties
  nameWithType: X509CertificateTrustedIssuerElement.Properties
- uid: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.StoreLocation*
  parent: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement
  isExternal: false
  name: StoreLocation
  nameWithType: X509CertificateTrustedIssuerElement.StoreLocation
- uid: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.StoreName*
  parent: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement
  isExternal: false
  name: StoreName
  nameWithType: X509CertificateTrustedIssuerElement.StoreName
- uid: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement.X509FindType*
  parent: System.ServiceModel.Configuration.X509CertificateTrustedIssuerElement
  isExternal: false
  name: X509FindType
  nameWithType: X509CertificateTrustedIssuerElement.X509FindType
