### YamlMime:ManagedReference
items:
- uid: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer
  id: QuaternionValueSerializer
  children:
  - System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.#ctor
  - System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: QuaternionValueSerializer
  nameWithType: QuaternionValueSerializer
  fullName: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer
  type: Class
  summary: "Converte as instâncias de <xref:System.String>para e de instâncias do <xref href=&quot;System.Windows.Media.Media3D.Quaternion&quot;> </xref>.</xref:System.String>"
  remarks: "Essa classe é destinada apenas a ser usado pelo <xref:System.Windows.Markup.Primitives.MarkupWriter>para fins de serialização.</xref:System.Windows.Markup.Primitives.MarkupWriter>"
  syntax:
    content: 'public class QuaternionValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.#ctor
  id: '#ctor'
  parent: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer
  langs:
  - csharp
  name: QuaternionValueSerializer()
  nameWithType: QuaternionValueSerializer.QuaternionValueSerializer()
  fullName: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.QuaternionValueSerializer()
  type: Constructor
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Media3D.Converters
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Windows.Media.Media3D.Converters.QuaternionValueSerializer&quot;> </xref> classe."
  syntax:
    content: public QuaternionValueSerializer ();
    parameters: []
  overload: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer
  langs:
  - csharp
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: QuaternionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Media3D.Converters
  summary: "Determina se a conversão de um determinado <xref:System.String>a uma instância de <xref href=&quot;System.Windows.Media.Media3D.Quaternion&quot;> </xref> é possível.</xref:System.String>"
  remarks: "Esse método sempre retornará `true`."
  syntax:
    content: public override bool CanConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "Cadeia de caracteres a ser avaliada para conversão."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Informações de contexto usadas para conversão."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se o valor pode ser convertido; Caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.CanConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: QuaternionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Media3D.Converters
  summary: "Determina se uma instância do <xref href=&quot;System.Windows.Media.Media3D.Quaternion&quot;> </xref> pode ser convertido em <xref:System.String>.</xref:System.String>"
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "Instância do <xref href=&quot;System.Windows.Media.Media3D.Quaternion&quot;> </xref> para avaliar para conversão."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Informações de contexto usadas para conversão."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se <code> value </code> pode ser convertido em um <xref:System.String>; caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.String>"
  overload: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.CanConvertToString*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "Occurs when <code>value</code> is not a <xref href=&quot;System.Windows.Media.Media3D.Quaternion&quot;></xref>."
  platform:
  - net462
- uid: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer
  langs:
  - csharp
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: QuaternionValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.ConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Media3D.Converters
  summary: "Converte um <xref:System.String>em um <xref href=&quot;System.Windows.Media.Media3D.Quaternion&quot;> </xref>.</xref:System.String>"
  syntax:
    content: public override object ConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "<xref:System.String>valor a ser convertido em um <xref href=&quot;System.Windows.Media.Media3D.Quaternion&quot;> </xref>.</xref:System.String>"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Informações de contexto usadas para conversão."
    return:
      type: System.Object
      description: "Uma nova instância da <xref href=&quot;System.Windows.Media.Media3D.Quaternion&quot;> </xref> com base em fornecido <code> value </code>."
  overload: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.ConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: QuaternionValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Media3D.Converters
  summary: "Converte uma instância de <xref href=&quot;System.Windows.Media.Media3D.Quaternion&quot;> </xref> para <xref:System.String>.</xref:System.String>"
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "Instância do <xref href=&quot;System.Windows.Media.Media3D.Quaternion&quot;> </xref> para avaliar para conversão."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Informações de contexto usadas para conversão."
    return:
      type: System.String
      description: "Um <xref:System.String>representação de fornecido <xref href=&quot;System.Windows.Media.Media3D.Quaternion&quot;> </xref> objeto.</xref:System.String>"
  overload: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.ConvertToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.#ctor
  parent: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer
  isExternal: false
  name: QuaternionValueSerializer()
  nameWithType: QuaternionValueSerializer.QuaternionValueSerializer()
  fullName: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.QuaternionValueSerializer()
- uid: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer
  isExternal: false
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: QuaternionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: QuaternionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer
  isExternal: false
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: QuaternionValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.ConvertFromString(String,IValueSerializerContext)
- uid: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: QuaternionValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.#ctor*
  parent: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer
  isExternal: false
  name: QuaternionValueSerializer
  nameWithType: QuaternionValueSerializer.QuaternionValueSerializer
- uid: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.CanConvertFromString*
  parent: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer
  isExternal: false
  name: CanConvertFromString
  nameWithType: QuaternionValueSerializer.CanConvertFromString
- uid: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.CanConvertToString*
  parent: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer
  isExternal: false
  name: CanConvertToString
  nameWithType: QuaternionValueSerializer.CanConvertToString
- uid: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.ConvertFromString*
  parent: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer
  isExternal: false
  name: ConvertFromString
  nameWithType: QuaternionValueSerializer.ConvertFromString
- uid: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer.ConvertToString*
  parent: System.Windows.Media.Media3D.Converters.QuaternionValueSerializer
  isExternal: false
  name: ConvertToString
  nameWithType: QuaternionValueSerializer.ConvertToString
