### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.TrustNotGrantedException
  id: TrustNotGrantedException
  children:
  - System.Deployment.Application.TrustNotGrantedException.#ctor
  - System.Deployment.Application.TrustNotGrantedException.#ctor(System.String)
  - System.Deployment.Application.TrustNotGrantedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.TrustNotGrantedException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: TrustNotGrantedException
  nameWithType: TrustNotGrantedException
  fullName: System.Deployment.Application.TrustNotGrantedException
  type: Class
  summary: "Indica que o aplicativo não tem o nível apropriado de confiança para ser executado no computador local."
  remarks: "Por padrão, [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] aplicativos recebem um nível de confiança em computadores cliente que impede que envolvidos em atividade possivelmente mal-intencionados, como excluir dados do disco rígido ou acessar a rede. Um [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] aplicativo pode usar elevação de permissão ou implantação de aplicativos confiáveis para solicitar um nível mais alto de confiança:-elevação de permissão pede ao usuário para conceder ao aplicativo em um nível mais alto de segurança.      -Implantação de aplicativo confiável corresponde à assinatura digital do [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] aplicativo com uma lista de editores confiáveis no computador local.       TrustNotGrantedException será lançada se: - o aplicativo usa a elevação de permissões e o usuário Negar a solicitação de confiança elevada; ou o aplicativo usa implantação de aplicativos confiáveis e o certificado digital usado para assinar o aplicativo não está listado como um editor confiável no computador local. Se você tiver implantado uma atualização para um aplicativo e a atualização usa mais permissões do que a versão anterior, e [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] lança um TrustNotGrantedException, a nova versão não será instalado."
  syntax:
    content: 'public class TrustNotGrantedException : System.Deployment.Application.DeploymentException'
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Deployment.Application.DeploymentException
  implements: []
  inheritedMembers:
  - System.Deployment.Application.DeploymentException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  platform:
  - net462
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.TrustNotGrantedException
  langs:
  - csharp
  name: TrustNotGrantedException()
  nameWithType: TrustNotGrantedException.TrustNotGrantedException()
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Deployment.Application.TrustNotGrantedException&quot;> </xref> classe com uma mensagem fornecida pelo sistema que descreve o erro."
  remarks: "Este construtor inicializa o <xref:System.Exception.Message%2A>propriedade da nova instância para uma mensagem fornecida pelo sistema que descreve o erro, como &quot;DefaultMessageDisplayedByParameterlessCtorWriterMustSupply&quot; Esta mensagem leva em conta a cultura atual do sistema.</xref:System.Exception.Message%2A>       A tabela a seguir mostra os valores de propriedade inicial para uma instância de <xref:System.InsufficientMemoryException>.</xref:System.InsufficientMemoryException>      | Propriedade | Valor |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| A cadeia de caracteres de mensagem de erro localizada. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public TrustNotGrantedException ();
    parameters: []
  overload: System.Deployment.Application.TrustNotGrantedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.TrustNotGrantedException
  langs:
  - csharp
  name: TrustNotGrantedException(String)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(String)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Deployment.Application.TrustNotGrantedException&quot;> </xref> classe com uma mensagem especificada que descreve o erro."
  remarks: "A tabela a seguir mostra os valores de propriedade inicial para uma instância de <xref:System.Deployment.Application.TrustNotGrantedException>.</xref:System.Deployment.Application.TrustNotGrantedException>      | Propriedade | Valor |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| A cadeia de caracteres de mensagem de erro especificada no `message`. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public TrustNotGrantedException (string message);
    parameters:
    - id: message
      type: System.String
      description: "A mensagem que descreve a exceção. O chamador desse construtor é necessário para garantir que essa cadeia de caracteres foi localizada para a cultura atual do sistema."
  overload: System.Deployment.Application.TrustNotGrantedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.TrustNotGrantedException
  langs:
  - csharp
  name: TrustNotGrantedException(SerializationInfo,StreamingContext)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Deployment.Application.TrustNotGrantedException&quot;> </xref> classe com os dados serializados."
  syntax:
    content: protected TrustNotGrantedException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "O objeto que contém os dados do objeto serializado."
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: "As informações contextuais sobre a origem ou destino."
  overload: System.Deployment.Application.TrustNotGrantedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.TrustNotGrantedException
  langs:
  - csharp
  name: TrustNotGrantedException(String,Exception)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(String,Exception)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(String,Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Deployment.Application.TrustNotGrantedException&quot;> </xref> classe com uma mensagem de erro especificada e uma referência à exceção interna que é a causa dessa exceção."
  syntax:
    content: public TrustNotGrantedException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "A mensagem que descreve a exceção. O chamador desse construtor é necessário para garantir que essa cadeia de caracteres foi localizada para a cultura atual do sistema."
    - id: innerException
      type: System.Exception
      description: "A exceção que é a causa da exceção atual. Se o `innerException` parâmetro não é <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, a exceção atual é gerada em um <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> bloco que manipula a exceção interna."
  overload: System.Deployment.Application.TrustNotGrantedException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Deployment.Application.DeploymentException
  isExternal: false
  name: System.Deployment.Application.DeploymentException
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException()
  nameWithType: TrustNotGrantedException.TrustNotGrantedException()
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException()
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.String)
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException(String)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(String)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException(SerializationInfo,StreamingContext)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException(String,Exception)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(String,Exception)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor*
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException
  nameWithType: TrustNotGrantedException.TrustNotGrantedException
