### YamlMime:ManagedReference
items:
- uid: System.Configuration.Provider.ProviderException
  id: ProviderException
  children:
  - System.Configuration.Provider.ProviderException.#ctor
  - System.Configuration.Provider.ProviderException.#ctor(System.String)
  - System.Configuration.Provider.ProviderException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Configuration.Provider.ProviderException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: ProviderException
  nameWithType: ProviderException
  fullName: System.Configuration.Provider.ProviderException
  type: Class
  summary: "A exceção que é lançada quando um erro do provedor de configuração. Essa classe de exceção também é usado por provedores de lançar exceções quando ocorrem erros internos no provedor que não são mapeadas para outras classes de exceção pré-existente."
  remarks: "O ProviderException é gerada quando ocorre um erro ao carregar um provedor de configuração."
  syntax:
    content: 'public class ProviderException : Exception'
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.Provider.ProviderException.#ctor
  id: '#ctor'
  parent: System.Configuration.Provider.ProviderException
  langs:
  - csharp
  name: ProviderException()
  nameWithType: ProviderException.ProviderException()
  fullName: System.Configuration.Provider.ProviderException.ProviderException()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: "Cria uma nova instância do <xref href=&quot;System.Configuration.Provider.ProviderException&quot;> </xref> classe."
  syntax:
    content: public ProviderException ();
    parameters: []
  overload: System.Configuration.Provider.ProviderException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Provider.ProviderException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.Provider.ProviderException
  langs:
  - csharp
  name: ProviderException(String)
  nameWithType: ProviderException.ProviderException(String)
  fullName: System.Configuration.Provider.ProviderException.ProviderException(String)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: "Cria uma nova instância do <xref href=&quot;System.Configuration.Provider.ProviderException&quot;> </xref> classe."
  syntax:
    content: public ProviderException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Uma mensagem que descreve por que isso <xref href=&quot;System.Configuration.Provider.ProviderException&quot;> </xref> foi lançada."
  overload: System.Configuration.Provider.ProviderException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Provider.ProviderException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Configuration.Provider.ProviderException
  langs:
  - csharp
  name: ProviderException(SerializationInfo,StreamingContext)
  nameWithType: ProviderException.ProviderException(SerializationInfo,StreamingContext)
  fullName: System.Configuration.Provider.ProviderException.ProviderException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: "Cria uma nova instância do <xref href=&quot;System.Configuration.Provider.ProviderException&quot;> </xref> classe."
  syntax:
    content: protected ProviderException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "O objeto que contém as informações a ser desserializado."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "Informações contextuais sobre a origem ou destino."
  overload: System.Configuration.Provider.ProviderException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Provider.ProviderException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Configuration.Provider.ProviderException
  langs:
  - csharp
  name: ProviderException(String,Exception)
  nameWithType: ProviderException.ProviderException(String,Exception)
  fullName: System.Configuration.Provider.ProviderException.ProviderException(String,Exception)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: "Cria uma nova instância do <xref href=&quot;System.Configuration.Provider.ProviderException&quot;> </xref> classe."
  syntax:
    content: public ProviderException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Uma mensagem que descreve por que isso <xref href=&quot;System.Configuration.Provider.ProviderException&quot;> </xref> foi lançada."
    - id: innerException
      type: System.Exception
      description: "A exceção que causou essa <xref href=&quot;System.Configuration.Provider.ProviderException&quot;> </xref> seja gerada."
  overload: System.Configuration.Provider.ProviderException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.Configuration.Provider.ProviderException.#ctor
  parent: System.Configuration.Provider.ProviderException
  isExternal: false
  name: ProviderException()
  nameWithType: ProviderException.ProviderException()
  fullName: System.Configuration.Provider.ProviderException.ProviderException()
- uid: System.Configuration.Provider.ProviderException.#ctor(System.String)
  parent: System.Configuration.Provider.ProviderException
  isExternal: false
  name: ProviderException(String)
  nameWithType: ProviderException.ProviderException(String)
  fullName: System.Configuration.Provider.ProviderException.ProviderException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Provider.ProviderException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Configuration.Provider.ProviderException
  isExternal: false
  name: ProviderException(SerializationInfo,StreamingContext)
  nameWithType: ProviderException.ProviderException(SerializationInfo,StreamingContext)
  fullName: System.Configuration.Provider.ProviderException.ProviderException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Configuration.Provider.ProviderException.#ctor(System.String,System.Exception)
  parent: System.Configuration.Provider.ProviderException
  isExternal: false
  name: ProviderException(String,Exception)
  nameWithType: ProviderException.ProviderException(String,Exception)
  fullName: System.Configuration.Provider.ProviderException.ProviderException(String,Exception)
- uid: System.Configuration.Provider.ProviderException.#ctor*
  parent: System.Configuration.Provider.ProviderException
  isExternal: false
  name: ProviderException
  nameWithType: ProviderException.ProviderException
