### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.Compiler
  id: Compiler
  children:
  - System.Web.Configuration.Compiler.#ctor(System.String,System.String,System.String,System.String,System.Int32)
  - System.Web.Configuration.Compiler.CompilerOptions
  - System.Web.Configuration.Compiler.Extension
  - System.Web.Configuration.Compiler.Language
  - System.Web.Configuration.Compiler.Properties
  - System.Web.Configuration.Compiler.Type
  - System.Web.Configuration.Compiler.WarningLevel
  langs:
  - csharp
  name: Compiler
  nameWithType: Compiler
  fullName: System.Web.Configuration.Compiler
  type: Class
  summary: "Define um compilador que é usado para oferecer suporte a infraestrutura de compilação de aplicativos da Web. Essa classe não pode ser herdada."
  remarks: "A classe de compilador fornece uma maneira de acessar um elemento de configuração do compilador de forma programática."
  syntax:
    content: 'public sealed class Compiler : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.#ctor(System.String,System.String,System.String,System.String,System.Int32)
  id: '#ctor(System.String,System.String,System.String,System.String,System.Int32)'
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: Compiler(String,String,String,String,Int32)
  nameWithType: Compiler.Compiler(String,String,String,String,Int32)
  fullName: System.Web.Configuration.Compiler.Compiler(String,String,String,String,Int32)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Cria uma instância de um <xref href=&quot;System.Web.Configuration.Compiler&quot;> </xref> inicializadas com os valores fornecidos."
  syntax:
    content: public Compiler (string compilerOptions, string extension, string language, string type, int warningLevel);
    parameters:
    - id: compilerOptions
      type: System.String
      description: "Lista as opções de compilador específicos adicionais para passar durante a compilação."
    - id: extension
      type: System.String
      description: "Fornece uma lista separada por ponto e vírgula de extensões de nome de arquivo usado para arquivos code-behind dinâmico. Por exemplo, &quot;CS&quot;."
    - id: language
      type: System.String
      description: "Fornece uma lista separada por vírgulas dos idiomas usados em arquivos de compilação dinâmica. Por exemplo, &quot;c#; cs; csharp&quot;."
    - id: type
      type: System.String
      description: "Especifica uma combinação de classe/montagem separada por vírgulas que indica a classe do .NET Framework."
    - id: warningLevel
      type: System.Int32
      description: "Especifica os níveis de aviso do compilador."
  overload: System.Web.Configuration.Compiler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.CompilerOptions
  id: CompilerOptions
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: CompilerOptions
  nameWithType: Compiler.CompilerOptions
  fullName: System.Web.Configuration.Compiler.CompilerOptions
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Obtém uma lista de opções de compilador específico a ser usado durante a compilação."
  syntax:
    content: public string CompilerOptions { get; }
    return:
      type: System.String
      description: "Um valor que especifica as opções de compilador específicas para usar durante a compilação. Isso não é um conjunto mesclado, mas em vez disso, substitui qualquer valor definido anteriormente em entradas de configuração anteriores."
  overload: System.Web.Configuration.Compiler.CompilerOptions*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.Extension
  id: Extension
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: Extension
  nameWithType: Compiler.Extension
  fullName: System.Web.Configuration.Compiler.Extension
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Obtém uma lista de extensões de nome de arquivo usado para arquivos code-behind dinâmico."
  remarks: "Quando a lista de extensões de nome de arquivo inclui mais de uma extensão, a lista é separada por ponto e vírgula."
  syntax:
    content: public string Extension { get; }
    return:
      type: System.String
      description: "Um valor que especifica as extensões de nome de arquivo usadas para arquivos code-behind dinâmico, os arquivos no diretório de código e outros referenciado arquivos."
  overload: System.Web.Configuration.Compiler.Extension*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.Language
  id: Language
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: Language
  nameWithType: Compiler.Language
  fullName: System.Web.Configuration.Compiler.Language
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Obtém uma lista de linguagens de programação para usar arquivos de compilação dinâmica."
  remarks: "Quando a lista de linguagens de programação inclui mais de um idioma, a lista é separada por ponto e vírgula."
  syntax:
    content: public string Language { get; }
    return:
      type: System.String
      description: "Um valor que especifica as linguagens de programação para usar arquivos de compilação dinâmica."
  overload: System.Web.Configuration.Compiler.Language*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.Properties
  id: Properties
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: Properties
  nameWithType: Compiler.Properties
  fullName: System.Web.Configuration.Compiler.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A ser adicionado."
  overload: System.Web.Configuration.Compiler.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.Type
  id: Type
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: Type
  nameWithType: Compiler.Type
  fullName: System.Web.Configuration.Compiler.Type
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Obtém o nome do tipo do compilador do provedor de idioma para arquivos de compilação dinâmica."
  remarks: "Especifica o nome do tipo do provedor de idioma, incluindo o nome do assembly que contém a implementação de provedor."
  syntax:
    content: public string Type { get; }
    return:
      type: System.String
      description: "Um valor que especifica o nome do tipo do compilador de idioma a ser usado nos arquivos de compilação dinâmica."
  overload: System.Web.Configuration.Compiler.Type*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.WarningLevel
  id: WarningLevel
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: WarningLevel
  nameWithType: Compiler.WarningLevel
  fullName: System.Web.Configuration.Compiler.WarningLevel
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Obtém o nível de aviso do compilador."
  remarks: "Especifica o nível de aviso do compilador padrão; Determina o nível no qual o provedor do idioma trata avisos de compilação como erros."
  syntax:
    content: public int WarningLevel { get; }
    return:
      type: System.Int32
      description: "Um valor que especifica o nível de aviso do compilador."
  overload: System.Web.Configuration.Compiler.WarningLevel*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.Compiler.#ctor(System.String,System.String,System.String,System.String,System.Int32)
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Compiler(String,String,String,String,Int32)
  nameWithType: Compiler.Compiler(String,String,String,String,Int32)
  fullName: System.Web.Configuration.Compiler.Compiler(String,String,String,String,Int32)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.Compiler.CompilerOptions
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: CompilerOptions
  nameWithType: Compiler.CompilerOptions
  fullName: System.Web.Configuration.Compiler.CompilerOptions
- uid: System.Web.Configuration.Compiler.Extension
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Extension
  nameWithType: Compiler.Extension
  fullName: System.Web.Configuration.Compiler.Extension
- uid: System.Web.Configuration.Compiler.Language
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Language
  nameWithType: Compiler.Language
  fullName: System.Web.Configuration.Compiler.Language
- uid: System.Web.Configuration.Compiler.Properties
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Properties
  nameWithType: Compiler.Properties
  fullName: System.Web.Configuration.Compiler.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.Compiler.Type
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Type
  nameWithType: Compiler.Type
  fullName: System.Web.Configuration.Compiler.Type
- uid: System.Web.Configuration.Compiler.WarningLevel
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: WarningLevel
  nameWithType: Compiler.WarningLevel
  fullName: System.Web.Configuration.Compiler.WarningLevel
- uid: System.Web.Configuration.Compiler.#ctor*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Compiler
  nameWithType: Compiler.Compiler
- uid: System.Web.Configuration.Compiler.CompilerOptions*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: CompilerOptions
  nameWithType: Compiler.CompilerOptions
- uid: System.Web.Configuration.Compiler.Extension*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Extension
  nameWithType: Compiler.Extension
- uid: System.Web.Configuration.Compiler.Language*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Language
  nameWithType: Compiler.Language
- uid: System.Web.Configuration.Compiler.Properties*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Properties
  nameWithType: Compiler.Properties
- uid: System.Web.Configuration.Compiler.Type*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Type
  nameWithType: Compiler.Type
- uid: System.Web.Configuration.Compiler.WarningLevel*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: WarningLevel
  nameWithType: Compiler.WarningLevel
