### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsGroupNameAttribute
  id: SettingsGroupNameAttribute
  children:
  - System.Configuration.SettingsGroupNameAttribute.#ctor(System.String)
  - System.Configuration.SettingsGroupNameAttribute.GroupName
  langs:
  - csharp
  name: SettingsGroupNameAttribute
  nameWithType: SettingsGroupNameAttribute
  fullName: System.Configuration.SettingsGroupNameAttribute
  type: Class
  summary: "Especifica um nome para o grupo de propriedade de configurações do aplicativo. Essa classe não pode ser herdada."
  remarks: "Uma classe de configurações de aplicativo, derivada de <xref:System.Configuration.ApplicationSettingsBase>, define uma ou mais propriedades que pertencem ao mesmo grupo de propriedade de configurações de aplicativo.</xref:System.Configuration.ApplicationSettingsBase> Por padrão, o grupo é atribuído o nome da classe de configurações. No entanto, SettingsGroupNameAttribute pode ser usado para especificar explicitamente um nome para o grupo de propriedades. Esse nome pode ser útil organizar grandes conjuntos de propriedades, para obter assistência em ferramentas de programação de tempo de design e ferramentas administrativas do tempo de execução e assim por diante. O provedor de configurações associadas ainda pode usar esse nome para organizar as configurações no repositório de dados.       O SettingsGroupNameAttribute só pode ser aplicada no nível de classe."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class)]

      public sealed class SettingsGroupNameAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsGroupNameAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsGroupNameAttribute
  langs:
  - csharp
  name: SettingsGroupNameAttribute(String)
  nameWithType: SettingsGroupNameAttribute.SettingsGroupNameAttribute(String)
  fullName: System.Configuration.SettingsGroupNameAttribute.SettingsGroupNameAttribute(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Configuration.SettingsGroupNameAttribute&quot;> </xref> classe."
  remarks: "Embora o comprimento máximo teórico do `groupName` parâmetro é restrita por limites superiores de um <xref:System.Int32>, limites práticos, determinados pelo uso e limitações de cota impostas pelo provedor de configurações, será muito menores.</xref:System.Int32>      > [!NOTE] > O nome do grupo de configurações não precisa ser exclusivo."
  syntax:
    content: public SettingsGroupNameAttribute (string groupName);
    parameters:
    - id: groupName
      type: System.String
      description: "Um <xref:System.String>que contém o nome do grupo de propriedades de configurações de aplicativo.</xref:System.String>"
  overload: System.Configuration.SettingsGroupNameAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsGroupNameAttribute.GroupName
  id: GroupName
  parent: System.Configuration.SettingsGroupNameAttribute
  langs:
  - csharp
  name: GroupName
  nameWithType: SettingsGroupNameAttribute.GroupName
  fullName: System.Configuration.SettingsGroupNameAttribute.GroupName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Obtém o nome do grupo de propriedades de configurações de aplicativo."
  remarks: "O valor da propriedade de nome de grupo é definido <xref:System.Configuration.SettingsGroupNameAttribute.%23ctor%2A>construtor.</xref:System.Configuration.SettingsGroupNameAttribute.%23ctor%2A>"
  syntax:
    content: public string GroupName { get; }
    return:
      type: System.String
      description: "Um <xref:System.String>que contém o nome do grupo de propriedades de configurações de aplicativo.</xref:System.String>"
  overload: System.Configuration.SettingsGroupNameAttribute.GroupName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsGroupNameAttribute.#ctor(System.String)
  parent: System.Configuration.SettingsGroupNameAttribute
  isExternal: false
  name: SettingsGroupNameAttribute(String)
  nameWithType: SettingsGroupNameAttribute.SettingsGroupNameAttribute(String)
  fullName: System.Configuration.SettingsGroupNameAttribute.SettingsGroupNameAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsGroupNameAttribute.GroupName
  parent: System.Configuration.SettingsGroupNameAttribute
  isExternal: false
  name: GroupName
  nameWithType: SettingsGroupNameAttribute.GroupName
  fullName: System.Configuration.SettingsGroupNameAttribute.GroupName
- uid: System.Configuration.SettingsGroupNameAttribute.#ctor*
  parent: System.Configuration.SettingsGroupNameAttribute
  isExternal: false
  name: SettingsGroupNameAttribute
  nameWithType: SettingsGroupNameAttribute.SettingsGroupNameAttribute
- uid: System.Configuration.SettingsGroupNameAttribute.GroupName*
  parent: System.Configuration.SettingsGroupNameAttribute
  isExternal: false
  name: GroupName
  nameWithType: SettingsGroupNameAttribute.GroupName
