### YamlMime:ManagedReference
items:
- uid: System.Web.ApplicationServices.KnownTypesProvider
  id: KnownTypesProvider
  children:
  - System.Web.ApplicationServices.KnownTypesProvider.GetKnownTypes(System.Reflection.ICustomAttributeProvider)
  langs:
  - csharp
  name: KnownTypesProvider
  nameWithType: KnownTypesProvider
  fullName: System.Web.ApplicationServices.KnownTypesProvider
  type: Class
  summary: "Cria uma matriz de <xref:System.Type>objetos que contêm os tipos de propriedades de perfil individual.</xref:System.Type>"
  syntax:
    content: public static class KnownTypesProvider
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.KnownTypesProvider.GetKnownTypes(System.Reflection.ICustomAttributeProvider)
  id: GetKnownTypes(System.Reflection.ICustomAttributeProvider)
  parent: System.Web.ApplicationServices.KnownTypesProvider
  langs:
  - csharp
  name: GetKnownTypes(ICustomAttributeProvider)
  nameWithType: KnownTypesProvider.GetKnownTypes(ICustomAttributeProvider)
  fullName: System.Web.ApplicationServices.KnownTypesProvider.GetKnownTypes(ICustomAttributeProvider)
  type: Method
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Cria uma matriz de <xref:System.Type>objetos que contêm os tipos de propriedades de perfil individual.</xref:System.Type>"
  syntax:
    content: public static Type[] GetKnownTypes (System.Reflection.ICustomAttributeProvider knownTypeAttributeTarget);
    parameters:
    - id: knownTypeAttributeTarget
      type: System.Reflection.ICustomAttributeProvider
      description: "Um objeto de provedor."
    return:
      type: System.Type[]
      description: "Uma matriz de tipos de propriedades de perfil individual."
  overload: System.Web.ApplicationServices.KnownTypesProvider.GetKnownTypes*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.ApplicationServices.KnownTypesProvider.GetKnownTypes(System.Reflection.ICustomAttributeProvider)
  parent: System.Web.ApplicationServices.KnownTypesProvider
  isExternal: false
  name: GetKnownTypes(ICustomAttributeProvider)
  nameWithType: KnownTypesProvider.GetKnownTypes(ICustomAttributeProvider)
  fullName: System.Web.ApplicationServices.KnownTypesProvider.GetKnownTypes(ICustomAttributeProvider)
- uid: System.Type[]
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type[]
  spec.csharp:
  - uid: System.Type
    name: Type
    nameWithType: Type
    fullName: Type[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Reflection.ICustomAttributeProvider
  parent: System.Reflection
  isExternal: false
  name: ICustomAttributeProvider
  nameWithType: ICustomAttributeProvider
  fullName: System.Reflection.ICustomAttributeProvider
- uid: System.Web.ApplicationServices.KnownTypesProvider.GetKnownTypes*
  parent: System.Web.ApplicationServices.KnownTypesProvider
  isExternal: false
  name: GetKnownTypes
  nameWithType: KnownTypesProvider.GetKnownTypes
