### YamlMime:ManagedReference
items:
- uid: System.Configuration.ISettingsProviderService
  id: ISettingsProviderService
  children:
  - System.Configuration.ISettingsProviderService.GetSettingsProvider(System.Configuration.SettingsProperty)
  langs:
  - csharp
  name: ISettingsProviderService
  nameWithType: ISettingsProviderService
  fullName: System.Configuration.ISettingsProviderService
  type: Interface
  summary: "Fornece uma interface para a definição de um provedor de configurações de aplicativos alternativo."
  remarks: "O <xref:System.Configuration.IPersistComponentSettings>interface permite que os controles e componentes hospedados em um aplicativo para manter as configurações do aplicativo de maneira totalmente transparente para o aplicativo.</xref:System.Configuration.IPersistComponentSettings> No entanto, em alguns casos, o aplicativo ou o ambiente pode precisar substituir nativamente usado por um componente com um dos seus próprios escolhendo o provedor de configurações. A interface ISettingsProviderService permite a criação de um serviço simples que se comunica tal um provedor de configurações alternativas, geralmente oferecido por meio de <xref:System.ComponentModel.Container>.</xref:System.ComponentModel.Container> de propriedade       ISettingsProviderService é normalmente usado por ferramentas de tempo de design e depuradores que fornecem suporte especial para as configurações do aplicativo. Para tornar essa uma função de disposição diretamente, a <xref:System.Configuration.ApplicationSettingsBase>classe contém construtores que usam uma referência para o componente proprietário.</xref:System.Configuration.ApplicationSettingsBase> Esses construtores de consulta automaticamente para provedores de configurações compatíveis."
  syntax:
    content: public interface ISettingsProviderService
  implements: []
  platform:
  - net462
- uid: System.Configuration.ISettingsProviderService.GetSettingsProvider(System.Configuration.SettingsProperty)
  id: GetSettingsProvider(System.Configuration.SettingsProperty)
  parent: System.Configuration.ISettingsProviderService
  langs:
  - csharp
  name: GetSettingsProvider(SettingsProperty)
  nameWithType: ISettingsProviderService.GetSettingsProvider(SettingsProperty)
  fullName: System.Configuration.ISettingsProviderService.GetSettingsProvider(SettingsProperty)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Retorna o provedor de configurações compatíveis com a propriedade de configurações especificadas."
  remarks: "O método GetSettingsProvider permite que um <xref:System.Configuration.ISettingsProviderService>oferecer seus serviços de serialização para qualquer componente que se encontra.</xref:System.Configuration.ISettingsProviderService> Este método determina se o provedor de configurações associadas pode persistir o tipo de propriedade de configurações do aplicativo especificado. Se for possível, este método retorna uma referência ao provedor de configurações; Caso contrário, ele retorna `null`."
  syntax:
    content: public System.Configuration.SettingsProvider GetSettingsProvider (System.Configuration.SettingsProperty property);
    parameters:
    - id: property
      type: System.Configuration.SettingsProperty
      description: "O <xref href=&quot;System.Configuration.SettingsProperty&quot;> </xref> que requer serialização."
    return:
      type: System.Configuration.SettingsProvider
      description: "Se encontrado, o <xref href=&quot;System.Configuration.SettingsProvider&quot;> </xref> que pode manter a propriedade de configurações especificado; caso contrário, <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.ISettingsProviderService.GetSettingsProvider*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ISettingsProviderService.GetSettingsProvider(System.Configuration.SettingsProperty)
  parent: System.Configuration.ISettingsProviderService
  isExternal: false
  name: GetSettingsProvider(SettingsProperty)
  nameWithType: ISettingsProviderService.GetSettingsProvider(SettingsProperty)
  fullName: System.Configuration.ISettingsProviderService.GetSettingsProvider(SettingsProperty)
- uid: System.Configuration.SettingsProvider
  parent: System.Configuration
  isExternal: false
  name: SettingsProvider
  nameWithType: SettingsProvider
  fullName: System.Configuration.SettingsProvider
- uid: System.Configuration.SettingsProperty
  parent: System.Configuration
  isExternal: false
  name: SettingsProperty
  nameWithType: SettingsProperty
  fullName: System.Configuration.SettingsProperty
- uid: System.Configuration.ISettingsProviderService.GetSettingsProvider*
  parent: System.Configuration.ISettingsProviderService
  isExternal: false
  name: GetSettingsProvider
  nameWithType: ISettingsProviderService.GetSettingsProvider
