### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ComMethodElement
  id: ComMethodElement
  children:
  - System.ServiceModel.Configuration.ComMethodElement.#ctor
  - System.ServiceModel.Configuration.ComMethodElement.#ctor(System.String)
  - System.ServiceModel.Configuration.ComMethodElement.ExposedMethod
  - System.ServiceModel.Configuration.ComMethodElement.Properties
  langs:
  - csharp
  name: ComMethodElement
  nameWithType: ComMethodElement
  fullName: System.ServiceModel.Configuration.ComMethodElement
  type: Class
  summary: "Representa um método COM+ que está exposto quando a interface em um componente COM+ é exposta como um serviço Web. Essa classe não pode ser herdada."
  remarks: "COM+ integration ferramenta de configuração (ComSvcConfig.exe) pode ser usada para adicionar métodos específicos de uma interface COM apareçam no contrato de serviço gerado.       Por exemplo, você pode usar o comando a seguir para adicionar três métodos nomeados no `IFinances` interface COM o `ItemOrders.Financial` componente, o contrato de serviço gerado.      ```   ComSvcConfig.exe /i /application:OnlineStore /contract:ItemOrders.Financial,IFinances.{TransferFunds,AddFunds,RemoveFunds} /hosting:complus   ```Quando você executa o ComSvcConfig.exe muito, em seguida, gera o seguinte contrato de serviço listando os métodos mencionados anteriormente como `exposedMethod` elementos.      ```      <comContract contractType=&quot;{C551FBA9-E3AA-4272-8C2A-84BD8D290AC7}&quot; name=&quot;IFinances&quot; namespace=&quot;http://contoso.com/services/financial&quot;>       <exposedMethod name=&quot;TransferFunds&quot;/>       <exposedMethod name=&quot;AddFunds&quot;/>       <exposedMethod name=&quot;RemoveFunds&quot;/>   </comContract>      ```No momento da inicialização de serviço, o tempo de execução tenta gerar um contrato de serviço refletir sobre e adicionando apenas os métodos incluídos na lista de `exposedMethod` elementos. Um rastreamento é produzido para cada método de interface não está incluído no contrato de serviço."
  syntax:
    content: 'public sealed class ComMethodElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComMethodElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ComMethodElement
  langs:
  - csharp
  name: ComMethodElement()
  nameWithType: ComMethodElement.ComMethodElement()
  fullName: System.ServiceModel.Configuration.ComMethodElement.ComMethodElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.ServiceModel.Configuration.ComMethodElement&quot;> </xref> classe."
  syntax:
    content: public ComMethodElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ComMethodElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComMethodElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.ComMethodElement
  langs:
  - csharp
  name: ComMethodElement(String)
  nameWithType: ComMethodElement.ComMethodElement(String)
  fullName: System.ServiceModel.Configuration.ComMethodElement.ComMethodElement(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.ServiceModel.Configuration.ComMethodElement&quot;> </xref> classe com o método especificado."
  syntax:
    content: public ComMethodElement (string method);
    parameters:
    - id: method
      type: System.String
      description: "Um método COM+ exposto."
  overload: System.ServiceModel.Configuration.ComMethodElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComMethodElement.ExposedMethod
  id: ExposedMethod
  parent: System.ServiceModel.Configuration.ComMethodElement
  langs:
  - csharp
  name: ExposedMethod
  nameWithType: ComMethodElement.ExposedMethod
  fullName: System.ServiceModel.Configuration.ComMethodElement.ExposedMethod
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém o método COM+ que está exposto quando a interface em um componente COM+ é exposta como um serviço Web."
  syntax:
    content: public string ExposedMethod { get; set; }
    return:
      type: System.String
      description: "O nome do método COM+ que está exposto quando a interface em um componente COM+ é exposta como um serviço Web."
  overload: System.ServiceModel.Configuration.ComMethodElement.ExposedMethod*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComMethodElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ComMethodElement
  langs:
  - csharp
  name: Properties
  nameWithType: ComMethodElement.Properties
  fullName: System.ServiceModel.Configuration.ComMethodElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A ser adicionado."
  overload: System.ServiceModel.Configuration.ComMethodElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.ComMethodElement.#ctor
  parent: System.ServiceModel.Configuration.ComMethodElement
  isExternal: false
  name: ComMethodElement()
  nameWithType: ComMethodElement.ComMethodElement()
  fullName: System.ServiceModel.Configuration.ComMethodElement.ComMethodElement()
- uid: System.ServiceModel.Configuration.ComMethodElement.#ctor(System.String)
  parent: System.ServiceModel.Configuration.ComMethodElement
  isExternal: false
  name: ComMethodElement(String)
  nameWithType: ComMethodElement.ComMethodElement(String)
  fullName: System.ServiceModel.Configuration.ComMethodElement.ComMethodElement(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.ComMethodElement.ExposedMethod
  parent: System.ServiceModel.Configuration.ComMethodElement
  isExternal: false
  name: ExposedMethod
  nameWithType: ComMethodElement.ExposedMethod
  fullName: System.ServiceModel.Configuration.ComMethodElement.ExposedMethod
- uid: System.ServiceModel.Configuration.ComMethodElement.Properties
  parent: System.ServiceModel.Configuration.ComMethodElement
  isExternal: false
  name: Properties
  nameWithType: ComMethodElement.Properties
  fullName: System.ServiceModel.Configuration.ComMethodElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ComMethodElement.#ctor*
  parent: System.ServiceModel.Configuration.ComMethodElement
  isExternal: false
  name: ComMethodElement
  nameWithType: ComMethodElement.ComMethodElement
- uid: System.ServiceModel.Configuration.ComMethodElement.ExposedMethod*
  parent: System.ServiceModel.Configuration.ComMethodElement
  isExternal: false
  name: ExposedMethod
  nameWithType: ComMethodElement.ExposedMethod
- uid: System.ServiceModel.Configuration.ComMethodElement.Properties*
  parent: System.ServiceModel.Configuration.ComMethodElement
  isExternal: false
  name: Properties
  nameWithType: ComMethodElement.Properties
