### YamlMime:ManagedReference
items:
- uid: System.Configuration.IriParsingElement
  id: IriParsingElement
  children:
  - System.Configuration.IriParsingElement.#ctor
  - System.Configuration.IriParsingElement.Enabled
  - System.Configuration.IriParsingElement.Properties
  langs:
  - csharp
  name: IriParsingElement
  nameWithType: IriParsingElement
  fullName: System.Configuration.IriParsingElement
  type: Class
  summary: "Fornece a definição de configuração para internacional Resource identificador (IRI) processamento o &lt;xref:System.Uri?displayProperty=fullName&gt; classe."
  remarks: "Existente <xref:System.Uri?displayProperty=fullName>classe foi estendida para oferecer suporte para identificadores de recursos internacionais (IRI) com base na RFC 3987.</xref:System.Uri?displayProperty=fullName> Os usuários atuais não verão qualquer alteração no comportamento do .NET Framework 2.0, a menos que eles permitem especificamente IRI. Isso garante a compatibilidade com versões anteriores do .NET Framework.       A definição de configuração para o IriParsingElement serão lidos uma vez quando o primeiro <xref:System.Uri?displayProperty=fullName>classe é construída.</xref:System.Uri?displayProperty=fullName> Alterações na configuração depois desse tempo são ignoradas.       Para obter mais informações sobre suporte a IRI, consulte a seção comentários para a <xref:System.Uri?displayProperty=fullName>classe.</xref:System.Uri?displayProperty=fullName>"
  syntax:
    content: 'public sealed class IriParsingElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Configuration.IriParsingElement.#ctor
  id: '#ctor'
  parent: System.Configuration.IriParsingElement
  langs:
  - csharp
  name: IriParsingElement()
  nameWithType: IriParsingElement.IriParsingElement()
  fullName: System.Configuration.IriParsingElement.IriParsingElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Configuration.IriParsingElement&quot;> </xref> classe."
  remarks: "Este construtor cria um <xref:System.Configuration.IriParsingElement>instância.</xref:System.Configuration.IriParsingElement>"
  syntax:
    content: public IriParsingElement ();
    parameters: []
  overload: System.Configuration.IriParsingElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IriParsingElement.Enabled
  id: Enabled
  parent: System.Configuration.IriParsingElement
  langs:
  - csharp
  name: Enabled
  nameWithType: IriParsingElement.Enabled
  fullName: System.Configuration.IriParsingElement.Enabled
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Obtém ou define o valor de <xref href=&quot;System.Configuration.IriParsingElement&quot;> </xref> configuração."
  remarks: "O <xref:System.Configuration.IriParsingElement>processamento da configuração configuração controles IRI na <xref:System.Uri?displayProperty=fullName>classe.</xref:System.Uri?displayProperty=fullName> </xref:System.Configuration.IriParsingElement> Essa configuração controla também indiretamente internacional domínio IDN (nome) processamento conjunto com a <xref:System.Configuration.IdnElement?displayProperty=fullName>classe.</xref:System.Configuration.IdnElement?displayProperty=fullName> Processamento de IRI deve ser habilitado para processamento para ser possível de IDN. Se o processamento de IRI é desabilitado, o processamento de IDN será definido para a configuração padrão em que o comportamento do .NET Framework 2.0 é usado para fins de compatibilidade e nomes IDN não são usados.       O parâmetro de configuração para o <xref:System.Configuration.IriParsingElement>serão lidos uma vez quando o primeiro <xref:System.Uri?displayProperty=fullName>classe é construída.</xref:System.Uri?displayProperty=fullName> </xref:System.Configuration.IriParsingElement> Alterações na configuração depois desse tempo são ignoradas.       Para obter mais informações sobre suporte a IRI, consulte a seção comentários para a <xref:System.Uri?displayProperty=fullName>classe.</xref:System.Uri?displayProperty=fullName>"
  syntax:
    content: public bool Enabled { get; set; }
    return:
      type: System.Boolean
      description: "Um booliano que indica se o processamento de identificador de recurso internacional (IRI) está habilitado."
  overload: System.Configuration.IriParsingElement.Enabled*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IriParsingElement.Properties
  id: Properties
  parent: System.Configuration.IriParsingElement
  langs:
  - csharp
  name: Properties
  nameWithType: IriParsingElement.Properties
  fullName: System.Configuration.IriParsingElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A ser adicionado."
  overload: System.Configuration.IriParsingElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Configuration.IriParsingElement.#ctor
  parent: System.Configuration.IriParsingElement
  isExternal: false
  name: IriParsingElement()
  nameWithType: IriParsingElement.IriParsingElement()
  fullName: System.Configuration.IriParsingElement.IriParsingElement()
- uid: System.Configuration.IriParsingElement.Enabled
  parent: System.Configuration.IriParsingElement
  isExternal: false
  name: Enabled
  nameWithType: IriParsingElement.Enabled
  fullName: System.Configuration.IriParsingElement.Enabled
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.IriParsingElement.Properties
  parent: System.Configuration.IriParsingElement
  isExternal: false
  name: Properties
  nameWithType: IriParsingElement.Properties
  fullName: System.Configuration.IriParsingElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Configuration.IriParsingElement.#ctor*
  parent: System.Configuration.IriParsingElement
  isExternal: false
  name: IriParsingElement
  nameWithType: IriParsingElement.IriParsingElement
- uid: System.Configuration.IriParsingElement.Enabled*
  parent: System.Configuration.IriParsingElement
  isExternal: false
  name: Enabled
  nameWithType: IriParsingElement.Enabled
- uid: System.Configuration.IriParsingElement.Properties*
  parent: System.Configuration.IriParsingElement
  isExternal: false
  name: Properties
  nameWithType: IriParsingElement.Properties
