### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler
  id: HttpCapabilitiesSectionHandler
  children:
  - System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor
  - System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: HttpCapabilitiesSectionHandler
  nameWithType: HttpCapabilitiesSectionHandler
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler
  type: Class
  summary: "Auxilia na leitura do <xref uid=&quot;langword_csharp_&lt;browserCaps&gt;&quot; name=&quot;&lt;browserCaps&gt;&quot; href=&quot;&quot;> </xref> seção de um arquivo de configuração e criação de uma instância do <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> classe que contém as informações de recursos para o navegador do cliente."
  remarks: "A classe HttpCapabilitiesSectionHandler e correspondente `<browserCaps>` seção de configuração foram preteridos no .NET Framework versão 2.0. O método preferencial para o gerenciamento de recursos do navegador é por meio de arquivos de definição de navegador que são compilados para uso pela <xref:System.Web.Configuration.BrowserCapabilitiesFactory>classe.</xref:System.Web.Configuration.BrowserCapabilitiesFactory> O objetivo de ambas as abordagens de configuração é gerar uma instância da <xref:System.Web.HttpBrowserCapabilities>classe que pode ser acessado a partir da <xref:System.Web.HttpRequest.Browser%2A>propriedade de <xref:System.Web.HttpRequest>classe.</xref:System.Web.HttpRequest> </xref:System.Web.HttpRequest.Browser%2A> </xref:System.Web.HttpBrowserCapabilities>       Usando os arquivos de definição de navegador para armazenar recursos do navegador oferece vantagens em relação a alternativa. Ele oferece melhor desempenho porque as informações de definição do navegador são analisadas a partir do arquivo de configuração XML e compiladas em uma classe antecipadamente. Os arquivos de definição do navegador também são mais fáceis de manter:-as definições são hierárquicas e, portanto, contar com menos em expressões regulares para determinar os recursos do navegador.      -As definições podem ser organizadas em vários arquivos, tornando mais fácil de gerenciar.      -As definições podem ser definidas em qualquer nível, no nível de Machine. config ou um aplicativo específico. Isso elimina a necessidade de copiar todo o conjunto de definições para fins de substituição de recursos para um navegador específico."
  syntax:
    content: 'public class HttpCapabilitiesSectionHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  langs:
  - csharp
  name: HttpCapabilitiesSectionHandler()
  nameWithType: HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Web.Configuration.HttpCapabilitiesSectionHandler&quot;> </xref> classe."
  syntax:
    content: public HttpCapabilitiesSectionHandler ();
    parameters: []
  overload: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Cria uma instância de <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> classe que contém as informações de recursos para o navegador do cliente."
  remarks: "Esta classe deriva seus dados de definição de navegador do `<browserCaps>` seção de configuração. Esta seção está preterida no .NET Framework versão 2.0."
  syntax:
    content: public object Create (object parent, object configurationContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "O nó de configuração pai."
    - id: configurationContext
      type: System.Object
      description: "O contexto de configuração do arquivo de configuração atual."
    - id: section
      type: System.Xml.XmlNode
      description: "A seção do arquivo de configuração que contém as informações."
    return:
      type: System.Object
      description: "Uma instância de <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> que contém as informações de recursos para o navegador do cliente."
  overload: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: HttpCapabilitiesSectionHandler()
  nameWithType: HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor*
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: HttpCapabilitiesSectionHandler
  nameWithType: HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create*
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: Create
  nameWithType: HttpCapabilitiesSectionHandler.Create
