### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationSettings
  id: ConfigurationSettings
  children:
  - System.Configuration.ConfigurationSettings.AppSettings
  - System.Configuration.ConfigurationSettings.GetConfig(System.String)
  langs:
  - csharp
  name: ConfigurationSettings
  nameWithType: ConfigurationSettings
  fullName: System.Configuration.ConfigurationSettings
  type: Class
  summary: "Fornece suporte de versões 1.0 e 1.1 do tempo de execução para ler seções de configuração e definições de configuração comuns."
  remarks: "Usar os métodos estáticos e as propriedades do tipo ConfigurationSettings é o método recomendado para ler as informações de configuração em tempo de execução para aplicativos de versões 1.0 e 1.1.      > [!NOTE] > ConfigurationSettings a classe fornece somente para compatibilidade com versões anteriores. Para novos aplicativos, você deve usar o <xref:System.Configuration.ConfigurationManager>classe ou <xref:System.Web.Configuration.WebConfigurationManager>classe em vez disso.</xref:System.Web.Configuration.WebConfigurationManager> </xref:System.Configuration.ConfigurationManager> Para usar essas duas classes, você deve adicionar uma referência em seu projeto ou aplicativo para o namespace System. Configuration."
  syntax:
    content: public sealed class ConfigurationSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationSettings.AppSettings
  id: AppSettings
  parent: System.Configuration.ConfigurationSettings
  langs:
  - csharp
  name: AppSettings
  nameWithType: ConfigurationSettings.AppSettings
  fullName: System.Configuration.ConfigurationSettings.AppSettings
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Obtém somente leitura <xref href=&quot;System.Collections.Specialized.NameValueCollection&quot;> </xref> da seção de configurações de aplicativo do arquivo de configuração."
  remarks: "O `appSettings` elemento da seção do arquivo de configuração contém uma série de pares de nome/valor que seu aplicativo pode usar para qualquer finalidade.       Esse método é preterido e é mantido para compatibilidade com versões anteriores. Use o método GetSection.      > [!NOTE] > O <xref:System.Configuration.ConfigurationSettings>classe fornece compatibilidade com versões anteriores apenas.</xref:System.Configuration.ConfigurationSettings> Você deve usar o <xref:System.Configuration.ConfigurationManager>classe ou <xref:System.Web.Configuration.WebConfigurationManager>classe em vez disso.</xref:System.Web.Configuration.WebConfigurationManager> </xref:System.Configuration.ConfigurationManager>"
  syntax:
    content: public static System.Collections.Specialized.NameValueCollection AppSettings { get; }
    return:
      type: System.Collections.Specialized.NameValueCollection
      description: "Somente leitura <xref href=&quot;System.Collections.Specialized.NameValueCollection&quot;> </xref> da seção de configurações de aplicativo do arquivo de configuração."
  overload: System.Configuration.ConfigurationSettings.AppSettings*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationSettings.GetConfig(System.String)
  id: GetConfig(System.String)
  parent: System.Configuration.ConfigurationSettings
  langs:
  - csharp
  name: GetConfig(String)
  nameWithType: ConfigurationSettings.GetConfig(String)
  fullName: System.Configuration.ConfigurationSettings.GetConfig(String)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Retorna o <xref href=&quot;System.Configuration.ConfigurationSection&quot;> </xref> objeto para o caminho e nome da seção de configuração passado."
  remarks: "Esse método é preterido e é mantido para compatibilidade com versões anteriores. Use o método GetSection."
  syntax:
    content: public static object GetConfig (string sectionName);
    parameters:
    - id: sectionName
      type: System.String
      description: "Um nome de configuração e o caminho, como &quot;system.net/settings&quot;."
    return:
      type: System.Object
      description: "O <xref href=&quot;System.Configuration.ConfigurationSection&quot;> </xref> objeto para o caminho e nome da seção de configuração passado.       <div class=&quot;alert NOTE&quot;>    O <xref href=&quot;System.Configuration.ConfigurationSettings&quot;> </xref> classe fornece somente para compatibilidade com versões anteriores. Você deve usar o <xref href=&quot;System.Configuration.ConfigurationManager&quot;> </xref> classe ou <xref href=&quot;System.Web.Configuration.WebConfigurationManager&quot;> </xref> classe em vez disso.      </div>"
  overload: System.Configuration.ConfigurationSettings.GetConfig*
  exceptions:
  - type: System.Configuration.ConfigurationException
    commentId: T:System.Configuration.ConfigurationException
    description: "Não é possível recuperar a seção solicitada."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationException
  nameWithType: ConfigurationException
  fullName: System.Configuration.ConfigurationException
- uid: System.Configuration.ConfigurationSettings.AppSettings
  parent: System.Configuration.ConfigurationSettings
  isExternal: false
  name: AppSettings
  nameWithType: ConfigurationSettings.AppSettings
  fullName: System.Configuration.ConfigurationSettings.AppSettings
- uid: System.Collections.Specialized.NameValueCollection
  parent: System.Collections.Specialized
  isExternal: false
  name: NameValueCollection
  nameWithType: NameValueCollection
  fullName: System.Collections.Specialized.NameValueCollection
- uid: System.Configuration.ConfigurationSettings.GetConfig(System.String)
  parent: System.Configuration.ConfigurationSettings
  isExternal: false
  name: GetConfig(String)
  nameWithType: ConfigurationSettings.GetConfig(String)
  fullName: System.Configuration.ConfigurationSettings.GetConfig(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationSettings.AppSettings*
  parent: System.Configuration.ConfigurationSettings
  isExternal: false
  name: AppSettings
  nameWithType: ConfigurationSettings.AppSettings
- uid: System.Configuration.ConfigurationSettings.GetConfig*
  parent: System.Configuration.ConfigurationSettings
  isExternal: false
  name: GetConfig
  nameWithType: ConfigurationSettings.GetConfig
