### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.XPathMessageFilterElementComparer
  id: XPathMessageFilterElementComparer
  children:
  - System.ServiceModel.Configuration.XPathMessageFilterElementComparer.#ctor
  - System.ServiceModel.Configuration.XPathMessageFilterElementComparer.System#Collections#IComparer#Compare(System.Object,System.Object)
  langs:
  - csharp
  name: XPathMessageFilterElementComparer
  nameWithType: XPathMessageFilterElementComparer
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElementComparer
  type: Class
  summary: "Fornece funcionalidade para comparar dois <xref href=&quot;System.ServiceModel.Configuration.XPathMessageFilterElement&quot;> </xref> instâncias."
  syntax:
    content: 'public class XPathMessageFilterElementComparer : System.Collections.IComparer'
  inheritance:
  - System.Object
  implements:
  - System.Collections.IComparer
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.XPathMessageFilterElementComparer
  langs:
  - csharp
  name: XPathMessageFilterElementComparer()
  nameWithType: XPathMessageFilterElementComparer.XPathMessageFilterElementComparer()
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.XPathMessageFilterElementComparer()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.ServiceModel.Configuration.XPathMessageFilterElementComparer&quot;> </xref> classe."
  syntax:
    content: public XPathMessageFilterElementComparer ();
    parameters: []
  overload: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.System#Collections#IComparer#Compare(System.Object,System.Object)
  id: System#Collections#IComparer#Compare(System.Object,System.Object)
  isEii: true
  parent: System.ServiceModel.Configuration.XPathMessageFilterElementComparer
  langs:
  - csharp
  name: System.Collections.IComparer.Compare(Object,Object)
  nameWithType: XPathMessageFilterElementComparer.System.Collections.IComparer.Compare(Object,Object)
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.System.Collections.IComparer.Compare(Object,Object)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Comparar dois <xref href=&quot;System.ServiceModel.Configuration.XPathMessageFilterElement&quot;> </xref> instâncias."
  syntax:
    content: int IComparer.Compare (object x, object y);
    parameters:
    - id: x
      type: System.Object
      description: "A <xref href=&quot;System.ServiceModel.Configuration.XPathMessageFilterElement&quot;></xref>."
    - id: y
      type: System.Object
      description: "A <xref href=&quot;System.ServiceModel.Configuration.XPathMessageFilterElement&quot;></xref>."
    return:
      type: System.Int32
      description: "A tabela a seguir mostra os valores possíveis.       <table><thead><tr><th> Valor       </th><th> Condição       </th></tr></thead><tbody><tr><td> -1       </td><td><code>x</code>is less than <code>y</code>.       </td></tr><tr><td> 0       </td><td><code>x</code>is equal to <code>y</code>.       </td></tr><tr><td> 1       </td><td><code>x</code>é maior do que <code> y </code>.       </td></tr></tbody></table>"
  overload: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.System#Collections#IComparer#Compare*
  exceptions:
  - type: System.InvalidOperationException
    commentId: T:System.InvalidOperationException
    description: "O filtro XPath especificado por <code> x </code> ou <code> y </code> não pode ser analisado."
  - type: System.IndexOutOfRangeException
    commentId: T:System.IndexOutOfRangeException
    description: "O prefixo do namespace XPath especificado por <code> x </code> ou <code> y </code>.cannot ser encontrado."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.InvalidOperationException
  isExternal: true
  name: System.InvalidOperationException
- uid: System.IndexOutOfRangeException
  isExternal: true
  name: System.IndexOutOfRangeException
- uid: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.#ctor
  parent: System.ServiceModel.Configuration.XPathMessageFilterElementComparer
  isExternal: false
  name: XPathMessageFilterElementComparer()
  nameWithType: XPathMessageFilterElementComparer.XPathMessageFilterElementComparer()
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.XPathMessageFilterElementComparer()
- uid: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.System#Collections#IComparer#Compare(System.Object,System.Object)
  parent: System.ServiceModel.Configuration.XPathMessageFilterElementComparer
  isExternal: false
  name: System.Collections.IComparer.Compare(Object,Object)
  nameWithType: XPathMessageFilterElementComparer.System.Collections.IComparer.Compare(Object,Object)
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.System.Collections.IComparer.Compare(Object,Object)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.#ctor*
  parent: System.ServiceModel.Configuration.XPathMessageFilterElementComparer
  isExternal: false
  name: XPathMessageFilterElementComparer
  nameWithType: XPathMessageFilterElementComparer.XPathMessageFilterElementComparer
- uid: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.System#Collections#IComparer#Compare*
  parent: System.ServiceModel.Configuration.XPathMessageFilterElementComparer
  isExternal: false
  name: System.Collections.IComparer.Compare
  nameWithType: XPathMessageFilterElementComparer.System.Collections.IComparer.Compare
