### YamlMime:ManagedReference
items:
- uid: System.Web.UI.Design.IWebApplication
  id: IWebApplication
  children:
  - System.Web.UI.Design.IWebApplication.GetProjectItemFromUrl(System.String)
  - System.Web.UI.Design.IWebApplication.OpenWebConfiguration(System.Boolean)
  - System.Web.UI.Design.IWebApplication.RootProjectItem
  langs:
  - csharp
  name: IWebApplication
  nameWithType: IWebApplication
  fullName: System.Web.UI.Design.IWebApplication
  type: Interface
  summary: "Fornece uma interface para acessar um aplicativo Web em um host de design, como [!INCLUDE[vsprvsext](~/add/includes/ajax-current-ext-md.md)], em tempo de design."
  syntax:
    content: >-
      [System.Runtime.InteropServices.Guid("cff39fa8-5607-4b6d-86f3-cc80b3cfe2dd")]

      public interface IWebApplication : IServiceProvider
  implements:
  - System.IServiceProvider
  platform:
  - net462
- uid: System.Web.UI.Design.IWebApplication.GetProjectItemFromUrl(System.String)
  id: GetProjectItemFromUrl(System.String)
  parent: System.Web.UI.Design.IWebApplication
  langs:
  - csharp
  name: GetProjectItemFromUrl(String)
  nameWithType: IWebApplication.GetProjectItemFromUrl(String)
  fullName: System.Web.UI.Design.IWebApplication.GetProjectItemFromUrl(String)
  type: Method
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  summary: "Retorna um item de projeto de um host de design com base em sua URL."
  syntax:
    content: public System.Web.UI.Design.IProjectItem GetProjectItemFromUrl (string appRelativeUrl);
    parameters:
    - id: appRelativeUrl
      type: System.String
      description: "O caminho relativo para o item de projeto para recuperar."
    return:
      type: System.Web.UI.Design.IProjectItem
      description: "Um item de projeto a partir de um host de design com base em sua URL."
  overload: System.Web.UI.Design.IWebApplication.GetProjectItemFromUrl*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.Design.IWebApplication.OpenWebConfiguration(System.Boolean)
  id: OpenWebConfiguration(System.Boolean)
  parent: System.Web.UI.Design.IWebApplication
  langs:
  - csharp
  name: OpenWebConfiguration(Boolean)
  nameWithType: IWebApplication.OpenWebConfiguration(Boolean)
  fullName: System.Web.UI.Design.IWebApplication.OpenWebConfiguration(Boolean)
  type: Method
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  summary: "Retorna um <xref href=&quot;System.Configuration.Configuration&quot;> </xref> objeto que representa o aplicativo Web atual no host de design."
  syntax:
    content: public System.Configuration.Configuration OpenWebConfiguration (bool isReadOnly);
    parameters:
    - id: isReadOnly
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>para indicar retornado <xref href=&quot;System.Configuration.Configuration&quot;> </xref> editável; caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
    return:
      type: System.Configuration.Configuration
      description: "Um objeto que representa o aplicativo Web atual no host de design."
  overload: System.Web.UI.Design.IWebApplication.OpenWebConfiguration*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.Design.IWebApplication.RootProjectItem
  id: RootProjectItem
  parent: System.Web.UI.Design.IWebApplication
  langs:
  - csharp
  name: RootProjectItem
  nameWithType: IWebApplication.RootProjectItem
  fullName: System.Web.UI.Design.IWebApplication.RootProjectItem
  type: Property
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  summary: "Obtém o item de projeto raiz do host de design."
  syntax:
    content: public System.Web.UI.Design.IProjectItem RootProjectItem { get; }
    return:
      type: System.Web.UI.Design.IProjectItem
      description: "O item de projeto raiz do host de design."
  overload: System.Web.UI.Design.IWebApplication.RootProjectItem*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.UI.Design.IWebApplication.GetProjectItemFromUrl(System.String)
  parent: System.Web.UI.Design.IWebApplication
  isExternal: false
  name: GetProjectItemFromUrl(String)
  nameWithType: IWebApplication.GetProjectItemFromUrl(String)
  fullName: System.Web.UI.Design.IWebApplication.GetProjectItemFromUrl(String)
- uid: System.Web.UI.Design.IProjectItem
  parent: System.Web.UI.Design
  isExternal: false
  name: IProjectItem
  nameWithType: IProjectItem
  fullName: System.Web.UI.Design.IProjectItem
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.UI.Design.IWebApplication.OpenWebConfiguration(System.Boolean)
  parent: System.Web.UI.Design.IWebApplication
  isExternal: false
  name: OpenWebConfiguration(Boolean)
  nameWithType: IWebApplication.OpenWebConfiguration(Boolean)
  fullName: System.Web.UI.Design.IWebApplication.OpenWebConfiguration(Boolean)
- uid: System.Configuration.Configuration
  parent: System.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.UI.Design.IWebApplication.RootProjectItem
  parent: System.Web.UI.Design.IWebApplication
  isExternal: false
  name: RootProjectItem
  nameWithType: IWebApplication.RootProjectItem
  fullName: System.Web.UI.Design.IWebApplication.RootProjectItem
- uid: System.Web.UI.Design.IWebApplication.GetProjectItemFromUrl*
  parent: System.Web.UI.Design.IWebApplication
  isExternal: false
  name: GetProjectItemFromUrl
  nameWithType: IWebApplication.GetProjectItemFromUrl
- uid: System.Web.UI.Design.IWebApplication.OpenWebConfiguration*
  parent: System.Web.UI.Design.IWebApplication
  isExternal: false
  name: OpenWebConfiguration
  nameWithType: IWebApplication.OpenWebConfiguration
- uid: System.Web.UI.Design.IWebApplication.RootProjectItem*
  parent: System.Web.UI.Design.IWebApplication
  isExternal: false
  name: RootProjectItem
  nameWithType: IWebApplication.RootProjectItem
