### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.XhtmlConformanceSection
  id: XhtmlConformanceSection
  children:
  - System.Web.Configuration.XhtmlConformanceSection.#ctor
  - System.Web.Configuration.XhtmlConformanceSection.Mode
  - System.Web.Configuration.XhtmlConformanceSection.Properties
  langs:
  - csharp
  name: XhtmlConformanceSection
  nameWithType: XhtmlConformanceSection
  fullName: System.Web.Configuration.XhtmlConformanceSection
  type: Class
  summary: "Configura o <xref uid=&quot;langword_csharp_xhtmlConformance&quot; name=&quot;xhtmlConformance&quot; href=&quot;&quot;> </xref> seção. Essa classe não pode ser herdada."
  remarks: "A classe XhtmlConformanceSection fornece uma maneira de acessar e modificar programaticamente o `xhtmlConformance` seção de um arquivo de configuração.      > [!NOTE] > ASP.NET permite que você crie páginas da Web que são compatíveis com os padrões XHTML 1.1. Para obter mais informações sobre o padrão XHTML 1.1, consulte o site do W3C. Por padrão, quando você estiver trabalhando com navegadores que oferecem suporte a HTML 4.0 ou posterior, páginas e controles ASP.NET processam marcação que é compatível com o padrão XHTML 1.0 Transitional. No entanto, em algumas circunstâncias, talvez não seja ASP.NET para renderizar marcação XHTML. Isso ocorre geralmente quando você tem páginas existentes que dependem de marcas ou atributos que normalmente estaria proibidos pelo XHTML."
  syntax:
    content: 'public sealed class XhtmlConformanceSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.XhtmlConformanceSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.XhtmlConformanceSection
  langs:
  - csharp
  name: XhtmlConformanceSection()
  nameWithType: XhtmlConformanceSection.XhtmlConformanceSection()
  fullName: System.Web.Configuration.XhtmlConformanceSection.XhtmlConformanceSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Web.Configuration.XhtmlConformanceSection&quot;> </xref> classe usando parâmetros padrão."
  remarks: "O construtor XhtmlConformanceSection não se destina a ser usado diretamente no seu código. Ele é chamado pelo sistema de configuração do ASP.NET. Obter uma instância de <xref:System.Web.Configuration.XhtmlConformanceSection>classe usando o <xref:System.Configuration.Configuration.GetSection%2A>método.</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.XhtmlConformanceSection>"
  syntax:
    content: public XhtmlConformanceSection ();
    parameters: []
  overload: System.Web.Configuration.XhtmlConformanceSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.XhtmlConformanceSection.Mode
  id: Mode
  parent: System.Web.Configuration.XhtmlConformanceSection
  langs:
  - csharp
  name: Mode
  nameWithType: XhtmlConformanceSection.Mode
  fullName: System.Web.Configuration.XhtmlConformanceSection.Mode
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Obtém ou define a propriedade Mode."
  remarks: "Por padrão, quando você estiver trabalhando com navegadores que oferecem suporte a HTML 4.0 ou posterior, páginas e controles ASP.NET processam marcação que é compatível com o padrão XHTML 1.0 Transitional. No entanto, em algumas circunstâncias, talvez não seja ASP.NET para renderizar marcação XHTML. Isso ocorre geralmente quando você tem páginas existentes que dependem de marcas ou atributos que normalmente estaria proibidos pelo XHTML."
  syntax:
    content: public System.Web.Configuration.XhtmlConformanceMode Mode { get; set; }
    return:
      type: System.Web.Configuration.XhtmlConformanceMode
      description: "Uma da <xref href=&quot;System.Web.Configuration.XhtmlConformanceMode&quot;> </xref> valores. O padrão é <xref href=&quot;System.Web.Configuration.XhtmlConformanceMode&quot;> </xref>."
  overload: System.Web.Configuration.XhtmlConformanceSection.Mode*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.XhtmlConformanceSection.Properties
  id: Properties
  parent: System.Web.Configuration.XhtmlConformanceSection
  langs:
  - csharp
  name: Properties
  nameWithType: XhtmlConformanceSection.Properties
  fullName: System.Web.Configuration.XhtmlConformanceSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A ser adicionado."
  overload: System.Web.Configuration.XhtmlConformanceSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.XhtmlConformanceSection.#ctor
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: XhtmlConformanceSection()
  nameWithType: XhtmlConformanceSection.XhtmlConformanceSection()
  fullName: System.Web.Configuration.XhtmlConformanceSection.XhtmlConformanceSection()
- uid: System.Web.Configuration.XhtmlConformanceSection.Mode
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: Mode
  nameWithType: XhtmlConformanceSection.Mode
  fullName: System.Web.Configuration.XhtmlConformanceSection.Mode
- uid: System.Web.Configuration.XhtmlConformanceMode
  parent: System.Web.Configuration
  isExternal: false
  name: XhtmlConformanceMode
  nameWithType: XhtmlConformanceMode
  fullName: System.Web.Configuration.XhtmlConformanceMode
- uid: System.Web.Configuration.XhtmlConformanceSection.Properties
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: Properties
  nameWithType: XhtmlConformanceSection.Properties
  fullName: System.Web.Configuration.XhtmlConformanceSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.XhtmlConformanceSection.#ctor*
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: XhtmlConformanceSection
  nameWithType: XhtmlConformanceSection.XhtmlConformanceSection
- uid: System.Web.Configuration.XhtmlConformanceSection.Mode*
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: Mode
  nameWithType: XhtmlConformanceSection.Mode
- uid: System.Web.Configuration.XhtmlConformanceSection.Properties*
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: Properties
  nameWithType: XhtmlConformanceSection.Properties
