### YamlMime:ManagedReference
items:
- uid: System.Configuration.TypeNameConverter
  id: TypeNameConverter
  children:
  - System.Configuration.TypeNameConverter.#ctor
  - System.Configuration.TypeNameConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Configuration.TypeNameConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: TypeNameConverter
  nameWithType: TypeNameConverter
  fullName: System.Configuration.TypeNameConverter
  type: Class
  summary: "Converte entre valores de tipo e a cadeia de caracteres. Essa classe não pode ser herdada."
  remarks: "Este tipo, como todos os outros conversor tipos de configuração, converte cadeias de caracteres encontradas no arquivo de configuração de e para as propriedades com rigidez de tipos relacionadas.       Em particular, a classe TypeNameConverter converte um <xref:System.String>valor atribuído a um tipo de configuração, como um <xref:System.Type>valor e vice-versa.</xref:System.Type> </xref:System.String> O tipo de chamada é a classe responsável por processar a configuração que está associada."
  example:
  - "The following example shows how to obtain a type associated with a custom section. For the implementation of the custom section, refer to the code example in the <xref:System.Configuration.ConfigurationConverterBase> class reference.  \n  \n [!code-vb[System.Configuration.TypeNameConverter#1](~/add/codesnippet/visualbasic/t-system.configuration.t_0_1.vb)]\n [!code-cs[System.Configuration.TypeNameConverter#1](~/add/codesnippet/csharp/t-system.configuration.t_0_1.cs)]  \n  \n The following example is a configuration excerpt used by the previous example.  \n  \n```  \n<?xml version=\"1.0\" encoding=\"utf-8\"?>  \n<configuration>  \n  \n  <configSections>  \n    <section name=\"CustomSection\"   \n      type=\"Samples.AspNet.CustomSection,   \n      ConfigurationConverters,   \n      Version=1.0.0.0, Culture=neutral,   \n      PublicKeyToken=null\"   \n      allowDefinition=\"Everywhere\"   \n      allowExeDefinition=\"MachineToApplication\"   \n      restartOnExternalChanges=\"true\" />  \n  </configSections>  \n  \n  <CustomSection fileName=\"default.txt\" maxIdleTime=\"90\"   \n    timeDelay=\"infinite\" cdStr=\"str0, str1\" permission=\"Read\"  \n    maxUsers=\"Infinite\"/>  \n  \n</configuration>  \n```"
  syntax:
    content: 'public sealed class TypeNameConverter : System.Configuration.ConfigurationConverterBase'
  inheritance:
  - System.Object
  - System.ComponentModel.TypeConverter
  - System.Configuration.ConfigurationConverterBase
  implements: []
  inheritedMembers:
  - System.ComponentModel.TypeConverter.CanConvertFrom(System.Type)
  - System.ComponentModel.TypeConverter.CanConvertTo(System.Type)
  - System.ComponentModel.TypeConverter.ConvertFrom(System.Object)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.String)
  - System.ComponentModel.TypeConverter.ConvertTo(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.Object)
  - System.ComponentModel.TypeConverter.CreateInstance(System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.CreateInstance(System.ComponentModel.ITypeDescriptorContext,System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.GetConvertFromException(System.Object)
  - System.ComponentModel.TypeConverter.GetConvertToException(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object,System.Attribute[])
  - System.ComponentModel.TypeConverter.GetProperties(System.Object)
  - System.ComponentModel.TypeConverter.GetPropertiesSupported
  - System.ComponentModel.TypeConverter.GetPropertiesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValues
  - System.ComponentModel.TypeConverter.GetStandardValues(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.IsValid(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.IsValid(System.Object)
  - System.ComponentModel.TypeConverter.SortProperties(System.ComponentModel.PropertyDescriptorCollection,System.String[])
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  platform:
  - net462
- uid: System.Configuration.TypeNameConverter.#ctor
  id: '#ctor'
  parent: System.Configuration.TypeNameConverter
  langs:
  - csharp
  name: TypeNameConverter()
  nameWithType: TypeNameConverter.TypeNameConverter()
  fullName: System.Configuration.TypeNameConverter.TypeNameConverter()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Configuration.TypeNameConverter&quot;> </xref> classe."
  remarks: "Normalmente, você usa os tipos de conversor fornecidos pelo sistema. A única vez em que você precisa usar o construtor de TypeNameConverter é quando você cria seu próprio tipo de conversão."
  syntax:
    content: public TypeNameConverter ();
    parameters: []
  overload: System.Configuration.TypeNameConverter.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TypeNameConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TypeNameConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: TypeNameConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.TypeNameConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Converte um <xref:System.String>do objeto para um <xref:System.Type>objeto.</xref:System.Type> </xref:System.String>"
  remarks: "O sistema usa o método ConvertFrom durante a leitura de um arquivo de configuração para converter um <xref:System.String>valor para um <xref:System.Type>valor.</xref:System.Type> </xref:System.String>"
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object data);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "O <xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> usado para conversões de tipo de objeto."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "O <xref:System.Globalization.CultureInfo>objeto usado durante a conversão.</xref:System.Globalization.CultureInfo>"
    - id: data
      type: System.Object
      description: "O <xref:System.String>objeto converter.</xref:System.String>"
    return:
      type: System.Object
      description: "O <xref:System.Type>que representa o <code> data </code> parâmetro.</xref:System.Type>"
  overload: System.Configuration.TypeNameConverter.ConvertFrom*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "O <xref:System.Type>valor não pode ser resolvido.</xref:System.Type>"
  platform:
  - net462
- uid: System.Configuration.TypeNameConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TypeNameConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: TypeNameConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.TypeNameConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Converte um <xref:System.Type>do objeto para um <xref:System.String>objeto.</xref:System.String> </xref:System.Type>"
  remarks: "O sistema usa o método ConvertTo ao gravar em um arquivo de configuração para converter um <xref:System.Type>valor para um <xref:System.String>valor.</xref:System.String> </xref:System.Type>"
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object value, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "O <xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> usado para conversões de tipo de objeto."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "O <xref:System.Globalization.CultureInfo>objeto usado durante a conversão.</xref:System.Globalization.CultureInfo>"
    - id: value
      type: System.Object
      description: "O valor a converter."
    - id: type
      type: System.Type
      description: "O tipo para converter."
    return:
      type: System.Object
      description: "O <xref:System.String>que representa o <code> value </code> parâmetro.</xref:System.String>"
  overload: System.Configuration.TypeNameConverter.ConvertTo*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationConverterBase
  isExternal: false
  name: System.Configuration.ConfigurationConverterBase
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Configuration.TypeNameConverter.#ctor
  parent: System.Configuration.TypeNameConverter
  isExternal: false
  name: TypeNameConverter()
  nameWithType: TypeNameConverter.TypeNameConverter()
  fullName: System.Configuration.TypeNameConverter.TypeNameConverter()
- uid: System.Configuration.TypeNameConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TypeNameConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: TypeNameConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.TypeNameConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: false
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: true
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Configuration.TypeNameConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TypeNameConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: TypeNameConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.TypeNameConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.TypeNameConverter.#ctor*
  parent: System.Configuration.TypeNameConverter
  isExternal: false
  name: TypeNameConverter
  nameWithType: TypeNameConverter.TypeNameConverter
- uid: System.Configuration.TypeNameConverter.ConvertFrom*
  parent: System.Configuration.TypeNameConverter
  isExternal: false
  name: ConvertFrom
  nameWithType: TypeNameConverter.ConvertFrom
- uid: System.Configuration.TypeNameConverter.ConvertTo*
  parent: System.Configuration.TypeNameConverter
  isExternal: false
  name: ConvertTo
  nameWithType: TypeNameConverter.ConvertTo
