### YamlMime:ManagedReference
items:
- uid: System.Xml.IApplicationResourceStreamResolver
  id: IApplicationResourceStreamResolver
  children:
  - System.Xml.IApplicationResourceStreamResolver.GetApplicationResourceStream(System.Uri)
  langs:
  - csharp
  name: IApplicationResourceStreamResolver
  nameWithType: IApplicationResourceStreamResolver
  fullName: System.Xml.IApplicationResourceStreamResolver
  type: Interface
  summary: "Representa um resolvedor de fluxo de recurso do aplicativo."
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]

      [System.Obsolete("This API supports the .NET Framework infrastructure and is not intended to be used directly from your code.", true)]

      public interface IApplicationResourceStreamResolver
  implements: []
  platform:
  - net462
- uid: System.Xml.IApplicationResourceStreamResolver.GetApplicationResourceStream(System.Uri)
  id: GetApplicationResourceStream(System.Uri)
  parent: System.Xml.IApplicationResourceStreamResolver
  langs:
  - csharp
  name: GetApplicationResourceStream(Uri)
  nameWithType: IApplicationResourceStreamResolver.GetApplicationResourceStream(Uri)
  fullName: System.Xml.IApplicationResourceStreamResolver.GetApplicationResourceStream(Uri)
  type: Method
  assemblies:
  - System.Xml
  namespace: System.Xml
  summary: "Retorna um fluxo de recursos do aplicativo do URI especificado."
  syntax:
    content: public System.IO.Stream GetApplicationResourceStream (Uri relativeUri);
    parameters:
    - id: relativeUri
      type: System.Uri
      description: "O URI relativo."
    return:
      type: System.IO.Stream
      description: "Um fluxo de recursos do aplicativo."
  overload: System.Xml.IApplicationResourceStreamResolver.GetApplicationResourceStream*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Xml.IApplicationResourceStreamResolver.GetApplicationResourceStream(System.Uri)
  parent: System.Xml.IApplicationResourceStreamResolver
  isExternal: false
  name: GetApplicationResourceStream(Uri)
  nameWithType: IApplicationResourceStreamResolver.GetApplicationResourceStream(Uri)
  fullName: System.Xml.IApplicationResourceStreamResolver.GetApplicationResourceStream(Uri)
- uid: System.IO.Stream
  parent: System.IO
  isExternal: true
  name: Stream
  nameWithType: Stream
  fullName: System.IO.Stream
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.Xml.IApplicationResourceStreamResolver.GetApplicationResourceStream*
  parent: System.Xml.IApplicationResourceStreamResolver
  isExternal: false
  name: GetApplicationResourceStream
  nameWithType: IApplicationResourceStreamResolver.GetApplicationResourceStream
