### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  id: BaseAddressPrefixFilterElement
  children:
  - System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor
  - System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor(System.Uri)
  - System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix
  - System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties
  langs:
  - csharp
  name: BaseAddressPrefixFilterElement
  nameWithType: BaseAddressPrefixFilterElement
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  type: Class
  summary: "Representa um elemento de configuração que especifica uma passagem pelo filtro, que fornece um mecanismo para obter as associações de IIS apropriadas ao hospedar um [!INCLUDE[indigo1](~/add/includes/ajax-current-ext-md.md)] aplicativo no IIS. Essa classe não pode ser herdada."
  remarks: "Um provedor do filtro de prefixo um mecanismo para um serviço para associar a um URI específico. Ele permite hospedar vários aplicativos com diferentes endereços base para o mesmo esquema no mesmo site.       Sites do IIS são contêineres de aplicativos virtuais que contêm diretórios virtuais. O aplicativo em um site pode ser acessado por meio de um ou mais associação do IIS. Associações do IIS fornecem duas informações: protocolo de associação e informações de associação. Associação de protocolo (por exemplo, HTTP) define o esquema durante o qual a comunicação ocorre, e (por exemplo, endereço IP, porta, cabeçalho de host) de informações de associação contém dados usados para acessar o site.       O IIS oferece suporte à especificação várias associações IIS por site, o que resulta em vários endereços de base por esquema. Como um [!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)] serviço hospedado em um site permite que a associação apenas um endereço base por esquema, você pode usar o recurso de filtro de prefixo para escolher o endereço base necessário do serviço hospedado.  Os endereços base entrados fornecidos pelo IIS, são filtrados com base no filtro de lista de prefixo opcional.       Por exemplo, seu site pode conter os seguintes endereços base ```   http://testl.fabrikam.com/Service.svc   http://test2.fabrikam.com/Service.svc   ``` você pode usar o seguinte arquivo de configuração para especificar um filtro de prefixo no nível do appdomain.      ```   <system.serviceModel>     <serviceHostingEnvironment>        <baseAddressPrefixFilters>           <add prefix=”net.tcp://test1.fabrikam.com:8000”/>           <add prefix=”http://test2.fabrikam.com:9000”/>       </baseAddressPrefixFilters>     </serviceHostingEnvironment>   </system.serviceModel>   ```Neste exemplo, `net.tcp://test1.fabrikam.com:8000` e `http://test2.fabrikam.com:9000` são os endereços base somente para seus respectivos esquemas que têm permissão para ser passado.       Por padrão, quando o prefixo não for especificado, todos os endereços são passados. Especifica o prefixo resultará em apenas o endereço base correspondente para esse esquema deverá ser passado.      > [!NOTE] > O filtro não oferece suporte a todos os curingas. Além disso, o baseAddresses fornecida pelo IIS pode ter endereços associados a outros esquemas não está presentes no `baseAddressPrefixFilters` lista. Esses endereços não serão filtrados."
  syntax:
    content: 'public sealed class BaseAddressPrefixFilterElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  langs:
  - csharp
  name: BaseAddressPrefixFilterElement()
  nameWithType: BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement()
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.ServiceModel.Configuration.BaseAddressPrefixFilterElement&quot;> </xref> classe."
  syntax:
    content: public BaseAddressPrefixFilterElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor(System.Uri)
  id: '#ctor(System.Uri)'
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  langs:
  - csharp
  name: BaseAddressPrefixFilterElement(Uri)
  nameWithType: BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement(Uri)
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement(Uri)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.ServiceModel.Configuration.BaseAddressPrefixFilterElement&quot;> </xref> classe com um URI específico."
  syntax:
    content: public BaseAddressPrefixFilterElement (Uri prefix);
    parameters:
    - id: prefix
      type: System.Uri
      description: "Um filtro que faz com que o serviço ao escutar em todos os URIs que começam com esse prefixo específico."
  overload: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix
  id: Prefix
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  langs:
  - csharp
  name: Prefix
  nameWithType: BaseAddressPrefixFilterElement.Prefix
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém ou define um prefixo que é usado para corresponder a uma parte de um endereço base."
  syntax:
    content: public Uri Prefix { get; set; }
    return:
      type: System.Uri
      description: "Um URI que é usado para corresponder a uma parte de um endereço base."
  overload: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  langs:
  - csharp
  name: Properties
  nameWithType: BaseAddressPrefixFilterElement.Properties
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A ser adicionado."
  overload: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: BaseAddressPrefixFilterElement()
  nameWithType: BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement()
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement()
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor(System.Uri)
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: BaseAddressPrefixFilterElement(Uri)
  nameWithType: BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement(Uri)
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement(Uri)
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: Prefix
  nameWithType: BaseAddressPrefixFilterElement.Prefix
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: Properties
  nameWithType: BaseAddressPrefixFilterElement.Properties
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor*
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: BaseAddressPrefixFilterElement
  nameWithType: BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix*
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: Prefix
  nameWithType: BaseAddressPrefixFilterElement.Prefix
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties*
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: Properties
  nameWithType: BaseAddressPrefixFilterElement.Properties
