### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.Internal.ServerWebConfig
  id: ServerWebConfig
  children:
  - System.EnterpriseServices.Internal.ServerWebConfig.#ctor
  - System.EnterpriseServices.Internal.ServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  - System.EnterpriseServices.Internal.ServerWebConfig.Create(System.String,System.String,System.String@)
  langs:
  - csharp
  name: ServerWebConfig
  nameWithType: ServerWebConfig
  fullName: System.EnterpriseServices.Internal.ServerWebConfig
  type: Class
  summary: "Cria um arquivo Web. config para um aplicativo habilitado para SOAP COM+. Também é possível adicionar entradas de componente para o arquivo que está sendo publicado no aplicativo de interfaces de COM."
  remarks: "A classe ServerWebConfig é usada para criar um arquivo Web. config durante a criação de uma raiz virtual no serviços de informações da Internet (IIS) 6.0 para um aplicativo habilitado para SOAP COM+. Ela também pode adicionar elementos XML para o arquivo Web. config para interfaces de componentes que estão sendo adicionados ao aplicativo.       ServerWebConfig é usado internamente pelo .NET Framework. Você não precisa usá-lo diretamente no seu código."
  syntax:
    content: 'public class ServerWebConfig : System.EnterpriseServices.Internal.IServerWebConfig'
  inheritance:
  - System.Object
  implements:
  - System.EnterpriseServices.Internal.IServerWebConfig
  inheritedMembers: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ServerWebConfig.#ctor
  id: '#ctor'
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  langs:
  - csharp
  name: ServerWebConfig()
  nameWithType: ServerWebConfig.ServerWebConfig()
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.ServerWebConfig()
  type: Constructor
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Inicializa uma nova instância do <xref href=&quot;System.EnterpriseServices.Internal.ServerWebConfig&quot;> </xref> classe."
  syntax:
    content: public ServerWebConfig ();
    parameters: []
  overload: System.EnterpriseServices.Internal.ServerWebConfig.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  id: AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  langs:
  - csharp
  name: AddElement(String,String,String,String,String,String)
  nameWithType: ServerWebConfig.AddElement(String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.AddElement(String,String,String,String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Adiciona os elementos XML de um arquivo Web. config para uma interface COM que está sendo publicada em um aplicativo habilitado para SOAP COM+."
  remarks: "Para o tipo especificado, o método AddElement adiciona ao arquivo Web. config a `<wellknown>` e `<activated>` elementos como filhos do `<service>` elemento com o XPath a seguir: `/configuration/system.runtime.remoting/application/service` o `AssemblyName`, `TypeName`, `ProgId`, e `WkoMode` parâmetros são incorporados nos valores de atributo dos dois elementos adicionados.       AddElement não deve ser chamado diretamente. Em vez disso, chame o <xref:System.EnterpriseServices.Internal.Publish.ProcessServerTlb%2A>método.</xref:System.EnterpriseServices.Internal.Publish.ProcessServerTlb%2A>"
  syntax:
    content: public void AddElement (string FilePath, string AssemblyName, string TypeName, string ProgId, string WkoMode, out string Error);
    parameters:
    - id: FilePath
      type: System.String
      description: "O caminho do arquivo Web. config existente."
    - id: AssemblyName
      type: System.String
      description: "O nome do assembly que contém o tipo que está sendo adicionado."
    - id: TypeName
      type: System.String
      description: "O nome do tipo que está sendo adicionado."
    - id: ProgId
      type: System.String
      description: "O identificador programático para o tipo que está sendo adicionado."
    - id: WkoMode
      type: System.String
      description: "Uma constante de cadeia de caracteres que corresponde ao nome de um membro do <xref href=&quot;System.Runtime.Remoting.WellKnownObjectMode&quot;> </xref> enumeração, que indica como um objeto conhecido é ativado."
    - id: Error
      type: System.String
      description: "Uma cadeia de caracteres no qual uma mensagem de erro pode ser gravada."
  overload: System.EnterpriseServices.Internal.ServerWebConfig.AddElement*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ServerWebConfig.Create(System.String,System.String,System.String@)
  id: Create(System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  langs:
  - csharp
  name: Create(String,String,String)
  nameWithType: ServerWebConfig.Create(String,String,String)
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.Create(String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Cria um arquivo Web. config para um aplicativo habilitado para SOAP COM+ para que o arquivo está pronto para ter elementos XML adicionados para interfaces COM que está sendo publicados."
  remarks: "O método Create cria um arquivo Web. config que contém a hierarquia para um elemento vazio com o XPath a seguir: ```   /configuration/system.runtime.remoting/application/service   ``` em vez de criar uma instância uma <xref:System.EnterpriseServices.Internal.ServerWebConfig>de classe de objeto e criar diretamente, chamada de chamar o <xref:System.EnterpriseServices.Internal.Publish.CreateVirtualRoot%2A>método.</xref:System.EnterpriseServices.Internal.Publish.CreateVirtualRoot%2A> </xref:System.EnterpriseServices.Internal.ServerWebConfig>"
  syntax:
    content: public void Create (string FilePath, string FilePrefix, out string Error);
    parameters:
    - id: FilePath
      type: System.String
      description: "A pasta na qual o arquivo de configuração deve ser criado."
    - id: FilePrefix
      type: System.String
      description: "O valor de cadeia de caracteres &quot;Web&quot;, para que uma extensão é adicionada."
    - id: Error
      type: System.String
      description: "Uma cadeia de caracteres no qual uma mensagem de erro pode ser gravada."
  overload: System.EnterpriseServices.Internal.ServerWebConfig.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.EnterpriseServices.Internal.ServerWebConfig.#ctor
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: ServerWebConfig()
  nameWithType: ServerWebConfig.ServerWebConfig()
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.ServerWebConfig()
- uid: System.EnterpriseServices.Internal.ServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: AddElement(String,String,String,String,String,String)
  nameWithType: ServerWebConfig.AddElement(String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.AddElement(String,String,String,String,String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.EnterpriseServices.Internal.ServerWebConfig.Create(System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: Create(String,String,String)
  nameWithType: ServerWebConfig.Create(String,String,String)
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.Create(String,String,String)
- uid: System.EnterpriseServices.Internal.ServerWebConfig.#ctor*
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: ServerWebConfig
  nameWithType: ServerWebConfig.ServerWebConfig
- uid: System.EnterpriseServices.Internal.ServerWebConfig.AddElement*
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: AddElement
  nameWithType: ServerWebConfig.AddElement
- uid: System.EnterpriseServices.Internal.ServerWebConfig.Create*
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: Create
  nameWithType: ServerWebConfig.Create
