### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsProviderAttribute
  id: SettingsProviderAttribute
  children:
  - System.Configuration.SettingsProviderAttribute.#ctor(System.String)
  - System.Configuration.SettingsProviderAttribute.#ctor(System.Type)
  - System.Configuration.SettingsProviderAttribute.ProviderTypeName
  langs:
  - csharp
  name: SettingsProviderAttribute
  nameWithType: SettingsProviderAttribute
  fullName: System.Configuration.SettingsProviderAttribute
  type: Class
  summary: "Especifica o provedor de configurações usado para fornecer armazenamento para a propriedade ou classe de configurações do aplicativo atual. Essa classe não pode ser herdada."
  remarks: "Cada classe de configurações de aplicativo define um grupo de propriedades de configurações do aplicativo que representam informações que persiste entre as execuções do aplicativo. No entanto, é um provedor de configurações, uma classe derivada de <xref:System.Configuration.SettingsProvider>— que realmente fornece o mecanismo de armazenamento.</xref:System.Configuration.SettingsProvider>       O SettingsProviderAttribute Especifica o provedor de configurações usado para fornecer armazenamento para propriedades de configurações do aplicativo. Esse atributo pode ser aplicado à classe de configurações do aplicativo inteiro ou propriedades de configurações de aplicativos individuais. Um SettingsProviderAttribute definido no nível de propriedade substituirá o atributo de nível de classe. Se um provedor de configurações não for especificado explicitamente, o provedor padrão é usado. Para aplicativos cliente, o provedor padrão é <xref:System.Configuration.LocalFileSettingsProvider>.</xref:System.Configuration.LocalFileSettingsProvider>       Provedores de configuração não pode ser determinado em tempo de execução. Determinar a tempo de execução de métodos de armazenamento deve ser codificado para a própria classe de provedor de configurações.      > [!CAUTION] > Usando configurações personalizadas de provedores de terceiros arbitrários é inerentemente seguro porque esses provedores tem acesso de leitura/gravação completa a informações de configuração do aplicativo. Um provedor de configurações deve ser completamente verificado antes que ele for adotado para uso geral."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Property)]

      public sealed class SettingsProviderAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsProviderAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsProviderAttribute
  langs:
  - csharp
  name: SettingsProviderAttribute(String)
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute(String)
  fullName: System.Configuration.SettingsProviderAttribute.SettingsProviderAttribute(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicializa uma instância do <xref href=&quot;System.Configuration.SettingsProviderAttribute&quot;> </xref> classe."
  remarks: "O nome do tipo é o nome de classe, derivada de <xref:System.Configuration.SettingsProvider>que está sendo especificado como o provedor de configurações.</xref:System.Configuration.SettingsProvider>      > [!CAUTION] > Usando configurações personalizadas de provedores de terceiros arbitrários é inerentemente seguro porque esses provedores tem acesso de leitura/gravação completa a informações de configuração do aplicativo. Um provedor de configurações deve ser completamente verificado antes que ele for adotado para uso geral."
  syntax:
    content: public SettingsProviderAttribute (string providerTypeName);
    parameters:
    - id: providerTypeName
      type: System.String
      description: "Um <xref:System.String>que contém o nome do provedor de configurações.</xref:System.String>"
  overload: System.Configuration.SettingsProviderAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsProviderAttribute.#ctor(System.Type)
  id: '#ctor(System.Type)'
  parent: System.Configuration.SettingsProviderAttribute
  langs:
  - csharp
  name: SettingsProviderAttribute(Type)
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute(Type)
  fullName: System.Configuration.SettingsProviderAttribute.SettingsProviderAttribute(Type)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Configuration.SettingsProviderAttribute&quot;> </xref> classe."
  syntax:
    content: public SettingsProviderAttribute (Type providerType);
    parameters:
    - id: providerType
      type: System.Type
      description: "Um <xref:System.Type>que contém o tipo de provedor de configurações.</xref:System.Type>"
  overload: System.Configuration.SettingsProviderAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsProviderAttribute.ProviderTypeName
  id: ProviderTypeName
  parent: System.Configuration.SettingsProviderAttribute
  langs:
  - csharp
  name: ProviderTypeName
  nameWithType: SettingsProviderAttribute.ProviderTypeName
  fullName: System.Configuration.SettingsProviderAttribute.ProviderTypeName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Obtém o nome do tipo do provedor de configurações."
  remarks: "A propriedade ProviderTypeName está definida no <xref:System.Configuration.SettingsProviderAttribute.%23ctor%2A>para a classe.</xref:System.Configuration.SettingsProviderAttribute.%23ctor%2A>"
  syntax:
    content: public string ProviderTypeName { get; }
    return:
      type: System.String
      description: "Um <xref:System.String>que contém o nome do provedor de configurações.</xref:System.String>"
  overload: System.Configuration.SettingsProviderAttribute.ProviderTypeName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsProviderAttribute.#ctor(System.String)
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: SettingsProviderAttribute(String)
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute(String)
  fullName: System.Configuration.SettingsProviderAttribute.SettingsProviderAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsProviderAttribute.#ctor(System.Type)
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: SettingsProviderAttribute(Type)
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute(Type)
  fullName: System.Configuration.SettingsProviderAttribute.SettingsProviderAttribute(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.SettingsProviderAttribute.ProviderTypeName
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: ProviderTypeName
  nameWithType: SettingsProviderAttribute.ProviderTypeName
  fullName: System.Configuration.SettingsProviderAttribute.ProviderTypeName
- uid: System.Configuration.SettingsProviderAttribute.#ctor*
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: SettingsProviderAttribute
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute
- uid: System.Configuration.SettingsProviderAttribute.ProviderTypeName*
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: ProviderTypeName
  nameWithType: SettingsProviderAttribute.ProviderTypeName
