### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.DeploymentSection
  id: DeploymentSection
  children:
  - System.Web.Configuration.DeploymentSection.#ctor
  - System.Web.Configuration.DeploymentSection.Properties
  - System.Web.Configuration.DeploymentSection.Retail
  langs:
  - csharp
  name: DeploymentSection
  nameWithType: DeploymentSection
  fullName: System.Web.Configuration.DeploymentSection
  type: Class
  summary: "Define uma configuração que normalmente é usada em um servidor de produção para substituir as configurações de nível de aplicativo que são apropriadas somente em computadores de desenvolvimento."
  syntax:
    content: 'public sealed class DeploymentSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.DeploymentSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.DeploymentSection
  langs:
  - csharp
  name: DeploymentSection()
  nameWithType: DeploymentSection.DeploymentSection()
  fullName: System.Web.Configuration.DeploymentSection.DeploymentSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Web.Configuration.DeploymentSection&quot;> </xref> classe."
  remarks: "Este construtor é chamado pelo sistema de configuração do ASP.NET. Obter uma instância de <xref:System.Web.Configuration.DeploymentSection>classe usando o <xref:System.Configuration.Configuration.GetSection%2A>método.</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.DeploymentSection>"
  syntax:
    content: public DeploymentSection ();
    parameters: []
  overload: System.Web.Configuration.DeploymentSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.DeploymentSection.Properties
  id: Properties
  parent: System.Web.Configuration.DeploymentSection
  langs:
  - csharp
  name: Properties
  nameWithType: DeploymentSection.Properties
  fullName: System.Web.Configuration.DeploymentSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A ser adicionado."
  overload: System.Web.Configuration.DeploymentSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.DeploymentSection.Retail
  id: Retail
  parent: System.Web.Configuration.DeploymentSection
  langs:
  - csharp
  name: Retail
  nameWithType: DeploymentSection.Retail
  fullName: System.Web.Configuration.DeploymentSection.Retail
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Obtém ou define um valor que especifica se os aplicativos Web no computador são implantados em <xref uid=&quot;langword_csharp_retail&quot; name=&quot;retail&quot; href=&quot;&quot;> </xref> modo."
  remarks: "Quando for varejo `true`, desabilita a saída do rastreamento ASP.NET, desabilita a depuração de recursos e desabilita detalhado mensagens de erro gerada pelo sistema para usuários remotos. Para aplicativos que têm um `customErrors` elemento no arquivo Web. config do aplicativo, o `mode` atributo será forçado a `On`. Essas configurações substituem as configurações feitas em arquivos Web. config do aplicativo.      > [!NOTE] > Quando você usa o `retail` configuração, você deve continuar a definir o `debug` atributo `false` em arquivos Web. config do aplicativo que são implantados no servidor. O `debug` configuração desabilita o tempo limite de execução de solicitação, e isso não é substituído pelo `retail` configuração. Para obter mais informações, consulte. [A maioria dos problemas de suporte comuns do ASP.NET - relatórios a partir de profundo dentro de suporte do Microsoft Developer](http://www.hanselman.com/blog/MostCommonASPNETSupportIssuesReportingFromDeepInsideMicrosoftDeveloperSupport.aspx) no blog de Scott Hanselman."
  example:
  - "The following configuration file example shows how to set this property to `true` in the machine.config file. The machine.config file is located in this folder:  \n  \n `%windir%\\Microsoft.NET\\Framework\\<frameworkversion>\\Config`  \n  \n```  \n<system.web>  \n  <deployment   \n    retail=\"true\" />  \n</system.web>  \n```"
  syntax:
    content: public bool Retail { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Se os aplicativos Web são implantados em <xref uid=&quot;langword_csharp_retail&quot; name=&quot;retail&quot; href=&quot;&quot;> </xref> modo; caso contrário, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. O padrão é <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.DeploymentSection.Retail*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.DeploymentSection.#ctor
  parent: System.Web.Configuration.DeploymentSection
  isExternal: false
  name: DeploymentSection()
  nameWithType: DeploymentSection.DeploymentSection()
  fullName: System.Web.Configuration.DeploymentSection.DeploymentSection()
- uid: System.Web.Configuration.DeploymentSection.Properties
  parent: System.Web.Configuration.DeploymentSection
  isExternal: false
  name: Properties
  nameWithType: DeploymentSection.Properties
  fullName: System.Web.Configuration.DeploymentSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.DeploymentSection.Retail
  parent: System.Web.Configuration.DeploymentSection
  isExternal: false
  name: Retail
  nameWithType: DeploymentSection.Retail
  fullName: System.Web.Configuration.DeploymentSection.Retail
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.DeploymentSection.#ctor*
  parent: System.Web.Configuration.DeploymentSection
  isExternal: false
  name: DeploymentSection
  nameWithType: DeploymentSection.DeploymentSection
- uid: System.Web.Configuration.DeploymentSection.Properties*
  parent: System.Web.Configuration.DeploymentSection
  isExternal: false
  name: Properties
  nameWithType: DeploymentSection.Properties
- uid: System.Web.Configuration.DeploymentSection.Retail*
  parent: System.Web.Configuration.DeploymentSection
  isExternal: false
  name: Retail
  nameWithType: DeploymentSection.Retail
