### YamlMime:ManagedReference
items:
- uid: System.Runtime.Serialization.Configuration.SerializationSectionGroup
  id: SerializationSectionGroup
  children:
  - System.Runtime.Serialization.Configuration.SerializationSectionGroup.#ctor
  - System.Runtime.Serialization.Configuration.SerializationSectionGroup.DataContractSerializer
  - System.Runtime.Serialization.Configuration.SerializationSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  - System.Runtime.Serialization.Configuration.SerializationSectionGroup.NetDataContractSerializer
  langs:
  - csharp
  name: SerializationSectionGroup
  nameWithType: SerializationSectionGroup
  fullName: System.Runtime.Serialization.Configuration.SerializationSectionGroup
  type: Class
  summary: "Manipula os elementos XML usados para configurar a serialização por <xref:System.Runtime.Serialization.DataContractSerializer>.</xref:System.Runtime.Serialization.DataContractSerializer>"
  remarks: "This class is used to handle the [\\&lt;dataContractSerializer\\&gt;](../Topic/%3CdataContractSerializer%3E.md) group, which contains the [\\&lt;dataContractSerializer\\&gt;](../Topic/%3CdataContractSerializer%3E.md) element, specifically, to allow the addition of types to the collection of known types. For more information about data contract known types, see [Data Contract Known Types](~/add/includes/ajax-current-ext-md.md).  \n  \n For an example of using the element to add to the known types collection, see [\\&lt;declaredTypes\\&gt;](../Topic/%3CdeclaredTypes%3E.md)."
  syntax:
    content: 'public sealed class SerializationSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  platform:
  - net462
- uid: System.Runtime.Serialization.Configuration.SerializationSectionGroup.#ctor
  id: '#ctor'
  parent: System.Runtime.Serialization.Configuration.SerializationSectionGroup
  langs:
  - csharp
  name: SerializationSectionGroup()
  nameWithType: SerializationSectionGroup.SerializationSectionGroup()
  fullName: System.Runtime.Serialization.Configuration.SerializationSectionGroup.SerializationSectionGroup()
  type: Constructor
  assemblies:
  - System.Runtime.Serialization
  namespace: System.Runtime.Serialization.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Runtime.Serialization.Configuration.SerializationSectionGroup&quot;> </xref> classe."
  syntax:
    content: public SerializationSectionGroup ();
    parameters: []
  overload: System.Runtime.Serialization.Configuration.SerializationSectionGroup.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Serialization.Configuration.SerializationSectionGroup.DataContractSerializer
  id: DataContractSerializer
  parent: System.Runtime.Serialization.Configuration.SerializationSectionGroup
  langs:
  - csharp
  name: DataContractSerializer
  nameWithType: SerializationSectionGroup.DataContractSerializer
  fullName: System.Runtime.Serialization.Configuration.SerializationSectionGroup.DataContractSerializer
  type: Property
  assemblies:
  - System.Runtime.Serialization
  namespace: System.Runtime.Serialization.Configuration
  summary: "Obtém o <xref href=&quot;System.Runtime.Serialization.Configuration.DataContractSerializerSection&quot;> </xref> usado para configurar a coleção de tipos conhecidos."
  syntax:
    content: public System.Runtime.Serialization.Configuration.DataContractSerializerSection DataContractSerializer { get; }
    return:
      type: System.Runtime.Serialization.Configuration.DataContractSerializerSection
      description: "O <xref href=&quot;System.Runtime.Serialization.Configuration.DataContractSerializerSection&quot;> </xref> usado para a seção de configuração de serialização."
  overload: System.Runtime.Serialization.Configuration.SerializationSectionGroup.DataContractSerializer*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Serialization.Configuration.SerializationSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  id: GetSectionGroup(System.Configuration.Configuration)
  parent: System.Runtime.Serialization.Configuration.SerializationSectionGroup
  langs:
  - csharp
  name: GetSectionGroup(Configuration)
  nameWithType: SerializationSectionGroup.GetSectionGroup(Configuration)
  fullName: System.Runtime.Serialization.Configuration.SerializationSectionGroup.GetSectionGroup(Configuration)
  type: Method
  assemblies:
  - System.Runtime.Serialization
  namespace: System.Runtime.Serialization.Configuration
  summary: "Obtém a seção de configuração de serialização para a configuração especificada."
  syntax:
    content: public static System.Runtime.Serialization.Configuration.SerializationSectionGroup GetSectionGroup (System.Configuration.Configuration config);
    parameters:
    - id: config
      type: System.Configuration.Configuration
      description: "Um <xref href=&quot;System.Configuration.Configuration&quot;> </xref> que representa a configuração para recuperar."
    return:
      type: System.Runtime.Serialization.Configuration.SerializationSectionGroup
      description: "Um <xref href=&quot;System.Runtime.Serialization.Configuration.SerializationSectionGroup&quot;> </xref> que representa a seção de configuração."
  overload: System.Runtime.Serialization.Configuration.SerializationSectionGroup.GetSectionGroup*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Serialization.Configuration.SerializationSectionGroup.NetDataContractSerializer
  id: NetDataContractSerializer
  parent: System.Runtime.Serialization.Configuration.SerializationSectionGroup
  langs:
  - csharp
  name: NetDataContractSerializer
  nameWithType: SerializationSectionGroup.NetDataContractSerializer
  fullName: System.Runtime.Serialization.Configuration.SerializationSectionGroup.NetDataContractSerializer
  type: Property
  assemblies:
  - System.Runtime.Serialization
  namespace: System.Runtime.Serialization.Configuration
  summary: "Obtém o <xref href=&quot;System.Runtime.Serialization.Configuration.NetDataContractSerializerSection&quot;> </xref> usado para configurar a coleção de tipos conhecidos."
  syntax:
    content: public System.Runtime.Serialization.Configuration.NetDataContractSerializerSection NetDataContractSerializer { get; }
    return:
      type: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection
      description: "O <xref href=&quot;System.Runtime.Serialization.Configuration.NetDataContractSerializerSection&quot;> </xref> objeto."
  overload: System.Runtime.Serialization.Configuration.SerializationSectionGroup.NetDataContractSerializer*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: System.Configuration.ConfigurationSectionGroup
- uid: System.Runtime.Serialization.Configuration.SerializationSectionGroup.#ctor
  parent: System.Runtime.Serialization.Configuration.SerializationSectionGroup
  isExternal: false
  name: SerializationSectionGroup()
  nameWithType: SerializationSectionGroup.SerializationSectionGroup()
  fullName: System.Runtime.Serialization.Configuration.SerializationSectionGroup.SerializationSectionGroup()
- uid: System.Runtime.Serialization.Configuration.SerializationSectionGroup.DataContractSerializer
  parent: System.Runtime.Serialization.Configuration.SerializationSectionGroup
  isExternal: false
  name: DataContractSerializer
  nameWithType: SerializationSectionGroup.DataContractSerializer
  fullName: System.Runtime.Serialization.Configuration.SerializationSectionGroup.DataContractSerializer
- uid: System.Runtime.Serialization.Configuration.DataContractSerializerSection
  parent: System.Runtime.Serialization.Configuration
  isExternal: false
  name: DataContractSerializerSection
  nameWithType: DataContractSerializerSection
  fullName: System.Runtime.Serialization.Configuration.DataContractSerializerSection
- uid: System.Runtime.Serialization.Configuration.SerializationSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  parent: System.Runtime.Serialization.Configuration.SerializationSectionGroup
  isExternal: false
  name: GetSectionGroup(Configuration)
  nameWithType: SerializationSectionGroup.GetSectionGroup(Configuration)
  fullName: System.Runtime.Serialization.Configuration.SerializationSectionGroup.GetSectionGroup(Configuration)
- uid: System.Runtime.Serialization.Configuration.SerializationSectionGroup
  parent: System.Runtime.Serialization.Configuration
  isExternal: false
  name: SerializationSectionGroup
  nameWithType: SerializationSectionGroup
  fullName: System.Runtime.Serialization.Configuration.SerializationSectionGroup
- uid: System.Configuration.Configuration
  parent: System.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: System.Runtime.Serialization.Configuration.SerializationSectionGroup.NetDataContractSerializer
  parent: System.Runtime.Serialization.Configuration.SerializationSectionGroup
  isExternal: false
  name: NetDataContractSerializer
  nameWithType: SerializationSectionGroup.NetDataContractSerializer
  fullName: System.Runtime.Serialization.Configuration.SerializationSectionGroup.NetDataContractSerializer
- uid: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection
  parent: System.Runtime.Serialization.Configuration
  isExternal: false
  name: NetDataContractSerializerSection
  nameWithType: NetDataContractSerializerSection
  fullName: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection
- uid: System.Runtime.Serialization.Configuration.SerializationSectionGroup.#ctor*
  parent: System.Runtime.Serialization.Configuration.SerializationSectionGroup
  isExternal: false
  name: SerializationSectionGroup
  nameWithType: SerializationSectionGroup.SerializationSectionGroup
- uid: System.Runtime.Serialization.Configuration.SerializationSectionGroup.DataContractSerializer*
  parent: System.Runtime.Serialization.Configuration.SerializationSectionGroup
  isExternal: false
  name: DataContractSerializer
  nameWithType: SerializationSectionGroup.DataContractSerializer
- uid: System.Runtime.Serialization.Configuration.SerializationSectionGroup.GetSectionGroup*
  parent: System.Runtime.Serialization.Configuration.SerializationSectionGroup
  isExternal: false
  name: GetSectionGroup
  nameWithType: SerializationSectionGroup.GetSectionGroup
- uid: System.Runtime.Serialization.Configuration.SerializationSectionGroup.NetDataContractSerializer*
  parent: System.Runtime.Serialization.Configuration.SerializationSectionGroup
  isExternal: false
  name: NetDataContractSerializer
  nameWithType: SerializationSectionGroup.NetDataContractSerializer
