### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ProtocolMappingElement
  id: ProtocolMappingElement
  children:
  - System.ServiceModel.Configuration.ProtocolMappingElement.#ctor
  - System.ServiceModel.Configuration.ProtocolMappingElement.#ctor(System.String,System.String,System.String)
  - System.ServiceModel.Configuration.ProtocolMappingElement.Binding
  - System.ServiceModel.Configuration.ProtocolMappingElement.BindingConfiguration
  - System.ServiceModel.Configuration.ProtocolMappingElement.Properties
  - System.ServiceModel.Configuration.ProtocolMappingElement.Scheme
  langs:
  - csharp
  name: ProtocolMappingElement
  nameWithType: ProtocolMappingElement
  fullName: System.ServiceModel.Configuration.ProtocolMappingElement
  type: Class
  summary: "Fornece a funcionalidade para criar um elemento de mapeamento de protocolo. Essa classe está lacrada."
  syntax:
    content: 'public sealed class ProtocolMappingElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  langs:
  - csharp
  name: ProtocolMappingElement()
  nameWithType: ProtocolMappingElement.ProtocolMappingElement()
  fullName: System.ServiceModel.Configuration.ProtocolMappingElement.ProtocolMappingElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Cria uma nova instância do <xref href=&quot;System.ServiceModel.Configuration.ProtocolMappingElement&quot;> </xref> classe."
  syntax:
    content: public ProtocolMappingElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ProtocolMappingElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.#ctor(System.String,System.String,System.String)
  id: '#ctor(System.String,System.String,System.String)'
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  langs:
  - csharp
  name: ProtocolMappingElement(String,String,String)
  nameWithType: ProtocolMappingElement.ProtocolMappingElement(String,String,String)
  fullName: System.ServiceModel.Configuration.ProtocolMappingElement.ProtocolMappingElement(String,String,String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Cria uma nova instância do <xref href=&quot;System.ServiceModel.Configuration.ProtocolMappingElement&quot;> </xref> classe com um tipo de esquema especificado, a associação e a configuração de associação."
  syntax:
    content: public ProtocolMappingElement (string schemeType, string binding, string bindingConfiguration);
    parameters:
    - id: schemeType
      type: System.String
      description: "Um esquema de protocolo de comunicação."
    - id: binding
      type: System.String
      description: "Um estilo de formato de mensagem de protocolo de comunicação."
    - id: bindingConfiguration
      type: System.String
      description: "As configurações de associação para a configuração do elemento de mapeamento de protocolo."
  overload: System.ServiceModel.Configuration.ProtocolMappingElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.Binding
  id: Binding
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  langs:
  - csharp
  name: Binding
  nameWithType: ProtocolMappingElement.Binding
  fullName: System.ServiceModel.Configuration.ProtocolMappingElement.Binding
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém ou define as configurações para a mensagem de protocolo de comunicação formatação."
  syntax:
    content: public string Binding { get; set; }
    return:
      type: System.String
      description: "A mensagem de protocolo de comunicação informações de formatação."
  overload: System.ServiceModel.Configuration.ProtocolMappingElement.Binding*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.BindingConfiguration
  id: BindingConfiguration
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  langs:
  - csharp
  name: BindingConfiguration
  nameWithType: ProtocolMappingElement.BindingConfiguration
  fullName: System.ServiceModel.Configuration.ProtocolMappingElement.BindingConfiguration
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém ou define as configurações de associação para o elemento de configuração de mapeamento de protocolo."
  syntax:
    content: public string BindingConfiguration { get; set; }
    return:
      type: System.String
      description: "O elemento de configuração de associação."
  overload: System.ServiceModel.Configuration.ProtocolMappingElement.BindingConfiguration*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  langs:
  - csharp
  name: Properties
  nameWithType: ProtocolMappingElement.Properties
  fullName: System.ServiceModel.Configuration.ProtocolMappingElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A ser adicionado."
  overload: System.ServiceModel.Configuration.ProtocolMappingElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.Scheme
  id: Scheme
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  langs:
  - csharp
  name: Scheme
  nameWithType: ProtocolMappingElement.Scheme
  fullName: System.ServiceModel.Configuration.ProtocolMappingElement.Scheme
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Obtém ou define o tipo de protocolo de comunicação."
  syntax:
    content: public string Scheme { get; set; }
    return:
      type: System.String
      description: "Nomeia o protocolo de comunicação."
  overload: System.ServiceModel.Configuration.ProtocolMappingElement.Scheme*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.#ctor
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  isExternal: false
  name: ProtocolMappingElement()
  nameWithType: ProtocolMappingElement.ProtocolMappingElement()
  fullName: System.ServiceModel.Configuration.ProtocolMappingElement.ProtocolMappingElement()
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.#ctor(System.String,System.String,System.String)
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  isExternal: false
  name: ProtocolMappingElement(String,String,String)
  nameWithType: ProtocolMappingElement.ProtocolMappingElement(String,String,String)
  fullName: System.ServiceModel.Configuration.ProtocolMappingElement.ProtocolMappingElement(String,String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.Binding
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  isExternal: false
  name: Binding
  nameWithType: ProtocolMappingElement.Binding
  fullName: System.ServiceModel.Configuration.ProtocolMappingElement.Binding
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.BindingConfiguration
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  isExternal: false
  name: BindingConfiguration
  nameWithType: ProtocolMappingElement.BindingConfiguration
  fullName: System.ServiceModel.Configuration.ProtocolMappingElement.BindingConfiguration
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.Properties
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  isExternal: false
  name: Properties
  nameWithType: ProtocolMappingElement.Properties
  fullName: System.ServiceModel.Configuration.ProtocolMappingElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.Scheme
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  isExternal: false
  name: Scheme
  nameWithType: ProtocolMappingElement.Scheme
  fullName: System.ServiceModel.Configuration.ProtocolMappingElement.Scheme
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.#ctor*
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  isExternal: false
  name: ProtocolMappingElement
  nameWithType: ProtocolMappingElement.ProtocolMappingElement
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.Binding*
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  isExternal: false
  name: Binding
  nameWithType: ProtocolMappingElement.Binding
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.BindingConfiguration*
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  isExternal: false
  name: BindingConfiguration
  nameWithType: ProtocolMappingElement.BindingConfiguration
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.Properties*
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  isExternal: false
  name: Properties
  nameWithType: ProtocolMappingElement.Properties
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.Scheme*
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  isExternal: false
  name: Scheme
  nameWithType: ProtocolMappingElement.Scheme
