### YamlMime:ManagedReference
items:
- uid: System.Configuration.TimeSpanMinutesConverter
  id: TimeSpanMinutesConverter
  children:
  - System.Configuration.TimeSpanMinutesConverter.#ctor
  - System.Configuration.TimeSpanMinutesConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Configuration.TimeSpanMinutesConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: TimeSpanMinutesConverter
  nameWithType: TimeSpanMinutesConverter
  fullName: System.Configuration.TimeSpanMinutesConverter
  type: Class
  summary: "Converte um período de tempo, expressado em minutos."
  remarks: "Este tipo, como todos os outros conversor tipos de configuração, converte cadeias de caracteres encontradas no arquivo de configuração de e para as propriedades com rigidez de tipos relacionadas.       Em particular, o TimeSpanMinutesConverter converte <xref:System.String>minutos, atribuídos a uma propriedade de configuração, a <xref:System.TimeSpan>minutos e vice-versa.</xref:System.TimeSpan> </xref:System.String>       O TimeSpanMinutesConverter persiste os valores do tipo `long` que representa o número de minutos."
  example:
  - "The following code example shows how to define a custom TimeSpanMinutesConverter type.  \n  \n [!code-vb[System.Configuration.TimeSpanMinutesConverter#1](~/add/codesnippet/visualbasic/t-system.configuration.t_3_1.vb)]\n [!code-cs[System.Configuration.TimeSpanMinutesConverter#1](~/add/codesnippet/csharp/t-system.configuration.t_3_1.cs)]  \n  \n The following is a configuration excerpt used by the previous example.  \n  \n```  \n<configuration>  \n  \n  <configSections>  \n    <section name=\"CustomSection\"  \n      type=\"Samples.AspNet.CustomSection,  \n      ConfigurationConverters,  \n      Version=1.0.0.0, Culture=neutral,  \n      PublicKeyToken=null\"  \n      allowDefinition=\"Everywhere\"  \n      allowExeDefinition=\"MachineToApplication\"  \n      restartOnExternalChanges=\"true\" />  \n  </configSections>  \n  \n  <CustomSection fileName=\"default.txt\" maxIdleTime=\"90\"   \n    timeDelay=\"infinite\" cdStr=\"str0, str1\" permission=\"Read\"   \n    maxUsers=\"Infinite\"/>  \n  \n</configuration>  \n```"
  syntax:
    content: 'public class TimeSpanMinutesConverter : System.Configuration.ConfigurationConverterBase'
  inheritance:
  - System.Object
  - System.ComponentModel.TypeConverter
  - System.Configuration.ConfigurationConverterBase
  implements: []
  inheritedMembers:
  - System.ComponentModel.TypeConverter.CanConvertFrom(System.Type)
  - System.ComponentModel.TypeConverter.CanConvertTo(System.Type)
  - System.ComponentModel.TypeConverter.ConvertFrom(System.Object)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.String)
  - System.ComponentModel.TypeConverter.ConvertTo(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.Object)
  - System.ComponentModel.TypeConverter.CreateInstance(System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.CreateInstance(System.ComponentModel.ITypeDescriptorContext,System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.GetConvertFromException(System.Object)
  - System.ComponentModel.TypeConverter.GetConvertToException(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object,System.Attribute[])
  - System.ComponentModel.TypeConverter.GetProperties(System.Object)
  - System.ComponentModel.TypeConverter.GetPropertiesSupported
  - System.ComponentModel.TypeConverter.GetPropertiesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValues
  - System.ComponentModel.TypeConverter.GetStandardValues(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.IsValid(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.IsValid(System.Object)
  - System.ComponentModel.TypeConverter.SortProperties(System.ComponentModel.PropertyDescriptorCollection,System.String[])
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  platform:
  - net462
- uid: System.Configuration.TimeSpanMinutesConverter.#ctor
  id: '#ctor'
  parent: System.Configuration.TimeSpanMinutesConverter
  langs:
  - csharp
  name: TimeSpanMinutesConverter()
  nameWithType: TimeSpanMinutesConverter.TimeSpanMinutesConverter()
  fullName: System.Configuration.TimeSpanMinutesConverter.TimeSpanMinutesConverter()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Configuration.TimeSpanMinutesConverter&quot;> </xref> classe."
  remarks: "Normalmente, você usa os tipos de conversor fornecidos pelo sistema. A única vez em que você precisa usar o construtor de TimeSpanMinutesConverter é quando você cria seu próprio tipo de conversão."
  syntax:
    content: public TimeSpanMinutesConverter ();
    parameters: []
  overload: System.Configuration.TimeSpanMinutesConverter.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanMinutesConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TimeSpanMinutesConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: TimeSpanMinutesConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.TimeSpanMinutesConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Converte um <xref:System.String>um <xref:System.TimeSpan>.</xref:System.TimeSpan> </xref:System.String>"
  remarks: "O sistema usa o método ConvertFrom durante a leitura de um arquivo de configuração para converter um <xref:System.String>valor para <xref:System.TimeSpan>.</xref:System.TimeSpan> </xref:System.String>"
  example:
  - "The following code example shows how to customize the ConvertFrom method.  \n  \n [!code-vb[System.Configuration.TimeSpanMinutesConverter#5](~/add/codesnippet/visualbasic/217172fc-63bd-4c91-9301-_1.vb)]\n [!code-cs[System.Configuration.TimeSpanMinutesConverter#5](~/add/codesnippet/csharp/217172fc-63bd-4c91-9301-_1.cs)]"
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object data);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "O <xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> usado para conversões de tipo de objeto."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "O <xref:System.Globalization.CultureInfo>objeto usado durante a conversão.</xref:System.Globalization.CultureInfo>"
    - id: data
      type: System.Object
      description: "O <xref:System.String>objeto converter.</xref:System.String>"
    return:
      type: System.Object
      description: "O <xref:System.TimeSpan>representar o <code> data </code> parâmetro em minutos.</xref:System.TimeSpan>"
  overload: System.Configuration.TimeSpanMinutesConverter.ConvertFrom*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanMinutesConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TimeSpanMinutesConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: TimeSpanMinutesConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.TimeSpanMinutesConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Converte um <xref:System.TimeSpan>um <xref:System.String>.</xref:System.String> </xref:System.TimeSpan>"
  remarks: "O sistema usa o método ConvertTo ao gravar em um arquivo de configuração para converter um <xref:System.TimeSpan> <xref:System.String>.</xref:System.String> </xref:System.TimeSpan>"
  example:
  - "The following code example shows how to customize the ConvertTo method.  \n  \n [!code-vb[System.Configuration.TimeSpanMinutesConverter#4](~/add/codesnippet/visualbasic/e18c626c-bb93-4990-9d92-_1.vb)]\n [!code-cs[System.Configuration.TimeSpanMinutesConverter#4](~/add/codesnippet/csharp/e18c626c-bb93-4990-9d92-_1.cs)]"
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object value, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "O <xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> usado para conversões de tipo de objeto."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "O <xref:System.Globalization.CultureInfo>objeto usado durante a conversão.</xref:System.Globalization.CultureInfo>"
    - id: value
      type: System.Object
      description: "O valor a converter."
    - id: type
      type: System.Type
      description: "O tipo para converter."
    return:
      type: System.Object
      description: "O <xref:System.String>representar o <code> value </code> parâmetro em minutos.</xref:System.String>"
  overload: System.Configuration.TimeSpanMinutesConverter.ConvertTo*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationConverterBase
  isExternal: false
  name: System.Configuration.ConfigurationConverterBase
- uid: System.Configuration.TimeSpanMinutesConverter.#ctor
  parent: System.Configuration.TimeSpanMinutesConverter
  isExternal: false
  name: TimeSpanMinutesConverter()
  nameWithType: TimeSpanMinutesConverter.TimeSpanMinutesConverter()
  fullName: System.Configuration.TimeSpanMinutesConverter.TimeSpanMinutesConverter()
- uid: System.Configuration.TimeSpanMinutesConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TimeSpanMinutesConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: TimeSpanMinutesConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.TimeSpanMinutesConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: false
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: true
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Configuration.TimeSpanMinutesConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TimeSpanMinutesConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: TimeSpanMinutesConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.TimeSpanMinutesConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.TimeSpanMinutesConverter.#ctor*
  parent: System.Configuration.TimeSpanMinutesConverter
  isExternal: false
  name: TimeSpanMinutesConverter
  nameWithType: TimeSpanMinutesConverter.TimeSpanMinutesConverter
- uid: System.Configuration.TimeSpanMinutesConverter.ConvertFrom*
  parent: System.Configuration.TimeSpanMinutesConverter
  isExternal: false
  name: ConvertFrom
  nameWithType: TimeSpanMinutesConverter.ConvertFrom
- uid: System.Configuration.TimeSpanMinutesConverter.ConvertTo*
  parent: System.Configuration.TimeSpanMinutesConverter
  isExternal: false
  name: ConvertTo
  nameWithType: TimeSpanMinutesConverter.ConvertTo
